### ISSUE TITLE
Position of »Send« button

### ISSUE THREAD

**Issue by aspdye** [owncloud/mail#1012]
I think we shoud take the "send" button out of the textbox. Looks strange ;)

**Comment by ChristophWurst** [comment]
@jancborchardt

**Comment by jancborchardt** [comment]
Yeah, I think I’ll go with putting it to the bottom right of the textbox, and put the Forward button left of it until we combine them.

**Comment by jancborchardt** [comment]
Fixed by https://github.com/owncloud/mail/pull/1094
