### ISSUE TITLE
Fix mailto composer

### ISSUE THREAD

**Issue by Gomez** [owncloud/mail#1020]
The "js/composer.js" was a copy of the composer.js. Should be killed and redone :)

**Comment by ChristophWurst** [comment]
Setting this to priority as it's also broken at the moment

**Comment by jancborchardt** [comment]
Maybe it’s better to not do this as separate composer, but really open the mail app. Then we do not need a separate view.

**Comment by ChristophWurst** [comment]
Yes, we should reuse the app as it is instead of duplicating functionality or views.
