### ISSUE TITLE
Pre process task for transifex.com

### ISSUE THREAD

**Issue by Gomez** [owncloud/mail#1031]
As we lose the translations in the handlebar js templates, we created a script to add them back:
https://github.com/owncloud/mail/pull/1030

The script need to be added to transiflex. @jancborchardt Can you do this? Otherwise we wait for @DeepDiver1975

**Comment by DeepDiver1975** [comment]
This is something i need to add to Jenkins ..

**Comment by Gomez** [comment]
Ok, can it be done without jenkins? Should we look for a other solution? Anyway we can wait some weeks..

**Comment by ChristophWurst** [comment]
@DeepDiver1975 can we fix that in 0.3? Is there anything you need for that? From my understanding, running the [translation extractor script](https://github.com/owncloud/mail/blob/master/translation-extractor.php) creates a .js file which contains all the translation strings. This should be enough, right?

**Comment by jancborchardt** [comment]
@DeepDiver1975 we need your mastery here. ;)

**Comment by jancborchardt** [comment]
@DeepDiver1975 this is needed for 0.3, please check it out.

**Comment by DeepDiver1975** [comment]
let me see what I can do .... the script is a general purpose script which is executed on all repos/apps.

I need to find a way to run a pre-processing task ...
