### ISSUE TITLE
Links from HTML emails open in message iFrame

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/mail#1041]
Instead, all links from inside emails should be force set to `target="_blank"` if possible. @LukasReschke @irgendwie @ChristophWurst is that possible?

**Comment by jakobsack** [comment]
That's pretty easy to do, I'll create a PR later today

**Comment by ChristophWurst** [comment]
Actually, this is a bug. We had this functionality already, but it seems like it was removed unintentionally…
