### ISSUE TITLE
Allow emails only with cc/bcc

### ISSUE THREAD

**Issue by iomartin** [owncloud/mail#1048]
Currently, you need at least one email in the "to" field, even if cc or bcc fields are filled. The "Send" button is greyed out until you enter something in the "to" field.

**Comment by aspdye** [comment]
This is an limitation known also in other mail clients like Open Xchange and Outlook (think they have fixed this).

**Comment by ChristophWurst** [comment]
@iomartin what's the use case for not putting any recipient into to 'to' field? AFAIK also Gnome's Evolutions warns when you try to send an email without any recipient.

**Comment by iomartin** [comment]
If I want to send email to a list of people and I don't want any of them to know the address of the other people I sent to. Some situations where you might want this:
- Notifying all your contacts that you have a new phone number;
- Contacting multiple companies/persons asking for the price for a service/product;
- Newsletter (like @aspdye said).

I like the warning approach of Evolution and other clients.I like the warning approach of Evolution and other clients.

**Comment by ChristophWurst** [comment]
I'm not sure if email is designed to be used that way. I'd rather say one could add a 'newsletter' functionality, which sends separate mails to a list of contacts.

Error message taken from Evolution: "Many email systems add an Apparently-To header to messages that only have BCC recipients. This header, if added, will list all of your recipients in your message. To avoid this, you should add at least one To: or CC: recipient."

Hence, I think we also shouldn't allow that.

**Comment by PoPoutdoor** [comment]
> If I want to send email to a list of people and I don't want any of them to know the address of the other people I sent to.

@iomartin Just send mail to yourself, with others in bcc.

**Comment by jancborchardt** [comment]
Yeah, basically everywhere when newsletters are sent to bcc recipients, the person puts themselves in the »to« field.

**Comment by PoPoutdoor** [comment]
Not an issue, shall we closed this?
