### ISSUE TITLE
https/ssl connection and html mail message body is blocked

### ISSUE THREAD

**Issue by kione** [owncloud/mail#1059]
Owncloud Server is fully reachable/functional over https connection, but mails with HTML content are blogged. Plain Text Mails are working properly

**Comment by ChristophWurst** [comment]
Thanks for reporting this bug!

Please use the issue template: https://raw.github.com/owncloud/core/master/issue_template.md

Which browser do you use?
Can you post a screenshot?

Thanks

**Comment by kione** [comment]
I am using Firefox, Iceweasel, Chromium (in IE i can disable security actions and it will show properly html mails in https://myowncloud), Server sides PHP 5.6.2. Mail Client Evolution (e.g. Webinterface) configured to use ssl on dedicated 465. Sending Plain Text Mails all good... Sending HTML Mails, no showing of the Mail Body but the spinning circle
OC 8.1.1, Mail 2.0, https:// >> problem occurs in blokking the iframe Mseeage Body, http:// >> no Problem. Screenshots
https://clouds.kione.de/multi/index.php/s/jqmvBTPq7fq7TmV

Thanks for caring!!

**Comment by kione** [comment]
I am using Firefox, Iceweasel, Chromium (in IE i can disable security actions and it will show properly html mails in https://myowncloud), Server sides PHP 5.6.2. Mail Client Evolution (e.g. Webinterface) configured to use ssl on dedicated 465. Sending Plain Text Mails all good... Sending HTML Mails, no showing of the Mail Body but the spinning circle
OC 8.1.1, Mail 2.0, https:// >> problem occurs in blokking the iframe Mseeage Body, http:// >> no Problem. Screenshots
https://clouds.kione.de/multi/index.php/s/jqmvBTPq7fq7TmV

Thanks for caring!!

**Comment by ChristophWurst** [comment]
HTML mails are shown inside an iframe. Please inspect the HTML structure when the error occurs and paste the ``src`` attribute's content here. I'm curious if that's a HTTP or HTTPS url…

**Comment by kione** [comment]
Me too, but it makes the difference. Dialing http:// will properly show all contents. But the https:// one, does not. What logs exactly do you need? 
![selection_08092015 002](https://cloud.githubusercontent.com/assets/12138578/9733613/0db5a280-562d-11e5-95c4-cdd3eabf33c1.jpg)

**Comment by kione** [comment]
SRC reveals the reason, how to solve it now..?

<div class="mail-message-body">
		<div id="mail-content">
			{{#if hasHtmlBody}}
			<div class="icon-loading">
				<iframe src="{{htmlBodyUrl}}" seamless>
				</iframe>
			</div>
			{{else}}
			{{{body}}}
			{{/if}}
		</div>

**Comment by ChristophWurst** [comment]
I think I found the problem: Local storage caching.

Please try the following:
* Open the app via ssl
* Open browser console and enter ``localstorage.clear();``
* Reload the page

Then it should work. The problem is your mixed ssl/non-ssl setup. Messages are cached in browser's local storage, therefore there's the non-ssl (http) url because you probably opened that exact same message via http before.

**Comment by kione** [comment]
![selection_08092015 003](https://cloud.githubusercontent.com/assets/12138578/9734450/66f26666-5633-11e5-9d46-20fa05d17c74.jpg)
![selection_08092015 004](https://cloud.githubusercontent.com/assets/12138578/9734452/66f51cda-5633-11e5-9f71-854f050ea379.jpg)

**Comment by kione** [comment]
'overwriteprotocol' => 'https', << solution, for me!
Thanks for sharing thoughts! My cloud servers are behind proxys which define the ssl status... So Owncloud was trying to load http instead of https.
Awesome work and once again: thank you so much!
