### ISSUE TITLE
New mails in unified inbox: Missing account color indicator and avatar

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/mail#1060]
For new mails which arrive in the unified inbox as result of the background loading (which is awesome!), both the account color indicator and the correct avatar are missing. They only appear correctly after a manual reload.

**Comment by jancborchardt** [comment]
Yo @ChristophWurst @Gomez this makes the app seem quite unpolished still. An easy fix maybe? :)

**Comment by ChristophWurst** [comment]
@jancborchardt http://devopsreactions.tumblr.com/post/135701476645/looking-for-someone-to-assign-the-bug-to

**Comment by jancborchardt** [comment]
Yeah yeah yeah ;D
