### ISSUE TITLE
cURL error 60

### ISSUE THREAD

**Issue by drewcaplan** [owncloud/mail#1067]
Hello, I am trying to install this but I am getting the following error when I do:

cURL error 60: See http://curl.haxx.se/libcurl/c/libcurl-errors.html

**Comment by PoPoutdoor** [comment]
Please provide detail procedure leading to the error.

**Comment by drewcaplan** [comment]
Installed OnwCloud, went to Apps and tried to install the Mail App
![screen shot 2015-09-10 at 11 42 11 am](https://cloud.githubusercontent.com/assets/14220020/9792960/00ac2a70-57b1-11e5-9c0f-4bc50c8b33a6.png)

**Comment by PoPoutdoor** [comment]
This is core related issue, try:

https://github.com/owncloud/core/search?q=curl+error+60&type=Issues&utf8=%E2%9C%93

**Comment by ChristophWurst** [comment]
Closing this because it's not an issue of this app
