### ISSUE TITLE
Add info about nighlty builds in App Store

### ISSUE THREAD

**Issue by enoch85** [owncloud/mail#1072]
Would be nice to link the nightly builds in app store https://apps.owncloud.com/content/show.php/Mail?content=169914

Here are the links: 
https://github.com/owncloud/mail#nightly-builds

cc @ChristophWurst @Gomez @DeepDiver1975

**Comment by ChristophWurst** [comment]
@jancborchardt do you have access to add that info?

**Comment by jancborchardt** [comment]
Updated! https://apps.owncloud.com/content/show.php?content=169914

**Comment by enoch85** [comment]
Yay! :+1:
