### ISSUE TITLE
Change color of button to ownCloud blue and white

### ISSUE THREAD

**Issue by enoch85** [owncloud/mail#1073]
The color of the redirect button is gray-white / white. It should be ownCloud blue and white instead.

Current in Chrome:
![image](https://cloud.githubusercontent.com/assets/4511254/9836847/24935bc8-5a29-11e5-972c-8e5bd91fc7e7.png)

**Mail version**
0.2

cc @jancborchardt

**Comment by jancborchardt** [comment]
Correction: The button should not be blue, but rather the grey with a black text. It’s correct like that on the update page for example.

**Comment by enoch85** [comment]
@jancborchardt Ok, the just change the text color then. Right?

**Comment by jancborchardt** [comment]
Yeah, but it’s weird that that’s not automatic. Maybe because the button is an `<a class="button"` and a gets black color by default? If you want to investigate and fix it properly that would be cool. :)

**Comment by enoch85** [comment]
@jancborchardt Sorry, don´t have time for investigating just now. School and work is calling...

**Comment by jancborchardt** [comment]
This is fixed by https://github.com/owncloud/core/pull/20232 and I might backport it. :)
