### ISSUE TITLE
[Nightly-20150915] White background on "+ New message" 

### ISSUE THREAD

**Issue by PoPoutdoor** [owncloud/mail#1076]
![sc](https://cloud.githubusercontent.com/assets/1781047/9866173/d84da718-5b91-11e5-9751-e290ac787dfb.jpg)

Browser: Firefox 38.2.1

**Comment by ChristophWurst** [comment]
It's white because the sidebar is also white in core 8.2.

I don't think there's anything we can do against that. If we change it back to gray it looks odd on 8.1 and lower…

@jancborchardt

**Comment by PoPoutdoor** [comment]
@ChristophWurst If coming Mail app version only supports Owncloud 8.2 and later, that's OK.

**Comment by ChristophWurst** [comment]
> @ChristophWurst If coming Mail app version only supports Owncloud 8.2 and later, that's OK.

I assume we'll still support OC 7 and better

**Comment by PoPoutdoor** [comment]
Sorry guys! I'm not aware clicked the close button.

**Comment by jancborchardt** [comment]
If anyone is up to put in a case logic where it’s styled differently for pre 8.2 ownClouds, go ahead. :)

**Comment by jancborchardt** [comment]
I’ll close since it’s a minor visual glitch and we focus on newer releases for now since we’re only at 0.2 anyway.
