### ISSUE TITLE
Blocked image error in owncloud log

### ISSUE THREAD

**Issue by PoPoutdoor** [owncloud/mail#1077]
https://github.com/owncloud/mail/blob/master/lib/service/htmlpurify/transformimagesrc.php#L57

Browser: Firefox 38.2.1

**Comment by ChristophWurst** [comment]
@jakobsack any idea?

**Comment by ChristophWurst** [comment]
@PoPoutdoor could you please post the log entry you are talking about? thanks

**Comment by jakobsack** [comment]
@ChristophWurst: I think I didn't check whether `$attr['style']` is set. This could throw a warning. 

@PoPoutdoor: is this asumption correct?

I'll fix it later today
