### ISSUE TITLE
[Nightly-20150915] Blocked image - trigger CSP violation.

### ISSUE THREAD

**Issue by PoPoutdoor** [owncloud/mail#1085]
Console message:

Content Security Policy: 頁面的設定阻擋了 *(translation: Page setting stop)* data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAABmJLR0QA/wD/AP+gvaeTAAAADUlEQVQI12NgYGBgAAAABQABXvMqOgAAAABJRU5ErkJggg== 的資源載入*(translation: loading resource)*:（「img-src http://127.0.0.1」）。

**Comment by ChristophWurst** [comment]
@jakobsack I think that could be a problem with blocking images

**Comment by ChristophWurst** [comment]
@PoPoutdoor you don't have to mention the nightly version in the title – just add it to the issue description ;-)

**Comment by jakobsack** [comment]
OK, that's my fault. Do you know how I can extend the CSP? Or do I have to use a real image?

**Comment by enoch85** [comment]
@PoPoutdoor Remember, the nighlty builds are updated every 12 hours. It dosen´t follow the master after every commit. :)

**Comment by PoPoutdoor** [comment]
@enoch85 I will check the commits on Master before post an issue.
