### ISSUE TITLE
Replying to mail cuts off the name of recipient

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/mail#1111]
When you reply to a mail from `"Ada Lovelace" <ada@example.org>` then the name will be cut off, only leaving the email address.

@ChristophWurst @irgendwie @Gomez to the rescue. ;)

**Comment by jancborchardt** [comment]
@irgendwie @Gomez @zinks- @ChristophWurst @Henni @oparoz this is reeeally the most annoying functionality issue at the moment. :\ Anyone up for fixing it?

**Comment by ChristophWurst** [comment]
Let's have a look at it…
