### ISSUE TITLE
Mail addresses with underscore _ can not be added

### ISSUE THREAD

**Issue by jbyvosges** [owncloud/mail#1113]
In Personal address mail the response was always : "invalid address mail".
I think it is because my address mail contains an underscore character "_". I have to put my address directly into mysql tables

**Comment by aspdye** [comment]
Can you please give us more information (like Version and Mailserver [Google, selfhosted, ...])

I will reproduce it ;)

**Comment by jbyvosges** [comment]
My email is j_lbarbry  at  yahoo.fr
My ownCloud : 8.1.3
The adress mail in Personnal page (above "Fill in an email address to enable password recovery and ...)
The message is "Invalid mail address" 
But it works once entered in mysql tables

**Comment by tapir** [comment]
same for me. owncloud 8.1.3. fresh install.
it wasn't like that with 8.1.1

**Comment by tapir** [comment]
@jbyvosges which table is it in? I don't see an email column in users table.

**Comment by jbyvosges** [comment]
@tapir : table oc_preferences
userid : your userid
appid : settings
configkey : email
configvalue : your email

**Comment by tapir** [comment]
Worked like a charm thanks

**Comment by jancborchardt** [comment]
It worked with 8.1.1 but doesn’t anymore with 8.1.3? Anything we changed on this front with those versions? @LukasReschke @DeepDiver1975

**Comment by ChristophWurst** [comment]
@jancborchardt  this is not an issue of the mail app, is it?

**Comment by aspdye** [comment]
It is not, becasue this error behaves diffrent on several ownCloud Versions :wink:

**Comment by ChristophWurst** [comment]
> It is not, becasue this error behaves diffrent on several ownCloud Versions :wink:

That's not my point. Those email settings are something that is set in owncloud core, not the mail app. I'll close this issue here. If the error still occurs, please open an issue in the owncloud core-repo. Thanks.
