### ISSUE TITLE
No app-navigation-accounts & folder listing

### ISSUE THREAD

**Issue by Gomez** [owncloud/mail#1116]
Noticed this the second time on two different installations:

![mail](https://cloud.githubusercontent.com/assets/48724/10116760/3d8c043e-643f-11e5-9aee-a455def9b6aa.png)

No JS Error or PHP Error. I tested with 8.0.7 & 8.1.3.

@ChristophWurst Never seen this? On a new ownCloud install?

**Comment by ChristophWurst** [comment]
Nope, haven't seen something like that so far

**Comment by Gomez** [comment]
My PHP Version: PHP 5.5.9-1ubuntu4.13 Development

**Comment by enoch85** [comment]
Any news on this? 

PHP 5.6
Server 8.2.2
Mail 0.2.1

**Comment by ChristophWurst** [comment]
Does that also happen with a recent nightly build?

**Comment by ChristophWurst** [comment]
@Gomez ping

**Comment by Gomez** [comment]
Never happened to me again. @enoch85 Reopen if you still has the problem.
