### ISSUE TITLE
Set up a demonstation site

### ISSUE THREAD

**Issue by imsoftware** [owncloud/mail#1119]

**Comment by DeepDiver1975** [comment]
I advise against this - since we need an imap/smtp server to connect to this could really be missused.
In addition this is a hell of work ... for what?

It's actually easy to install the app and test it.

Closing - THX

**Comment by aspdye** [comment]
@DeepDiver1975 Maybe we should integrate "Mail" to the ownCloud Demo ;) Somebody (me to) could provide an IMAP/SMTP Server not allowing to send and recive emails. (with Firewall-Blocks)

I understand your point of view (and I also dont think that this is one of the essential problems) but yeah...why not creating an demo?

**Comment by DeepDiver1975** [comment]
> I understand your point of view (and I also dont think that this is one of the essential problems) but yeah...why not creating an demo?

feel free to get in touch with scalability-junk on IRC - he is running the demo site. THX
