### ISSUE TITLE
Unified inbox doesn't work with > PHP 5.6

### ISSUE THREAD

**Issue by enoch85** [owncloud/mail#1121]
Just upgraded to PHP 5.6 and I can't see the folders in Unified Inbox anymore:

![image](https://cloud.githubusercontent.com/assets/4511254/10354510/e3d68614-6d60-11e5-89f4-bf4c8f3c539a.png)

Mail 0.3 (stable)

**Comment by Gomez** [comment]
Thanks @enoch85. Maybe related to #1116

**Comment by Gomez** [comment]
What was the version you run before?

**Comment by enoch85** [comment]
@Gomez 5.5

**Comment by enoch85** [comment]
Any update on this?

**Comment by jancborchardt** [comment]
Seems like something we need to fix for 0.3 @ChristophWurst @Gomez @irgendwie?

**Comment by irgendwie** [comment]
ArchLinux with PHP 5.6.15 and every owncloud stuff on master - no problems here, can't reproduce...

**Comment by jancborchardt** [comment]
Moving to the backlog then

**Comment by enoch85** [comment]
Just as a reference, Ubuntu Server 14.04. Upgraded to PHP 5.6 with the Ondrej PPA.

**Comment by irgendwie** [comment]
@enoch85 Installed Ubuntu Server 14.04 in a VM and also installed the php5.6 version from Ondrej PPA - can't reproduce the issue there! Everything works as expected!

Did you try removing and readding the mail accounts? Did you try cleaning localStorage, offline website data and cache? Did you try accessing the mail app in a private window/tab?

If it still fails, I have no idea what is going wrong, sry!

**Comment by enoch85** [comment]
@irgendwie Thanks for trying. I just tested to clear the app from DB and remove it from the apps dir - reinstalled it, and still same issue.

Any advice where to check for errors?

**Comment by enoch85** [comment]
Tested. Works.
