### ISSUE TITLE
»Could not find resource files« after installation

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/mail#1122]
I followed the setup process with the `install_ubuntu.sh` but the Mail app is stuck in loading state. Getting these errors in the log:

```
{"reqId":"NMA9QiPDigk9t12eIjAX","remoteAddr":"127.0.0.1","app":"mail","message":"Could not find resource file \"\/owncloud\/apps\/mail\/js\/vendor\/autosize\/jquery.autosize.js\"","level":3,"time":"2015-10-10T05:24:41+00:00"}
{"reqId":"NMA9QiPDigk9t12eIjAX","remoteAddr":"127.0.0.1","app":"mail","message":"Could not find resource file \"\/owncloud\/apps\/mail\/js\/vendor\/jQuery-Storage-API\/jquery.storageapi.js\"","level":3,"time":"2015-10-10T05:24:41+00:00"}
{"reqId":"NMA9QiPDigk9t12eIjAX","remoteAddr":"127.0.0.1","app":"mail","message":"Could not find resource file \"\/owncloud\/apps\/mail\/js\/vendor\/jquery-visibility\/jquery-visibility.js\"","level":3,"time":"2015-10-10T05:24:41+00:00"}
{"reqId":"NMA9QiPDigk9t12eIjAX","remoteAddr":"127.0.0.1","app":"mail","message":"Could not find resource file \"\/owncloud\/apps\/mail\/js\/vendor\/requirejs\/require.js\"","level":3,"time":"2015-10-10T05:24:41+00:00"}
{"reqId":"NMA9QiPDigk9t12eIjAX","remoteAddr":"127.0.0.1","app":"mail","message":"Could not find resource file \"\/owncloud\/apps\/mail\/js\/mail.min.js\"","level":3,"time":"2015-10-10T05:24:41+00:00"}
```
Similar in the JS console. What did I miss?
@ChristophWurst @irgendwie @Gomez? :)

**Comment by Gomez** [comment]
@jancborchardt Sorry Readme and install scripts are outdated. I need to work on it. But needs to wait for another week :(

**Comment by jancborchardt** [comment]
@Gomez can you give me the correct instructions manually meanwhile? Can’t use Mail otherwise. :\

**Comment by Gomez** [comment]
You miss the bower stuff:
./node_modules/.bin/bower install

**Comment by jancborchardt** [comment]
Still the same issues after a bower install …

**Comment by ChristophWurst** [comment]
> Still the same issues after a bower install …

The first four errors should be resolved after bower install. Can you confirm that?

One way of fixing it is to switch to PR #1093 and run ``make optimize-js``. That should pull all dependencies and generate the minified javascript ``mail.min.js`` file.

**Comment by jancborchardt** [comment]
@ChristophWurst cool, that fixed it. Can we merge that then and update the install script/docs so it’s only one command to run for a full dev install?

**Comment by jancborchardt** [comment]
@ChristophWurst @Gomez any updates on the command? Is it one now?

**Comment by ChristophWurst** [comment]
> @ChristophWurst @Gomez any updates on the command? Is it one now?

Yes, ``make optimize-js`` pulls all dependencies (PHP+JS) and creates the optimized js file.

**Comment by jancborchardt** [comment]
Awesome! :)
