### ISSUE TITLE
Improper escaping in cc field when replying

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/mail#1130]
Looks like this:
```
"&#x27;Name&#x27;" <email@example.com>
```

Any idea? @irgendwie @PoPoutdoor @zinks- @ChristophWurst @Gomez 
Makes replying really awkward, so setting to priority.

**Comment by ChristophWurst** [comment]
Does that happen all the time? I couldn't reproduce that on my system.

Where did you see the wrongly encoded name? Inside the 'to' field when composing or after sending the mail?

**Comment by irgendwie** [comment]
Not reproducible for me either... Is this still occurring @jancborchardt?

**Comment by itheiss** [comment]
Same to me. Unable to reproduce ...

**Comment by jancborchardt** [comment]
Yeah, can’t reproduce anymore either. :)

**Comment by jancborchardt** [comment]
This can be reproduced with messages which were loaded inline after opening the email app. (The ones which are also missing the color bar, in the unified inbox. ;)

**Comment by PoPoutdoor** [comment]
Just test with latest nightly, with Chinese character in to/cc field:

> to: "中文字測試" <xxxxxx@example.com>
> cc: "中文字顯示" <xxxxxx@example.com>

In Unified Inbox view, cc field is missing
In Account folder view, both fields display correctly

I guess code in Unified Inbox is not patch with UTF-7 fix yet.

**Comment by jancborchardt** [comment]
@xn--nding-jua @clementhk do you want to take a look at this? :)

**Comment by PoPoutdoor** [comment]
Dig up RFC5738: https://tools.ietf.org/html/rfc5738#section-1

Does current code support **UTF8=ACCEPT IMAP Capability** ?

**Comment by clementhk** [comment]
Guys, test it in the email content, if it comes out weird then it's that unicode problem, I'm guessing the problem would be where we parse email address, but again I'm not sure.
If you can write a test to reproduce then I could help to fix it.

**Comment by PoPoutdoor** [comment]
@clementhk Been test with CJK characters in email content some time ago, no decoding problem. Can you post the mail header?

**Comment by jancborchardt** [comment]
Ok, fixed for me now it seems. :D

**Comment by jancborchardt** [comment]
Dang … actually still happens. @DeepDiver1975 with our ownCloud mailserver at least, can you reproduce?

**Comment by jancborchardt** [comment]
New finding: This doesn’t have anything to do with only the emails which are just loaded. It happens for emails from specific people. Can’t make out a pattern yet. Maybe Microsoft Outlook.

**Comment by jancborchardt** [comment]
Found! The problem is when the person sending an email uses single apostrophes to frame the name. Send an email to:

> 'Name' <email@example.com>

and it will be displayed as:

> "&#x27;Name&#x27;" <email@example.com>

We should escape framing single apostrophes as well as double ones.

**Comment by jancborchardt** [comment]
Pull request to test: https://github.com/owncloud/mail/pull/1169
