### ISSUE TITLE
Mail app broken after OC 8.2 update?

### ISSUE THREAD

**Issue by briskspirit** [owncloud/mail#1137]
Hi. 

Installed Mail app on 8.1.3 and all was fine, but after update I see spinning wheels and message about "can't fetch account details"(or so, as it is translated)

And got error message into log file:
Class OCA\Mail\Service\Logger contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (OCP\ILogger::logException) at /var/www/owncloud/apps/mail/lib/service/logger.php#99

**Comment by Trevelian** [comment]
Hello, just to confirm, I have the same issue with the update 8.2.
PHP 5.6.14  -  Apache/2.4.16

Thanks,
Trevelian.

**Comment by niemalsnever** [comment]
Hello, I also have this issue with OwnCloud 8.2, it just says "Error loading the accounts".
PHP 5.6.3 - Apache/2.2.15 (CentOS)

Greetings,
niemalsnever

**Comment by Jaimy85** [comment]
I added the logException line from this site in file /var/www/owncloud/apps/mail/lib/service/logger.php, somehow this was not in the distributed app:

	public function logException(\Exception $exception, array $context = array()) {
		$this->logger->logException($exception, array_merge($this->context, $context));
	}

**Comment by briskspirit** [comment]
Yep, it helped, but how some UI problems on "new account" page )

**Comment by niemalsnever** [comment]
What do you mean by UI problems? I just tried that solution too and it worked for me. No issues on the new account page.

**Comment by briskspirit** [comment]
Because of my language pack. (Strange, but on 8.1.3 was all fine)
![1](https://cloud.githubusercontent.com/assets/11968822/10623515/50c8c2aa-7798-11e5-9f03-dc4e9800a0c6.png)

**Comment by briskspirit** [comment]
This is because of my language, but on 8.1.3 was fine

![1](https://cloud.githubusercontent.com/assets/11968822/10623550/98deabcc-7798-11e5-8ac9-410e54885504.png)

**Comment by briskspirit** [comment]
Hm, strange... Creating account failed: Error connecting to mail server.
But all credentials same as before

**Comment by DeepDiver1975** [comment]
@gomez looks like we need to publish a New mail app to the appstor

**Comment by briskspirit** [comment]
Tried to install app from github 0.3-alpha and got "dead" OC with some request id and not working. Helped only to remove mail dir from apps and removing mail preferences from DB.

**Comment by Gomez** [comment]
@DeepDiver1975 I think 0.3 is not ready. Lets do a update to the 0.2, tonight

**Comment by briskspirit** [comment]
0.2.1? to see difference in appstore

**Comment by Gomez** [comment]
@briskspirit I think so, we will comment here as soon as the release is in the appstore

**Comment by aspdye** [comment]
What about pushing the fixes already finished (form 0.3 - refactoring) into the 0.2.1 update?

**Comment by Gomez** [comment]
@aspdye The 0.3 is not yet ready. We have some bugs and regressions. But we will try to fix them soon.

**Comment by hitam4450** [comment]
I installed OC 8.2 as a clean install and enabled mail. Loading the page i receive the error: Could not load the account and the spinner is working indefinite.. No account has been defined yet !

regards, hitam4450

**Comment by briskspirit** [comment]
Look for Jamie85 comment how to fix that.

**Comment by hitam4450** [comment]
OK, thanks. I added the lines at the end of the file, now it works. it shows the main page.

**Comment by Gomez** [comment]
Fix is just released and uploaded to the app store: https://apps.owncloud.com/content/show.php/Mail?content=169914

**Comment by briskspirit** [comment]
Confirmed to work, but UI theme still with bugs.. (see screen in upper posts)

**Comment by Gomez** [comment]
@briskspirit Ok, would you be so nice to open a new issue for this bug?

**Comment by briskspirit** [comment]
ok...
