### ISSUE TITLE
i think installing the mail app has ruined my contacts

### ISSUE THREAD

**Issue by lachlan-00** [owncloud/mail#1142]
After trying the mail app this morning i've gone from 305 contacts syncing with davdroid to 18.

I'm not sure what else could have caused this; adding mail was the only change.

i've reflashed my rom and just in case and it's still missing the same amount of contacts

**Comment by lachlan-00** [comment]
(BAD Contact)
BEGIN:VCARD
VERSION:3.0
X-UNKNOWN-ELEMENT;TYPE=ÿþName:13health
N:;13health
PHONE1.PHONE;TYPE=Work:99999999
FN:13health 
UID:d0c73696-962c-40c0-bfa1-d8ef2ed99199@lachlandewaard.org
REV:2015-03-31T00:23:18+00:00
PRODID:-//ownCloud//NONSGML Contacts 0.3.0.16//EN
CATEGORIES:Business
TEL;TYPE=WORK;TYPE=WORK:13432584
END:VCARD

(Good Contact)

BEGIN:VCARD
VERSION:3.0
UID:df1459a8-8189-45a7-880d-f604170546a6
FN:Ben Recruiting
N:Recruiting;Ben;;;
TEL;TYPE=cell:(99) 9999 9999
PRODID:-//ownCloud//NONSGML Contacts 0.3.0.18//EN
REV:2015-09-14T03:53:12+00:00
CATEGORIES:Business
END:VCARD

**Comment by Gomez** [comment]
I don't think we write anything to contacts. But this needs to be sorted out. 
@ChristophWurst @jakobsack Is this correct? We are only read-only from contacts

**Comment by lachlan-00** [comment]
I've just done an upgrade to 8.2 and it looks like things are coming back. The data for the missing contacts hasn't changed as well.

I think i may have jumped the gun on mail. it's probably something else.

**Comment by Gomez** [comment]
Ok, i will close this. Maybe @ChristophWurst & @jakobsack still anwsers ...

Thx for report back @lachlan-00

**Comment by ChristophWurst** [comment]
> I don't think we write anything to contacts. But this needs to be sorted out.
> @ChristophWurst @jakobsack Is this correct? We are only read-only from contacts

Exactly. Other than reading contact data, we don't really touch anything.
