### ISSUE TITLE
composer.lock issue or question

### ISSUE THREAD

**Issue by Xefir** [owncloud/mail#1143]
I wondering why the composer.lock is part of the repository.
The file change each time you do a composer install or update and git wants to push it, witch is annoying.

Is there a reason to keep it under versioning control ?
Could it be on .gitignore ?

Thanks for your answers :)

**Comment by Gomez** [comment]
The composer.lock is our pinning for the dependencies. It needs to be in version control. You just need to do composer install.
See this info:
https://getcomposer.org/doc/01-basic-usage.md#composer-lock-the-lock-file

Closing this, if i am wrong we reopen.

**Comment by Xefir** [comment]
You're right, i didn't understand how this file works.
Thank you and sorry for the inconvenience ^^"
