### ISSUE TITLE
Error while loading the selected account (Courier-Imap)

### ISSUE THREAD

**Issue by Aesculapius** [owncloud/mail#1146]
As referenced in this ticket - same problem - the last version of the mail app (or since 8.1), our IMAP server (Courier) cannot be added/read by the app.

### Steps to reproduce
1. Add Courier imap account
2. 
3.

### Expected behaviour
Account added and mail shown

### Actual behaviour
Error shown: error while loading the selected account

### Server configuration
**Operating system**: Ubuntu 14.04

**Web server:** Apache 2.4.7

**Database:** MySql 5.5.4.4

**PHP version:** 5.5.9

**ownCloud version:** (see ownCloud admin page) 8.1.3

**Updated from an older ownCloud or fresh install:** updated

**List of activated apps:**
Enabled:
 - activity: 2.0.2
 - delete_confirmation: 1.0.1
 - documents: 0.10.2
 - files: 1.1.10
 - files_mv: 0.8.1a
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - galleryplus: 14.3.0
 - provisioning_api: 0.2
 - sharelinks: 1.0.1

**The content of config/config.php:**
$CONFIG = array (
  'instanceid' => 'instance',
  'passwordsalt' => 'salt',
  'datadirectory' => '/yoda/cloudstore/data/',
  'dbtype' => 'mysql',
  'version' => '8.1.3.0',
  'dbname' => 'db_owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'dbpassword' => 'secret',
  'overwritewebroot' => '/',
  'installed' => true,
  'forcessl' => true,
  'maintenance' => false,
  'trashbin_retention_obligation' => '30',
  'preview_libreoffice_path' => '/usr/bin/libreoffice',
  'theme' => '',
  'has_internet_connection' => true,
  'check_for_working_webdav' => true,
  'check_for_working_htaccess' => true,
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'trusted_domains' =>
  array (
    0 => 'arc.int32.nl',
  ),
  'mail_from_address' => 'info',
  'mail_smtpmode' => 'php',
  'mail_domain' => 'laurensdegroot.nl',
  'secret' => 'bladibla',
  'asset-pipeline.enabled' => true,
  'preview_max_scale_factor' => 1,
  'forceSSLforSubdomains' => true,
  'app.mail.imaplog.enabled' => true
);

**Are you using external storage, if yes which one:** local/smb/sftp/... no

**Are you using encryption:** no 

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Chrome

**Operating system:** Windows 10

#### ownCloud log (data/owncloud.log)
{"reqId":"qjrQ+lPmv374L5ponyAY","remoteAddr":"175.176.218.166","app":"index","message":"Exception: {\"Exception\":\"Horde_Imap_Client_Exception_ServerResponse\",\"Message\":\"IMAP error reported by server.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www_ssl\\\/apps\\\/mail\\\/vendor\\\/pear-pear.horde.org\\\/Horde_Imap_Client\\\/Horde\\\/Imap\\\/Client\\\/Socket.php(4301): Horde_Imap_Client_Socket->_getLine(Object(Horde_Imap_Client_Interaction_Pipeline))\\n#1 \\\/var\\\/www_ssl\\\/apps\\\/mail\\\/vendor\\\/pear-pear.horde.org\\\/Horde_Imap_Client\\\/Horde\\\/Imap\\\/Client\\\/Socket.php(4229): Horde_Imap_Client_Socket->_sendCmdChunk(Object(Horde_Imap_Client_Interaction_Pipeline), Array)\\n#2 \\\/var\\\/www_ssl\\\/apps\\\/mail\\\/vendor\\\/pear-pear.horde.org\\\/Horde_Imap_Client\\\/Horde\\\/Imap\\\/Client\\\/Socket.php(1748): Horde_Imap_Client_Socket->_sendCmd(Object(Horde_Imap_Client_Interaction_Pipeline))\\n#3 \\\/var\\\/www_ssl\\\/apps\\\/mail\\\/vendor\\\/pear-pear.horde.org\\\/Horde_Imap_Client\\\/Horde\\\/Imap\\\/Client\\\/Base.php(1724): Horde_Imap_Client_Socket->_status(Array, 1)\\n#4 \\\/var\\\/www_ssl\\\/apps\\\/mail\\\/lib\\\/mailbox.php(152): Horde_Imap_Client_Base->status(Object(Horde_Imap_Client_Mailbox), 1)\\n#5 \\\/var\\\/www_ssl\\\/apps\\\/mail\\\/lib\\\/mailbox.php(159): OCA\\\\Mail\\\\Mailbox->getStatus(1)\\n#6 \\\/var\\\/www_ssl\\\/apps\\\/mail\\\/lib\\\/account.php(503): OCA\\\\Mail\\\\Mailbox->getTotalMessages()\\n#7 \\\/var\\\/www_ssl\\\/apps\\\/mail\\\/lib\\\/account.php(534): OCA\\\\Mail\\\\Account->guessBestMailBox(Array)\\n#8 \\\/var\\\/www_ssl\\\/apps\\\/mail\\\/lib\\\/account.php(372): OCA\\\\Mail\\\\Account->getSpecialFolder('inbox', true)\\n#9 \\\/var\\\/www_ssl\\\/apps\\\/mail\\\/lib\\\/account.php(568): OCA\\\\Mail\\\\Account->getSpecialFoldersIds(false)\\n#10 \\\/var\\\/www_ssl\\\/apps\\\/mail\\\/lib\\\/account.php(299): OCA\\\\Mail\\\\Account->localizeSpecialMailboxes()\\n#11 \\\/var\\\/www_ssl\\\/apps\\\/mail\\\/lib\\\/account.php(527): OCA\\\\Mail\\\\Account->getMailboxes()\\n#12 \\\/var\\\/www_ssl\\\/apps\\\/mail\\\/lib\\\/account.php(405): OCA\\\\Mail\\\\Account->getSpecialFolder('inbox', false)\\n#13 \\\/var\\\/www_ssl\\\/apps\\\/mail\\\/lib\\\/service\\\/unifiedaccount.php(68): OCA\\\\Mail\\\\Account->getInbox()\\n#14 \\\/var\\\/www_ssl\\\/apps\\\/mail\\\/lib\\\/service\\\/unifiedaccount.php(47): OCA\\\\Mail\\\\Service\\\\UnifiedAccount->buildInbox()\\n#15 \\\/var\\\/www_ssl\\\/apps\\\/mail\\\/lib\\\/controller\\\/folderscontroller.php(61): OCA\\\\Mail\\\\Service\\\\UnifiedAccount->getListArray()\\n#16 [internal function]: OCA\\\\Mail\\\\Controller\\\\FoldersController->index(-1)\\n#17 \\\/var\\\/www_ssl\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(159): call_user_func_array(Array, Array)\\n#18 \\\/var\\\/www_ssl\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Mail\\\\Controller\\\\FoldersController), 'index')\\n#19 \\\/var\\\/www_ssl\\\/lib\\\/private\\\/appframework\\\/app.php(108): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Mail\\\\Controller\\\\FoldersController), 'index')\\n#20 \\\/var\\\/www_ssl\\\/lib\\\/private\\\/appframework\\\/routing\\\/routeactionhandler.php(45): OC\\\\AppFramework\\\\App::main('FoldersControll...', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#21 [internal function]: OC\\\\AppFramework\\\\routing\\\\RouteActionHandler->__invoke(Array)\\n#22 \\\/var\\\/www_ssl\\\/lib\\\/private\\\/route\\\/router.php(274): call_user_func(Object(OC\\\\AppFramework\\\\routing\\\\RouteActionHandler), Array)\\n#23 \\\/var\\\/www_ssl\\\/lib\\\/base.php(874): OC\\\\Route\\\\Router->match('\\\/apps\\\/mail\\\/acco...')\\n#24 \\\/var\\\/www_ssl\\\/index.php(40): OC::handleRequest()\\n#25 {main}\",\"File\":\"\\\/var\\\/www_ssl\\\/apps\\\/mail\\\/vendor\\\/pear-pear.horde.org\\\/Horde_Imap_Client\\\/Horde\\\/Imap\\\/Client\\\/Socket.php\",\"Line\":4589}","level":4,"time":"2015-10-30T08:17:05+00:00"}

**Comment by Xenopathic** [comment]
Could you enable the debug mode as described [in the README](https://github.com/owncloud/mail#debug-mode) and post the contents of the generated `horde.log` (removing any sensitive information)?

**Comment by jancborchardt** [comment]
Closing cause of missing info. @Aesculapius if you want us to fix it, please provide the info as @Xenopathic noted. :)

**Comment by Aesculapius** [comment]
Sorry for the delay, I kinda missed this post. The problem still exists though, even with the latest nightly.
My horde.log is as follows:

------------------------------
>> Mon, 22 Feb 2016 19:49:55 +0000
>> Connection to: imap://hostname.eu:9930/
>> Server connection took 0.4505 seconds.
S: * OK [CAPABILITY IMAP4rev1 UIDPLUS CHILDREN NAMESPACE THREAD=ORDEREDSUBJECT THREAD=REFERENCES SORT QUOTA IDLE AUTH=PLAIN ACL ACL2=UNION] Courier-IMAP ready. Copyright 1998-2011 Double Precision, Inc.  See COPYING for distribution information.
C: 1 [INITIAL CLIENT RESPONSE (username: mailuser)]
S: +
C: bWFpbHVzcgBtYWlsdXNyAHNob3Jvcyg1OA==
S: 1 OK LOGIN Ok.
>> Command 1 took 0.1183 seconds.
C: 2 CAPABILITY
S: * CAPABILITY IMAP4rev1 UIDPLUS CHILDREN NAMESPACE THREAD=ORDEREDSUBJECT THREAD=REFERENCES SORT QUOTA IDLE AUTH=PLAIN ACL ACL2=UNION
S: 2 OK CAPABILITY completed
>> Command 2 took 0.0069 seconds.
C: 3 LIST "" *
S: * LIST (\HasNoChildren) "." "INBOX.Sent.2012"
S: * LIST (\HasNoChildren) "." "INBOX.Archive.Bruiloft Ruud &- Manon.Aanzoek"
S: * LIST (\HasChildren) "." "INBOX.Twinklemedia.Oude correspondentie"
S: * LIST (\HasNoChildren) "." "INBOX.Drafts"
S: * LIST (\HasChildren) "." "INBOX.NVKI.Administratie ALG"
S: * LIST (\HasNoChildren) "." "INBOX.Archive.Vakantie NZ"
S: * LIST (\HasNoChildren) "." "INBOX.Twinklemedia.Oude correspondentie.Charles Poelmans"
S: * LIST (\HasNoChildren) "." "INBOX.Twinklemedia.Belasting_KvK_Bank"
S: * LIST (\HasChildren) "." "INBOX.NVKI.Bestuur"
S: * LIST (\HasNoChildren) "." "INBOX.Sent.2013"
S: * LIST (\HasNoChildren) "." "INBOX.Junk"
S: * LIST (\HasChildren) "." "INBOX.NVKI.Communicatie extern"
S: * LIST (\HasNoChildren) "." "INBOX.Anders.OwnCloud"
S: * LIST (\HasNoChildren) "." "INBOX.Anders.LinkedIn"
S: * LIST (\HasNoChildren) "." "INBOX.NVKI.Activiteiten.16 Werksessie Visie"
S: * LIST (\HasNoChildren) "." "INBOX.Twinklemedia.Hosting.Oude Hosting"
S: * LIST (\HasNoChildren) "." "INBOX.Sent.2010"
S: * LIST (\HasChildren) "." "INBOX.NVKI.Nieuwsbrieven"
S: * LIST (\HasNoChildren) "." "INBOX.Sent.2014"
S: * LIST (\HasNoChildren) "." "INBOX.NVKI.Commissies.Communicatie"
S: * LIST (\HasNoChildren) "." "INBOX.NVKI.Administratie ALG.Aanmeldingen"
S: * LIST (\HasChildren) "." "INBOX.NVKI.Financien"
S: * LIST (\HasNoChildren) "." "INBOX.NVKI.Financien.Contributie"
S: * LIST (\HasNoChildren) "." "INBOX.NVKI.Bestuur.Vergaderingen"
S: * LIST (\HasNoChildren) "." "INBOX.Sent.TUe 2011-2013"
S: * LIST (\HasNoChildren) "." "INBOX.Archive.Radboud_Siemens"
S: * LIST (\HasNoChildren) "." "INBOX.NVKI.Nieuwsbrieven.VMBI"
S: * LIST (\HasChildren) "." "INBOX.NVKI.Commissies"
S: * LIST (\HasNoChildren) "." "INBOX.Trash"
S: * LIST (\HasChildren) "." "INBOX.Archive"
S: * LIST (\HasNoChildren) "." "INBOX.Archive.2003-2010"
S: * LIST (\HasNoChildren) "." "INBOX.Anders.Twitter"
S: * LIST (\HasNoChildren) "." "INBOX.NVKI.Activiteiten.15 MIC"
S: * LIST (\HasNoChildren) "." "INBOX.Archive.LdeGroot@student_ru"
S: * LIST (\HasNoChildren) "." "INBOX.NVKI.Commissies.Onderwijs"
S: * LIST (\HasNoChildren) "." "INBOX.Twinklemedia.Oude correspondentie.Speedservice"
S: * LIST (\HasNoChildren) "." "INBOX.Deleted Items"
S: * LIST (\HasChildren) "." "INBOX.NVKI"
S: * LIST (\HasNoChildren) "." "INBOX.NVKI.Communicatie extern.TUe"
S: * LIST (\HasNoChildren) "." "INBOX.Sent.2009"
S: * LIST (\HasNoChildren) "." "INBOX.NVKI.Administratie ALG.Verzekeringen"
S: * LIST (\HasNoChildren) "." "INBOX.NVKI.Activiteiten.16 Stageplaatsen bemiddeling"
S: * LIST (\HasNoChildren) "." "INBOX.Twinklemedia.Hosting.Antagonist"
S: * LIST (\HasNoChildren) "." "INBOX.Sent.2011"
S: * LIST (\HasNoChildren) "." "INBOX.Junk E-mail"
S: * LIST (\HasNoChildren) "." "INBOX.Sent.2004-2007"
S: * LIST (\HasChildren) "." "INBOX.Sent"
S: * LIST (\HasNoChildren) "." "INBOX.Templates"
S: * LIST (\HasNoChildren) "." "INBOX.NVKI.Communicatie extern.NVKF"
S: * LIST (\HasChildren) "." "INBOX.NVKI.Activiteiten"
S: * LIST (\HasNoChildren) "." "INBOX.Anders.Rommel"
S: * LIST (\HasNoChildren) "." "INBOX.NVKI.Administratie ALG.Conscribo"
S: * LIST (\HasNoChildren) "." "INBOX.Sent Items"
S: * LIST (\HasNoChildren) "." "INBOX.Archive.TUe Archief"
S: * LIST (\HasNoChildren) "." "INBOX.Archive.Bruiloft Ruud &- Manon.Vrijgezellen"
S: * LIST (\HasNoChildren) "." "INBOX.NVKI.Financien.Ingekomen Facturen"
S: * LIST (\HasNoChildren) "." "INBOX.NVKI.Communicatie leden"
S: * LIST (\HasNoChildren) "." "INBOX.NVKI.Activiteiten.16 Woudschoten"
S: * LIST (\HasNoChildren) "." "INBOX.NVKI.Financien.Ingekomen Offertes"
S: * LIST (\HasNoChildren) "." "INBOX.backup"
S: * LIST (\HasNoChildren) "." "INBOX.NVKI.Website &- LinkedIn"
S: * LIST (\HasNoChildren) "." "INBOX.Archive.QMI"
S: * LIST (\HasNoChildren) "." "INBOX.NVKI.Communicatie extern.Diversen"
S: * LIST (\HasNoChildren) "." "INBOX.NVKI.Bestuur.Bila Steph"
S: * LIST (\HasNoChildren) "." "INBOX.Kroew.gastenboek"
S: * LIST (\HasNoChildren) "." "INBOX.Sent.2008"
S: * LIST (\HasNoChildren) "." "INBOX.INBOX"
S: * LIST (\HasChildren) "." "INBOX.Kroew"
S: * LIST (\HasChildren) "." "INBOX.Twinklemedia"
S: * LIST (\HasNoChildren) "." "INBOX.Twinklemedia.Oude correspondentie.Beenackers Milieu &- Tech"
S: * LIST (\HasChildren) "." "INBOX.Archive.Bruiloft Ruud &- Manon"
S: * LIST (\HasChildren) "." "INBOX.Twinklemedia.Hosting"
S: * LIST (\HasNoChildren) "." "INBOX.NVKI.Bestuur.ALV"
S: * LIST (\HasNoChildren) "." "INBOX.NVKI.Communicatie extern.BMTZ"
S: * LIST (\HasNoChildren) "." "INBOX.Twinklemedia.Oude correspondentie.Paul Jessen"
S: * LIST (\HasChildren) "." "INBOX.Anders"
S: * LIST (\HasNoChildren) "." "INBOX.Inbox.Operatie T"
S: * LIST (\HasNoChildren) "." "INBOX.NVKI.Commissies.Beroepsontwikkeling"
S: * LIST (\Unmarked \HasChildren) "." "INBOX"
S: * LIST (\Noselect \HasChildren) "." "INBOX.Inbox"
S: 3 OK LIST completed
>> Command 3 took 0.0248 seconds.
C: 4 STATUS INBOX (MESSAGES)
S: * STATUS "INBOX" (MESSAGES 1147)
S: 4 OK STATUS Completed.
>> Command 4 took 0.0223 seconds.
C: 5 STATUS INBOX (MESSAGES)
S: * STATUS "INBOX" (MESSAGES 1147)
S: 5 OK STATUS Completed.
>> Command 5 took 0.0218 seconds.
C: 6 STATUS INBOX.INBOX (MESSAGES)
S: * STATUS "INBOX.INBOX" (MESSAGES 1147)
S: 6 OK STATUS Completed.
>> Command 6 took 0.022 seconds.
C: 7 STATUS INBOX.Inbox (MESSAGES)
S: 7 NO Mailbox does not exist, or must be subscribed to.
>> Command 7 took 0.007 seconds.
C: 8 LOGOUT
S: * BYE Courier-IMAP server shutting down
S: 8 OK LOGOUT completed
>> Command 8 took 0.0068 seconds.
