### ISSUE TITLE
Enable for specific group

### ISSUE THREAD

**Issue by tflidd** [owncloud/mail#1150]
I can't enable the mail app only for a specific user group. When reading the documentation (https://doc.owncloud.org/server/8.1/admin_manual/installation/apps_management_installation.html#managing-apps) it seems to me that this has to be supported by an app.

If that is true, I'd like to request this feature. I think it can be very useful for testing (app is still in development) as you don't want to enable the app for everybody (yet).

**Comment by ChristophWurst** [comment]
@tflidd do you still need that feature?

**Comment by tflidd** [comment]
I just jused it in a test-setup. It would be nice to use it regularly but I don't want to make it available to everybody yet.

**Comment by ChristophWurst** [comment]
Maybe it depends on the core version in use, but I can enable the mail app for a specific group:
![bildschirmfoto von 2016-04-12 21-01-57](https://cloud.githubusercontent.com/assets/1374172/14472091/ca235ede-00f1-11e6-9ef5-eadca1d7e2ad.png)

Could you please check again?

**Comment by tflidd** [comment]
Great, it works on OC 8.2.3 :smile: On a test setup on OC 9.0.1 as well. So it seems that the latest versions do support it. I currently don't have an old version to test it.

**Comment by ChristophWurst** [comment]
@tflidd good to hear, thanks for testing :-)
