### ISSUE TITLE
Line breaks inserted for sent mail [$50]

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/mail#1151]
I just sent a mail out of the unified inbox and it seems like the Mail app forced some line breaks in there to keep it to ~70 characters a line. This should not happen. :)

@ChristophWurst @Gomez @irgendwie we didn’t do that before, right?

**Comment by ChristophWurst** [comment]
was the original mail a HTML mail?

**Comment by jancborchardt** [comment]
Nope, this happens when I write a completely new mail from the Mail app. Just did it (hacking here with @Gomez) – if you want to look into it then we will check out something else. :)

**Comment by ChristophWurst** [comment]
Hm, strange. I hope you guys are hacking on the mail app ;-)
I'm too busy for mail app hacking at the moment, I just had a look at the last remaining issues for 0.3.

**Comment by jancborchardt** [comment]
Interestingly enough, this doesn’t show in other clients such as Thunderbird. Does this have something to do with link detection or something else we parse in the text?

**Comment by Gomez** [comment]
Ok, this happens here:
https://github.com/owncloud/mail/blob/master/lib/account.php#L177

Before `$raw` everything is fine, mail gets send without line breaks. Than `$mail->getRaw()` messed it up.
@ChristophWurst You have a idea?

**Comment by ChristophWurst** [comment]
@Gomez the message is sent [here](https://github.com/owncloud/mail/blob/master/lib/account.php#L172). If ``$mail->getRaw()``then inserts those mysterious line breaks than that should only effect the message that is saved to the sent-folder, but not the actual message that is sent via SMTP.

I tried to locate the bug some weeks ago by going through the code step-by-step but couldn't really find out what's going wrong there.

**Comment by jancborchardt** [comment]
Why should those line breaks even be in the message which is saved to the sent folder?

**Comment by Gomez** [comment]
@ChristophWurst Right. The message gets send correctly. The linebreaks are only in the sent folder. Still Thunderbird dont show them. I will dig deeper...

**Comment by Gomez** [comment]
Ok, this drives my crazy :( With saveDrafts its the same (easier to reproduce):
https://github.com/owncloud/mail/blob/master/lib/account.php#L219
Reproduce
1. Click "New message"
2. Fill in body text without line breaks 
3. Click on drafts folder 
= line breaks in the saved draft (<br>)

I looked into horde/imp how they save the send mails, but cant really find it. getRaw() is rarly used. I suspect there is something wrong with toString() or the stream (inside the horde stuff)?

**Comment by jancborchardt** [comment]
Do we need to call on some Horde folks to help? Or does the issue lie on our side?

**Comment by Gomez** [comment]
Yes, maybe  @yunosh can help? Would be really cool!

**Comment by Gomez** [comment]
As this is already a bug in 0.2 we move it to 0.3.1.

**Comment by jancborchardt** [comment]
Moving to 0.5 cause this is a major issue atm – causes mail threads to get longer and input to lag. Also it destroys replying essentially. And it just looks broken and a bit embarassing. :\

**Comment by ChristophWurst** [comment]
I also suspect ``getRaw`` to be the root of this problem as the content of the message is written correctly [here](https://github.com/owncloud/mail/blob/dd1d0ce1ac82a65de57892268446948c871e1279/lib/account.php#L233). The stream returned by ``getRaw`` contains those pesky line breaks however…

**Comment by jancborchardt** [comment]
Ka-ching! Put 25 $ on it cause this annoys me on a daily basis. ;)

**Comment by jancborchardt** [comment]
(Btw @DeepDiver1975 how about we have these changes to title and tags be done by an owncloud-bounty-bot instead of your own account again. ;) Just helps to differentiate.)

**Comment by Gomez** [comment]
@ChristophWurst We should report it to horde upstream? (As i remember correctly they dont use it often in horde/imp).

**Comment by yunosh** [comment]
FWIW, flowed text format solves a **lot** of issues with consistent line breaking, especially when replying messages and creating long, quoted threads.
It looks like you used flowed format (unintentionally via the Horde library), but didn't implement it properly in your own client. Instead of turning flowed format off, and thus making replying and quoting potentially a mess, you should rather implement formatting of flowed text format in your client, when viewing messages. As you can see from the Thunderbird example, using the correct technique makes the message display just fine.

**Comment by jancborchardt** [comment]
@ChristophWurst @Gomez what do you think about @yunosh’s note, regarding https://github.com/owncloud/mail/pull/1482

**Comment by jancborchardt** [comment]
Also @yunosh, can you maybe help with it? :) And thanks for letting us know first of all!

**Comment by ChristophWurst** [comment]
@yunosh the above makes sense, we should add that flow back, but as you said this time on the client side. The way it was before was really bad from a user's perspective as the message looked unexpectedly different when sent. Let me think about a solution for this…
