### ISSUE TITLE
Missing unicode handling for the colored "bobbles"

### ISSUE THREAD

**Issue by irgendwie** [owncloud/mail#1153]
It seems, there is no unicode handling in the colored "bobbles" :smiley: 
Still, in Contacts app for example it works without a problem:

![unicode_char](https://cloud.githubusercontent.com/assets/8360698/10981926/c70ea118-840a-11e5-95de-e2e704ef14f8.png)

**Comment by jancborchardt** [comment]
This is a core/server issue with the avatar code – can you reopen it there? :) cc @MorrisJobke
