### ISSUE TITLE
Contact Categories as Option for recipient fields (e.g. multiple BCC for Newsletters)

### ISSUE THREAD

**Issue by timreeves** [owncloud/mail#1154]
While this is a specific feature request, I think we need to view it in a larger context:

I use Thunderbird on my PC, it syncs fine via SOGo Connector with OC Contacts, including the VCARD Categories in both directions. But Thunderbird uses it's own Contact Lists for getting mulitple recipients - which SOGo Connector even tries to Sync, using a proprietary BEGIN:VLIST format which is only supported by SOGo, causing a carddav fatal exception in ownCloud: https://github.com/owncloud/contacts/issues/1095. I have added a note to the known problem with SOGo Connector: http://www.sogo.nu/bugs/view.php?id=1851

So using Thunderbird and syncing Contacts to OC currently precludes using Thunderbird contact lists; but OTOH Thunderbird does not offer any possibility to use the contact categories for multiple recipient selection. So I thought, well perhaps I can send my Newsletters from the OC-GUI (Mail App) and use categories there...

To my private contact on this idea, DeepDiver replied "vorstellbar is so ziemlich alles ;-)" - one can imagine pretty much anything - and suggested to raise an issue here... Done!

Anyway, I currently only see nasty options to get my newsletters sorted out:
* Look for a replacement for Thunderbird which meets all requirements
* Copy a load of Contacts in TB to a non-synced address book and use lists there
* Or check out this Plugin: https://addons.mozilla.org/de/thunderbird/addon/categorymanager/
* Fork (or contribute to) SOGo Connector and add an option to turn off syncing contact lists
* See if Android offers Recipients by Category and if so do Newsletters from my Tablet

Have I missed anything? Any good ideas?

Cheers!

Tim

**Comment by timreeves** [comment]
Ho hum, the Thunderbird Plugin [CategoryManager](https://addons.mozilla.org/de/thunderbird/addon/categorymanager/) in fact does do the job nicely: Just install it, then create a new mail and switch on the contacts sidebar (F9), and apply the Category Filter you need, then klick below on BCC. Great plugin! Still, it would be nice to have a similar feature in OC-Mail...

**Comment by jancborchardt** [comment]
@timreeves this seems to be a duplicate of https://github.com/owncloud/mail/issues/772 (Write mails to group of contacts (mailing list / groups)) – right?

**Comment by timreeves** [comment]
@jancborchardt yes, you are right - sorry that I did not manage to find #772 , I did try searching the forum and Google, but one often does not know the "magic" keywords to search for...
