### ISSUE TITLE
@owncloud/mail team

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/mail#1156]
I created a team for the Mail app in the ownCloud organization. This allows us and also all collaborators in the ownCloud organization to mention us as a whole using @owncloud/mail (like the designers group). This makes it very easy to mention people for pull request reviews as a whole group, and others know who is working on the mail app on one simple overview page.

Not sure if this is visible to people even outside of the ownCloud org: https://github.com/orgs/owncloud/teams/mail – even without that you can hover over the @-mention and see the names in the tooltip.

In the team are so far:
* @ChristophWurst
* @Gomez
* @irgendwie
* @enoch85 
* @jakobsack
* @LukasReschke
* @DeepDiver1975
* @jancborchardt

Anyone who _doesn’t_ want to be in it? You can always let us know. :)

And anyone who wants to be in it? I didn’t add some people so far like: @zinks- @PoPoutdoor @clementhk (mainly because they are not in the ownCloud org yet for some reason) and @itheiss @Henni @vgezer @colmoneill @xn--nding-jua @jas4711 since I didn’t know if you want to be mentioned and receive notifications. :) Let me know if you’re down and we can just add you.

**Comment by ChristophWurst** [comment]
nice!

**Comment by itheiss** [comment]
I am fine with it. My input is to little but I nevertheless watching you guys and the progress :-))

**Comment by Gomez** [comment]
cool

**Comment by enoch85** [comment]
:1

Best Regards
Daniel Hansson

www.en0ch.se

Sent from OnePlus Two, sorry for typos.

**Comment by clementhk** [comment]
It's because I'll need to sign something to get there and I'm a lazy man :)
In any case I'm still willing to help with complicated issue.

**Comment by PoPoutdoor** [comment]
I feel OK not in the team because I'm not good at coding anyway.
I'll continue allocate time for the testing part and provide feedback from user POV. :)

**Comment by jakobsack** [comment]
:+1:

**Comment by jancborchardt** [comment]
@itheiss ok, so should I add you or not? :)

@clementhk hehe :D You can also simply state that all your contributions will be MIT licensed (just comment here to that effect) and then @karlitschek can add you to the ownCloud organization. :) Your contributions are very appreciated!

@PoPoutdoor hehe, I’m not coding that much either – not only code contributions are important, your testing and feedback of functionality & usability is always helpful! Same as for Clement, just state that your contributions will be MIT licensed and @karlitschek can add you to the ownCloud organization. :)

**Comment by PoPoutdoor** [comment]
@jancborchardt I cannot commit more time for the project ATM, so don't want to be somebody that I'm not up to self standard.

Anyway, I concur my contributions (past & future of this project, if any) in MIT license terms.

**Comment by itheiss** [comment]
@jancborchardt Feel free to add me

**Comment by clementhk** [comment]
@karlitschek all my contributions will be MIT licensed

**Comment by karlitschek** [comment]
Great. Thanks!

**Comment by irgendwie** [comment]
@jancborchardt I'm ok with that - still I have little time at the moment (bachelor thesis) and spend my spare time currently with the contactsrework project of @Henni
