### ISSUE TITLE
mail crach oc

### ISSUE THREAD

**Issue by iacopodeenosee** [owncloud/mail#1158]
### Expected behaviour
functional mail app running into owncloud

### Actual behaviour
after install it, by clonig the github repo and checkout the verion 0.2.1, owncloud crash

### Server configuration
**Operating system**:
qnap system 4.2
**Web server:**
apache
**Database:**
sqlite3
**PHP version:**
```
/mnt/ext/opt/apache/bin/php --version
PHP 5.5.29 (cli) (built: Oct 23 2015 06:28:15) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies
```
**ownCloud version:** (see ownCloud admin page)
8.1.4
**Updated from an older ownCloud or fresh install:**
fresh install
**List of activated apps:**
calendar,task,maps,contact and all default stuff

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => 'ocjmfhc340mw',
  'passwordsalt' => 'blabla',
  'secret' => 'blabla',
  'trusted_domains' => 
  array (
    0 => '192.168.1.140:8081',
  ),
  'datadirectory' => '/share/CACHEDEV1_DATA/.qpkg/owncloud/owncloud/data',
  'overwrite.cli.url' => 'https://192.168.1.140:8081/owncloud',
  'dbtype' => 'sqlite3',
  'version' => '8.1.4.2',
  'logtimezone' => 'UTC',
  'installed' => true,
  'loglevel' => 0,
  'appstore.experimental.enabled' => true,
);
```
**Are you using encryption:** no

### Client configuration
**Browser:**
firefox 42
**Operating system:**
arch linux 64 

#### Web server error log
```
none logs
```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"2huQX0r+oOwz4FQz9nNe","remoteAddr":"192.168.1.102","app":"index","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"Cannot include autoload. Did you run install dependencies using composer?\",\"Code\":0,\"Trace\":\"#0 \\\/share\\\/CACHEDEV1_DATA\\\/.qpkg\\\/owncloud\\\/owncloud\\\/lib\\\/private\\\/app.php(139): require_once()\\n#1 \\\/share\\\/CACHEDEV1_DATA\\\/.qpkg\\\/owncloud\\\/owncloud\\\/lib\\\/private\\\/app.php(120): OC_App::requireAppFile('mail')\\n#2 \\\/share\\\/CACHEDEV1_DATA\\\/.qpkg\\\/owncloud\\\/owncloud\\\/lib\\\/private\\\/app.php(98): OC_App::loadApp('mail')\\n#3 \\\/share\\\/CACHEDEV1_DATA\\\/.qpkg\\\/owncloud\\\/owncloud\\\/lib\\\/base.php(858): OC_App::loadApps()\\n#4 \\\/share\\\/CACHEDEV1_DATA\\\/.qpkg\\\/owncloud\\\/owncloud\\\/index.php(48): OC::handleRequest()\\n#5 {main}\",\"File\":\"\\\/share\\\/CACHEDEV1_DATA\\\/.qpkg\\\/owncloud\\\/owncloud\\\/apps\\\/mail\\\/appinfo\\\/app.php\",\"Line\":6}","level":4,"time":"2015-11-13T15:03:13+00:00","method":"GET","url":"\/owncloud\/index.php\/settings\/apps"}
```

**Comment by PoPoutdoor** [comment]
@iacopodeenosee You have to install Mail from Owncloud Apps pulldown menu for the official version.

**Comment by iacopodeenosee** [comment]
@PoPoutdoor i can't install it from app page of oc, because in this page is not load the app center, for this error:
``` "reqId":"o6ScHys1XgxUUifEXZLt","remoteAddr":"192.168.1.102","app":"core","message":"Could not get application: cURL error 28: Operation timed out after 0 milliseconds with 0 out of 0 bytes received","level":3,"time":"2015-11-13T13:43:59+00:00","method":"GET","url":"\/owncloud\/index.php\/settings\/apps\/list?category=0&includeUpdateInfo=1"```

i thought that I could install it directly copying the source from github, and changed repo to latest version (0.2.1),
i think is the same version available in the [app center] (https://apps.owncloud.com/content/show.php/Mail?content=169914), i used this method for all other app (contact,calendar,maps,task) and they works well.

**Comment by DeepDiver1975** [comment]
Installations from git should follow the instructions - please consult the readme
