### ISSUE TITLE
New build process requires root / let’s put compiled files in the repo

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/mail#1160]
The new build process makes me unable to run Mail on my server. I can’t install the node dependencies, and make can’t be found.

@ChristophWurst @Gomez how about we put the compiled files in the repository? I did that in the `build` branch and using that Mail works fine on my server.

(@Henni also does this in the Contacts rework, which is very helpful for being able to directly run a git clone for testing without needing to compile first.)

**Comment by Gomez** [comment]
Does the Nightly builds (kind of) solve this?

Your proposed way, we need to compile the js min file everytime we push changes. This only works if it is automated.

**Comment by ChristophWurst** [comment]
As @Gomez said, we decided to provide nightly builds for people who want to install the bleeding-edge version this app. I would say a git clone doesn't necessarily mean it works out of the box – most software needs some kind of build process before it can be used. I would leave it as it is.



> Your proposed way, we need to compile the js min file everytime we push changes. This only works if it is automated.

Right, that would be quite awkward. We already have the translation script that has to be run and I personally forgot to run it several times before a commit.

**Comment by jancborchardt** [comment]
Ok, was just a thought. :) About this and the translation script though: would pre-commit hooks be a use-case for this? (Never used them, just sounds relevant.)

**Comment by ChristophWurst** [comment]
Pre-commit hooks are [not copied when cloning the repo](http://www.git-scm.com/book/en/v2/Customizing-Git-Git-Hooks#Client-Side-Hooks). Therefore they don't help there.

**Comment by ChristophWurst** [comment]
@jancborchardt  can we delete the ``build`` branch?

**Comment by jancborchardt** [comment]
Yeah, deleted. :)
