### ISSUE TITLE
Hardcoded /apps/ dir

### ISSUE THREAD

**Issue by Gomez** [owncloud/mail#1163]
We hardcoded the apps dir all over the place:
https://github.com/owncloud/mail/blob/master/js/require_config.js#L17

If you install mail in an alternate path with 'apps_paths' in config.php it results in 404 for js files. 

@DeepDiver1975 @PVince81 Is this correct? Is there a js way to get the apps path?

**Comment by DeepDiver1975** [comment]
There is a JS way ..... I dont remember .,..

**Comment by PVince81** [comment]
Have a look at `OC.appwebroots['mail']`

**Comment by ChristophWurst** [comment]
@Gomez Is anybody having problems with that? Otherwise I vote for postponing to 0.4

**Comment by jancborchardt** [comment]
Yeah, I’d agree we should move this to 0.3 since there hasn’t been an actual report about this.

**Comment by powerpaul17** [comment]
I have the same problem with line 17 and I had to remove one "../" in order to get it working. My owncloud installation is in an "owncloud" subfolder.

**Comment by juliushaertl** [comment]
fixed with #1627
