### ISSUE TITLE
signature attachment will not be shown

### ISSUE THREAD

**Issue by Gurkengewuerz** [owncloud/mail#1165]
Hello,
I have the problem that the .asc file is not displayed in the attachments.
In the Webmailer of 1 and 1 the attachment is displayed.

P.S. The attachment is an automatic attachment. If I send the Key manually, the .asc file is displayed.

**Comment by ChristophWurst** [comment]
This is intended: https://github.com/owncloud/mail/blob/15ea99a63cd359e7abbc6f8dfea9e232f86c3f48/lib/model/imapmessage.php#L46
