### ISSUE TITLE
Unified inbox: error when saving drafts

### ISSUE THREAD

**Issue by ChristophWurst** [owncloud/mail#1172]
Seems like our drafts functionality silently fails at the moment. The client sends ``-1`` as ``accountId`` which the server doesn't understand.

Possible solutions:

1. Fix it properly on the client side:
This requires the client to automatically save the draft to the currently selected account. Additionally, changing the account should also transfer the draft message to the newly selected account.

2. Add some server-side hacks as we did in other parts of the app:
The problem here is the decision of which account to save the draft to. The first one?

@jancborchardt should we add an error notification? If people rely on the draft functionality but it silently fails, this means loss of user data.

**Comment by ChristophWurst** [comment]
Just to be clear: it's not about replies of unified inbox messages (as in #845), the problem are _new_ messages

**Comment by jancborchardt** [comment]
Yes, there should be an error notification for sure. It’s more important than any notification of success.

**Comment by Gomez** [comment]
No problems for me on saving new messaged to draft. If i change the account on the dropdown it gets saved in both accounts. We could optimize that, but not for 0.3.

So, is there something more todo? (in this ticket)
