### ISSUE TITLE
Jquery.min.js/Firefox issues

### ISSUE THREAD

**Issue by PoPoutdoor** [owncloud/mail#1180]
I open this to document findings with Mail app.

### Steps to reproduce
1. Enable debug in config.php
2. Disable config: 
    'asset-pipeline.enabled' => false,
3. Set default app to mail:
    'defaultapp' => 'mail',
4. Clear /assets:
    rm -f assets/*
5. Restart php-fpm and webserver:
    /etc/init.d/nginix restart;
    /etc/init.d/php-fpm restart
6. Use Firefox to login owncloud

### Expected behaviour
Mail app run without Jquery error

### Server configuration
**Operating system:** Linux
**Web server:** nginx
**Database:** mariadb-10.0.22
**PHP version:** PHP 5.6.14-pl0-gentoo
**ownCloud version:** Stable 8.1 https://github.com/owncloud/core/commit/563f0c8a81fb8dc37fb70a6fc23c01224ec496cf
**Updated from an older ownCloud or fresh install:** upgrade from 8.0.x
**List of activated apps:**
~~~
Enabled:
 - files: 1.1.10
 - files_sharing: 0.6.3
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - galleryplus: 14.3.0
 - mail: 0.3-alpha
 - provisioning_api: 0.2

Disabled:
 - documents
 - encryption
 - files_external
 - user_ldap
 - user_webdavauth
~~~
**The content of config/config.php:**
~~~
This is a test instance with default config, except:

  'asset-pipeline.enabled' => false,
  'check_for_working_htaccess' => false,
  'defaultapp' => 'mail',
~~~
**Are you using external storage:** no

**Are you using encryption:** no

### Client configuration
**Browser:** Firefox 42.0 Developer
**Operating system:** Linux

**Comment by PoPoutdoor** [comment]
Note: for Jquery errors only

1. after clicking login button:
    atSetDocument/< - jquery-1.10.2.js:1639
    ut - jquery-1.10.2.js:1329
    atSetDocument/< - jquery-1.10.2.js:1656
    ut - jquery-1.10.2.js:1329
    atSetDocument - jquery-1.10.2.js:1649

[Unified Inbox]

2. during page reload (F5):
    atSetDocument/< - jquery-1.10.2.js:1639
    ut - jquery-1.10.2.js:1329
    atSetDocument - jquery-1.10.2.js:1617
    atSetDocument/< - jquery-1.10.2.js:1656
    ut - jquery-1.10.2.js:1329
    atSetDocument - jquery-1.10.2.js:1649
3. loading message (RHS message plane)
    atSetDocument/< - jquery-1.10.2.js:1639
    ut - jquery-1.10.2.js:1329
    atSetDocument/< - jquery-1.10.2.js:1656
    ut - jquery-1.10.2.js:1329
    atSetDocument/< - jquery-1.10.2.js:1639
    ut - jquery-1.10.2.js:1329
    atSetDocument/< - jquery-1.10.2.js:1656
    ut - jquery-1.10.2.js:1329
        :
4. delete message (current)
    - no error with mouse click/keyboard delete on trash icon
    - after page reload (F5), keyboard delete shows error
    atMatchesSelector - jquery-1.10.2.js:1805

[Current account's folder]

Error not seen after changing to current account, ant folder

**Comment by PoPoutdoor** [comment]
Seems the error related to unified Inbox...

I'm not sure what are the cause for this, some ideas:

1. Firefox side bug, maybe related for first time loading non-cached js
2. Client side memory/stack problem, like low memory lead to corruption
3. js compatible issue with Unified Inbox

**Comment by ChristophWurst** [comment]
> Note: for Jquery errors only
> 
>     after clicking login button: atSetDocument/< - jquery-1.10.2.js:1639 ut - jquery-1.10.2.js:1329 atSetDocument/< - jquery-1.10.2.js:1656 ut - jquery-1.10.2.js:1329 atSetDocument - jquery-1.10.2.js:1649

Does this mean the error occurs before you are logged in?

**Comment by PoPoutdoor** [comment]
> Does this mean the error occurs before you are logged in?
Yes.

**Comment by PoPoutdoor** [comment]
After some cycle of clear browser cache + server restart, sometimes no error after Mail app loaded, only keyboard delete trigger Jquery error.

I notice this time blocked-image.png loaded twice.

**Comment by ChristophWurst** [comment]
> Does this mean the error occurs before you are logged in?
> 
> Yes.

This indicated there's a general problem on your system. I don't see any connection between the mail app and an error that occurs before you are even logged into the system…

Could you please try to disable the mail app and then reproduce the bug?

**Comment by PoPoutdoor** [comment]
> This indicated there's a general problem on your system. I don't see any connection between the mail app and an error that occurs before you are even logged into the system…

config.php
>  'defaultapp' => 'mail',

I'm not sure the Mail js loaded or not, or the js loading order matters.

> Could you please try to disable the mail app and then reproduce the bug?

Seems the Jquery error gone after Mail app disabled. I'll try some more clear browser cache+server restart cycles to confirm.

**Comment by PoPoutdoor** [comment]
Strange! 

After 3-4 cycles, I confirm Jquery error go away. Then, I enable Mail app again to confirm Jquery error caused by Mail, but I don't see any related error after some more clear browser cache+server restart cycles.

Can anybody tell what happened in between? Or reproduce the Jquery error?

Note: I disable & enable mail app with occ.

**Comment by PoPoutdoor** [comment]
After some intense use, Jquery error returns with Mail app enabled!

No more Jquery error after disable Mail app... any ideas?

**Comment by jancborchardt** [comment]
Moving to 0.4 for sure.

**Comment by PoPoutdoor** [comment]
Will test 0.3 alpha with core 0.7 and then do core upgrade, redo test with next major version.

**Comment by PoPoutdoor** [comment]
### core 7.0.4.2
Mail: Current Nightly build
### result
Seems good, but got similar Jquery error after intense Mail operation.

**Comment by PoPoutdoor** [comment]
Found out Firefox's profile corruption (I think) lead to strange javascript errors... create a new profile and test with latest versions of 7/8 doesn't notice any Jquery error so far.

Will closed this after testing for some more days.

**Comment by PoPoutdoor** [comment]
Issue confirmed not related to OwnCloud/Mail, close now.
