### ISSUE TITLE
Give a name to each email account

### ISSUE THREAD

**Issue by naziris** [owncloud/mail#1182]
I would love to see in future updates to option to give to mail addresses names like:
instead of mypersonal@email.com to label to as Personal, University, Work etc

And instead of having an endless list of folder for each account (in my case 8), to be able to expand the one you need.

I really like the merged inbox though! ;)

This is my first suggestions cause I have just installed your app.
I'll keep using it and keep you posted.

**Comment by ChristophWurst** [comment]
Thanks for sharing this suggestion. It should be easy to implement that, we just need another input field for the account setup and an additional database column. Are you experienced with PHP/JavaScript and want to help implement that feature? :-)

**Comment by ChristophWurst** [comment]
Regarding account collapsing, there's an open ticket for that: https://github.com/owncloud/mail/issues/677

**Comment by ChristophWurst** [comment]
no update for more than 6months -> I'm closing this now.

**Comment by jancborchardt** [comment]
Also, basically the issues are fixed:

> And instead of having an endless list of folder for each account (in my case 8), to be able to expand the one you need.

We do that since some time :) accounts are collapsed to the most important folders by default.

And we’ll not implement custom names for accounts, so closing.
