### ISSUE TITLE
End of owncloud 7 support

### ISSUE THREAD

**Issue by ChristophWurst** [owncloud/mail#1184]
Since oc7 reaches EOL soon, we can also increase the minimum core version to 8. This means some oc7-specific code might not be necessary anymore and can be removed therefore.

Source: https://github.com/owncloud/core/wiki/Maintenance-and-Release-Schedule

**Comment by aspdye** [comment]
EOL of ownCloud is reached 01-2016. But 0.3 is published before. Im also for removing Legacy Code from oc7 ... But are we "allowed" to do this with 0.3 or do we have to wait until 0.4 ;)

**Comment by DeepDiver1975** [comment]
0.4 is still enough

**Comment by aspdye** [comment]
Question: Are we also able to drop PHP 5.4 support (according to PHP Community's EOL Policy)

**Comment by ChristophWurst** [comment]
> Question: Are we also able to drop PHP 5.4 support (according to PHP Community's EOL Policy)

AFAIK oc8 supports php 5.4, so we should not drop support for it as long as we support oc8.

**Comment by aspdye** [comment]
@ChristophWurst Thats not correct, i think. ownCloud 8.0.X supports PHP >= 5.5 :wink: 
https://doc.owncloud.org/server/8.0/admin_manual/installation/source_installation.html

I think last version supporting PHP 5.4 was ownCloud 7.0. But I dont know - maybe this is diffrent in the Enterprise Edition :grimacing:

**Comment by phsc** [comment]
Owncloud 8.2 still supports PHP 5.4. And Owncloud 9.0 will still support PHP 5.4.

For your reference:
https://github.com/owncloud/core/issues/20787
https://github.com/owncloud/core/issues/16428
https://github.com/owncloud/core/pull/17919#issuecomment-125602581

**Comment by DeepDiver1975** [comment]
There are no plans to drop PHP 5.4

**Comment by MorrisJobke** [comment]
> @ChristophWurst Thats not correct, i think. ownCloud 8.0.X supports PHP >= 5.5  
> https://doc.owncloud.org/server/8.0/admin_manual/installation/source_installation.html

Fixed with https://github.com/owncloud/documentation/pull/2021

**Comment by aspdye** [comment]
EOL for ownCloud 7 had been moved to 5-2016 - does that change anything for the mail app?
