### ISSUE TITLE
PHP with a version lower than 5.6 is required.

### ISSUE THREAD

**Issue by JoanPlume** [owncloud/mail#1185]
This application can not be installed because of these unmet dependencies:
PHP with a version lower than 5.6 is required.

What is the solution ?

I'm in PHP 7

**Comment by ChristophWurst** [comment]
> What is the solution ?

Unfortunately, there is no solution at the moment, as the IMAP library we use is not yet compatible with PHP7. See https://github.com/owncloud/mail/issues/1050

**Comment by JoanPlume** [comment]
Thanks !
