### ISSUE TITLE
Unit tests with core master fail

### ISSUE THREAD

**Issue by ChristophWurst** [owncloud/mail#1186]
It seems like our unit tests fail when using current core master:

```
There was 1 failure:

1) OCA\Mail\Tests\Model\MessageTest::testParseAddressList with data set #0 ('user@example.com', array('user@example.com'))

Failed asserting that two arrays are equal.

--- Expected

+++ Actual

@@ @@

 Array (

+    0 => LibXMLError Object (...)

+    1 => LibXMLError Object (...)

+    2 => LibXMLError Object (...)

 )

/home/travis/build/owncloud/core/tests/lib/testcase.php:101
````

See PR #1183 for failing tests.

@DeepDiver1975 any idea?

**Comment by ChristophWurst** [comment]
@DeepDiver1975 it's your commit that is causing those errors (https://github.com/owncloud/core/pull/21269) ;-)

**Comment by DeepDiver1975** [comment]
Yes - this is because there is some xml parsing code used which does not cleanup the errors

**Comment by DeepDiver1975** [comment]
seems to be an issue in htmlpurifier .....
