### ISSUE TITLE
Open last emptied folder  shows "No messages in this folder!" while there is new mail

### ISSUE THREAD

**Issue by PoPoutdoor** [owncloud/mail#1188]
I open this to replace #935

![screenshot-2015-08-13 03 43 53](https://cloud.githubusercontent.com/assets/1781047/9235147/887db2f0-416f-11e5-848b-a8b06dc417f9.jpg)

![screenshot-2015-08-13 03 44 12](https://cloud.githubusercontent.com/assets/1781047/9235150/8f94198a-416f-11e5-9c29-341c0c3acfac.jpg)

The overlap disappeared after page reload.

Browser Firefox 42

**Comment by PoPoutdoor** [comment]
After tracing the code, I think the problem is on cache handling:
Cached and background jobs to fetch new mails
https://github.com/owncloud/mail/blob/master/js/ui.js#L243

Somehow cached version is not invalidated and return no message (empty folder)
https://github.com/owncloud/mail/blob/master/js/ui.js#L254

UI shows "No messages in this folder!" while background job fetched new mail and shows in "message list"
https://github.com/owncloud/mail/blob/master/js/ui.js#L272

Can we invalidate cache after reasonable time past?
Or, if cache returned as no message, only show "No messages in this folder!" after message list finished fetching with no message?

**Comment by jancborchardt** [comment]
@PoPoutdoor do you have any more info on this? Otherwise I assume it’s fixed and will close this. :)
