### ISSUE TITLE
Add a way to select many mails instead of one, and delete or mark them as read/unread, favorite

### ISSUE THREAD

**Issue by ele0s** [owncloud/mail#1195]
Hi,

Like the title said, we can't select many mails and operate on them

**Comment by phsc** [comment]
Duplicate of #660 

The mail app is still in quite an early stage. Some features, that you know from almost all email clients, are still missing. Please have a look at all the issues tagged as "feature parity" https://github.com/owncloud/mail/labels/feature%20parity.

**Comment by ChristophWurst** [comment]
@ele0s please search for existing issues before opening new ones. Thanks.
