### ISSUE TITLE
Unified folders for multiple accounts

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/mail#120]
As talked about in https://github.com/owncloud/mail/pull/106

> If we merge the folders where should be displayed which mail address was the recipient?

We should have some kind of color coding, like a small vertical bar on the left of the message. This is also how we do it in the Android News app: http://david-luhmer.de/wordpress/?p=126 – and this is also how K9-Mail does it.
It requires us to add a color preference to the mail account though – which I guess we need anyway with multi-account.
Sounds good @DeepDiver1975 @LukasReschke?

> When composing mails should we show a dropdown similar to Mail.app for the sender?

Yes, we should show it as the first field, before the recipient. So that »From« and »To« is a group. Of course the »From« field only needs to be shown if you have more than one account configured _and_ are in the All accounts view.

> Existing mail programs allows users to define what folders to use for Sent/Drafts/Trash. This is useful since IMAP service providers have often different folder structures. I don't want to have 5 different called Trash folders if we could merge them.

So yes – we should definitely merge the folders, and we should try to do it as automatic as possible. I mean, mostly they are called »Sent« or »Sent messages«, or »Trash« or »Deleted messages«. We can just hardcode it for most major mail providers so we can merge it.

**Comment by jancborchardt** [comment]
@LukasReschke are you interested in looking into this again? Since we have multi-account support it would be cool to support a unified inbox again.

**Comment by DeepDiver1975** [comment]
0.3 as well - requires major restructuring of the code - as of today the code base is not flexible enough to allow this.

**Comment by DeepDiver1975** [comment]
@jancborchardt like this

![bildschirmfoto von 2015-06-08 22 27 04](https://cloud.githubusercontent.com/assets/1005065/8044521/914698ea-0e2d-11e5-8418-98f8363cecfd.png)

**Comment by jancborchardt** [comment]
Yup, nice! Just some details:
* Let’s call it »All inboxes«
* of course only show it when there are 2 or more accounts
* any chance of an »All favorites« entry below it as well? ;)

Good stuff!

**Comment by DeepDiver1975** [comment]
- Ok
- done
- let's see


:WINK:

**Comment by jancborchardt** [comment]
For reference, this is the PR: https://github.com/owncloud/mail/pull/750

@DeepDiver1975 are the latest changes in there?

**Comment by jancborchardt** [comment]
Fixed via #750, great work! :)
