### ISSUE TITLE
Delete all messages / Empty a folder

### ISSUE THREAD

**Issue by artemanufrij** [owncloud/mail#1206]
I want to delete all items in my "Newsletter" folder. How can I do it?

**Comment by ChristophWurst** [comment]
> I want to delete all items in my "Newsletter" folder. How can I do it?

That is not yet possible. Do you have experience in coding? Then you could help us implement that feature ;-)

issue #660 is related

**Comment by jancborchardt** [comment]
We’d rather not make it so simple to clear a whole folder as it’s more likely to lead to data loss than be useful.
