### ISSUE TITLE
error loading messages

### ISSUE THREAD

**Issue by guidovanharten** [owncloud/mail#1209]
I downloaded the today nightly build of the mail app of Owncloud 8.2.2
After adding an account I get an error in the top of my browser:
Error loading messages

What can I do to solve this?

Regards,
Guido van Harten

**Comment by ChristophWurst** [comment]
Please fill out the [issue template](https://raw.githubusercontent.com/owncloud/core/master/issue_template.md) so we can get more information about your setup.

**Comment by enko** [comment]
This is probably the same as #1207 as I have the same error and when I check the error log I see the exception mentioned in #1207.

**Comment by ChristophWurst** [comment]
Yes, it seems to be the same problem. Let's continue in #1207

**Comment by guidovanharten** [comment]
I tried to describe the problem and today I used the new nightly build 
(20160109). It seems (...) the probleem is solved now.
But I have to wait a long time...
I am waiting if I can read the mail later today.
May be it will continued.

Regards,
Guido van Harten



Christoph Wurst schreef op 06-01-2016 21:24:
