### ISSUE TITLE
A few suggestions of new features/issues

### ISSUE THREAD

**Issue by ele0s** [owncloud/mail#1223]
Hi,

I have some issues to report, and new functionalities to suggest, so to avoid making an issue for each of them, I will put them in only one.

### Issues : 
* There is some parts of HTML mails that there aren't kept when we transfer them/answer to them (Only the text is kept)
* Icons of folders are'nt shown and the black popup who was normaly displayed when the mouse is on the "delete" button is buggy/"always present" on Chrome when we effectuate many operations on mails (For exemple, a lot of deletions)

![capture du 2016-01-14 20-57-56](https://cloud.githubusercontent.com/assets/9059362/12335855/97c61886-bb01-11e5-8f05-052b62fdbf17.png)
![capture du 2016-01-14 20-58-06](https://cloud.githubusercontent.com/assets/9059362/12335856/989d9658-bb01-11e5-8c59-86b4aced002b.png)

* Attachments are'nt kept when we transfer mails, or when whe save a mail who contain attachments as draft
* Answers are'nt save if we not send them

### Features :
* A new more ergonomic interface : 
  * Add a print mail button (print view, etc...)
  * See the numbers of unreads/reads mails present in folders
  * We can't display, create, transfer or answer mails in an another tabs/windows or resize them (A new button ? or when we click on the title of the message on the view panel)
  * Change the panels size
  * Add a "Download all attachments locally" button (with an automatic archiving of every attachments in zip file?)
* Add the possibility to sort mails by alphabetic order, date, etc... (with search regex too)
* Add auto-refresh of modification in mailbox (new mails, etc...)
* Add Gravatar support
* Add the possibility to change accounts configuration
* Add a button to define a message as spam and move it to junk folder, and vice versa...
* HTML/WYSIWYG editor
* Add a "save to draft" button
* Change the subject of an answer

**Comment by ChristophWurst** [comment]
> There is some parts of HTML mails that there aren't kept when we transfer them/answer to them (Only the text is kept)

Duplicate https://github.com/owncloud/mail/issues/782. HTML messages are not yet supported.

> cons of folders are'nt shown and the black popup who was normaly displayed when the mouse is on the "delete" button is buggy/"always present" on Chrome when we effectuate many operations on mails (For exemple, a lot of deletions)

What do you mean? The tipsy does not go away?

> Add a print mail button (print view, etc...)

Duplicate https://github.com/owncloud/mail/issues/717

> Add Gravatar support

Duplicate https://github.com/owncloud/mail/issues/1056

> Add auto-refresh of modification in mailbox (new mails, etc...)

This is already implemented. Simply wait up to 5 minutes and you'll see all new messages of you inboxes.

> HTML/WYSIWYG editor

Duplicate #782

> Add a "save to draft" button

Not necessary. We save drafts automatically. See [this](https://doc.owncloud.org/server/8.2/developer_manual/general/codingguidelines.html#user-interface) for more information.

Thanks for your feedback. However, _please_ try to search the existing issues and do not report things that have already been reported. Thanks.

**Comment by ChristophWurst** [comment]
May I ask you to open separate issues for the non-duplicates? It's easier for developers to have a look at individual issues. That way we can organize and schedule all the features easier. Thanks

**Comment by ele0s** [comment]
@ChristophWurst Well, I will do that soon, sorry for the duplicates

**Comment by jancborchardt** [comment]
@ele0s yo, awesome on the report! :) Don’t worry that there’s a lot of issues already existing – every new contributor needs some time to get into the project. Your feedback is very valued – you are also welcome in our IRC channel #owncloud-mail (on freenode IRC)! :)
