### ISSUE TITLE
Folders doesn't have icons

### ISSUE THREAD

**Issue by ele0s** [owncloud/mail#1227]
*From #1223*
Hi,

In my Owncloud instance, icons of folders (others than those basic like inbox, etc...) are'nt shown

There is maybe a correlation with #1040 

![capture du 2016-01-15 21-19-51](https://cloud.githubusercontent.com/assets/9059362/12364227/c00d1bf6-bbcd-11e5-8d72-2bc29a2ce8aa.png)

**Comment by ChristophWurst** [comment]
Only special folders have icons.

@jancborchardt is that intended? Do we want to change that?

**Comment by ele0s** [comment]
@ChristophWurst It would be better to see, cause here, it makes a high contrast between the icons of special folders, and folders with just blank space instead of icons like this : 


![noun_24262_cc](https://cloud.githubusercontent.com/assets/9059362/12365472/614d0588-bbd5-11e5-9228-ed0d51e6bdb5.png)

**Comment by jancborchardt** [comment]
It’s intended that all non-special folders have no icons. Having a generic folder icon for each and every other folder will just result in repetitive noise which is not really useful and will drown out the icons of the special folders.

**Comment by ChristophWurst** [comment]
Ok, so I'll close this issue for now.

**Comment by jancborchardt** [comment]
@ele0s hope this explains the design reasoning of this specific decision. :) Of course any issue report is helpful, so please keep em coming. And welcome to ownCloud Mail! :)
