### ISSUE TITLE
Tipsy of the "delete" button doesn't go away

### ISSUE THREAD

**Issue by ele0s** [owncloud/mail#1228]
*From #1223*
Hi,

As said in the issue cited above by @ChristophWurst : 
> > cons of folders are'nt shown and the black popup who was normaly displayed when the mouse is on the "delete" button is buggy/"always present" (I'm on Chrome) when we effectuate many operations on mails (For exemple, a lot of deletions)

> What do you mean? The tipsy does not go away?

Yes, the tipsy doesn't go away.
For more informations, I use the default theme

![capture du 2016-01-14 20-57-56](https://cloud.githubusercontent.com/assets/9059362/12335855/97c61886-bb01-11e5-8f05-052b62fdbf17.png)
![capture du 2016-01-14 20-58-06](https://cloud.githubusercontent.com/assets/9059362/12335856/989d9658-bb01-11e5-8c59-86b4aced002b.png)

**Comment by ChristophWurst** [comment]
@owncloud/mail any idea?

**Comment by jancborchardt** [comment]
@irgendwie you played around with this in the past, right? :)

**Comment by ErikPel** [comment]
Has the tipsy plugin been disabled because of this or is there something wrong with my server/browser because I can't see the tooltips at all?

**Comment by ChristophWurst** [comment]
> Has the tipsy plugin been disabled because of this or is there something wrong with my server/browser because I can't see the tooltips at all?

Tooltips are only shown before permanently deleting mails, hence you'll only find them in the trash-folder

**Comment by ErikPel** [comment]
Can there be multiple tooltips shown at once without this bug or would it work if we just put (".tooltip").remove() into the delete function?
@ChristophWurst

**Comment by jancborchardt** [comment]
Closing because https://github.com/owncloud/mail/pull/1250 fixes it, right? :)
