### ISSUE TITLE
Answers aren't saved as drafts

### ISSUE THREAD

**Issue by ele0s** [owncloud/mail#1230]
*From #1223*
Hi,

Answers aren't saved if we not send them, if we close the windows/tab when we write it, we loose everything

**Comment by ChristophWurst** [comment]
Please check your browser's console for errors. Theoretically drafts are saved when replying, but there were some bugs in the 0.2.1 release. This should be fixed by upcoming releases.

**Comment by ChristophWurst** [comment]
To debug this, please provide browser, owncloud and horde log. Thanks.

**Comment by ele0s** [comment]
After verification, it's a mistake, I close...
