### ISSUE TITLE
Sort mails in the view pane

### ISSUE THREAD

**Issue by ele0s** [owncloud/mail#1232]
*From  #1223*
Hi,

Most of mails clients allows users to sort mails by date, if they are bookmarked/read or contains attachments, by subject, sender, alphabetic order, etc...

It would be a nice feature, who will permit to quickly sort our mails

**Comment by jancborchardt** [comment]
- sort by date is default
- bookmarked/starred is a filter in the sidebar now
- sorting by subject or sender does not really make sense

Closing hence. :)
