### ISSUE TITLE
Add read and acknowledgment of receipts, and priority

### ISSUE THREAD

**Issue by ele0s** [owncloud/mail#1239]
Hi,

We can't activate the read receipt, acknowledgment of receipt and level of priority on sent mails.

Adding three buttons to add these features would be a great progress

**Comment by jancborchardt** [comment]
Inactive for 6 months so it seems no one is really interested in working on this. Also maybe because this functionality is not quite used in mainstream mail clients.

Closing for now. Feel free to implement though and opening a pull request. But it’s not a priority for the project. :)
