### ISSUE TITLE
Unified inbox: Account color indicators needed?

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/mail#1241]
I was looking at a few other mail apps with unified inboxes, and most notably iOS Mail doesn’t do any indicator for the account.

This led me to think about if it’s really necessary to show this indicator. It’s a lot of color in addition to the already very colorful avatar placeholders, and it feels a bit much. The individual inbox view is nicer and cleaner.

What do you think @owncloud/mail?

**Comment by irgendwie** [comment]
:see_no_evil: I actually like that feature! It's also implemented in K9 Mail (for Android).

**Comment by Gomez** [comment]
I need this info, too. Maybe it can be moved into the mail-message?

**Comment by jancborchardt** [comment]
@Gomez you mean it would be sufficient to be displayed only in the detail view? That of course would be the case anyway, in combination with the »to you« section below the mail subject.

@irgendwie yeah, I know it’s also in K9 … however that might not be the best role-model design wise. ;)

**Comment by DeepDiver1975** [comment]
I'd like to keep it as well

**Comment by jancborchardt** [comment]
Then I’d at least like to make the bar a bit narrower. 2px, maybe even 1px. What do you think?

**Comment by ChristophWurst** [comment]
> Then I’d at least like to make the bar a bit narrower. 2px, maybe even 1px. What do you think?

Could you try that and take some screenshots? 1px might be too narrow.

**Comment by irgendwie** [comment]
@jancborchardt We could make it optional and use the settings pane to enable/disable it.

**Comment by DeepDiver1975** [comment]
bäääh - settings :hankey:

**Comment by irgendwie** [comment]
customizability? :see_no_evil:

**Comment by jancborchardt** [comment]
Proper design ;) :rocket: 

Or should we introduce a slider control with which you can customize the width of that color bar? :D (Hint: No.)

**Comment by Gomez** [comment]
+1 for @ChristophWurst idea. Show us!

**Comment by jancborchardt** [comment]
Yeah, I was gonna do it but then following this thread was more interesting. ;D
