### ISSUE TITLE
Add browser notification (Feature request)

### ISSUE THREAD

**Issue by rakshazi** [owncloud/mail#1242]
Hello!

Please, add optional browser notification (Push Notifications is Chrome) about new mail, such as uses Facebook ( docs: https://developers.google.com/web/updates/2015/03/push-notifications-on-the-open-web ) or another kind of notification (sound + draw icon in red color) as used in Owncloud Conversations app (https://github.com/simeonackermann/OC-User-Conversations)

Best regards, Nikita.

**Comment by ChristophWurst** [comment]
Hello @rakshazi,
we already show browser notifications for incoming mail, see https://github.com/owncloud/mail/blob/8bfde57dcb93f7f68242729683aad6ad7d9db483/js/background.js#L19-L44. New mails are automatically checked every 5 Minutes, hence you will get a notification if there are any incoming messages.

> (sound + draw icon in red color) as used in Owncloud Conversations app (https://github.com/simeonackermann/OC-User-Conversations)

Additionally to notifications, the default favicon shows a red dot to indicate new messages, see https://github.com/owncloud/mail/blob/8bfde57dcb93f7f68242729683aad6ad7d9db483/js/background.js#L101

So simply open the mail app, switch to another tab and wait for an incoming message – you should be notified. If you face any problems, please let us know. You are welcome to join us in our IRC channel #owncloud-mail on freenode ;-)

I'm closing this for now, but feel free to re-open if notifications do not work on your setup. Thanks.
