### ISSUE TITLE
Improvement of contacts integration regarding "groups"

### ISSUE THREAD

**Issue by ttjaden** [owncloud/mail#1245]
Hi! Thanks for this really great application! For us, only one thin is missing: 
When sending a new mail, it would be great to be able to send this mail to a "group" from the contacts. Right now it's only possible to send mails to single contacts.

Would this be possible?

**Comment by ChristophWurst** [comment]
Hi @ttjaden,

yes, that would be a nice feature. We already have an issue for that: https://github.com/owncloud/mail/issues/772. Do you have experience in coding? Then maybe you could help implement that feature. If you need any further information or help you are welcome to join us in our IRC channel #owncloud-mail on freenode.

I'm closing this for now, let's continue in https://github.com/owncloud/mail/issues/772. Thanks for your contribution :-)
