### ISSUE TITLE
Subdirs only one level deep ?

### ISSUE THREAD

**Issue by hanslammerts** [owncloud/mail#1249]
Hi,

I just installed the latest nightly build (0.3), and I still have problems getting mails from sub-sub directories.
I have an Archive directory (displayed as .Archive in my Dovecot Maildir). In this Archive dir I have a lot of subdirectories (that contain subdirs as well). E.g.: Below .Arhive I have a subdir called .Linux. The mails in this subdir are shown.
In .Linux, I have three more subdirs. These subdirs are shown in the app as Linux.Backup, Linux.blabla and Linux.whatever. When I select these subdirs, no messages are shown.

Am I doing something wrong, or is this by design ?
I would like to see the following construction:

Linux
   |- (messages)
   |--SUBDIR
            |-(messages)
   |--SUBDIR
            |-(messages)
etc.

Is this at all possible ?

Regards,
Hans

**Comment by ChristophWurst** [comment]
Hi,
thanks for reporting. 

> Am I doing something wrong

This is not handled correctly by the mail app, see https://github.com/owncloud/mail/issues/618
I'm closing this since it's a duplicate, let's discuss that in the existing ticket.
