### ISSUE TITLE
Save state of app in URL

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/mail#125]
Currently when you refresh, you are redirected to the inbox of the first account. Rather the location (account and message ID) should be encoded in the URL so the state will be preserved. Ideally this also makes back/forward of the browser work.

**Comment by ChristophWurst** [comment]
I'll give [Marionette Approuter](http://marionettejs.com/docs/v2.4.2/marionette.approuter.html) a try once #944 has been implemented

**Comment by jancborchardt** [comment]
#1424 didn’t fix this though, right @ChristophWurst? I missed the issue reference there, just thought it was some backend fix.

**Comment by ChristophWurst** [comment]
Hm, actually you should see the current folder in the url and the back button can be used to navigate back. Moreover, you can open folders in new tabs. Hence, this issue is fixed, isn't it?

**Comment by jancborchardt** [comment]
Sorry, seemed to be a browser caching issue. It works nicely, thanks! :)

**Comment by jancborchardt** [comment]
Sorry, seemed to be a browser caching issue. It works nicely, thanks! :)
