### ISSUE TITLE
Internal server error while creating new Email Account

### ISSUE THREAD

**Issue by plastikschnitzer** [owncloud/mail#1251]
#### Steps to reproduce:
1. Go to mail app
2. Enter full imap mailbox credentials
3. hit "connect"

#### Expected behaviour:
No errors, Mailbox creation.

I use the plugin on another ownCloud installation with a different server and it works, I know how it should look like ;-)

#### Actual behaviour:
error message "Internal server error while creating new email account".

#### Server configuration
**Operating system**:  
FreeBSD 10.1

**Web server:**
Apache/2.4.18 (FreeBSD) OpenSSL/1.0.2e mod_fcgid/2.3.9

**Database:**
5.0.11-dev

**PHP version:**
5.5.30

**ownCloud version:** 
8.2.2.

**Updated from an older ownCloud or fresh install:**
Fresh install

**Are you using encryption:** 
no

#### Web server error log

Empty.

#### ownCloud log (data/owncloud.log)
`Error	PHP	Call to a member function write() on a non-object at /owncloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Socket.php#4335`

If I use nightly built version of the mail app, it changes to:
`
Error	PHP	Call to a member function write() on a non-object at /owncloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Socket.php#4428`

**Comment by ChristophWurst** [comment]
Hi @plastikschnitzer,
thanks a lot for using the issue template ;-)

Does that other server also run on FreeBSD? I'm not sure if that make a big difference, but I assume most people run ownCloud on Linux servers.

@owncloud/mail any idea?

**Comment by plastikschnitzer** [comment]
Thanks for your quick reply! The other server is production and running gentoo linux apache 2.4.10 PHP 5.6.12.
This freeBSD Server is a test, I have to scale things up and I am limited on the linux server.
I really like the mail app because it was just the "missing link" to make OC a full groupware which has the basics you need in your office (Files, Contacts, Calendar, Mail, Tasks, …) – so thumbs up for your work! I am following and testing your work for some time now ;-)

**Comment by ChristophWurst** [comment]
> I really like the mail app because it was just the "missing link" to make OC a full groupware which has the basics you need in your office (Files, Contacts, Calendar, Mail, Tasks, …) – so thumbs up for your work! I am following and testing your work for some time now ;-)

Awesome! You're welcome to join us in our IRC channel #owncloud-mail on freenode. We're close to releasing the 0.3 version of this app – only a few bugfixes have to be reviewed, then it's ready: https://github.com/owncloud/mail/pulls?q=is%3Aopen+is%3Apr+milestone%3A%220.3+%E2%80%93+refactoring!%22
Would be great if you can help test those ;-)

**Comment by ChristophWurst** [comment]
Did you enable the debug mode? See https://doc.owncloud.org/server/8.2/developer_manual/general/devenv.html#enabling-debug-mode

If enabled, the app is more verbose and logs several steps of the setup process. That could help locate the bug.

**Comment by plastikschnitzer** [comment]
I enabled debug mode and I did again a fresh install to be sure that I did not mess up anything. Here is the result:
`
Error 	PHP 	Call to undefined method stdClass::write() at /owncloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Socket.php#4335`

`Debug 	PHP 	Creating default object from empty value at /owncloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Socket.php#4281`

`Debug 	PHP 	fwrite() expects parameter 1 to be resource, null given at /owncloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Socket/Connection/Socket.php#62`

`Debug	PHP	fwrite() expects parameter 1 to be resource, null given at /owncloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Socket/Connection/Socket.php#62`
`
Debug	mail	Connecting to account {account}`

`Info	mail	Setting up manually configured acc`

**Comment by branigan** [comment]
Same Here Ubuntu 14.04 . Owncloud 8.2.2 mail 0.3

**Comment by plastikschnitzer** [comment]
Hi, I updated ownCloud to 9.0.1., mail app version 0.4.1. and its working now!
 
@branigan do you still experience this bug?
