### ISSUE TITLE
Feature Request:  Admin settings

### ISSUE THREAD

**Issue by Luticus** [owncloud/mail#1263]
Currently the mail app is user driven.  The user selects what server to connect to, and plugs in all the credentials and such.  I would like to see some settings in the admin area where I could force the mail app to use only my central email server and users only need to enter their authentication information (if it's different from their owncloud login credentials) 

The mail client I currently use (rainloop) does something like this, but I'm interested in the Mail app for deep owncloud integration.  Any chance this app will support this scenario or will it forever remain user controlled only?

**Comment by ChristophWurst** [comment]
Hi @Luticus,
this has already been reported, see https://github.com/owncloud/mail/issues/166.
Thanks.
