### ISSUE TITLE
Version 0.3.0 at appstore vs. 0.3 in app metadata

### ISSUE THREAD

**Issue by RealRancor** [owncloud/mail#1264]
Hi,

seems the appstore has currently version 0.3.0 defined:

https://apps.owncloud.com/content/show.php/Mail?content=169914
(and the tags here at the repos too)

where the metadata has 0.3:

https://github.com/owncloud/mail/blob/v0.3.0/appinfo/version
https://github.com/owncloud/mail/blob/v0.3.0/appinfo/info.xml#L6

A user reported a few hours ago in IRC that the app is not update able via the appstore as message like "version from the appstore differs from the version file provided by the app" (or similar) is shown.

**Comment by ChristophWurst** [comment]
From IRC (#owncloud-mail):

```
<xiu> hi :) I have a version mismatch error when trying to upgrade from 0.2.1
<xiu> App can't be installed because the version in info.xml/version is not the same as the version reported from the app store
<xiu> might be because the app store has version=0.3.0 where the info.xml only has 0.3 (https://github.com/owncloud/mail/blob/v0.3.0/appinfo/info.xml)
<ChristophWurst> DeepDiver: ^ any idea?
<DeepDiver> possibly - we can remove the version file anyhow
<DeepDiver> let me update the tar ...
<DeepDiver> tar has been updated
<DeepDiver> xiu: mind testing again? THX
<xiu> DeepDiver: working, thanks!
```

So I assume this has been fixed already. Thanks for reporting @RealRancor ;-)

**Comment by ChristophWurst** [comment]
@DeepDiver1975 should the version file be removed?
