### ISSUE TITLE
Individualize avatar auto-colors

### ISSUE THREAD

**Issue by smoes** [owncloud/mail#1269]
I was trying to change the avatar default auto-colors. I found them sitting within vendors HTMLPurifiers config file. Changing them had no effect (wrong location?). What is the proper way to modify them to individualize the mail app?

**Comment by ChristophWurst** [comment]
cc @jancborchardt

**Comment by jancborchardt** [comment]
They are automatically generated from the name/email, just like the avatar placeholders in ownCloud Files (for sharing, user mgmt etc.) They are just placeholders after all.

In any case, the relevant code is in core here: https://github.com/owncloud/core/blob/master/core/js/placeholder.js#L58
Where a HSL (hue, saturation, lightness) color value is generated with a varying hue based on the name as said above. Hope that helps. :)

**Comment by smoes** [comment]
Thanks, that helped a lot.

**Comment by jancborchardt** [comment]
@smoes cool! If you have any more feedback or even want to contribute, you’re very welcome! :)

**Comment by smoes** [comment]
I am actually thinking about implementing my color _hack_ in a nice and clean matter. It is very easy to provide an array of colors and still choose a color based on the provided hash. However I am not sure how to contribute to the owncloud core. Any starting points? (I assume this can not be developed as a plugin?)

**Comment by jancborchardt** [comment]
We’re not planning on making the placeholder colors configurable in the GUI. If you have an algorithm which delivers a palette working better than the current one (regarding contrast and niceness of colors etc), you can open a pull request to the core repository though.
