### ISSUE TITLE
classic mail client view

### ISSUE THREAD

**Issue by andrkac** [owncloud/mail#1281]
Is there a chance to make (as option) a classic view, with message list on right top and message content on right bottom?
I'm still using 4:3 monitor...

message headers should be also changed into one-liners in this case.

**Comment by ChristophWurst** [comment]
Hi @andrkac,
is there any problem with the current design and 4:3 monitors? The screenshot in the readme was also taken on an 4:3 monitor and I don't see any issues there.

cc @jancborchardt

**Comment by jancborchardt** [comment]
There is no plan to do this for several reasons:

- It’s an outdated layout not used by modern email clients. People are used to the 2-column-layout we currently use also from other apps.
- We would need to maintain two different layouts which is too much work.
- The current layout should scale fine to different monitor sizes and resolutions.

Please send a screenshot and describe the exact problem – maybe there’s a different way we can fix this. :)
