### ISSUE TITLE
How about the »Official« tag for the Mail app?

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/mail#1287]
Just thought about it and we fulfill all requirements since some time already: https://doc.owncloud.org/server/8.2/developer_manual/app/publishing.html#official

We currently have the »Approved« tag and it seems it’s time to graduate. :)

What do you think @owncloud/mail @karlitschek @jospoortvliet @LukasReschke? What needs to be done?

**Comment by karlitschek** [comment]
I would totally support this. @LukasReschke What do you think?

**Comment by LukasReschke** [comment]
Seconded.

This app needs a code signing certificate for 9.0 in this case. Please sort out who does the releases and submit a request as described at https://doc.owncloud.org/server/9.0/developer_manual/app/code_signing.html#how-to-get-your-app-signed. It's quick to do and provides massive security advantages.

Basically like @nickvergessen has done it at https://github.com/owncloud/appstore-issues/issues/42. Once this is done the app just needs to be tagged properly in the appstore. And I think also on each update an admin needs to be notified to set the flag properly

**Comment by Gomez** [comment]
I would do it, if @DeepDiver1975 agrees?

**Comment by DeepDiver1975** [comment]
Fine with me. THX @gomez

**Comment by jancborchardt** [comment]
I for one welcome @Gomez as our release manager overlord.

**Comment by ChristophWurst** [comment]
:+1:

**Comment by enoch85** [comment]
Just tested 0.3 with PHP 5.6. Really nice work guys! I'm impressed how much it has improved since 0.2.

**Comment by Gomez** [comment]
Cert is done:
https://github.com/owncloud/appstore-issues/issues/45
@DeepDiver1975 Is it possible to transfer mail to my appstore account? https://apps.owncloud.com/usermanager/search.php?username=PortKnox

**Comment by jancborchardt** [comment]
@DeepDiver1975 @karlitschek can the app be transferred to another account? In this case, @Gomez’s/PortKnox? Then we can have it Official.

**Comment by karlitschek** [comment]
Sure. I transferred the app to PortKnox. Admin still have access to update the app if needed of course.

**Comment by jancborchardt** [comment]
Yeeha, thanks! Now go nuts @Gomez :)

**Comment by Gomez** [comment]
@LukasReschke Ok all done. Check v0.4.0 in the appstore.

**Comment by LukasReschke** [comment]
Tagged as official.
