### ISSUE TITLE
Consistent use of Marionette views

### ISSUE THREAD

**Issue by ChristophWurst** [owncloud/mail#1306]
While some parts of the client are already structured into Marionette views, some views are missing:
- a view for the content
- a view for the messages
  - contains the message listview (already exists)
  - a message (detail) view

I created a simple UML-diagram for the final design:

![view_classes](https://cloud.githubusercontent.com/assets/1374172/13155792/b08dd5d6-d67f-11e5-9223-15d6bdfee6e9.png)

All that should be possible with the different view-types Marionette provides, e.g. LayoutView, ListView, ItemView.

With those views in place it should finally be possible to kill ui.js and (re)move most of those jquery-hacks (e.g. replacing content views instead of showing and hiding different html elements).

@owncloud/mail @ErikPel @radlr any input is appreciated. Please let me know if there's anything we can improve before someone starts implementing.

**Comment by Gomez** [comment]
As discussed with @jancborchardt We can drop the SettingsView and merge it with the three dot menu. Work is already done here.

Looks good! Which one can i implement?

**Comment by ChristophWurst** [comment]
> As discussed with @jancborchardt We can drop the SettingsView and merge it with the three dot menu. Work is already done here.

Awesome! If it helps you can use at the sketch app for reference, it uses a three dot menu with marionette too: https://github.com/ChristophWurst/sketch/tree/master/js/view

> Which one can i implement?

I'll first have a look at the content and messagecontent view. That should be the foundation for any further works. So simply pick all the views you would like to create and let us know so we don't work on the same components ;-)

**Comment by ChristophWurst** [comment]
Let's create a check list to track our progress:

View | Status | Developer
------|-------|---------
AppView | :white_check_mark:  | -
NavigationView | :white_check_mark: | -
NewMessageView |  | ?
AccountsView | :white_check_mark: | -
SettingsView | | @Gomez 
ContentView | | @ChristophWurst
SetupView | :white_check_mark: | -
MessageContentView | | ?
MessageListView | :white_check_mark: | -
MessageView | | ?
LoadingView | | ?

If anybody is working on a view, please update the table.

**Comment by ChristophWurst** [comment]
> As discussed with @jancborchardt We can drop the SettingsView and merge it with the three dot menu. Work is already done here.

I thougt about that and I'm afraid I have to disagree. Removing the settings is fine, but putting the button for adding an account to existing account's menus is strange. I assume users won't expect to find it there. Can we leave that in the settings view until we find an appropriate place to put it?

**Comment by jancborchardt** [comment]
@ChristophWurst we could also put it all the way to the bottom of the account list, that was the other thought. But we thought it might be better to put it in the menu since it’s not an action you do that often. Also, it’s symmetric to deleting an account so it has some sort of relevance there. Especially when you have only one account yet.

**Comment by ChristophWurst** [comment]
I think most of the original plan has been implemented in the meantime, so I'm closing this now :rocket:
