### ISSUE TITLE
HTML messages not displayed

### ISSUE THREAD

**Issue by Neraste** [owncloud/mail#1316]
HI OC mail team!

I have never been able to display HTML formatted messages for several versions, while plain text ones are fine. So I decided to open an issue there.

It is really close to #1059, but I am not behind a proxy.

### Steps to reproduce
1. Create an account (say, connected to a Gmail account) ;
2. Try to read an HTML formatted mail

### Expected behaviour
The message is displayed, like in desktop mail client or Gmail webmail.

### Actual behaviour

Message title and author are shown, as well as reply form. But the message itself is not displayed.

#### On Firefox

There is only an empty iframe:

```html
<div id="mail-content">
		<div id="show-images-text">
			The images have been blocked to protect your privacy.
			<button id="show-images-button">Show images from this sender</button>
		</div>
		<div class="icon-loading">
			<iframe src="https://cloud_debug/index.php/apps/mail/accounts/1/folders/SU5CT1g=/messages/3625/html" seamless="">
                <html><head></head><body></body></html>
			</iframe>
		</div>
	</div>
```

In JS log, I get:

```
Error: Permission denied to access property "document"
.contents()
.map()
x.fn[e]()
h.onWindowResize()
PageStyleActor<.getAppliedProps()
PageStyleActor<.getApplied<()
```

I tried to apply issue #1059 solution, but it was no help.

#### On Chromium

Same as Firefox, but I get a loading wheel instead of message body.

**OwnCloud Mail version:** 0.3.0

**Mailserver or service:** Gmail, but occurs also with other services

**Transport security - IMAP:** SSL, but occurs also with different settings

**Transport security - SMTP:** SSL, but occurs also with different settings

**Number of accounts:** 1

**ownCloud Mail version build date:** Using stable release

### Server configuration
**Operating system**: OpenSUSE 13.2 on armv7hl

**Web server:** nginx 1.8.0-1.1

**Database:** MariaDB 10.0.20-2.12.1

**PHP version:** PHP 5.6.1-39.1

**ownCloud version:** 8.2.2

**Updated from an older ownCloud or fresh install:** Fresh install

**List of activated apps:** Default modules after fresh install, plus mail app of course.

```
  - activity: 2.1.3
  - files: 1.2.0
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - files_videoviewer: 0.1.3
  - firstrunwizard: 1.1
  - gallery: 14.2.0
  - mail: 0.3.0
  - notifications: 0.1.0
  - provisioning_api: 0.3.0
  - templateeditor: 0.1
  - updater: 0.6
```

**The content of config/config.php:**

```
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "cloud_debug"
        ],
        "datadirectory": "owncloud/location/data",
        "overwrite.cli.url": "http:\/\/localhost",
        "overwriteprotocol": "https",
        "dbtype": "mysql",
        "version": "8.2.2.2",
        "dbname": "owncloud_debug",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "instanceid": "oc36oct8asmd",
    }
}

```

**Nginx config:** force HTTPS

### Client configuration
**Browser:** Firefox 43, Chromium 48

**Operating system:** OpenSUSE Tumbleweed on x86_64

### Logs
Nothing interesting seems to appear in logs, but what I have reported in Firefox JS log.

**Comment by ChristophWurst** [comment]
Hi @Neraste,
is ``https://cloud_instance/`` really the host you are accessing the the app? 

> "trusted_domains": [ "localhost", "cloud_debug" ],

^Here you list other hosts. Are they really different?

**Comment by Neraste** [comment]
Yeah, I messed up annonyfication...

**Comment by ChristophWurst** [comment]
> Yeah, I messed up annonyfication... Sorry if this was misleading.

No worries. So the host you access the app is the same as in the iframe url? Is it the very same protocol and url?

**Comment by Neraste** [comment]
Yes, same URL and same protocol (HTTPS).

**Comment by ChristophWurst** [comment]
Strange. @LukasReschke any idea?

**Comment by Neraste** [comment]
As I mentioned, I have had this behavior in previous versions too : OC 8.1.0

**Comment by jancborchardt** [comment]
Closing cause we can’t reproduce. This might be fixed in newer versions.
