### ISSUE TITLE
Wiki & FAQs

### ISSUE THREAD

**Issue by aspdye** [owncloud/mail#1331]
Like Calendar does: 

- [ ] Enable Wiki for Repository
- [ ] Move Troubleshooting from README.md to Wiki
- [ ] Create some FAQ stuff
- [ ] Reference Wiki in the README.md

cc @jancborchardt @DeepDiver1975 @ChristophWurst

**Comment by jancborchardt** [comment]
I’m strongly against using the wiki, as it just complicates where people look for stuff. Any FAQ / Troubleshooting should be in the repo – that way it’s both referencable online and you have it offline with the app in case you need it.

**Comment by aspdye** [comment]
I see your point, and i must say that I agree @jancborchardt. But I think we should find a solution - practiced in all repositories (calendar, contacts and mail).

**Comment by jancborchardt** [comment]
I’d say a file called »HELP.md« or something descriptive, directly in the root folder. »Troubleshooting« is a very technical word« and »FAQ« is the worst abbreviation in existence.

**Comment by ChristophWurst** [comment]
personally, I'd prefer adding a 'doc' folder as discussed in #1164
