### ISSUE TITLE
Add .ico favicon for the notification favicon

### ISSUE THREAD

**Issue by ChristophWurst** [owncloud/mail#1335]
Similar to the default favicon, the notification favicon (the one with the red dot) should also be used in case of a browser not supporting png favicons.

ref https://github.com/owncloud/mail/pull/1324

@jancborchardt @owncloud/designers

**Comment by jancborchardt** [comment]
Since we’re dropping .ico for 9.1 I wouldn’t bother with this to be honest.

**Comment by ChristophWurst** [comment]
> Since we’re dropping .ico for 9.1 I wouldn’t bother with this to be honest.

Alright, I didn't know about the .ico drop.
