### ISSUE TITLE
Sending Mail gives an Server Error Message - but sends correctly

### ISSUE THREAD

**Issue by Maulwurf16** [owncloud/mail#1336]
I have several imap Mail Accounts configured and wanted to test send a mail from one account to another. So i just wrote one from my gmail adress to my outlook adress. The Web UI gave me a server error warning - the message however was sent correctly. (I checked in outlook and there it was). Also, the mail client picked it up correctly.
I think I ran out of some timing request? My "server setup" is absolutely low end and slow, as it's running on a raspberry pi 1st gen.
However... The warning shouldn't be displayed, if everything went absolutely fine.

### Steps to reproduce
1.Setup Imap Mail Account(s)
2.Send Mail

### Expected behaviour
Mail should be sent and no Error shown

### Actual behaviour
The Mail App throws a "Server Error" Warning and the Owncloud Log shows these two:

Error	mail	Sending mail failed: Error when communicating with the server.	a minute ago
Info	mail	Updating draft <0> in account <2>	a minute ago

**OwnCloud Mail version:** (see ownCloud apps admin page)
0.3

**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)

outlook and gmail

**Transport security - IMAP:** (None, SSL, TLS, STARTTLS) 

imap, tsl

**Transport security - SMTP:** (None, SSL, TLS, STARTTLS)

imap tsl

**Number of accounts:**

4

**ownCloud Mail version build date:** (only if you are using a Nightly Build)

## ownCloud Core

8.2.2

### Server configuration
**Operating system**:
Raspian
**Web server:**
Apache
**Database:**
MySQL
**PHP version:**
latest
**ownCloud version:** (see ownCloud admin page)
8.2.2
**Updated from an older ownCloud or fresh install:**
fresh install
**List of activated apps:**
calendar, contacts, mail, log viewer,documents, activity
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

pi@raspberrypi:/var/www $ sudo -u www-data php owncloud/occ config:list system
{
    "system": {
        "instanceid": "#",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.0.16"
        ],
        "datadirectory": "\/media\/usb-hdd\/owncloud\/data",
        "overwrite.cli.url": "http:\/\/192.168.0.16\/owncloud",
        "dbtype": "mysql",
        "version": "8.2.2.2",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "mail_domain": "#",
        "mail_from_address": "#",
        "mail_smtpmode": "smtp",
        "theme": "",
        "loglevel": 0,
        "maintenance": false,
        "trashbin_retention_obligation": "auto",
        "appstore.experimental.enabled": true,
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "smtp.gmail.com",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "ssl",
        "activity_expire_days": 365
    }
}

**Comment by ChristophWurst** [comment]
@Maulwurf16 thank you for reporting your issue.
Please provide all information asked in the issue template so we can debug this error. Thanks.

**Comment by Maulwurf16** [comment]
Owncloud log:
```
Level	App	Message	Time
Debug	core	OC_Image->fixOrientation() Orientation: -1	2 minutes ago
Debug	core	OC_Image->fixOrientation() Image is not a JPEG.	2 minutes ago
Debug	mail	loading messages 0 to 20 of folder <YWxsLWluYm94ZXM=>	3 minutes ago
Error	news	Unexpected error when updating feed More than one result	11 minutes ago
Error	index	Horde_Imap_Client_Exception: Mail server denied authentication.	15 minutes ago
Error	index	Horde_Imap_Client_Exception: Mail server denied authentication.	16 minutes ago
Error	index	Horde_Imap_Client_Exception: Mail server denied authentication.	16 minutes ago
Error	index	Horde_Imap_Client_Exception: Mail server denied authentication.	17 minutes ago
Error	index	Horde_Imap_Client_Exception: Mail server denied authentication.	18 minutes ago
```

Horde log:
```
sudo tail /media/usb-hdd/owncloud/data/horde.log
C: 7 UID STORE 0 +FLAGS \deleted
S: 7 BAD Could not parse command
>> Command 7 took 0.0815 seconds.
C: 8 UID EXPUNGE 1:*
S: 8 OK Success
>> Command 8 took 0.0253 seconds.
C: 9 LOGOUT
S: * BYE LOGOUT Requested
S: 9 OK 73 good day (Success)
>> Command 9 took 0.0398 seconds.
```

Nevermind I am so sorry. It seems more to be a problem with the two web.de accounts I have set up. They only allow one imap connection every 15 minutes.
The warning was about those two accounts and just happened to be at the same time, I sent a mail. So it was that warning, that was displayed. I just tried it several times again. If web.de allows an imap connection, no warning is shown and the mail app just displays the correct "mail sent" message.

Maybe one could change the imap connection intervall?

**Comment by ChristophWurst** [comment]
> Nevermind I am so sorry. It seems more to be a problem with the two web.de accounts I have set up. They only allow one imap connection every 15 minutes.

Really? One connection every 15 minutes?

> Maybe one could change the imap connection intervall?

There's nothing we can do about that with PHP as every request has a separate connection to the IMAP server which results in multiple connections being opened simultaneously.

**Comment by Maulwurf16** [comment]
Yeah - they had this 15 minutes timout for all users for several time, until they dropped it officially last year.
However, surfing around I figured, that they sporadically re enable that timeout, if you "spammed" the imap protocoll to your mail account.
Well, as I was playing with the mail app and checking the mail in thunderbird, I assume that they re enabled the time out for my account (for now).

Well... I am really sorry for bugging you all and I'll just keep using my great working mail client :)

**Comment by ChristophWurst** [comment]
> Well... I am really sorry for bugging you all and I'll just keep using my great working mail client :)

No worries, I'm pleased to hear it's working now ;-)
