### ISSUE TITLE
ownCloud 9.0.0: error while loading messages

### ISSUE THREAD

**Issue by Echse27** [owncloud/mail#1341]
### Steps to reproduce
1. After upgrade OC from 8.2.2 this error appiers
2. complete uninstall of the mail app include drop table "oc_mail_accounts" with all old mailaccounts and reinstalling the app reproduce this error
3. deactivating and activate the mail app with the same error

### Expected behaviour
The mail account appiers but the error message "error while loading messages" appiers in the top of the screen and no mails and maildetails are shown.

**OwnCloud Mail version: 0.3.0

**Mailserver or service: GMail

**Transport security - IMAP: SSL 

**Transport security - SMTP: SSL

**Number of accounts: 2

### Server configuration
**Operating system** UbuntuServer 14.04 LTS

**Web server:** Apache/2.4.7 (Ubuntu) Server Build: Jan 14 2016

**Database:** MySQL 5.5.47-0ubuntu0.14.04.1

**PHP version:** PHP 5.5.9-1ubuntu4.14

**ownCloud version:** 9.0.0

**Updated from an older ownCloud or fresh install:**
Upgrade from 8.2.2
Download the new realease and copy the config and data folder into the new OwnCloud Folderstructure.
The rights I have also adjusted
All are fine but the mail app not.

**List of activated apps:**

Enabled:
  - activity: 2.2.1
  - announcementcenter: 1.1.1
  - calendar: 1.0
  - comments: 0.2
  - contacts: 1.0.0.0
  - dav: 0.1.5
  - direct_menu: 0.7.0
  - documents: 0.12.0
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_mv: 0.8.2
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - libreonline: 0.1
  - mail: true
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - registration: 0.1.3
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - encryption
  - external
  - files_external
  - spreedme
  - user_external
  - user_ldap

```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "oc4ymjyh19zr",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.0.110",
            "MADOMAIN",
            "MYDOMAIN"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "https:\/\/MYIP\/owncloud",
        "dbtype": "mysql",
        "version": "9.0.0.19",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "mail_from_address": "MAILUSER",
        "mail_smtpmode": "smtp",
        "mail_domain": "gmail.com",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "smtp.gmail.com",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "ssl",
        "maintenance": false,
        "loglevel": 3,
        "trashbin_retention_obligation": "auto",
        "theme": "",
        "appstore.experimental.enabled": true,
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}

```

### Client configuration
**Browser:**
Chromium Version 48.0.2564.116 Ubuntu 14.04 (64-bit)

**Operating system:**
Ubuntu 14.04. LTS Client

### Logs
#### Web server error log
```
Insert your webserver log here
```
DateTime::__construct(): Failed to parse time string (Tue, 29 Dec 2015 19:14:06 UT) at position 26 (U): The timezone could not be found in the database at /var/www/owncloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/DateTime.php#40

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```
{"reqId":"6nvfAx\/i11eEJDPqX5Me","remoteAddr":"109.192.41.72","app":"PHP","message":"Undefined index: newVersionString at \/var\/www\/owncloud\/apps\/updatenotification\/templates\/admin.php#8","level":3,"time":"2016-03-12T15:10:25+00:00"}
{"reqId":"Xl8DWODtRL70u0YirLxD","remoteAddr":"79.216.40.40","app":"no app in context","message":"Exception: {\"Exception\":\"OCP\\\\Files\\\\NotFoundException\",\"Message\":\"\\\/SofortUpload\\\/20160312_160827.jpg not found while trying to get owner\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/filesystem.php(913): OC\\\\Files\\\\View->getOwner('\\\/SofortUpload\\\/2...')\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/activity\\\/lib\\\/fileshooks.php(191): OC\\\\Files\\\\Filesystem::getOwner('\\\/SofortUpload\\\/2...')\\n#2 \\\/var\\\/www\\\/owncloud\\\/apps\\\/activity\\\/lib\\\/fileshooks.php(145): OCA\\\\Activity\\\\FilesHooks->getSourcePathAndOwner('\\\/SofortUpload\\\/2...')\\n#3 \\\/var\\\/www\\\/owncloud\\\/apps\\\/activity\\\/lib\\\/fileshooks.php(101): OCA\\\\Activity\\\\FilesHooks->addNotificationsForFileAction('\\\/SofortUpload\\\/2...', 'file_created', 'created_self', 'created_by')\\n#4 \\\/var\\\/www\\\/owncloud\\\/apps\\\/activity\\\/lib\\\/fileshooksstatic.php(60): OCA\\\\Activity\\\\FilesHooks->fileCreate('\\\/SofortUpload\\\/2...')\\n#5 [internal function]: OCA\\\\Activity\\\\FilesHooksStatic::fileCreate(Array)\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/hook.php(105): call_user_func(Array, Array)\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/filechunking.php(224): OC_Hook::emit('OC_Filesystem', 'post_create', Array)\\n#8 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/connector\\\/sabre\\\/file.php(436): OC_FileChunking->file_assemble(Object(OCA\\\\Files_Trashbin\\\\Storage), 'files\\\/SofortUpl...', '\\\/josch\\\/files\\\/So...')\\n#9 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/connector\\\/sabre\\\/file.php(103): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->createFileChunked(Resource id #39)\\n#10 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/connector\\\/sabre\\\/directory.php(134): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->put(Resource id #39)\\n#11 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1036): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->createFile('20160312_160827...', Resource id #39)\\n#12 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(525): Sabre\\\\DAV\\\\Server->createFile('SofortUpload\\\/20...', Resource id #39, NULL)\\n#13 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#14 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#15 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(459): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#16 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#17 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(55): Sabre\\\\DAV\\\\Server->exec()\\n#18 \\\/var\\\/www\\\/owncloud\\\/remote.php(138): require_once('\\\/var\\\/www\\\/ownclo...')\\n#19 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php\",\"Line\":1583}","level":3,"time":"2016-03-12T15:10:39+00:00"}


#### Horde log (data/horde.log)
```
Insert your horde log here, see https://github.com/owncloud/mail#debug-mode
```
------------------------------
>> Sat, 12 Mar 2016 15:22:39 +0000
>> Connection to: imap://imap.gmail.com:993/
>> Server connection took 0.0644 seconds.
S: * OK Gimap ready for requests from 109.192.41.72 o12mb11657975wlb
C: 1 CAPABILITY
S: * CAPABILITY IMAP4rev1 UNSELECT IDLE NAMESPACE QUOTA ID XLIST CHILDREN X-GM-EXT-1 XYZZY SASL-IR AUTH=XOAUTH2 AUTH=PLAIN AUTH=PLAIN-CLIENTTOKEN AUTH=OAUTHBEARER AUTH=XOAUTH
S: 1 OK Thats all she wrote! o12mb11657975wlb
>> Command 1 took 0.0183 seconds.
C: 2 AUTHENTICATE PLAIN [INITIAL CLIENT RESPONSE (username: ralflange83@gmail.com)]
S: * CAPABILITY IMAP4rev1 UNSELECT IDLE NAMESPACE QUOTA ID XLIST CHILDREN X-GM-EXT-1 UIDPLUS COMPRESS=DEFLATE ENABLE MOVE CONDSTORE ESEARCH UTF8=ACCEPT APPENDLIMIT=35882577 LIST-EXTENDED LIST-STATUS
S: 2 OK ralflange83@gmail.com authenticated (Success)
>> Command 2 took 0.0793 seconds.
C: 3 ENABLE UTF8=ACCEPT
C: 4 LIST () "" (*)
S: * ENABLED UTF8=ACCEPT
S: 3 OK Success
>> Command 3 took 0.0183 seconds.
S: * LIST (\HasNoChildren) "/" "Arbeit"
S: * LIST (\HasNoChildren) "/" "Belege"
S: * LIST (\HasNoChildren) "/" "Deleted Messages"
S: * LIST (\HasNoChildren) "/" "Drafts"
S: * LIST (\HasNoChildren) "/" "INBOX"
S: * LIST (\HasNoChildren) "/" "Junkbox"
S: * LIST (\HasNoChildren) "/" "Outbox"
S: * LIST (\HasNoChildren) "/" "Privat"
S: * LIST (\HasNoChildren) "/" "Reisen"
S: * LIST (\HasNoChildren) "/" "Sent"
S: * LIST (\HasNoChildren) "/" "Sent Messages"
S: * LIST (\HasNoChildren) "/" "Trash"
S: * LIST (\HasChildren \NonExistent) "/" "[Google Mail]"
S: * LIST (\HasNoChildren) "/" "[Google Mail]/Alle Nachrichten"
S: * LIST (\HasNoChildren) "/" "[Google Mail]/Entwürfe"
S: * LIST (\HasNoChildren) "/" "[Google Mail]/Gesendet"
S: * LIST (\HasNoChildren) "/" "[Google Mail]/Markiert"
S: * LIST (\HasNoChildren) "/" "[Google Mail]/Papierkorb"
S: * LIST (\HasNoChildren) "/" "[Google Mail]/Spam"
S: * LIST (\HasNoChildren) "/" "[Google Mail]/Wichtig"
S: 4 OK Success
>> Command 4 took 0.0391 seconds.
C: 5 STATUS Sent (MESSAGES)
S: * STATUS "Sent" (MESSAGES 10)
S: 5 OK Success
>> Command 5 took 0.0213 seconds.
C: 6 STATUS Sent (MESSAGES)
S: * STATUS "Sent" (MESSAGES 10)
S: 6 OK Success
>> Command 6 took 0.019 seconds.
C: 7 STATUS "Sent Messages" (MESSAGES)
S: * STATUS "Sent Messages" (MESSAGES 0)
S: 7 OK Success
>> Command 7 took 0.0194 seconds.
C: 8 STATUS "Deleted Messages" (MESSAGES)
S: * STATUS "Deleted Messages" (MESSAGES 31)
S: 8 OK Success
>> Command 8 took 0.019 seconds.
C: 9 STATUS "Deleted Messages" (MESSAGES)
S: * STATUS "Deleted Messages" (MESSAGES 31)
S: 9 OK Success
>> Command 9 took 0.0185 seconds.
C: 10 STATUS Trash (MESSAGES)
S: * STATUS "Trash" (MESSAGES 0)
S: 10 OK Success
>> Command 10 took 0.018 seconds.
C: 11 LIST () "" (INBOX Drafts Sent "Sent Messages" "[Google Mail]/Spam" "Deleted Messages" Trash "[Google Mail]/Alle Nachrichten" Arbeit Belege "[Google Mail]/Entwürfe" "[Google Mail]/Gesendet" Junkbox "[Google Mail]/Markiert" Outbox "[Google Mail]/Papierkorb" Privat Reisen "[Google Mail]/Wichtig") RETURN (STATUS (MESSAGES RECENT UIDNEXT UIDVALIDITY UNSEEN))
S: * LIST (\HasNoChildren) "/" "Arbeit"
S: * STATUS "Arbeit" (MESSAGES 0 RECENT 0 UIDNEXT 1 UIDVALIDITY 620905595 UNSEEN 0)
S: * LIST (\HasNoChildren) "/" "Belege"
S: * STATUS "Belege" (MESSAGES 0 RECENT 0 UIDNEXT 1 UIDVALIDITY 620905596 UNSEEN 0)
S: * LIST (\HasNoChildren) "/" "Deleted Messages"
S: * STATUS "Deleted Messages" (MESSAGES 31 RECENT 0 UIDNEXT 78 UIDVALIDITY 620905606 UNSEEN 0)
S: * LIST (\HasNoChildren) "/" "Drafts"
S: * STATUS "Drafts" (MESSAGES 1 RECENT 0 UIDNEXT 250 UIDVALIDITY 620905605 UNSEEN 0)
S: * LIST (\HasNoChildren) "/" "INBOX"
S: * STATUS "INBOX" (MESSAGES 41 RECENT 0 UIDNEXT 10168 UIDVALIDITY 620905582 UNSEEN 2)
S: * LIST (\HasNoChildren) "/" "Junkbox"
S: * STATUS "Junkbox" (MESSAGES 0 RECENT 0 UIDNEXT 1 UIDVALIDITY 620905607 UNSEEN 0)
S: * LIST (\HasNoChildren) "/" "Outbox"
S: * STATUS "Outbox" (MESSAGES 0 RECENT 0 UIDNEXT 1 UIDVALIDITY 620905603 UNSEEN 0)
S: * LIST (\HasNoChildren) "/" "Privat"
S: * STATUS "Privat" (MESSAGES 0 RECENT 0 UIDNEXT 1 UIDVALIDITY 620905593 UNSEEN 0)
S: * LIST (\HasNoChildren) "/" "Reisen"
S: * STATUS "Reisen" (MESSAGES 0 RECENT 0 UIDNEXT 1 UIDVALIDITY 620905594 UNSEEN 0)
S: * LIST (\HasNoChildren) "/" "Sent"
S: * STATUS "Sent" (MESSAGES 10 RECENT 0 UIDNEXT 557 UIDVALIDITY 620905597 UNSEEN 0)
S: * LIST (\HasNoChildren) "/" "Sent Messages"
S: * STATUS "Sent Messages" (MESSAGES 0 RECENT 0 UIDNEXT 1 UIDVALIDITY 620905604 UNSEEN 0)
S: * LIST (\HasNoChildren) "/" "Trash"
S: * STATUS "Trash" (MESSAGES 0 RECENT 0 UIDNEXT 2881 UIDVALIDITY 620905598 UNSEEN 0)
S: * LIST (\HasNoChildren) "/" "[Google Mail]/Alle Nachrichten"
S: * STATUS "[Google Mail]/Alle Nachrichten" (MESSAGES 1924 RECENT 0 UIDNEXT 18642 UIDVALIDITY 620905592 UNSEEN 2)
S: * LIST (\HasNoChildren) "/" "[Google Mail]/Entwürfe"
S: * STATUS "[Google Mail]/Entwürfe" (MESSAGES 0 RECENT 0 UIDNEXT 3006 UIDVALIDITY 620905588 UNSEEN 0)
S: * LIST (\HasNoChildren) "/" "[Google Mail]/Gesendet"
S: * STATUS "[Google Mail]/Gesendet" (MESSAGES 58 RECENT 0 UIDNEXT 1798 UIDVALIDITY 620905587 UNSEEN 0)
S: * LIST (\HasNoChildren) "/" "[Google Mail]/Markiert"
S: * STATUS "[Google Mail]/Markiert" (MESSAGES 0 RECENT 0 UIDNEXT 28 UIDVALIDITY 620905585 UNSEEN 0)
S: * LIST (\HasNoChildren) "/" "[Google Mail]/Papierkorb"
S: * STATUS "[Google Mail]/Papierkorb" (MESSAGES 31 RECENT 0 UIDNEXT 12335 UIDVALIDITY 620905583 UNSEEN 3)
S: * LIST (\HasNoChildren) "/" "[Google Mail]/Spam"
S: * STATUS "[Google Mail]/Spam" (MESSAGES 0 RECENT 0 UIDNEXT 622 UIDVALIDITY 620905584 UNSEEN 0)
S: * LIST (\HasNoChildren) "/" "[Google Mail]/Wichtig"
S: * STATUS "[Google Mail]/Wichtig" (MESSAGES 163 RECENT 0 UIDNEXT 8252 UIDVALIDITY 620905599 UNSEEN 1)
S: 11 OK Success
>> Command 11 took 0.0322 seconds.
C: 12 STATUS INBOX (MESSAGES RECENT UIDNEXT UIDVALIDITY UNSEEN)
S: * STATUS "INBOX" (MESSAGES 41 RECENT 0 UIDNEXT 10168 UIDVALIDITY 620905582 UNSEEN 2)
S: 12 OK Success
>> Command 12 took 0.0203 seconds.
C: 13 STATUS "[Google Mail]" (MESSAGES RECENT UIDNEXT UIDVALIDITY UNSEEN)
S: 13 NO [NONEXISTENT] Invalid folder: [Google Mail] (Failure)
>> Command 13 took 0.0185 seconds.
C: 14 STATUS Sent (MESSAGES)
S: * STATUS "Sent" (MESSAGES 10)
S: 14 OK Success
>> Command 14 took 0.0195 seconds.
C: 15 STATUS Sent (MESSAGES)
S: * STATUS "Sent" (MESSAGES 10)
S: 15 OK Success
>> Command 15 took 0.0193 seconds.
C: 16 STATUS "Sent Messages" (MESSAGES)
S: * STATUS "Sent Messages" (MESSAGES 0)
S: 16 OK Success
>> Command 16 took 0.0275 seconds.
C: 17 STATUS "Deleted Messages" (MESSAGES)
S: * STATUS "Deleted Messages" (MESSAGES 31)
S: 17 OK Success
>> Command 17 took 0.0186 seconds.
C: 18 STATUS "Deleted Messages" (MESSAGES)
S: * STATUS "Deleted Messages" (MESSAGES 31)
S: 18 OK Success
>> Command 18 took 0.0194 seconds.
C: 19 STATUS Trash (MESSAGES)
S: * STATUS "Trash" (MESSAGES 0)
S: 19 OK Success
>> Command 19 took 0.0187 seconds.
C: 20 LOGOUT
S: * BYE LOGOUT Requested
S: 20 OK 73 good day (Success)
>> Command 20 took 0.0185 seconds.
------------------------------

**Comment by ChristophWurst** [comment]
> Web server error log
> 
> DateTime::__construct(): Failed to parse time string (Tue, 29 Dec 2015 19:14:06 UT) at position 26 (U): The timezone could not be found in the database at /var/www/owncloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/DateTime.php#40

Do you know if you had mail 0.3 installed before the update? Those horde libs are not changed when upgrading owncloud core, hence the error should also have been thrown on owncloud 8.2.

> ownCloud log (data/owncloud.log)
> 
> {"reqId":"6nvfAx\/i11eEJDPqX5Me","remoteAddr":"109.192.41.72","app":"PHP","message":"Undefined index: newVersionString at \/var\/www\/owncloud\/apps\/updatenotification\/templates\/admin.php#8","level":3,"time":"2016-03-12T15:10:25+00:00"}
> {"reqId":"Xl8DWODtRL70u0YirLxD","remoteAddr":"79.216.40.40","app":"no app in context","message":"Exception: {\"Exception\":\"OCP\\\\Files\\\\NotFoundException\",\"Message\":\"\\\/SofortUpload\\\/20160312_160827.jpg not found while trying to get owner\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/filesystem.php(913): OC\\\\Files\\\\View->getOwner('\\\/SofortUpload\\\/2...')\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/activity\\\/lib\\\/fileshooks.php(191): OC\\\\Files\\\\Filesystem::getOwner('\\\/SofortUpload\\\/2...')\\n#2 \\\/var\\\/www\\\/owncloud\\\/apps\\\/activity\\\/lib\\\/fileshooks.php(145): OCA\\\\Activity\\\\FilesHooks->getSourcePathAndOwner('\\\/SofortUpload\\\/2...')\\n#3 \\\/var\\\/www\\\/owncloud\\\/apps\\\/activity\\\/lib\\\/fileshooks.php(101): OCA\\\\Activity\\\\FilesHooks->addNotificationsForFileAction('\\\/SofortUpload\\\/2...', 'file_created', 'created_self', 'created_by')\\n#4 \\\/var\\\/www\\\/owncloud\\\/apps\\\/activity\\\/lib\\\/fileshooksstatic.php(60): OCA\\\\Activity\\\\FilesHooks->fileCreate('\\\/SofortUpload\\\/2...')\\n#5 [internal function]: OCA\\\\Activity\\\\FilesHooksStatic::fileCreate(Array)\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/hook.php(105): call_user_func(Array, Array)\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/filechunking.php(224): OC_Hook::emit('OC_Filesystem', 'post_create', Array)\\n#8 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/connector\\\/sabre\\\/file.php(436): OC_FileChunking->file_assemble(Object(OCA\\\\Files_Trashbin\\\\Storage), 'files\\\/SofortUpl...', '\\\/josch\\\/files\\\/So...')\\n#9 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/connector\\\/sabre\\\/file.php(103): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->createFileChunked(Resource id #39)\\n#10 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/connector\\\/sabre\\\/directory.php(134): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->put(Resource id #39)\\n#11 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1036): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->createFile('20160312_160827...', Resource id #39)\\n#12 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(525): Sabre\\\\DAV\\\\Server->createFile('SofortUpload\\\/20...', Resource id #39, NULL)\\n#13 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#14 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#15 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(459): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#16 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#17 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(55): Sabre\\\\DAV\\\\Server->exec()\\n#18 \\\/var\\\/www\\\/owncloud\\\/remote.php(138): require_once('\\\/var\\\/www\\\/ownclo...')\\n#19 {main}\",\"File\

Those are erros of other apps. You might want to open an issue in core (it's the files app).

**Comment by Echse27** [comment]
I used mail 0.3.0 also before...
Am 12.03.2016 4:57 nachm. schrieb "Christoph Wurst" <
notifications@github.com>:

**Comment by danielcb** [comment]
I'm seeing the same error. In the dev console I see that the following url gets called:
https://<domain>/index.php/apps/mail/accounts/-1/folders/...

This just happens with one account. All other accounts are working and accessing the correct indexes (e.g. something besides -1).

The only obvious difference between the accounts is that the defect one uses multiple mail accounts.

**Comment by Echse27** [comment]
So now, i have done this:

DROP TABLE oc_mail_accounts
and i DELETE the entries for the mail app in the TABLE oc_appconfig

then i have delet the complete mail folder in owncloud/apps/
I newley istall the mailapp and the config of the first account looks good, but after that the message "error while loading messages" appiers also.
Inside the LOG i found the old error:

	DateTime::__construct(): Failed to parse time string (Tue, 29 Dec 2015 19:14:06 UT) at position 26 (U): The timezone could not be found in the database at /var/www/owncloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/DateTime.php#40

I don´t know whats up, but it looks like something is happen with the time (Tue, 29 Dec 2015....) ???

**Comment by Maulwurf16** [comment]
same Problem here. Used Mail 0.3 with Owncloud 8.2.2 with (almost) no problems. Since the OC Upgrade to 9.0, Mail isn't capable of fetching E-Mails anymore.
Also, I have added 4 Mail Accounts in my User Account. I will post Debug Data, once I'm at home.

**Comment by JanMiddelkoop** [comment]
I have just installed the nightly build of Mail in a clean setup of ownCloud 9.  I expected problems, but it actually seems to work fine with ownCloud 9 on a CentOS server running php7, with multiple mail accounts.  Maybe you could try the nightly builds?

https://en0ch.se/index.php/s/3v5J3XXeQCCp73p

**Comment by Echse27** [comment]
@Jan
Thank's for the tip...
I will give it a try.
Am 15.03.2016 11:10 nachm. schrieb "Jan Middelkoop" <
notifications@github.com>:

**Comment by joergmschulz** [comment]
Sorry, for me this behaviour stays even with the nightly version owncloud_mail_nightly_build_20160316.tar.gz.

**Comment by joergmschulz** [comment]
>  just installed the nightly build of Mail

Sorry, for me this behaviour stays even with the nightly version owncloud_mail_nightly_build_20160316.tar.gz.

**Comment by ChristophWurst** [comment]
I could finally reproduce this on one of my owncloud installation: #1348. Let's continue there.
