### ISSUE TITLE
Accounts not having different colours

### ISSUE THREAD

**Issue by smartroad** [owncloud/mail#1342]
### Steps to reproduce
1. Add more than one account

### Expected behaviour
Different colour for each account both on the left of the account name and one the left of the email list

### Actual behaviour
Getting the same colour for the two accounts I have added (light yellow/green)

**OwnCloud Mail version:**
8.2.2

**Mailserver or service:**
gmail and IMAP

**Transport security - IMAP:** (SSL) 

**Transport security - SMTP:** (SSL)

**Number of accounts:**
2

### Server configuration
**Operating system**: Rasbian Light

**Web server:** NGINX

**Database:** MYSQL

**PHP version:** 5.6.17

**ownCloud version:** 8.2.2

**Updated from an older ownCloud or fresh install:** Fresh

**List of activated apps:** 

```
Enabled:
  - activity: 2.1.3
  - audios: 1.2.5
  - calendar: 0.8.2
  - contacts: 0.5.0.0
  - documents: 0.11.1
  - files: 1.2.0
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - files_videoviewer: 0.1.3
  - firstrunwizard: 1.1
  - galleryplus: 14.4.0
  - mail: 0.3.0
  - news: 7.1.2
  - notifications: 0.1.0
  - provisioning_api: 0.3.0
  - templateeditor: 0.1
  - updater: 0.6
Disabled:
  - encryption
  - external
  - files_external
  - gallery
  - user_external
  - user_ldap
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "oct4db0njs11",

        "datadirectory": "\/mnt\/owncloud",

        "dbtype": "mysql",
        "version": "8.2.2.2",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "logtimezone": "UTC",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "appcodechecker": false,
        "appstore.experimental.enabled": true,
        "theme": "bobcloud",
        "mail_from_address": "info",
        "mail_smtpmode": "php",
        "mail_domain": "gingerlens.co.uk",
        "loglevel": 2,
        "maintenance": false
    }
}
```

### Client configuration
**Browser:**
Firefox 44.0.2

**Operating system:**
Windows 7

**Comment by ChristophWurst** [comment]
@smartroad AFAIK those colors are chosen based on a hashsum of the account name. Hence, there's nothing one can do about that with the current implementation.

@jancborchardt any solution for that problem? How about hard-coding 10 account colors, assuming nobody has more then 10 mail accounts?

**Comment by JanMiddelkoop** [comment]
In line with #1182, I'd suggest adding a field to configure the color manually.

**Comment by smartroad** [comment]
I discovered that the colors aren't exactly the same. I took a screen shot and checked the rgb values and both have the same green and blue but the red has 2 points different. So although they look the same technically they are different, even if only just and not to the human eye!

Being able to set manually would be a great solution :)

**Comment by jancborchardt** [comment]
We’ll not offer the ability to set the color manually since that’s overkill. @ChristophWurst the approach with 10 (or however many) preset colors is good.

**Comment by jancborchardt** [comment]
They should of course be based on the algorithm used in our placeholder.js library to look nice.

**Comment by skjnldsv** [comment]
Isn't it fixed?

**Comment by jancborchardt** [comment]
Yup, can be closed. :)
