### ISSUE TITLE
Horde fails parsing time strings

### ISSUE THREAD

**Issue by ChristophWurst** [owncloud/mail#1348]
### Steps to reproduce
1. Disable server-side cache (otherwise the exception is only logged the first time the message is fetched and hence the error is not reproducible)
2. Open the app
3. Open a folder (it doesn't fail on all of my folders)

### Expected behaviour
Messages should be loaded

### Actual behaviour
"Erros while loading messages" message shown.

**OwnCloud Mail version:** (see ownCloud apps admin page)
master 2016-03-16

**PHP**
PHP 5.6.17-0+deb8u1 (cli) (built: Jan 13 2016 09:10:12), Debian

#### ownCloud log (data/owncloud.log)
```
{"reqId":"iOuGVWFX\/hJDEtU7aVlx","remoteAddr":"x.x.x.x","app":"PHP","message":"DateTime::__construct(): Failed to parse time string (Mon, 5 Mar 2012 13:00:59 +0000 (GMT+00:00)) at position 35 (+): Double timezone specification at \/var\/www\/owncloud\/apps\/mail\/vendor\/pear-pear.horde.org\/Horde_Imap_Client\/Horde\/Imap\/Client\/DateTime.php#38","level":3,"time":"2016-03-16T10:13:12+00:00"}
```

#### Horde log (data/horde.log)
```
Nothing unusual
```

#### Browser log
```
Nothing
```

replaces #1341, #1337, #1333, #1328, #655 (also oc9 and mail 0.3 has this issue)

**Comment by ChristophWurst** [comment]
I can't reproduce that on php7, hence it may be a php5-only bug…

**Comment by BenS89** [comment]
Would be interesting to know why this did not occur on 8.2.2...

**Comment by DeepDiver1975** [comment]
Would be great to see the message headers of that one single email which did cause this.

**Comment by ChristophWurst** [comment]
@DeepDiver1975 unfortunately, I'm not able to identify that message. I've enabled all debug logs, but that time string (something in 2012) does not occur in there. Apparently the oldest messages of that folder are from 2014. It's really that folder though, I triple checked it…
According to the log the failing time string is ``Mon, 5 Mar 2012 13:00:59 +0000 (GMT+00:00)``.

**Comment by DeepDiver1975** [comment]
@ChristophWurst conditional breakpoint at this location an see what's going on?

**Comment by ChristophWurst** [comment]
could never debug this and since then *I think* the error never occurred again. Maybe it was fixed upstream.
