### ISSUE TITLE
ownCloud crashes if Mail-App v0.4.0 and Music-App are both enabled

### ISSUE THREAD

**Issue by xn--nding-jua** [owncloud/mail#1358]
### Steps to reproduce
1. Install music-app v0.3.8
2. Install mail-app v0.3.0
3. Upgrade to mail-app v0.4.0

### Expected behaviour
Both apps should work without problems

### Actual behaviour
With enabled music-app the ownCloud-server crashes with "Internal Server Error" and is not usable until the music-app or the mail-app is disabled.

Hint to the error: the route "music.page.index" could not be found:

"Exception":"Symfony\\Component\\Routing\\Exception\\RouteNotFoundException","Message":"Unable to generate a URL for the named route \"music.page.index\" as such route does not exist.

**OwnCloud Mail version:** 0.4.0

**Mailserver or service:** all-inkl.com

**Transport security - IMAP:** TLS

**Transport security - SMTP:** TLS

**Number of accounts:** 2

### Server configuration
**Operating system**: Ubuntu 14.04.2 LTS

**Web server:** Apache (unknown version)

**Database:** SQL 5.4

**PHP version:** 5.6

**ownCloud version:** 8.2.1.4

**Updated from an older ownCloud or fresh install:** from an older installation (6.x -> 7.x -> 8.0 -> 8.1 -> 8.2.1)

**List of activated apps:**

Enabled:
  - activity: 2.1.3
  - bookmarks: 0.6
  - calendar: 0.8.1
  - contacts: 0.5.0.0
  - documents: 0.11.0
  - encryption: 1.1.0
  - files: 1.2.0
  - files_external: 0.3.0
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - files_videoviewer: 0.1.3
  - firstrunwizard: 1.1
  - galleryplus: 14.4.0
  - logreader: 1.1.0
  - mail: 0.4.0
  - news: 7.1.1
  - notifications: 0.1.0
  - ocusagecharts: 3.4.5
  - tasks: 0.8.1
  - updater: 0.6

Disabled:
  - external
  - files_mv
  - gallery
  - music
  - provisioning_api
  - templateeditor
  - user_external
  - user_ldap

**The content of config/config.php:**
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "www.noeding-online.de",
            "cloud.noeding-online.de",
            "noeding-online.de"
        ],
        "datadirectory": "\/www\/htdocs\/w00bd480\/noedingonline\/cloud\/data",
        "tempdirectory": "\/www\/htdocs\/w00bd480\/tmp",
        "dbtype": "mysql",
        "version": "8.2.1.4",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "theme": "",
        "maintenance": false,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "php",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "forcessl": true,
        "trashbin_retention_obligation": "30, 60",
        "versions_retention_obligation": "auto",
        "loglevel": 4,
        "log_rotate_size": 10485760,
        "logtimezone": "Europe\/Berlin",
        "check_for_working_webdav": true,
        "check_for_working_htaccess": true,
        "xframe_restriction": false,
        "secret": "***REMOVED SENSITIVE VALUE***",
        "forceSSLforSubdomains": true,
        "enable_previews": true,
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown"
        ],
        "singleuser": false,
        "remember_login_cookie_lifetime": 1296000,
        "session_lifetime": 86400,
        "session_keepalive": true,
        "appstore.experimental.enabled": true,
        "filesystem_check_changes": 0,
        "default_language": "de",
        "updatechecker": false,
        "cipher": "AES-256-CFB",
        "minimum.supported.desktop.version": "2.0.0",
        "filelocking.enabled": true
    }
}

### Client configuration
**Browser:** Mozilla Firefox 44.0.2

**Operating system:** Windows 10 x64

#### Web server error log
No access to webserver-log (shared host)

#### ownCloud log (data/owncloud.log)
Error	index	Exception: {"Exception":"Symfony\\Component\\Routing\\Exception\\RouteNotFoundException","Message":"Unable to generate a URL for the named route \"music.page.index\" as such route does not exist.","Code":0,"Trace":"#0 \/www\/htdocs\/w00bd480\/noedingonline\/cloud\/lib\/private\/route\/router.php(314): Symfony\\Component\\Routing\\Generator\\UrlGenerator->generate('music.page.inde...', Array, false)\n#1 \/www\/htdocs\/w00bd480\/noedingonline\/cloud\/lib\/private\/urlgenerator.php(65): OC\\Route\\Router->generate('music.page.inde...', Array)\n#2 \/www\/htdocs\/w00bd480\/noedingonline\/cloud\/apps\/music\/appinfo\/app.php(26): OC\\URLGenerator->linkToRoute('music.page.inde...')\n#3 \/www\/htdocs\/w00bd480\/noedingonline\/cloud\/lib\/private\/app.php(160): require_once('\/www\/htdocs\/w00...')\n#4 \/www\/htdocs\/w00bd480\/noedingonline\/cloud\/lib\/private\/app.php(141): OC_App::requireAppFile('music')\n#5 \/www\/htdocs\/w00bd480\/noedingonline\/cloud\/lib\/private\/app.php(118): OC_App::loadApp('music')\n#6 \/www\/htdocs\/w00bd480\/noedingonline\/cloud\/lib\/private\/util.php(130): OC_App::loadApps(Array)\n#7 \/www\/htdocs\/w00bd480\/noedingonline\/cloud\/lib\/private\/files\/filesystem.php(240): OC_Util::setupFS()\n#8 \/www\/htdocs\/w00bd480\/noedingonline\/cloud\/lib\/private\/server.php(147): OC\\Files\\Filesystem::getMountManager()\n#9 \/www\/htdocs\/w00bd480\/noedingonline\/cloud\/3rdparty\/pimple\/pimple\/src\/Pimple\/Container.php(112): OC\\Server->OC\\{closure}(Object(OC\\Server))\n#10 \/www\/htdocs\/w00bd480\/noedingonline\/cloud\/lib\/private\/appframework\/utility\/simplecontainer.php(104): Pimple\\Container->offsetGet('RootFolder')\n#11 \/www\/htdocs\/w00bd480\/noedingonline\/cloud\/lib\/private\/server.php(599): OC\\AppFramework\\Utility\\SimpleContainer->query('RootFolder')\n#12 \/www\/htdocs\/w00bd480\/noedingonline\/cloud\/lib\/private\/server.php(616): OC\\Server->getRootFolder()\n#13 \/www\/htdocs\/w00bd480\/noedingonline\/cloud\/apps\/mail\/appinfo\/application.php(42): OC\\Server->getUserFolder('Christian')\n#14 \/www\/htdocs\/w00bd480\/noedingonline\/cloud\/apps\/mail\/appinfo\/routes.php(23): OCA\\Mail\\AppInfo\\Application->__construct()\n#15 \/www\/htdocs\/w00bd480\/noedingonline\/cloud\/lib\/private\/route\/router.php(323): include_once('\/www\/htdocs\/w00...')\n#16 \/www\/htdocs\/w00bd480\/noedingonline\/cloud\/lib\/private\/route\/router.php(162): OC\\Route\\Router->requireRouteFile('\/www\/htdocs\/w00...', 'mail')\n#17 \/www\/htdocs\/w00bd480\/noedingonline\/cloud\/lib\/private\/route\/router.php(313): OC\\Route\\Router->loadRoutes()\n#18 \/www\/htdocs\/w00bd480\/noedingonline\/cloud\/lib\/private\/urlgenerator.php(65): OC\\Route\\Router->generate('mail.page.index', Array)\n#19 \/www\/htdocs\/w00bd480\/noedingonline\/cloud\/apps\/mail\/appinfo\/app.php(40): OC\\URLGenerator->linkToRoute('mail.page.index')\n#20 \/www\/htdocs\/w00bd480\/noedingonline\/cloud\/lib\/private\/app.php(160): require_once('\/www\/htdocs\/w00...')\n#21 \/www\/htdocs\/w00bd480\/noedingonline\/cloud\/lib\/private\/app.php(141): OC_App::requireAppFile('mail')\n#22 \/www\/htdocs\/w00bd480\/noedingonline\/cloud\/lib\/private\/app.php(118): OC_App::loadApp('mail')\n#23 \/www\/htdocs\/w00bd480\/noedingonline\/cloud\/lib\/base.php(835): OC_App::loadApps()\n#24 \/www\/htdocs\/w00bd480\/noedingonline\/cloud\/index.php(39): OC::handleRequest()\n#25 {main}","File":"\/www\/htdocs\/w00bd480\/noedingonline\/cloud\/3rdparty\/symfony\/routing\/Symfony\/Component\/Routing\/Generator\/UrlGenerator.php","Line":134}

**Comment by ChristophWurst** [comment]
cc @MorrisJobke

**Comment by MorrisJobke** [comment]
There was a bug in 0.3.8 -> fixed in 0.3.9 https://github.com/owncloud/music/releases

**Comment by xn--nding-jua** [comment]
Ah, thanks for the info. Will give it a try someday. At the moment i went back to mail v0.3.0 and everything works fine. I've made several fixes to the music-app so I cannot update without changing the code.

**Comment by ChristophWurst** [comment]
@xn--nding-jua can this issue be closed then?

**Comment by xn--nding-jua** [comment]
I think so. I will give it a try and if it will not work I can reopen this issue (but I trust in Morris ;-) )

**Comment by MorrisJobke** [comment]
> I think so. I will give it a try and if it will not work I can reopen this issue (but I trust in Morris ;-) )

I got another similar issue. I will look into this later if I missed something. cc @blizzz

**Comment by MorrisJobke** [comment]
https://github.com/owncloud/music/issues/481
