### ISSUE TITLE
Regression: Deleting first mail does not switch to next youngest one anymore

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/mail#1360]
When deleting the top most email, it switches back to the last one in the list.

Instead it should work as designed, switching back to the next (now new first) email in the list.

**Comment by ChristophWurst** [comment]
Is there any error in the js console? It still works here.

**Comment by jancborchardt** [comment]
Can’t reproduce anymore either, probably a bug related to https://github.com/owncloud/mail/issues/1359
