### ISSUE TITLE
Hidden left panel button on Mobile version

### ISSUE THREAD

**Issue by quik87** [owncloud/mail#1362]
### Steps to reproduce
1.Access to mail by a chrome brownser 49.0.2623.91 on Android 5.1.1
2.
3.

### Expected behaviour
You should see the button to hide/show left panel, to create a new mail and acceso to mail folders.

### Actual behaviour
The buttors appear for a second and disapear, and you cannot access to left panel.

**OwnCloud Mail version:** 0.4.0

**Mailserver or service:** 1and1 mail

**Transport security - IMAP:** SSL

**Transport security - SMTP:** TLS

**Number of accounts:** 50

### Server configuration
**Operating system**: Centos 6.7

**Web server:** Apache

**Database:** mysql 

**PHP version:** 5.4.45

**ownCloud version:** 8.2.3

**Comment by ChristophWurst** [comment]
@quik87 which button do you mean? Could you take a screenshot please?

**Comment by quik87** [comment]
I confuse that appears a button, but the functionality to show the left panel that appears sliding to the right
