### ISSUE TITLE
Show Troubleshooting-Guide (Gmail, Outlook.com, ...) for users

### ISSUE THREAD

**Issue by aspdye** [owncloud/mail#1372]
I think, something like
> An error has occurred while adding your account. Try again, or follow our **Troubeshooting-Guide**

would be very nice for our "non-technical" users.
Many errors like Gmail Display Unlock Chapta or Outlook.com's App Password could be solved like this, but currently the troubleshooting guide is only visible for admins (README.md) :wink:

**Comment by ChristophWurst** [comment]
Duplicate of https://github.com/owncloud/mail/issues/1164
