### ISSUE TITLE
Properly handle html  mails with embedded attachments

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/mail#138]
as of today we show embedded images of an html mail as attachment - but it should be displayed within the html mail

summoning @LukasReschke regarding security impacts

**Comment by jancborchardt** [comment]
@LukasReschke @DeepDiver1975 this seems to be fixed – HTML mails work fine. Or is this about something else?

**Comment by jancborchardt** [comment]
Postponing to 0.3 – @LukasReschke if you have time please check it out. :)
