### ISSUE TITLE
"Add attachment from file" not working

### ISSUE THREAD

**Issue by BenS89** [owncloud/mail#1380]
### Steps to reproduce
1. Create a new mail
2. Click on "Add attachment from file"
3. Chose a file and click "Select" (in german: "Auswählen")

### Expected behaviour
The selected file gets added as attachment.

### Actual behaviour
Nothing happens. There is the following JavaScript error:

<code>mail.min.js?v=598ec0e…:121 Uncaught ChildViewContainerMissingError: The specified "childViewContainer" was not found: ul</code>

**OwnCloud Mail version:** (see ownCloud apps admin page)  0.4.0

**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...) iCloud

**Number of accounts:** 1

### Server configuration
**Operating system**: Qnap Embedded Linux

**Web server:** Apache 2.4.12

**Database:** MariaDB 5.5

**PHP version:** 5.6

**ownCloud version:** (see ownCloud admin page) 9.0

**Updated from an older ownCloud or fresh install:** yes, from 8.2.2

**List of activated apps:** Calendar 1.0, Contacts 1.0, Mail 0.4.0

**Comment by Gomez** [comment]
Duplicate: https://github.com/owncloud/mail/issues/1371

Fixed here https://github.com/owncloud/mail/pull/1378

**Comment by BenS89** [comment]
#1378 does not fix this issue.

**Comment by ChristophWurst** [comment]
> #1378 does not fix this issue.

To be able to fix that bug I need more information. What errors did you get when using that branch?

**Comment by BenS89** [comment]
Sorry for that. I still get the JS error 
<code>Uncaught ChildViewContainerMissingError: The specified "childViewContainer" was not found: ul</code> 
at
 <code>mail.min.js?v=598ec0e…:121</code>

**Comment by ChristophWurst** [comment]
No worries. Seeing that you're using ``mail.min.js`` – did you run the make to re-create that file? It's the minified version used in production only. Hence, you won't see any changes unless you enable debug mode, or re-create that file using the Makefile.

**Comment by ChristophWurst** [comment]
Thanks for testing ;-)
