### ISSUE TITLE
Menu button vanishes on mobile

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/mail#1384]
On Firefox mobile for Android, the menu button in the top left doesn't show. Initially it's visible but not anymore when the list is loaded.

@ChristophWurst related to view refactoring? Smth for 0.4.1 I'd say.

**Comment by gouglhupf** [comment]
Actually it occur on Firefox and Chrome both desktop and mobile (I havn't checked the others). While the app is loading the messages the menu button is there. After that it probably replaces the hole container "#app-content" and not only the subcontainer ".container". So the menu button will be removed. I could be wrong. I will see if I can find out more... Be you have any ideas.

**Comment by ChristophWurst** [comment]
I'll have a look at this after #1399 has been finished
