### ISSUE TITLE
Lag between clicking message and it being displayed (regression)

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/mail#1387]
After updating my production instance to stable9 and latest Mail master, there is a significant delay between clicking the message and it loading in the content view. The old open mail stays in the view for about 4 seconds if it hasn’t been opened before.

This should of course switch directly over (and show a spinner). Otherwise it seems very unresponsive.

**Comment by ChristophWurst** [comment]
Known bug: https://github.com/owncloud/mail/pull/1309#issuecomment-186782163

I need some reviewers/testers for https://github.com/owncloud/mail/pull/1321, so I can finish the view and loading-view refactoring.

**Comment by jancborchardt** [comment]
Ok – the lag seems to be gone, but the spinner doesn’t vanish when the message is loaded (as you mentioned there might be spinner problems).

**Comment by ChristophWurst** [comment]
Exactly. That should be fixed as soon as I have finished the refactoring. Sorry about the issues in the meantime.

**Comment by jancborchardt** [comment]
THIS IS COMPLETELY UNACCEPTABLE! Sure sure no problem

**Comment by ChristophWurst** [comment]
Let's continue in #1025
