### ISSUE TITLE
Address autocompletion not working anymore with new Contacts app (regression)

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/mail#1388]
Any idea bout this @DeepDiver1975 @Henni @ChristophWurst @Gomez?

**Comment by Gomez** [comment]
Yes, we know. There was some discussion on the last meetup. @DeepDiver1975 @ChristophWurst You remember, what was it exactly? Something needs to be done in Contacts first? Lets write it down, so we can work on it.

**Comment by ChristophWurst** [comment]
This is not a bug with the new contacts app, but rather a problem of this app. Collected addresses are also not completed. Hence, this is a duplicate of #1345

What is broken with the new dav app is the contacts image, but that needs be fixed in core: https://github.com/owncloud/core/issues/23345

**Comment by jancborchardt** [comment]
Great, ok. Would be really awesome to have this fixed for 0.4.2 :)

**Comment by ChristophWurst** [comment]
Sure, PR is welcome :-P

**Comment by jancborchardt** [comment]
:D that’s what I’m thinking
