### ISSUE TITLE
log SMTP communication

### ISSUE THREAD

**Issue by ChristophWurst** [owncloud/mail#1392]
Similar to the existing IMAP logging, SMTP logging is helpful to debug mail sending errors. Thankfully, horde already [integrates this](https://github.com/horde/horde/blob/master/framework/Mail/lib/Horde/Mail/Transport/Smtphorde.php#L69-L72), we just have to make use of it.

**Comment by gouglhupf** [comment]
Thanks for committing my changes.

**Comment by ChristophWurst** [comment]
@gouglhupf pro tip: if you add "fixes #1392" to the commit message or the PR description, github closes the referenced issue automatically ;-)

**Comment by ChristophWurst** [comment]
@gouglhupf you are also very welcome to join us on our IRC channel #owncloud-mail on freenode ;-)
