### ISSUE TITLE
'TypeError: require(...).openComposer is not a function' when clicking 'New message'

### ISSUE THREAD

**Issue by ChristophWurst** [owncloud/mail#1393]
### Steps to reproduce
1. open the app
2. click 'New message'
3. see an error in the js console

### Expected behaviour
The composer is shown

### Actual behaviour
An error is thrown and the composer is not shown

@Gomez is that the error you had?

**Comment by Gomez** [comment]
No, i had a not defined error.

**Comment by ChristophWurst** [comment]
fixed in #1394
