### ISSUE TITLE
Send button hidden behind JavaScript XMPP Chat pane

### ISSUE THREAD

**Issue by roelbrand** [owncloud/mail#1404]
### Steps to reproduce
1. Install JavaScript XMPP Chat app, configure and login to XMPP account
2. login to ownCloud and make sure the XMPP pane is opened on the right side of the browser window
3. Open ownCloud Mail
4. click "New Message"

### Expected behaviour
The Send buttong on the bottom right of the New Message pane should be visible

### Actual behaviour
The Send button is hidden behind the XMPP pane and will only become visible by hiding the XMPP pane (clicking it to mimimize).

### ownCloud Mail

**ownCloud Mail version:** (see ownCloud apps admin page)
0.4.1

**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)
private mail server

**Transport security - IMAP:** (None, SSL, TLS, STARTTLS) 
SSL

**Transport security - SMTP:** (None, SSL, TLS, STARTTLS)
SSL

**Number of accounts:**
1

**ownCloud Mail version build date:** (only if you are using a Nightly Build)

#### Server configuration
**Operating system**:
Linux (Ubuntu)

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
PHP 5.5.9-1ubuntu4.14

**ownCloud version:** (see ownCloud admin page)
9.0.0

**Updated from an older ownCloud or fresh install:**
Updated

**List of activated apps:**
Enabled:
  - activity: 2.2.1
  - calendar: 1.0
  - comments: 0.2
  - contacts: 1.1.0.0
  - dav: 0.1.5
  - external: 1.2
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_external: 0.5.2
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - mail: 0.4.1
  - music: 0.3.10
  - news: 8.1.0
  - notes: 2.0.1
  - notifications: 0.2.3
  - ojsxc: 3.0.0
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
  - user_ldap: 0.8.0
  - user_pwauth: 2.3

**The content of config/config.php:**
{
    "system": {
        "installed": true,
        "dbtype": "mysql",
        "dbname": "owncloud",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "localhost",
        "dbtableprefix": "",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "forcessl": true,
        "overwritehost": "",
        "overwriteprotocol": "",
        "theme": "",
        "3rdpartyroot": "",
        "3rdpartyurl": "",
        "defaultapp": "files",
        "knowledgebaseenabled": true,
        "knowledgebaseurl": "http:\/\/api.apps.owncloud.com\/v1",
        "appstoreenabled": true,
        "appstoreurl": "http:\/\/api.apps.owncloud.com\/v1",
        "mail_smtpmode": "php",
        "mail_smtphost": "127.0.0.1",
        "mail_smtpport": "25",
        "appcodechecker": false,
        "updatechecker": true,
        "log_type": "owncloud",
        "logfile": "\/tmp\/owncloud.log",
        "loglevel": 2,
        "datadirectory": "\/data\/sites\/owncloud.ik.nu\/data",
        "apps_paths": [
            {
                "path": "\/data\/sites\/owncloud.ik.nu\/htdocs\/apps",
                "url": "\/apps",
                "writable": true
            }
        ],
        "instanceid": "51df105a4a805",
        "version": "9.0.0.19",
        "maintenance": false,
        "trusted_domains": [
            "owncloud.ik.nu"
        ],
        "secret": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "owncloud",
        "mail_domain": "ik.nu",
        "singleuser": false,
        "appstore.experimental.enabled": true,
        "trashbin_retention_obligation": "auto",
        "debug": false,
        "ldapIgnoreNamingRules": false
    }
}

#### Client configuration
**Browser:**
Firefox 

**Operating system:**
Linux Debian

**Comment by ChristophWurst** [comment]
I don't think there is anything that we should/could do to prevent that. In my opinion this is an issue of the chat app, it could overlap any other important control too.
