### ISSUE TITLE
E-Mail Notification spams Owncloud Log (and doesn't work?)

### ISSUE THREAD

**Issue by Maulwurf16** [owncloud/mail#1408]
### Steps to reproduce
1. Look at Owncloud Log

### Expected behaviour
Absolutey nothing should happen in the background (except for new mails incoming)

### Actual behaviour
Every 15 Minutes when my Cron Job fires, Mail produces this error entry in my Owncloud Log. I cannot see anything else bad happening. However, this has to mean something, or am I wrong? :)

### ownCloud Mail

**ownCloud Mail version:** (see ownCloud apps admin page) 0.4.1

**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...) Outlook

**Transport security - IMAP:** (None, SSL, TLS, STARTTLS)  TLS

**Transport security - SMTP:** (None, SSL, TLS, STARTTLS) TLS

**Number of accounts:** 1

**ownCloud Mail version build date:** (only if you are using a Nightly Build)

#### Server configuration
**Operating system**: raspbian jessy

**Web server:** Apache 2.4.10

**Database:** Mysql 5.0.11

**PHP version:** 5.5.44-0

**ownCloud version:** (see ownCloud admin page) 9.0.0

**Updated from an older ownCloud or fresh install:** updated

**List of activated apps:**

```
Enabled:
  - activity: 2.2.1
  - calendar: true
  - comments: 0.2
  - contacts: true
  - dav: 0.1.5
  - documents: true
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_external: 0.5.2
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - logreader: true
  - mail: true
  - news: 8.2.0
  - notifications: 0.2.3
  - ownnote: true
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - encryption
  - external
  - user_external
  - user_ldap
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "ocjzm5q41b9c",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "mwcloud.dynv6.net",
            "192.168.0.16"
        ],
        "datadirectory": "\/media\/usb-hdd\/owncloud\/data",
        "dbtype": "mysql",
        "version": "9.0.0.19",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "mail_domain": "gmail.com",
        "mail_from_address": "markus.westerhausen",
        "mail_smtpmode": "smtp",
        "theme": "",
        "loglevel": 2,
        "maintenance": false,
        "trashbin_retention_obligation": "auto",
        "appstore.experimental.enabled": true,
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "smtp.gmail.com",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "ssl",
        "activity_expire_days": 365,
        "app.mail.imaplog.enabled": false
    }
}
```

#### Client configuration
**Browser:**

**Operating system:**

##### Web server error log
```
nothing
```

##### ownCloud log (data/owncloud.log)
```
	Error while running background job (class: OCA\Activity\BackgroundJob\EmailNotification, arguments: ): {"Exception":"Exception","Message":"Session has been closed - no further changes to the session are allowed","Code":0,"Trace":"#0 \/var\/www\/owncloud\/lib\/private\/session\/memory.php(49): OC\\Session\\Memory->validateSession()\n#1 \/var\/www\/owncloud\/lib\/private\/security\/csrf\/tokenstorage\/sessionstorage.php(63): OC\\Session\\Memory->set('requesttoken', 'O6BErTBPZ4K\/qar...')\n#2 \/var\/www\/owncloud\/lib\/private\/security\/csrf\/csrftokenmanager.php(57): OC\\Security\\CSRF\\TokenStorage\\SessionStorage->setToken('O6BErTBPZ4K\/qar...')\n#3 \/var\/www\/owncloud\/lib\/public\/util.php(496): OC\\Security\\CSRF\\CsrfTokenManager->getToken()\n#4 \/var\/www\/owncloud\/lib\/private\/template.php(75): OCP\\Util::callRegister()\n#5 \/var\/www\/owncloud\/apps\/activity\/lib\/mailqueuehandler.php(250): OC_Template->__construct('activity', 'email.notificat...', '')\n#6 \/var\/www\/owncloud\/apps\/activity\/lib\/backgroundjob\/emailnotification.php(134): OCA\\Activity\\MailQueueHandler->sendEmailToUser('Maulwurf', 'markus.westerha...', 'de_DE', 'Europe\/Berlin', 1460286026)\n#7 \/var\/www\/owncloud\/apps\/activity\/lib\/backgroundjob\/emailnotification.php(94): OCA\\Activity\\BackgroundJob\\EmailNotification->runStep(500, 1460286026)\n#8 \/var\/www\/owncloud\/lib\/private\/backgroundjob\/job.php(52): OCA\\Activity\\BackgroundJob\\EmailNotification->run(NULL)\n#9 \/var\/www\/owncloud\/lib\/private\/backgroundjob\/timedjob.php(53): OC\\BackgroundJob\\Job->execute(Object(OC\\BackgroundJob\\JobList), Object(OC\\Log))\n#10 \/var\/www\/owncloud\/cron.php(141): OC\\BackgroundJob\\TimedJob->execute(Object(OC\\BackgroundJob\\JobList), Object(OC\\Log))\n#11 {main}","File":"\/var\/www\/owncloud\/lib\/private\/session\/memory.php","Line":105}
```

##### Horde IMAP log (data/horde_imap.log)
```
nothing:


S: 12 OK LOGOUT completed
>> Command 12 took 0.0215 seconds.
C: 9 LOGOUT
S: * BYE Server logging out
S: 9 OK LOGOUT completed
>> Command 9 took 0.0236 seconds.
C: 5 LOGOUT
S: * BYE Server logging out
S: 5 OK LOGOUT completed
>> Command 5 took 0.0266 seconds.

```

##### Horde SMTP log (data/horde_smtp.log)
```
nothing
```

##### Browser log
```
none, as this happens every cron job with every browser
```

**Comment by DeepDiver1975** [comment]
> Error while running background job (class: OCA\Activity\BackgroundJob\EmailNotification, arguments: ): {"Exception":"Exception","Message":"Session has been closed - no further changes to the session are allowed","Code":0,"Trace":"#0 \/var\/www\/owncloud\/lib\/private\/session\/memory.php(49): OC\\Session\\Memory->validateSession()\n#1 \/var\/www\/owncloud\/lib\/private\/security\/csrf\/tokenstorage\/sessionstorage.php(63): OC\\Session\\Memory->set('requesttoken', 'O6BErTBPZ4K\/qar...')\n#2 \/var\/www\/owncloud\/lib\/private\/security\/csrf\/csrftokenmanager.php(57): OC\\Security\\CSRF\\TokenStorage\\SessionStorage->setToken('O6BErTBPZ4K\/qar...')\n#3 \/var\/www\/owncloud\/lib\/public\/util.php(496): OC\\Security\\CSRF\\CsrfTokenManager->getToken()\n#4 \/var\/www\/owncloud\/lib\/private\/template.php(75): OCP\\Util::callRegister()\n#5 \/var\/www\/owncloud\/apps\/activity\/lib\/mailqueuehandler.php(250): OC_Template->__construct('activity', 'email.notificat...', '')\n#6 \/var\/www\/owncloud\/apps\/activity\/lib\/backgroundjob\/emailnotification.php(134): OCA\\Activity\\MailQueueHandler->sendEmailToUser('Maulwurf', 'markus.westerha...', 'de_DE', 'Europe\/Berlin', 1460286026)\n#7 \/var\/www\/owncloud\/apps\/activity\/lib\/backgroundjob\/emailnotification.php(94): OCA\\Activity\\BackgroundJob\\EmailNotification->runStep(500, 1460286026)\n#8 \/var\/www\/owncloud\/lib\/private\/backgroundjob\/job.php(52): OCA\\Activity\\BackgroundJob\\EmailNotification->run(NULL)\n#9 \/var\/www\/owncloud\/lib\/private\/backgroundjob\/timedjob.php(53): OC\\BackgroundJob\\Job->execute(Object(OC\\BackgroundJob\\JobList), Object(OC\\Log))\n#10 \/var\/www\/owncloud\/cron.php(141): OC\\BackgroundJob\\TimedJob->execute(Object(OC\\BackgroundJob\\JobList), Object(OC\\Log))\n#11 {main}","File":"\/var\/www\/owncloud\/lib\/private\/session\/memory.php","Line":105}

this error is not related to the mail app - please open in the activity app - THX
