### ISSUE TITLE
[Enhancement] Ask for Mailbox Passwords after Admin sets an new Password

### ISSUE THREAD

**Issue by aspdye** [owncloud/mail#1409]

**Comment by DeepDiver1975** [comment]
#887

**Comment by aspdye** [comment]
Nope ... After the ownCloud! Admin changed your ownCloud! password :wink:

**Comment by DeepDiver1975** [comment]
> Nope ... After the ownCloud! Admin changed your ownCloud! password :wink:

how is that related to the mail account setup?

Please add some more explanations to your issues. THX
