### ISSUE TITLE
General error: 2006 MySQL server has gone away

### ISSUE THREAD

**Issue by docdamien** [owncloud/mail#1414]
### Steps to reproduce
1. try to install Mail add-on on ownCloud 8.2.3 (latest 8.x)

### Expected behavior
Installation of mail activates

### Actual behaviour
SQLSTATE[HY000]: General error: 2006 MySQL server has gone away error is shown, files are copied (or at least directory is created) but app isn't installed

#### Server configuration
**Operating system**: 

**Web server:** apache

**Database:** mysql

**PHP version:** 5.4

**ownCloud version:** 8.2.3

**Updated from an older ownCloud or fresh install:** fresh, 30 minutes old untouched install

**List of activated apps:** calendar, contacts

**Comment by ChristophWurst** [comment]
HI @docdamien,
please fill out the *full* issue template. Where did you install the app from? Thanks

**Comment by docdamien** [comment]
Hey, 
I went to the top left menu, apps, productivity and clicked on the activate button for the mail app (same procedure for the other app, which installed fine).
After about 30 seconds, the error message appeared.

**Comment by ChristophWurst** [comment]
@docdamien please check if you can install other apps, e.g. the news app. I don't think that is an error in the mail app.

**Comment by DeepDiver1975** [comment]
What is the wait timeout on the mysql server?

**Comment by DeepDiver1975** [comment]
if too little - adopt your config please refs - https://github.com/owncloud/core/pull/23943

**Comment by docdamien** [comment]
Other apps work (news, calendar, documents etc), maybe they need less time to talk to the MySQL server?
It's shared server so I dont have access to deep configuration files to lookup that sort of stuff. I tried again earlier and got something like error 7 (cURL), I'll give it another shot later

**Comment by DeepDiver1975** [comment]
> It's shared server so I dont have access to deep configuration files to lookup that sort of stuff.

You might want to ask the hoster to get an understanding of the config value

**Comment by ChristophWurst** [comment]
we improved the app performance in the last releases, hence let's hope this issue does not occur anymore. In any case, there is little to nothing that we can do to fix this problem, sorry.
