### ISSUE TITLE
Data too long for column 'email'

### ISSUE THREAD

**Issue by otbe** [owncloud/mail#1421]
### Steps to reproduce
1. Answer on mail with a long return address.

### Expected behaviour
Email should be sent out.

### Actual behaviour
```Server Error``` appears at header.
Owncloud logs show an exception like this:

```
An exception occurred while executing 'INSERT INTO `oc_mail_collected_addresses`(`user_id`,`email`) VALUES(?,?)' with params [ 'id', 'my_mail_log_mail_address' ] right truncated: 1406 Data too long for column 'email' at row 1
```

### ownCloud Mail

**ownCloud Mail version:** (see ownCloud apps admin page)
0.4.1

#### Server configuration
**Operating system**:
docker image (9.0.1-fpm)

**Comment by ChristophWurst** [comment]
Hi @otbe,
thanks for reporting. We should increase the [column size](https://github.com/owncloud/mail/blob/775f737fadb193dd0716a9cce1ed5ebef9d15768/appinfo/database.xml#L141) to prevent those errors. Moreover, we should fail gracefully and just log an error when the address collector fails. It's not super critical if one address is not saved, but users might get the impression that their message has not been sent.

**Comment by otbe** [comment]
@ChristophWurst 
Thanks for your hint. Thought the email was not sent, but it was actually! :)

**Comment by tahaalibra** [comment]
Should it be 256 (RFC document specifies this as maximum length).

**Comment by ChristophWurst** [comment]
@tahaalibra sounds good! Wanna hava a look at this?
