### ISSUE TITLE
Mail app breaks sharing on OC 9.0.1

### ISSUE THREAD

**Issue by reuterbal** [owncloud/mail#1422]
### Steps to reproduce
1. Enable Mail app
2. Enter Files app
3. Click 'Share'-Icon next to a file or folder

### Expected behaviour
Sharing should work as expected.

### Actual behaviour
Sidebar shows 'Resharing is not allowed'

### ownCloud Mail

**ownCloud Mail version:** (see ownCloud apps admin page)
0.4.1

**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)
Private servers (Mail app itself works fine)

**Transport security - IMAP:** (None, SSL, TLS, STARTTLS) 
TLS

**Transport security - SMTP:** (None, SSL, TLS, STARTTLS)
TLS

**Number of accounts:**
2

**ownCloud Mail version build date:** (only if you are using a Nightly Build)

#### Server configuration
**Operating system**:
Ubuntu 14.04.4 LTS
```
# uname -a
Linux stuart.re-web.eu 3.13.0-77-generic #121-Ubuntu SMP Wed Jan 20 10:50:42 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Web server:**
```
# apache2 -V
[Thu Apr 14 14:17:21.566414 2016] [core:warn] [pid 22421] AH00111: Config variable ${APACHE_PID_FILE} is not defined
[Thu Apr 14 14:17:21.578995 2016] [core:warn] [pid 22421] AH00111: Config variable ${APACHE_LOCK_DIR} is not defined
[Thu Apr 14 14:17:21.579747 2016] [core:warn] [pid 22421] AH00111: Config variable ${APACHE_RUN_DIR} is not defined
Server version: Apache/2.4.7 (Ubuntu)
Server built:   Jan 14 2016 17:45:23
Server's Module Magic Number: 20120211:27
Server loaded:  APR 1.5.1-dev, APR-UTIL 1.5.3
Compiled using: APR 1.5.1-dev, APR-UTIL 1.5.3
Architecture:   64-bit
Server MPM:     prefork
  threaded:     no
    forked:     yes (variable process count)
Server compiled with....
 -D APR_HAS_SENDFILE
 -D APR_HAS_MMAP
 -D APR_HAVE_IPV6 (IPv4-mapped addresses enabled)
 -D APR_USE_SYSVSEM_SERIALIZE
 -D APR_USE_PTHREAD_SERIALIZE
 -D SINGLE_LISTEN_UNSERIALIZED_ACCEPT
 -D APR_HAS_OTHER_CHILD
 -D AP_HAVE_RELIABLE_PIPED_LOGS
 -D DYNAMIC_MODULE_LIMIT=256
 -D HTTPD_ROOT="/etc/apache2"
 -D SUEXEC_BIN="/usr/lib/apache2/suexec"
 -D DEFAULT_PIDLOG="/var/run/apache2.pid"
 -D DEFAULT_SCOREBOARD="logs/apache_runtime_status"
 -D DEFAULT_ERRORLOG="logs/error_log"
 -D AP_TYPES_CONFIG_FILE="mime.types"
 -D SERVER_CONFIG_FILE="apache2.conf"
```

**Database:**
```
# mysqld --version
mysqld  Ver 5.6.28-0ubuntu0.14.04.1 for debian-linux-gnu on x86_64 ((Ubuntu))
```

**PHP version:**
```
# php5 --version
PHP 5.5.9-1ubuntu4.14 (cli) (built: Oct 28 2015 01:34:46) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies
```

**ownCloud version:** (see ownCloud admin page)
ownCloud 9.0.1 (stable)

**Updated from an older ownCloud or fresh install:**
Updated from 8.2 to 9.0.0 to 9.0.1 (via Ubuntu PPA)

**List of activated apps:**
```
# sudo -u www-data bash -c "php occ app:list"
Enabled:
  - activity: 2.2.1
  - calendar: 1.1
  - comments: 0.2
  - contacts: 1.1.0.0
  - dav: 0.1.6
  - documents: 0.13.0
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - mail
  - news: 8.4.1
  - notifications: 0.2.3
  - passwords: 17.1
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - tasks: 0.9.0
  - templateeditor: 0.1
  - updatenotification: 0.1.0
  - user_ldap: 0.8.0
Disabled:
  - encryption
  - external
  - files_external
  - user_external
```

**The content of config/config.php:**

```
# sudo -u www-data php occ config:list system
{
    "system": {
        "instanceid": "ocuivwzzyfgt",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "oc.re-web.eu"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "https:\/\/oc.re-web.eu",
        "dbtype": "mysql",
        "version": "9.0.1.3",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "mail_smtpmode": "sendmail",
        "mail_from_address": "oc",
        "mail_domain": "re-web.eu",
        "ldapIgnoreNamingRules": false,
        "appstore.experimental.enabled": true,
        "maintenance": false,
        "updatechecker": false,
        "loglevel": 1,
        "singleuser": false,
        "theme": "",
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice"
    }
}
```

#### Client configuration
**Browser:**
Firefox 45.0.1

**Operating system:**
Ubuntu 14.04.4 LTS

##### Web server error log
```
<empty>
```

##### ownCloud log (data/owncloud.log)
```
{"reqId":"Ro8woZKZ6hq2iArR\/o37","remoteAddr":"0.0.0.0","app":"files","message":" Backends provided no user object for 0bdab00e-51b6-1035-842e-8dc6aa673cb8","level":3,"time":"2016-04-14T12:25:36+00:00","method":"GET","url":"\/ocs\/v2.php\/apps\/files_sharing\/api\/v1\/shares?format=json&path=%2FDocuments&shared_with_me=true","user":"0bdab00e-51b6-1035-842e-8dc6aa673cb8"}
{"reqId":"Ro8woZKZ6hq2iArR\/o37","remoteAddr":"0.0.0.0","app":"PHP","message":"OC\\User\\NoUserException: Backends provided no user object for 0bdab00e-51b6-1035-842e-8dc6aa673cb8 at \/var\/www\/owncloud\/lib\/private\/files\/filesystem.php#387","level":3,"time":"2016-04-14T12:25:36+00:00","method":"GET","url":"\/ocs\/v2.php\/apps\/files_sharing\/api\/v1\/shares?format=json&path=%2FDocuments&shared_with_me=true","user":"0bdab00e-51b6-1035-842e-8dc6aa673cb8"}
{"reqId":"0EteorD4cebZGsVqmscr","remoteAddr":"0.0.0.0","app":"files","message":" Backends provided no user object for 0bdab00e-51b6-1035-842e-8dc6aa673cb8","level":3,"time":"2016-04-14T12:25:36+00:00","method":"GET","url":"\/ocs\/v2.php\/apps\/files_sharing\/api\/v1\/shares?format=json&path=%2FDocuments&reshares=true","user":"0bdab00e-51b6-1035-842e-8dc6aa673cb8"}
{"reqId":"0EteorD4cebZGsVqmscr","remoteAddr":"0.0.0.0","app":"PHP","message":"OC\\User\\NoUserException: Backends provided no user object for 0bdab00e-51b6-1035-842e-8dc6aa673cb8 at \/var\/www\/owncloud\/lib\/private\/files\/filesystem.php#387","level":3,"time":"2016-04-14T12:25:36+00:00","method":"GET","url":"\/ocs\/v2.php\/apps\/files_sharing\/api\/v1\/shares?format=json&path=%2FDocuments&reshares=true","user":"0bdab00e-51b6-1035-842e-8dc6aa673cb8"}
```

##### Browser log
Browser console:
```
TypeError: data1[0].ocs is undefined
ShareItemModel<.fetch/<()
 shareitemmodel.js:615
x.Callbacks/c()
 jquery.min.js:4
x.Callbacks/p.fireWith()
 jquery.min.js:4
.when/a/<()
 jquery.min.js:4
x.Callbacks/c()
 jquery.min.js:4
x.Callbacks/p.fireWith()
 jquery.min.js:4
k()
 jquery.min.js:6
.send/r()
 jquery.min.js:6
```
Associated requests return code 200.

**Comment by ChristophWurst** [comment]
@reuterbal why/how should the mail app cause that error? I don't see the connection

**Comment by reuterbal** [comment]
Enable Mail app -> Sharing not working
Disable Mail app -> Sharing works again
That's why.

**Comment by plastikschnitzer** [comment]
I can not confirm this bug with Mail App 0.4.2. – everything works as expected with sharing files and enabled mail app. OC 9.0.1. on Gentoo Linux, Apache 2.4.10, PHP 5.6.12

**Comment by ChristophWurst** [comment]
@plastikschnitzer thanks a lot for testing. I can also not reproduce this issue :-/

**Comment by plastikschnitzer** [comment]
I tested on an upgraded install, here is my list of enabled apps:

Activity 2.2.1
Announcement Center 1.1.1
Collaborative tags 0.2
Comments 0.2
Default encryption module 1.2.0
Deleted files 0.8.0
External Sites 1.2
Federation 0.0.4
First Run Wizard 1.1
Mail Template Editor 0.1
Notifications 0.2.3
PDF Viewer 0.8
Provisioning API 0.4.1
Share Files 0.9.1
Text Editor 2.1
Update notification 0.1.0
Versions 1.2.0
Video player 0.9.8
Calendar 1.1
Contacts 1.1.0.0
Mail 0.4.2
OwnNote 1.07
Piwik Tracking 0.1.0

**Comment by ChristophWurst** [comment]
@reuterbal was the user configured via ldap?

**Comment by olerichter** [comment]
At least for me it only happens with ldap users, i will try to reproduce it from a plain installation this evening but i can't promise that have time to do it.
I am running on Debian stretch 4.4.0-1-amd64, with apache 2.4.18 with php 7.0.5.

**Comment by ChristophWurst** [comment]
Interesting. Let's continue in https://github.com/owncloud/core/issues/23816 as the reported issue also only occurs for ldap users. Thanks.

**Comment by vadila2000** [comment]
Hi, all. Sorry for English. Have the same problem after upgrade from 8.2.3 to 9.0.0 - 9.0.1 - 9.0.2
Enable Mail app -> Sharing not working
Disable Mail app -> Sharing works again.
My server configs:
1. uname -a
 3.19.0-59-generic #66~14.04.1-Ubuntu SMP Fri May 13 17:27:10 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
2. apachectl status
Server Version: Apache/2.4.7 (Ubuntu) mod_fastcgi/mod_fastcgi-SNAP-0910052141
    mod_fcgid/2.3.9 PHP/5.5.9-1ubuntu4.16 mod_python/3.3.1 Python/2.7.6 OpenSSL
3. mysqld --version
mysqld  Ver 5.5.49-MariaDB-1ubuntu0.14.04.1 for debian-linux-gnu on x86_64 ((Ubuntu))
4. php5 --version
PHP 5.5.9-1ubuntu4.16 (cli) (built: Apr 20 2016 14:31:27)
5. OwnCloud ver 9.0.2
6. sudo -u www-data bash -c "php occ app:list"
Enabled:
  - activity: 2.2.1
  - bookmarks: 0.7
  - calendar: 1.2.1
  - comments: 0.2
  - contacts: 1.2.0.0
  - dav: 0.1.6
  - direct_menu: 0.7.1
  - documents: 0.12.0
  - external: 1.2
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_external: 0.5.2
  - files_mv: 0.8.2
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - galleryplus: 15.0.0
  - music: 0.3.11
  - notifications: 0.2.3
  - ownnote: 1.08
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
  - user_external: 0.4
  - user_ldap: 0.8.0
Disabled:
  - encryption
  - gallery
  - news

7. {
    "system": {
        "instanceid": "ocva2kfacx7s",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "edge25t.skgpstroy.ru"
        ],
        "datadirectory": "\/skgpsusr\/www\/html\/owncloud\/data",
        "overwrite.cli.url": "https:\/\/edge25t.skgpstroy.ru\/owncloud",
        "dbtype": "mysql",
        "version": "9.0.2.2",
        "dbname": "oc912",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "ldapIgnoreNamingRules": false,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_from_address": "vadim",
        "mail_domain": "skgpstroy.ru",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "mail.skgpstroy.ru",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "loglevel": 1
    }
}
-------------------

I can provide virtual lab environment for test purposes of any kind and catching the bug.

**Comment by jancborchardt** [comment]
cc @blizzz @LukasReschke @MorrisJobke on it because we have the same problem and should help debugging. :)
