### ISSUE TITLE
Account color when having multiple accounts is still using old color generator

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/mail#1423]
When you have multiple accounts, both the color dot in the sidebar next to the account as well as the line left of the messages in the unified inbox list still use the old color generator.

cc @skjnldsv can you fix this as well so they use the new core color generator? :)

**Comment by skjnldsv** [comment]
Of course! :)
Should I add a core version check? Or just asume the code will go to an upgraded mail version which won't be compatible with an old core?

**Comment by jancborchardt** [comment]
Same as for Contacts I would say. It should be compatible with a slightly older version of core as well.

**Comment by skjnldsv** [comment]
Got it! :+1:
