### ISSUE TITLE
Force visually distinguishable colors in some cases

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/mail#1428]
As a follow-up to the new color generator: https://github.com/owncloud/mail/pull/1425

There should be a way/function to force request visually distinguishable colors. For example when you need 2 or 3 different colors for mail accounts, calendars, etc. the colors should not necessarily be generated completely automatic. Otherwise you might end up with very similar colors (like me now for the mail accounts, and as other people reported with the old algorithm too).

cc @skjnldsv @owncloud/designers

**Comment by skjnldsv** [comment]
Hum, this is difficult to do, you can't want a random generator and want to be able to choose a color on the same time. 
The only alternative I see there is using a stored id for the account and add a way to change an account id. :/

**Comment by jancborchardt** [comment]
@skjnldsv in the old version of the generator where we used hsl, only the hue value changed. There you could very easily assess if one color and another one was far enough apart. Since there’s 255 hue values, you could say two values need to be at least 20 (or so) apart to be distinguishable.

Is something like this possible with the new generator?

**Comment by skjnldsv** [comment]
Hum, yes it is possible, but it will increase the possibility to have two exact colors. If we space the values by 20, we end up having only 18 colors! :/

**Comment by jancborchardt** [comment]
> Hum, yes it is possible, but it will increase the possibility to have two exact colors. If we space the values by 20, we end up having only 18 colors! :/

So what we do is have an additional function. It takes the values from the generator, but makes sure they are spaced apart nicely enough?

**Comment by skjnldsv** [comment]
For the mail only?
Could be a good idea, I don't think anyone will have more than 18 accounts on the same spot.
And you keep the same base as the core generator.

**Comment by jancborchardt** [comment]
@skjnldsv yeah, only for the mail accounts. And in Calendar for the calendar colors. For the avatar placeholders, color similarity is not that bad.
