### ISSUE TITLE
Pressing cc/bcc on a reply / new message doesn’t work and deletes what was written

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/mail#1440]
Pretty hard regression. First the text is gone (gladly recovered through drafts ;) and cc/bcc doesn’t work.

@ChristophWurst @Gomez

**Comment by ChristophWurst** [comment]
Yup, pretty bad. But totally simple to fix: don't let the browser navigate [here](https://github.com/owncloud/mail/blob/master/js/templates/composer.html#L10) – the router will catch that and navigate to the default page.

**Comment by ChristophWurst** [comment]
When fixing we should also see if there are other #-links we have to adjust.
