### ISSUE TITLE
base64 decode folder IDs in the URL

### ISSUE THREAD

**Issue by ChristophWurst** [owncloud/mail#1454]
Folder IDs are usually human readable, so let's not encode them in the URL

### Expected behaviour
``http://localhost:8080/index.php/apps/mail/#accounts/3/folders/INBOX``

### Actual behaviour
``http://localhost:8080/index.php/apps/mail/#accounts/3/folders/SU5CT1g=``

@tahaalibra

**Comment by DeepDiver1975** [comment]
This will be funny ... IMAP uses utf7 whereas URLs are utf8 encoded .... There was a reason to choose base64 ... Just saying :wink:

**Comment by ChristophWurst** [comment]
I didn't think about that. Dang it. :angry:
