### ISSUE TITLE
0.4.3 breaks account setup

### ISSUE THREAD

**Issue by Scheirle** [owncloud/mail#1458]
Probably because of commit: https://github.com/owncloud/mail/commit/cba074422cf4c09126c260a59fd94c87bc353334

Removes a function (https://github.com/owncloud/mail/commit/cba074422cf4c09126c260a59fd94c87bc353334#diff-884dda3768608d1c7619643c2210677cL22) but still calls it (https://github.com/owncloud/mail/commit/cba074422cf4c09126c260a59fd94c87bc353334#diff-884dda3768608d1c7619643c2210677cL40). 

---

### Steps to reproduce
1. Have no configured accounts
2. Open the mail app

### Expected behaviour
Account setup form should be loaded

### Actual behaviour
Nothing happens. Spinning wheel.

### ownCloud Mail

**ownCloud Mail version:** (see ownCloud apps admin page)
0.4.3

**Number of accounts:**
0

#### Server configuration
**Operating system**: 
Debian jessie

**Web server:**
apache

**Database:**
mysql

**PHP version:**
5.6.19

**ownCloud version:** (see ownCloud admin page)
9.0.1

#### Client configuration
**Browser:**
firefox

##### Web server error log
```
(empty)
```

##### ownCloud log (data/owncloud.log)
```
(empty)
```

##### Browser log
```
20:59:49.223 Content Security Policy: Die Direktive 'frame-src'  sollte nicht mehr verwendet werden. Bitte verwenden Sie stattdessen die Direktive 'child-src'. <unbekannt>
20:59:50.368 Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# instead jquery.min.js:1:0
20:59:50.835 Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf self blockiert ("script-src https://owncloud.scheirle.de 'unsafe-eval'"). mail
20:59:51.264 getPreventDefault() sollte nicht mehr verwendet werden. Verwenden Sie stattdessen defaultPrevented. jquery.min.js:5:17117
20:59:51.464 ReferenceError: addAccount is not defined
 mail.min.js:145:31125

```

**Comment by kajla** [comment]
I have got same problem :(

Mail version 0.4.3

Screenshot:
[img]http://i.imgur.com/UsnRgeX.jpg[/img]

From log:
Exception: {"Exception":"Horde_Imap_Client_Exception","Message":"Mail server denied authentication.","Code":102,"Trace":"#0 \/var\/www\/owncloud\/apps\/mail\/vendor\/pear-pear.horde.org\/Horde_Imap_Client\/Horde\/Imap\/Client\/Base.php(831): Horde_Imap_Client_Socket->_login(*** username and password replaced ***)\n#1 \/var\/www\/owncloud\/apps\/mail\/lib\/account.php(143): Horde_Imap_Client_Base->login(*** username and password replaced ***)\n#2 \/var\/www\/owncloud\/apps\/mail\/lib\/account.php(276): OCA\\Mail\\Account->getImapConnection()\n#3 \/var\/www\/owncloud\/apps\/mail\/lib\/account.php(322): OCA\\Mail\\Account->listMailboxes()\n#4 \/var\/www\/owncloud\/apps\/mail\/lib\/account.php(336): OCA\\Mail\\Account->getMailboxes()\n#5 \/var\/www\/owncloud\/apps\/mail\/lib\/controller\/folderscontroller.php(61): OCA\\Mail\\Account->getListArray()\n#6 [internal function]: OCA\\Mail\\Controller\\FoldersController->index(2)\n#7 \/var\/www\/owncloud\/lib\/private\/appframework\/http\/dispatcher.php(159): call_user_func_array(Array, Array)\n#8 \/var\/www\/owncloud\/lib\/private\/appframework\/http\/dispatcher.php(89): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OCA\\Mail\\Controller\\FoldersController), 'index')\n#9 \/var\/www\/owncloud\/lib\/private\/appframework\/app.php(110): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\Mail\\Controller\\FoldersController), 'index')\n#10 \/var\/www\/owncloud\/lib\/private\/appframework\/routing\/routeactionhandler.php(45): OC\\AppFramework\\App::main('FoldersControll...', 'index', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#11 [internal function]: OC\\AppFramework\\routing\\RouteActionHandler->__invoke(Array)\n#12 \/var\/www\/owncloud\/lib\/private\/route\/router.php(276): call_user_func(Object(OC\\AppFramework\\routing\\RouteActionHandler), Array)\n#13 \/var\/www\/owncloud\/lib\/base.php(882): OC\\Route\\Router->match('\/apps\/mail\/acco...')\n#14 \/var\/www\/owncloud\/index.php(39): OC::handleRequest()\n#15 {main}","File":"\/var\/www\/owncloud\/apps\/mail\/vendor\/pear-pear.horde.org\/Horde_Imap_Client\/Horde\/Imap\/Client\/Socket.php","Line":572}
