### ISSUE TITLE
[Question] How to auto setup for new user?

### ISSUE THREAD

**Issue by Mannshoch** [owncloud/mail#1469]
### Steps to reproduce / Actual behaviour
1. create a new user
2. login as new user
3. no e-Mail is setup

### Expected behaviour
new user get automatic their Mail addres set-up.
( I work with https://github.com/owncloud/apps/tree/master/user_external )

### ownCloud Mail

**ownCloud Mail version:** 0.4.2

**Mailserver or service:** roundcube

**Transport security - IMAP:** SSL, TLS

**Transport security - SMTP:** SSL, TLS

#### Server configuration
**Operating system**: unknown

**Web server:** Appache

**Database:** MySQL

**PHP version:** 5.6

**ownCloud version:** 9

**Updated from an older ownCloud or fresh install:** fresh

**List of activated apps:** user_external

**The content of config/config.php:**

```
  'default_language' => 'de',
  'user_backends' => array (
    0 => array (
            "class"     => "OC_User_IMAP",
            "arguments" => array (
                              0 => '{[NAME].[HOSTER]:993/imap/ssl}'
                              ),
    ),
),

**Comment by ChristophWurst** [comment]
Hi @Mannshoch,
the app you're using is a **user backen**, this has nothing to do with the mail app which is an IMAP client. However, there is an open issue regarding the configuration of an default mail server, see https://github.com/owncloud/mail/issues/166. Is that what you where looking for?

**Comment by Mannshoch** [comment]
Yes. It seems that this ticket is what I'm looking for. Thanks a lot.
