### ISSUE TITLE
Automatically login if ownCloud username is an email address

### ISSUE THREAD

**Issue by Zepmann** [owncloud/mail#1487]
### Steps to reproduce
1. Enable Mail app as admin.
2. Log out as admin.
3. (at the login form) Enter an email address as the ownCloud username.
4. Enter the correct password to login to ownCloud.
5. Access the Mail app.

### Expected behaviour
Mail app should attempt to use the ownCloud username from step 3 to login automatically. The email address is retrieved from step 3. The password associated with the email address (used by the IMAP and SMTP server) is retrieved from step 4. The Mail app should *not* store the password in the database for this default account if it logs in successfully. Instead, the password should be stored in memory for as long as the user's ownCloud session is logged in.

This will allow a seamless integration in ownCloud installations that use the [External user support app](https://doc.owncloud.org/server/9.0/admin_manual/configuration_user/user_auth_ftp_smb_imap.html) to authenticate users against an IMAP server that requires the full email address when authenticating. An advantage is that an up-to-date password is always available, assuming the user's password does not change once logged into ownCloud. Another advantage is that IMAP/SMTP passwords do not need to be stored persistently. Finally, from a usability perspective it is just convenient: the user never needs to enter his password twice, and does not need to re-enter the password (for the email address used as an ownCloud username) in the Mail app if it ever changes.

The Mail app could check whether the External user authentication app is enabled in addition to the use of an email address to login to ownCloud, before it will attempt to automatically login the user. Alternatively, the admin could enable auto-login (possibly with manually specified IMAP and SMTP settings) through `config.php` configuration option(s) or through the Admin configuration page.

### Actual behaviour
Mail app asks for the user's password.

### ownCloud Mail

**ownCloud Mail version:** 0.4.4

**Mailserver or service:** Self-hosted (and *only* if IMAP is used to login to ownCloud)

**Transport security - IMAP:** whatever the admin configures or is auto-detected.

**Transport security - SMTP:** whatever the admin configures or is auto-detected.

**Number of accounts:** 1 to infinite

**ownCloud Mail version build date:** N/A

### ownCloud Core
Not relevant for feature request, so snipped.

### Other thoughts
- This function was supported by the now defunct Roundcube app.

**Comment by aspdye** [comment]
dup #23

**Comment by aspdye** [comment]
dup :grin:

**Comment by Zepmann** [comment]
Confirmed. I could not find it initially. It is an older issue than I expected.

**Comment by ChristophWurst** [comment]
@Zepmann thanks a lot for putting so much effort into writing this feature request though! :-)
