### ISSUE TITLE
Mail App 1.2.0.0. cannot be installed in OC 9.0.2

### ISSUE THREAD

**Issue by hitam4450** [owncloud/mail#1491]
### Steps to reproduce
1. Enable mail app
2.
3.

### Expected behaviour
Tell us what should happen
It should be enabled
### Actual behaviour
Tell us what happens instead
It reports an erreor (See enclosed screenshot)
### ownCloud Mail
1.2.0.0
**ownCloud Mail version:** (see ownCloud apps admin page)
9.0.2
![oc9 0 2_mail_120](https://cloud.githubusercontent.com/assets/9738727/15183494/8db9e876-1791-11e6-9deb-d9702f938845.png)

**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)

**Transport security - IMAP:** (None, SSL, TLS, STARTTLS) 

**Transport security - SMTP:** (None, SSL, TLS, STARTTLS)

**Number of accounts:**

**ownCloud Mail version build date:** (only if you are using a Nightly Build)

#### Server configuration
**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**ownCloud version:** (see ownCloud admin page)

**Updated from an older ownCloud or fresh install:**

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

#### Client configuration
**Browser:**

**Operating system:**

##### Web server error log
```
Insert your webserver log here
```

##### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

##### Horde IMAP log (data/horde_imap.log)
```
Insert your horde IMAP log here, see https://github.com/owncloud/mail#debug-mode
```

##### Horde SMTP log (data/horde_smtp.log)
```
Insert your horde SMTP log here, see https://github.com/owncloud/mail#debug-mode
```

##### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by ChristophWurst** [comment]
Hi @hitam4450,
that was a fake/spam entry on the app store. I reported it and it's removed now.
Thanks

**Comment by hitam4450** [comment]
Ok, Thanks! :thumbsup:
