### ISSUE TITLE
Send new mail

### ISSUE THREAD

**Issue by benedikt-d** [owncloud/mail#1493]
### Steps to reproduce
1. Open Owncloud
2. Open Owncloud Mail
3. Try to Initiate new mail conversation.

### Expected behaviour

New Email Button within <div id="mail-new-message-fixed"></div>

### Actual behaviour
I'm looking for a button to create a new mail.I can only respond to conversations or complete a draft that I have found somewhere else. Is this a bug or a feature that has not been implemented yet?

![2016-05-13 16_06_18](https://cloud.githubusercontent.com/assets/3420538/15250498/5dac92c4-1925-11e6-9eef-741cbbaa58fd.png)

### ownCloud Mail

**ownCloud Mail version:** mail: 0.5.1

**Mailserver or service:** SMTP 

**Transport security - IMAP:** TLS

**Transport security - SMTP:** TLS

**Number of accounts:** 1

#### Server configuration
**Operating system**: Arch Linux

**Web server:** Apache

**Database:** MySQL

**PHP version:** PHP version 7.0.6

**ownCloud version:** ownCloud 9.0.2 (production)

**Updated from an older ownCloud or fresh install:** Updated Version

**List of activated apps:** 

```
Enabled:
  - activity: 2.2.1
  - calendar: 1.2.2
  - comments: 0.2
  - contacts: 1.2.0.0
  - dav: 0.1.6
  - encryption: 1.2.0
  - external: 1.2
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_external: 0.5.2
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - mail: 0.5.1
  - notifications: 0.2.3
  - passwordpolicy: 1.1
  - passwords: 18.0
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
  - user_external: 0.4
Disabled:
  - user_ldap
```

**The content of config/config.php:**

```
{
"system": {
"instanceid": "oc7bgl0k807o",
"passwordsalt": "REMOVED SENSITIVE VALUE",
"secret": "REMOVED SENSITIVE VALUE",
"trusted_domains": [
"REMOVED SENSITIVE VALUE",
"localhost",
"REMOVED SENSITIVE VALUE",
"REMOVED SENSITIVE VALUE",
"REMOVED SENSITIVE VALUE",
"REMOVED SENSITIVE VALUE"
],
"datadirectory": "\/flux\/data\/owncloud\/data",
"version": "9.0.2.2",
"dbtype": "mysql",
"dbhost": "localhost",
"dbname": "owncloud",
"dbuser": "REMOVED SENSITIVE VALUE",
"dbpassword": "REMOVED SENSITIVE VALUE",
"installed": true,
"default_language": "en",
"defaultapp": "files",
"mail_domain": "REMOVED SENSITIVE VALUE",
"mail_from_address": "office",
"mail_smtpdebug": false,
"mail_smtpmode": "smtp",
"memcache.local": "\OC\Memcache\APCu",
"trashbin_retention_obligation": "false",
"versions_retention_obligation": "disabled",
"appcodechecker": true,
"updatechecker": false,
"has_internet_connection": true,
"check_for_working_webdav": false,
"config_is_read_only": false,
"log_type": "owncloud",
"logfile": "\/var\/log\/owncloud\/owncloud.log",
"loglevel": 0,
"syslog_tag": "owncloud",
"session_lifetime": 86400,
"session_keepalive": true,
"logdateformat": "F d, Y H:i:s",
"logtimezone": "UTC",
"customclient_desktop": "http:\/\/owncloud.org\/sync-clients\/",
"customclient_android": "https:\/\/play.google.com\/store\/apps\/details?id=com.owncloud.android",
"customclient_ios": "https:\/\/itunes.apple.com\/us\/app\/owncloud\/id543672169?mt=8",
"appstoreenabled": false,
"appstoreurl": "https:\/\/api.owncloud.com\/v1",
"apps_paths": [
{
"path": "\/usr\/share\/webapps\/owncloud\/apps",
"url": "\/apps",
"writable": false
}
],
"enable_previews": true,
"preview_max_x": 2048,
"preview_max_y": 2048,
"preview_max_scale_factor": 20,
"preview_max_filesize_image": 300,
"preview_libreoffice_path": "\/bin\/libreoffice",
"preview_office_cl_parameters": " --headless --nologo --nofirststartwizard --invisible --norestore -convert-to pdf -outdir ",
"enabledPreviewProviders": [
"OC\Preview\PNG",
"OC\Preview\JPEG",
"OC\Preview\GIF",
"OC\Preview\BMP",
"OC\Preview\XBitmap",
"OC\Preview\MP3",
"OC\Preview\TXT",
"OC\Preview\MarkDown"
],
"maintenance": false,
"singleuser": false,
"supportedDatabases": [
"mysql"
],
"blacklisted_files": [
".htaccess"
],
"cipher": "AES-256-CFB",
"minimum.supported.desktop.version": "1.7.0",
"filesystem_check_changes": 0,
"overwrite.cli.url": "REMOVED SENSITIVE VALUE",
"dbtableprefix": "oc_",
"theme": "",
"appstore.experimental.enabled": true,
"mail_smtphost": "REMOVED SENSITIVE VALUE",
"mail_smtpport": "REMOVED SENSITIVE VALUE",
"mail_smtpsecure": "REMOVED SENSITIVE VALUE",
"mail_smtpauthtype": "LOGIN",
"mail_smtpauth": 1,
"mail_smtpname": "REMOVED SENSITIVE VALUE",
"mail_smtppassword": "REMOVED SENSITIVE VALUE"
}
}
```

#### Client configuration
**Browser:** Tested: Chrome + Firefox

**Operating system:** Archlinux

##### Web server error log
```
nothing found
```

##### ownCloud log (data/owncloud.log)
```
nothing relevant found
```

##### Horde IMAP log (data/horde_imap.log)
```
nothing found
```

##### Horde SMTP log (data/horde_smtp.log)
```
nothing found
```

##### Browser log
```
Browser Log Chrome:

mail.min.js?v=76d3e6c…:119 Uncaught TypeError: Cannot read property 'previousAttributes' of undefined

html:1 Refused to load the image 'cid:image001.jpg@01D15437.F41B9D80' because it violates the following Content Security Policy directive: "img-src 'self' data: blob:".

xxx.xxx.de/:1 Refused to load the image 'cid:image001.jpg@01D15437.F41B9D80' because it violates the following Content Security Policy directive: "img-src 'self' data: blob:".
```

**Comment by ChristophWurst** [comment]
Hi @benedikt-d,
please don't ignore the issue template when filing bugs. Please provide the information that is asked in there so we get information about your setup. If possible, please also provide a screenshot of the interface. Thanks

**Comment by benedikt-d** [comment]
ownCloud 9.0.2 (production)
Mail 0.4.4
PHP version 7.0.6

**Comment by ChristophWurst** [comment]
@benedikt-d thanks for providing more information. There is still a lot of important information missing, e.g. number of accounts, browser, logs. So please fill out the issue template.

**Comment by benedikt-d** [comment]
Browser Log Chrome:

mail.min.js?v=76d3e6c…:119 Uncaught TypeError: Cannot read property 'previousAttributes' of undefined

html:1 Refused to load the image 'cid:image001.jpg@01D15437.F41B9D80' because it violates the following Content Security Policy directive: "img-src 'self' data: blob:".

xxx.xxx.de/:1 Refused to load the image 'cid:image001.jpg@01D15437.F41B9D80' because it violates the following Content Security Policy directive: "img-src 'self' data: blob:".

**Comment by benedikt-d** [comment]
{
    "system": {
        "instanceid": "oc7bgl0k807o",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "localhost",
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "\/flux\/data\/owncloud\/data",
        "version": "9.0.2.2",
        "dbtype": "mysql",
        "dbhost": "localhost",
        "dbname": "owncloud",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "default_language": "en",
        "defaultapp": "files",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "office",
        "mail_smtpdebug": false,
        "mail_smtpmode": "smtp",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "trashbin_retention_obligation": "false",
        "versions_retention_obligation": "disabled",
        "appcodechecker": true,
        "updatechecker": false,
        "has_internet_connection": true,
        "check_for_working_webdav": false,
        "config_is_read_only": false,
        "log_type": "owncloud",
        "logfile": "\/var\/log\/owncloud\/owncloud.log",
        "loglevel": 0,
        "syslog_tag": "owncloud",
        "session_lifetime": 86400,
        "session_keepalive": true,
        "logdateformat": "F d, Y H:i:s",
        "logtimezone": "UTC",
        "customclient_desktop": "http:\/\/owncloud.org\/sync-clients\/",
        "customclient_android": "https:\/\/play.google.com\/store\/apps\/details?id=com.owncloud.android",
        "customclient_ios": "https:\/\/itunes.apple.com\/us\/app\/owncloud\/id543672169?mt=8",
        "appstoreenabled": false,
        "appstoreurl": "https:\/\/api.owncloud.com\/v1",
        "apps_paths": [
            {
                "path": "\/usr\/share\/webapps\/owncloud\/apps",
                "url": "\/apps",
                "writable": false
            }
        ],
        "enable_previews": true,
        "preview_max_x": 2048,
        "preview_max_y": 2048,
        "preview_max_scale_factor": 20,
        "preview_max_filesize_image": 300,
        "preview_libreoffice_path": "\/bin\/libreoffice",
        "preview_office_cl_parameters": " --headless --nologo --nofirststartwizard --invisible --norestore -convert-to pdf -outdir ",
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown"
        ],
        "maintenance": false,
        "singleuser": false,
        "supportedDatabases": [
            "mysql"
        ],
        "blacklisted_files": [
            ".htaccess"
        ],
        "cipher": "AES-256-CFB",
        "minimum.supported.desktop.version": "1.7.0",
        "filesystem_check_changes": 0,
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "theme": "",
        "appstore.experimental.enabled": true,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
    }
}

**Comment by ChristophWurst** [comment]
Still, we need *all* the information in the issue template.

**Comment by benedikt-d** [comment]
I updated and inserted all the content in the template.

**Comment by benedikt-d** [comment]
What other infor is missing?

**Comment by ChristophWurst** [comment]
> mail.min.js?v=76d3e6c…:119 Uncaught TypeError: Cannot read property 'previousAttributes' of undefined

Could you please enable [debug mode](https://doc.owncloud.org/server/9.0/developer_manual/general/devenv.html#enabling-debug-mode) and try to reproduce the error? Some kind of js stack trace when the error occurs would be great. As I could not find any application code using this property, this could also be an issue in a 3rd party lib. I'd need to know which code triggers the error to debug this. Thanks

**Comment by benedikt-d** [comment]
I managed to fix the error by reinstalling my owncloud instance sorry for bothering.
