### ISSUE TITLE
Change settings on existing mail account

### ISSUE THREAD

**Issue by benedikt-d** [owncloud/mail#1494]
I can set up a new Mail account but can not change the settings on existing mail accounts.

**Comment by ChristophWurst** [comment]
Again, please use the issue template AND [use the github search](https://github.com/owncloud/mail/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+account+change++settings) to find existing issues. This is a dupicate of #942

**Comment by benedikt-d** [comment]
Sorry didn't find anything... I will use the template in future.

**Comment by ChristophWurst** [comment]
> didn't find anything

That can happen, don't worry :)
