### ISSUE TITLE
Autoconfig server info

### ISSUE THREAD

**Issue by bispawel** [owncloud/mail#1495]
Before first connect mail account - Is it possible to fill somewhere in config files, info about server (imap, smtp) ? It should auto fill the fields about upcoming and outgoing servers...
I try change config in /apps/mail/js/templates/setup.html as (value="") but it dosen't work.
Is it any possible to do that?

**Comment by ChristophWurst** [comment]
Hi @bispawel,
I guess you're talking about a configuration option for defining a default imap/smtp server, see https://github.com/owncloud/mail/issues/166 for more info.
You should never change files of any app as that will likely introduce bugs that are unexpected and impossible to reproduce. Moreover code integrity checks will fail and you'll get an error. So please don't touch those files, ever.
