### ISSUE TITLE
Gracefully handle unified inbox fail when one account is not working.

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/mail#1497]
Currently when one account doesn't work (removed, connection error, etc), the whole unified inbox shows a weird connection error.

We should gracefully fall back to simply show the unified inbox without the erroneous account.

**Comment by ChristophWurst** [comment]
@jancborchardt did you use the github search before filing that issue? :see_no_evil: https://github.com/owncloud/mail/issues/1475

**Comment by ChristophWurst** [comment]
I like the similarity of those two titles :D

**Comment by jancborchardt** [comment]
Haha no I didn't – my bad, I'm only on mobile and GH search is a pain here. ;)
