### ISSUE TITLE
Not loading messages in IMAP folder

### ISSUE THREAD

**Issue by moraus** [owncloud/mail#1499]
### Steps to reproduce
1. Add IMAP account with SSL on 993
2. Open INBOX - messages are loading OK
3. Select any other folder form the menu at the left
4. The mails in this folder are not shown/loaded in the mid section. (Only the previous contents)

### Expected behaviour
The contents of the folder should appear in the mid section

### Actual behaviour
The mails in the IMAP folder should appear

### ownCloud Mail

**ownCloud Mail version:** 0.4.4

**Mailserver or service:** Exim4 / Courier

**Transport security - IMAP:** SSL

**Transport security - SMTP:** STARTTLS

**Number of accounts:** 1

**ownCloud Mail version build date:** OC 9.0.2

#### Server configuration
**Operating system**: Ubuntu 16.04

**Web server:** Apache

**Database:** Mysql

**PHP version:** 5.7

**ownCloud version:** 9.0.2

**Updated from an older ownCloud or fresh install:** Update

**List of activated apps:**
Enabled:
  - activity: 2.2.1
  - bookmarks: true
  - calendar: 1.2.2
  - comments: 0.2
  - contacts: true
  - dav: 0.1.6
  - external: 1.2
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_external: 0.5.2
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - mail: true
  - notifications: 0.2.3
  - passman: 1.3.38
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - tasks: true
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - encryption
  - user_external
  - user_ldap

**The content of config/config.php:**
{
    "system": {
        "memcache.local": "\\OC\\Memcache\\APCu",
        "asset-pipeline.enabled": false,
        "overwritewebroot": "\/owncloud",
        "overwrite.cli.url": "\/owncloud",
        "version": "9.0.2.2",
        "installed": true,
        "forcessl": true,
        "log_type": "owncloud",
        "logfile": "\/var\/log\/owncloud\/owncloud.log",
        "loglevel": "0",
        "log_authfailip": "true",
        "log_rotate_size": "1048576",
        "instanceid": "524c75e9927b2",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "\/store\/owncloud\/data",
        "dbtype": "mysql",
        "dbname": "owncloud",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "127.0.0.1",
        "dbtableprefix": "oc_",
        "maxZipInputSize": 838860800,
        "allowZipDownload": true,
        "theme": "",
        "maintenance": false,
        "mail_smtpdebug": true,
        "mail_smtpmode": "smtp",
        "mail_smtphost": "moraeus.org",
        "mail_smtpport": "587",
        "mail_smtptimeout": 30,
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpsecure": "tls",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "owncloud",
        "mail_domain": "moraeus.org",
        "app.mail.imaplog.enabled": true,
        "app.mail.smtplog.enabled": true,
        "app.mail.server-side-cache.enabled": false,
        "remember_login_cookie_lifetime": 1296000,
        "session_lifetime": 86400,
        "session_keepalive": true,
        "apps_paths": [
            {
                "path": "\/var\/www\/owncloud\/apps",
                "url": "\/apps",
                "writable": true
            }
        ],
        "appstoreenabled": true,
        "appstoreurl": "https:\/\/api.owncloud.com\/v1",
        "appstore.experimental.enabled": true,
        "appcodechecker": false,
        "updatechecker": false,
        "trusted_domains": [
            "moraeus.org",
            "10.0.0.2"
        ],
        "check_for_working_webdav": true,
        "check_for_working_htaccess": true,
        "has_internet_connection": true,
        "secret": "***REMOVED SENSITIVE VALUE***",
        "forceSSLforSubdomains": true,
        "trashbin_retention_obligation": "auto",
        "debug": true
    }
}

#### Client configuration
**Browser:** Firefox

**Operating system:** Ubuntu 16.04

##### Web server error log
```
Insert your webserver log here
```

##### ownCloud log (data/owncloud.log)
{"reqId":"Zm1J7beWzGkj8wPoD6FE","remoteAddr":"84.16.211.225","app":"mail","message":"loading messages 0 to 20 of folder <SU5CT1g=>","level":0,"time":"2016-05-23T08:15:52+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/mail\/accounts\/3\/folders\/SU5CT1g%3D\/messages?from=0&to=20&filter=","user":"moraus"}
{"reqId":"Y14O1JL69TiMINh2duUl","remoteAddr":"84.16.211.225","app":"mail","message":"loading messages 0 to 20 of folder <SU5CT1g=>","level":0,"time":"2016-05-23T08:15:55+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/mail\/accounts\/3\/folders\/SU5CT1g%3D\/messages?from=0&to=20&filter=","user":"moraus"}
{"reqId":"jXApmE6miFy5B3s0Rbr+","remoteAddr":"84.16.211.225","app":"mail","message":"loading messages 0 to 20 of folder <SU5CT1g=>","level":0,"time":"2016-05-23T08:16:50+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/mail\/accounts\/3\/folders\/SU5CT1g%3D\/messages?from=0&to=20&filter=","user":"moraus"}

##### Horde IMAP log (data/horde_imap.log)
>> Mon, 23 May 2016 08:45:31 +0000
>> Connection to: imap://moraeus.org:993/
>> Server connection took 0.0905 seconds.
S: * OK [CAPABILITY IMAP4rev1 UIDPLUS CHILDREN NAMESPACE THREAD=ORDEREDSUBJECT THREAD=REFERENCES SORT QUOTA IDLE AUTH=PLAIN ACL ACL2=UNION] Courier-IMAP ready. Copyright 1998-2011 Double Precision, Inc.  See COPYING for distribution information.
C: 1 [INITIAL CLIENT RESPONSE (username: moraus)]
S: +
C: bW9yYXVzAG1vcmF1cwBEcjEwTGh2dA==
S: 1 OK LOGIN Ok.
>> Command 1 took 0.0806 seconds.
C: 2 CAPABILITY
S: * CAPABILITY IMAP4rev1 UIDPLUS CHILDREN NAMESPACE THREAD=ORDEREDSUBJECT THREAD=REFERENCES SORT QUOTA IDLE AUTH=PLAIN ACL ACL2=UNION
S: 2 OK CAPABILITY completed
>> Command 2 took 0.0011 seconds.
C: 3 LIST "" *
S: * LIST (\HasNoChildren) "." "INBOX.Husaberg"
S: * LIST (\HasNoChildren) "." "INBOX.MunkholmenGarveri"
S: * LIST (\HasNoChildren) "." "INBOX.EBS-velforening"
S: * LIST (\HasNoChildren) "." "INBOX.Kvitteringer"
S: * LIST (\HasNoChildren) "." "INBOX.Sent"
S: * LIST (\HasNoChildren) "." "INBOX.Gain"
S: * LIST (\HasNoChildren) "." "INBOX.Audi"
S: * LIST (\HasNoChildren) "." "INBOX.Drafts"
S: * LIST (\HasNoChildren) "." "INBOX.Privat"
S: * LIST (\HasNoChildren) "." "INBOX.SEC"
S: * LIST (\HasNoChildren) "." "INBOX.Inhrvn8"
S: * LIST (\HasNoChildren) "." "INBOX.Archive"
S: * LIST (\HasNoChildren) "." "INBOX.Deleted Messages"
S: * LIST (\HasNoChildren) "." "INBOX.Junk"
S: * LIST (\HasNoChildren) "." "INBOX.Notes"
S: * LIST (\Unmarked \HasChildren) "." "INBOX"
S: 3 OK LIST completed
>> Command 3 took 0.0037 seconds.
C: 4 STATUS INBOX (MESSAGES RECENT UIDNEXT UIDVALIDITY UNSEEN)
C: 5 STATUS INBOX.Drafts (MESSAGES RECENT UIDNEXT UIDVALIDITY UNSEEN)
C: 6 STATUS INBOX.Sent (MESSAGES RECENT UIDNEXT UIDVALIDITY UNSEEN)
C: 7 STATUS INBOX.Archive (MESSAGES RECENT UIDNEXT UIDVALIDITY UNSEEN)
C: 8 STATUS INBOX.Junk (MESSAGES RECENT UIDNEXT UIDVALIDITY UNSEEN)
C: 9 STATUS "INBOX.Deleted Messages" (MESSAGES RECENT UIDNEXT UIDVALIDITY UNSEEN)
C: 10 STATUS INBOX.Audi (MESSAGES RECENT UIDNEXT UIDVALIDITY UNSEEN)
C: 11 STATUS INBOX.EBS-velforening (MESSAGES RECENT UIDNEXT UIDVALIDITY UNSEEN)
C: 12 STATUS INBOX.Gain (MESSAGES RECENT UIDNEXT UIDVALIDITY UNSEEN)
C: 13 STATUS INBOX.Husaberg (MESSAGES RECENT UIDNEXT UIDVALIDITY UNSEEN)
C: 14 STATUS INBOX.Inhrvn8 (MESSAGES RECENT UIDNEXT UIDVALIDITY UNSEEN)
C: 15 STATUS INBOX.Kvitteringer (MESSAGES RECENT UIDNEXT UIDVALIDITY UNSEEN)
C: 16 STATUS INBOX.MunkholmenGarveri (MESSAGES RECENT UIDNEXT UIDVALIDITY UNSEEN)
C: 17 STATUS INBOX.Notes (MESSAGES RECENT UIDNEXT UIDVALIDITY UNSEEN)
C: 18 STATUS INBOX.Privat (MESSAGES RECENT UIDNEXT UIDVALIDITY UNSEEN)
C: 19 STATUS INBOX.SEC (MESSAGES RECENT UIDNEXT UIDVALIDITY UNSEEN)
S: * STATUS "INBOX" (MESSAGES 8 RECENT 0 UIDNEXT 18420 UIDVALIDITY 1173770886 UNSEEN 0)
S: 4 OK STATUS Completed.
>> Command 4 took 0.0035 seconds.
S: * STATUS "INBOX.Drafts" (MESSAGES 0 RECENT 0 UIDNEXT 2394 UIDVALIDITY 1173770888 UNSEEN 0)
S: 5 OK STATUS Completed.
>> Command 5 took 0.004 seconds.
S: * STATUS "INBOX.Sent" (MESSAGES 1920 RECENT 0 UIDNEXT 1950 UIDVALIDITY 1173770914 UNSEEN 0)
S: 6 OK STATUS Completed.
>> Command 6 took 0.0406 seconds.
S: * STATUS "INBOX.Archive" (MESSAGES 84 RECENT 0 UIDNEXT 85 UIDVALIDITY 1299096532 UNSEEN 0)
S: 7 OK STATUS Completed.
>> Command 7 took 0.041 seconds.
S: * STATUS "INBOX.Junk" (MESSAGES 782 RECENT 0 UIDNEXT 3384 UIDVALIDITY 1173770892 UNSEEN 0)
S: 8 OK STATUS Completed.
>> Command 8 took 0.0413 seconds.
S: * STATUS "INBOX.Deleted Messages" (MESSAGES 65 RECENT 0 UIDNEXT 9287 UIDVALIDITY 1244711543 UNSEEN 0)
S: 9 OK STATUS Completed.
>> Command 9 took 0.0416 seconds.
S: * STATUS "INBOX.Audi" (MESSAGES 183 RECENT 0 UIDNEXT 191 UIDVALIDITY 1210078756 UNSEEN 0)
S: 10 OK STATUS Completed.
>> Command 10 took 0.0418 seconds.
S: * STATUS "INBOX.EBS-velforening" (MESSAGES 26 RECENT 0 UIDNEXT 27 UIDVALIDITY 398957180 UNSEEN 0)
S: 11 OK STATUS Completed.
>> Command 11 took 0.0422 seconds.
S: * STATUS "INBOX.Gain" (MESSAGES 51 RECENT 0 UIDNEXT 52 UIDVALIDITY 1173739904 UNSEEN 0)
S: 12 OK STATUS Completed.
>> Command 12 took 0.0425 seconds.
S: * STATUS "INBOX.Husaberg" (MESSAGES 87 RECENT 0 UIDNEXT 89 UIDVALIDITY 406723835 UNSEEN 0)
S: 13 OK STATUS Completed.
>> Command 13 took 0.0428 seconds.
S: * STATUS "INBOX.Inhrvn8" (MESSAGES 213 RECENT 0 UIDNEXT 214 UIDVALIDITY 1188886710 UNSEEN 0)
S: 14 OK STATUS Completed.
>> Command 14 took 0.0432 seconds.
S: * STATUS "INBOX.Kvitteringer" (MESSAGES 102 RECENT 0 UIDNEXT 127 UIDVALIDITY 379312020 UNSEEN 0)
S: 15 OK STATUS Completed.
>> Command 15 took 0.0435 seconds.
S: * STATUS "INBOX.MunkholmenGarveri" (MESSAGES 9 RECENT 0 UIDNEXT 10 UIDVALIDITY 401442740 UNSEEN 0)
S: 16 OK STATUS Completed.
>> Command 16 took 0.0439 seconds.
S: * STATUS "INBOX.Notes" (MESSAGES 28 RECENT 0 UIDNEXT 216 UIDVALIDITY 1287950382 UNSEEN 0)
S: 17 OK STATUS Completed.
>> Command 17 took 0.0442 seconds.
S: * STATUS "INBOX.Privat" (MESSAGES 231 RECENT 0 UIDNEXT 296 UIDVALIDITY 1173770893 UNSEEN 0)
S: 18 OK STATUS Completed.
>> Command 18 took 0.0445 seconds.
S: * STATUS "INBOX.SEC" (MESSAGES 103 RECENT 0 UIDNEXT 150 UIDVALIDITY 1173770900 UNSEEN 0)
S: 19 OK STATUS Completed.
>> Command 19 took 0.0449 seconds.
C: 20 STATUS INBOX (MESSAGES RECENT UIDNEXT UIDVALIDITY UNSEEN)
S: * STATUS "INBOX" (MESSAGES 8 RECENT 0 UIDNEXT 18420 UIDVALIDITY 1173770886 UNSEEN 0)
S: 20 OK STATUS Completed.
>> Command 20 took 0.0016 seconds.
C: 21 LOGOUT
S: * BYE Courier-IMAP server shutting down
S: 21 OK LOGOUT completed
>> Command 21 took 0.0019 seconds.
------------------------------

NB! The rest of horde_imap.log is left out due to private information. This can be sent on request.

##### Horde SMTP log (data/horde_smtp.log)
```
Insert your horde SMTP log here, see https://github.com/owncloud/mail#debug-mode
```

##### Browser log
[ui] "composer:leave" Array [  ] backbone.radio.js:161:7
[ui] "messagesview:filter:clear" Array [  ] backbone.radio.js:161:7
[folder] "setactive" Array [ Object, Object ] backbone.radio.js:161:7
[ui] "content:loading" Array [  ] backbone.radio.js:161:7
[ui] "messagesview:messages:reset" Array [  ] backbone.radio.js:161:7
[message] "entities" Array [ Object, Object, Object ] backbone.radio.js:161:7
[ui] "messagecontent:show" Array [  ] backbone.radio.js:161:7
[ui] "messagesview:message:setactive" Array [ null ] backbone.radio.js:161:7
Deprecation warning: tipsy is deprecated. Use tooltip instead. js.js:2216:2
[ui] "messagesview:messages:add" Array [ Array[8] ] backbone.radio.js:161:7
[ui] "composer:leave" Array [  ] backbone.radio.js:161:7
[ui] "message:loading" Array [  ] backbone.radio.js:161:7
Deprecation warning: tipsy is deprecated. Use tooltip instead. js.js:2216:2
[ui] "messagesview:message:setactive" Array [ 18419 ] backbone.radio.js:161:7
[message] "entity" Array [ Object, Object, 18419 ] backbone.radio.js:161:7
[ui] "composer:events:undelegate" Array [  ] backbone.radio.js:161:7
Deprecation warning: tipsy is deprecated. Use tooltip instead. js.js:2216:2
[ui] "messagesview:messageflag:set" Array [ 18419, "unseen", false ] backbone.radio.js:161:7
[ui] "message:show" Array [ Object ] backbone.radio.js:161:7
[message] "load" Array [ Object, Object, 18419 ] backbone.radio.js:161:7
[message] "entities" Array [ Object, Object, Object ] backbone.radio.js:161:7
[ui] "messagesview:messages:update" Array [  ] backbone.radio.js:161:7
[ui] "messagesview:filter:clear" Array [  ] backbone.radio.js:161:7
[folder] "setactive" Array [ Object, Object ] backbone.radio.js:161:7
[navigation] "folder" Array [ 3, "SU5CT1guQXVkaQ==", undefined ] backbone.radio.js:161:7
Strict-Transport-Security: The connection to the site is untrustworthy, so the specified header was ignored.[Learn More] flags
Deprecation warning: tipsy is deprecated. Use tooltip instead. js.js:2216:2
[ui] "messagesview:message:setactive" Array [ 18419 ] backbone.radio.js:161:7
Strict-Transport-Security: The connection to the site is untrustworthy, so the specified header was ignored.[Learn More] messages
[message] "bodies" Array [ Object, Object, Array[8] ]

**Comment by moraus** [comment]
@ChristophWurst: Please let me know if you need any additional information.

**Comment by ChristophWurst** [comment]
@moraus there was a bug in 0.4.4/0.5.0 that made it impossible to select subfolders. Please update to 0.5.1, which is available in the app store.

**Comment by moraus** [comment]
Upgrading to 0.5.1 fixes this issue. Remember to clear local cache.

**Comment by ChristophWurst** [comment]
Great! Local storage cache is [cleared automatically](https://github.com/owncloud/mail/pull/1457) on upgrades since 0.4.4 ;-)
