### ISSUE TITLE
Cannot view email content - tries to load it from a "localhost" domain...

### ISSUE THREAD

**Issue by kuba-orlik** [owncloud/mail#1504]
### Steps to reproduce
1. Open Mail
2. click on a message
3. See an endlessly spinning circle instead of the message's content

The browser console says it tried to load the content from a "localhost" domain, even though I'm accessing the site via FQDN.

### Expected behaviour
Message content shows up

### Actual behaviour
Nothing happens

### ownCloud Mail

**ownCloud Mail version:** 0.5.0

**Mailserver or service:** Postfix

**Transport security - IMAP:** SSL

**Transport security - SMTP:** SSL

**Number of accounts:** 1

#### Server configuration
**Operating system**: Ubuntu Server (running in the official container)

**Web server:** Apache

**Database:** MySQL

**PHP version:** 5.6

**ownCloud version:** 9.0.2

**Updated from an older ownCloud or fresh install:** fresh

**List of activated apps:** 

```
Enabled:
  - activity: 2.2.1
  - calendar: 1.2.2
  - comments: 0.2
  - contacts: 1.2.0.0
  - dav: 0.1.6
  - documents: 0.12.0
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - mail: 0.5.0
  - news: 8.8.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - encryption
  - external
  - files_external
  - ocsms
  - user_external
  - user_ldap
```

**The content of config/config.php:**

```<?php
$CONFIG = array (
  'trusted_domains' =>
  array (
    0 => 'localhost',
  ),
  'asset-pipeline.enabled' => true,
  'appstore.experimental.enabled' => true,
  'datadirectory' => '/var/www/html/data',
  'overwrite.cli.url' => 'http://localhost:4000',
  'dbtype' => 'mysql',
  'version' => '9.0.2.2',
  'dbname' => 'owncloud',
  'dbhost' => 'mysql',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_admin',
  'logtimezone' => 'UTC',
  'installed' => true
);

```

#### Client configuration
**Browser:** Firefox

**Operating system:** Ubuntu 16.04

##### Browser log
```
Content Security Policy: Directive 'frame-src' has been deprecated. Please use directive 'child-src' instead. <unknown>
Content Security Policy: The page's settings blocked the loading of a resource at self ("script-src https://owncloud.mydomain.name 'unsafe-eval'"). mail:1:0
Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# instead a3af31a82fb7e139c233fb88a8dca7ab.js:1:0
Content Security Policy: The page's settings blocked the loading of a resource at self ("script-src https://owncloud.mydomain.name 'unsafe-eval'"). mail
Use of getPreventDefault() is deprecated.  Use defaultPrevented instead. a3af31a82fb7e139c233fb88a8dca7ab.js:5:17117
Use of getUserData() or setUserData() is deprecated.  Use WeakMap or element.dataset instead. cacheobj.js:877:23
Content Security Policy: The page's settings blocked the loading of a resource at http://localhost:4000/apps/mail/accounts/1/folders/SU5CT1g=/messages/4329/html ("frame-src https://owncloud.mydomain.name").
```

**Comment by ChristophWurst** [comment]
Hi @kuba-orlik,
please fix your config. Both 'trusted_domains' and 'overwrite.cli.url' point to localhost.

After fixing it you might need to clear the client-side cache with 'localstorage.clear()' in your browser's console.
Thanks!

**Comment by kuba-orlik** [comment]
@ChristophWurst Unfortunately, it didn't work. I've updated the `config.php` file and run `localStorage.clear()` in my browser's console and flushed all of my browser's caches - and the issue persists :<

What else should I try?

**Comment by ChristophWurst** [comment]
try disabling 'asset-pipeline.enabled', maybe that is causing problems too.

**Comment by kuba-orlik** [comment]
I've disabled the asset-pipeline, cleared localStorage, even tried on a different PC - the issue is still there. Would you like me to provide some more information on my oc installation?

**Comment by ChristophWurst** [comment]
@kuba-orlik which specific request fails? Please post the full URL (remove sensitive information if necessary)

**Comment by kuba-orlik** [comment]
It's the URL that's supposed to fetch the html content of the email message:

```
Content Security Policy: The page's settings blocked the loading of a resource at http://localhost:4000/apps/mail/accounts/1/folders/SU5CT1g=/messages/4347/html ("frame-src https://owncloud.kuba-orlik.name").
```

**Comment by ChristophWurst** [comment]
It shouldn't request that URL in the first place. This could mean te URL generation for the HTML-body iframe is generated wrong.

Do all other apps work as expected? I still suspect a config issue

**Comment by kuba-orlik** [comment]
All other apps work as expected. I'd be fine with entirely clearing the email database, if that's necessary and you could tell me how :)

**Comment by ChristophWurst** [comment]
@kuba-orlik don't do that, it won't help ;-)

**Comment by kuba-orlik** [comment]
I've tried gripping the "data"  folder for "localhost" and I skimmed through the oc database, but I didn't find any suspects. What more can I do to help diagnose this issue?

**Comment by kuba-orlik** [comment]
Come me to think of it, is host name necessary in the URL that's causing this issue? I think it would behave correctly if it was just "/apps/accounts/mail/..."

**Comment by kuba-orlik** [comment]
Hi, any thoughts? Is there some more debugging information that I can provide to solve this mystery? :)

**Comment by ChristophWurst** [comment]
do you know how to debug with xdebug? :)

**Comment by kuba-orlik** [comment]
I used to work with it some years ago -- I think I can set up dev environment and give some additional information if you give me some pointers :)

**Comment by ChristophWurst** [comment]
Awesome! Set a breakpoint to this https://github.com/owncloud/mail/blob/e7b1edbc5f85b7902a32dde20083fdf6b97d6de0/lib/controller/messagescontroller.php#L474 line and see what the returned value is. You can also step into the method to diagnose where the wrong value comes from. Let me know if you need help or more info, thanks :-)

**Comment by kuba-orlik** [comment]
Sorry for the delay. The returned string is:

`http://localhost:4000/apps/mail/accounts/1/folders/SU5CT1g=/messages/4528/html`

**Comment by ChristophWurst** [comment]
Okay, so there's the wrong URL. Can you maybe debug the url generation method to see why it uses localhost?

**Comment by kuba-orlik** [comment]
Now I see the issue: I haven't configured my nginx proxy to rewrite the "host" headers. Now I have a different issue: when I go to the admin panel, it goes into an infinite refresh loop... I think it might be caused by the fact that my proxy is being served over https...

**Comment by ChristophWurst** [comment]
Great. Since this is unrelated to the mail app, I'm closing this ticket now.

Have a look at the [nginx sample config](https://doc.owncloud.org/server/9.0/admin_manual/installation/nginx_owncloud_9x.html#owncloud-in-the-webroot-of-nginx) or ask in the #owncloud IRC channel on freenode if you need help with your setup. Thanks :-)

**Comment by kuba-orlik** [comment]
For future reference: It was an issue with my reverse-proxy configuration. Here are the relevant bits of configuration (it required configuration both on owncloud's and nginx's side):

* nginx:

  ```
 location / {
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Host proxy-domain.tld;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_pass http://localhost:4000;
            proxy_redirect http://localhost:4000 https://proxy-domain.tld;
        }
 ```

* owncloud's config.php:

  ```
  'trusted_domains' =>
  array (
    0 => 'proxy-domain.tld,
  ),
  'overwritehost' => 'proxy-domain.tld',
  "overwriteprotocol" => "https",
  ```
