### ISSUE TITLE
Not necessary to collapse folders for only one account

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/mail#1506]
For multiple accounts, collapsing the folders makes a lot of sense. However with only one account, it is less useful as there is plenty of space in the sidebar. For single accounts we should show the folders always.

cc @ChristophWurst what do you think?

**Comment by ChristophWurst** [comment]
While collapsing is most useful with multiple accounts, I think it also makes the interface cleaner and easier to use a lot if less important folders are hidden by default.

**Comment by jancborchardt** [comment]
Yeah, good point … the interface is cleaner and it makes the mail interface a lot simpler and focused. Good that we talked about it, just wanted to make sure. ;)
