### ISSUE TITLE
Update 0.4.4. -> 0.5.0. or 0.5.1. not working

### ISSUE THREAD

**Issue by plastikschnitzer** [owncloud/mail#1509]
### Steps to reproduce
1. Udate to 0.5.1. in OC App section

### Expected behaviour
The App should be updated.

### Actual behaviour
Error message (translated from German) shows up in the app section: The signature could not be verified. Please contact the app developer and check your admin screen.

The ownCloud Error log is empty!

If I disable the app, copy new files manually into owncloud/apps/ and enable the app, the database update screen shows up, but then instead of being redirected to the ownCloud login, it ends up with an owncloud screen which shows you "internal server error". Not the apache error 500 screen! 

See error log down below.

I had to copy the 0.4.4. files back into /apps/ and enable the app again, then everything is working again – but as version 0.4.4.

### ownCloud Core

Server configuration

Operating system: FreeBSD

Web server: Apache 2.4.18

Database: MySQL 5.6.19.

PHP version: 5.5.30

ownCloud version: 9.0.2.

Updated from an older ownCloud or fresh install: updated

List of activated apps:

Activity
Announcement Center
Collaborative tags
Comments
Default encryption module
Deleted files
External sites
Federation
First run wizard
Mail Template Editor
Notifications
PDF Viewer
Provisioning API
Share Files
Text editor
Update notification
Versions
Video player
Calendar
Contacts
Mail
OwnNote
Piwik Tracking

##### ownCloud log (data/owncloud.log)

Error	PHP	        Exception: Cannot include autoload. Did you run install dependencies using composer? at /usr/local/www/apache24/noexec/owncloud/apps/mail/appinfo/app.php#25 
Error	index	Exception: {"Exception":"Exception","Message":"Cannot include autoload. Did you run install dependencies using composer?","Code":0,"Trace":"#0 \/usr\/local\/www\/apache24\/noexec\/owncloud\/lib\/private\/app.php(163): require_once()\n#1 \/usr\/local\/www\/apache24\/noexec\/owncloud\/lib\/private\/app.php(144): OC_App::requireAppFile('mail')\n#2 \/usr\/local\/www\/apache24\/noexec\/owncloud\/lib\/private\/app.php(117): OC_App::loadApp('mail')\n#3 \/usr\/local\/www\/apache24\/noexec\/owncloud\/lib\/base.php(878): OC_App::loadApps()\n#4 \/usr\/local\/www\/apache24\/noexec\/owncloud\/index.php(39): OC::handleRequest()\n#5 {main}","File":"\/usr\/local\/www\/apache24\/noexec\/owncloud\/apps\/mail\/appinfo\/app.php","Line":25}

**Comment by Gomez** [comment]
I updated the tarball. Would you please try again and report back.

**Comment by plastikschnitzer** [comment]
I tried again and its working, thank you for the quick fix!

**Comment by ChristophWurst** [comment]
:rocket:

**Comment by plastikschnitzer** [comment]
By the way: I love to read what you are planning to do in the next milestones during GSOC :-)
The signature makes the app "complete" concerning the basics which. I will keep on testing as always :-D

**Comment by ChristophWurst** [comment]
Thanks @plastikschnitzer! Wanna be a beta-tester? I can ping you before the next release

**Comment by plastikschnitzer** [comment]
Sure! Where do I have to subscribe?

**Comment by ChristophWurst** [comment]
Awesome! Please send me a short mail to my private address (which you can find [in the sources](https://github.com/owncloud/mail/blob/bec16874180ac8ee028da3844a2954bbe44c2cf1/lib/searchmailbox.php#L3)) and I'll send out a mail before the next release. Thank you very much!
