### ISSUE TITLE
No "ü, ä, ö and ß" are saved in darfts

### ISSUE THREAD

**Issue by ttjaden** [owncloud/mail#1530]
### Steps to reproduce
1. Writing an email with the text: "Hallo süße Maus!"
2. not sending, so that a draft is saved
3. opening the draft

### Expected behaviour
The text ""Hallo süße Maus!" should appear

### Actual behaviour
The text "Hallo se Maus!" appears
So no "ü, ö, ä, ß" are saved in the drafts :(

### ownCloud Mail
**ownCloud Mail version:** 0.5.1
**Mailserver or service:** own Email-Hoster over SMTP and IMAP
**Transport security - IMAP:** SSL
**Transport security - SMTP:** SSL
**Number of accounts:** 1 in for every owncloud account (total 13 accounts)

### ownCloud Core
9.0.2
#### Server configuration
**Operating system**:
**Web server:** Shared Hoster: HostEurope
**Database:** MySQL
**PHP version:** 5.6
**ownCloud version:** 9.0.2
**Updated from an older ownCloud or fresh install:**

**List of activated apps:**
mail
documents
gallery
contacts
calendar
polls
```

**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => 'oce1w4ex53o6',
  'passwordsalt' => 'xxx',
  'secret' => 'xxx',
  'trusted_domains' => 
  array (
    0 => 'speisegut.yourweb.de',
    1 => 'ssl.webpack.de',
    2 => 'www.speisegut.yourweb.de',
  ),
  'datadirectory' => '/is/htdocs/wp11175861_KA06S74282/www/owncloud/data',
  'overwrite.cli.url' => 'http://speisegut.yourweb.de',
  'dbtype' => 'mysql',
  'version' => '9.0.2.2',
  'dbname' => 'db11175861-oc',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'xxx',
  'dbpassword' => 'xxx',
  'logtimezone' => 'UTC',
  'installed' => true,
  'mail_from_address' => 'admin',
  'mail_smtpmode' => 'php',
  'mail_domain' => 'speisegut.yourweb.com',
  'appstore.experimental.enabled' => true,
  'maintenance' => false,
  'theme' => '',
  'loglevel' => 0,
);

```

#### Client configuration
**Browser:** Firefox 47
**Operating system:** Windows 7

**Comment by ChristophWurst** [comment]
dup of https://github.com/owncloud/mail/issues/1329

**Comment by ChristophWurst** [comment]
schei Encoding! ;-)
