### ISSUE TITLE
Last missing feature: Sending to groups

### ISSUE THREAD

**Issue by ttjaden** [owncloud/mail#1531]
I would be more than great if it would be possible to send an Email to several contacts over the group name. Right now i always have to type all 20 names when sending a Mail to a special group in my contacts.

Will there be a solution in the near future? If there is a possibility to donate, I really would do it!

**Comment by ChristophWurst** [comment]
dup of https://github.com/owncloud/mail/issues/772. 

> If there is a possibility to donate, I really would do it!

awesome! we support donations via bountysource. Check the linked issue's footer, there's a link ;-)

**Comment by ttjaden** [comment]
Hallo!

konnte den Link nicht finden: Kannst du ihn mir zukommen lassen? Ich
würde dir/euch gerne 50€ zukommen lassen und mich sehr drüber freuen,
wenn das mit dem Gruppen anmailen dann bald tatsächlich ein Feature ist :)

Beste Grüße,
Tjarko


Am 14.06.2016 um 23:36 schrieb Christoph Wurst:

**Comment by ChristophWurst** [comment]
Hi,
here's the link: https://www.bountysource.com/issues/22110687-write-mails-to-group-of-contacts-mailing-list-groups?utm_campaign=plugin&utm_content=tracker%2F216487&utm_medium=issues&utm_source=github
Thank you very much! :rocket:

**Comment by ttjaden** [comment]
Done ... 50$ are on the way ;)


Am 14.06.2016 um 23:50 schrieb Christoph Wurst:

**Comment by ChristophWurst** [comment]
:money_with_wings: :dancers: :money_with_wings: :dancer: :money_with_wings:
