### ISSUE TITLE
Bring back contacts images with v9 contacts app

### ISSUE THREAD

**Issue by Gomez** [owncloud/mail#1537]
We lost it here: https://github.com/owncloud/mail/issues/1337

Needs to be merged:
https://github.com/owncloud/core/pull/25081

@ChristophWurst Maybe a todo for openSuseConf

**Comment by ChristophWurst** [comment]
@Gomez I reviewed it already and it will bring back contact images, finally. There is nothing to do in the mail app, I'm closing this issue therefore.
