### ISSUE TITLE
Reply indicator only shown after refresh

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/mail#1541]
Currently the reply indicator is only shown after refresh (or folder change or »check new messages«). In any case, the indicator should directly be shown as soon as the reply is sent.

**Comment by ChristophWurst** [comment]
works for individual accounts, but not for the unified inbox. (I assume the existing logic needs another hack because in the unified inbox the message id is actually not the message id)

**Comment by jancborchardt** [comment]
Fixed via https://github.com/owncloud/mail/pull/1604
