### ISSUE TITLE
'Add attachment from Files' UX when adding multiple files

### ISSUE THREAD

**Issue by ChristophWurst** [owncloud/mail#1542]
It's cumbersome to add multiple files as attachment as the file picker does neither allow multi-select, nor does it remember the last path. Ideally we should fix both, but we'll have to check whether the oc file picker allows multi-select and specifying the initial path.

**Comment by jancborchardt** [comment]
Yup! Totally agree, and there’s issues for both in core:

- File picker: remember last used folder https://github.com/owncloud/core/issues/23772
- Filepicker: Can't select multiple files on Mac OS X https://github.com/owncloud/core/issues/18282

**Comment by jancborchardt** [comment]
The relevant issues in Nextcloud server:
- Filepicker: remember last used folder https://github.com/nextcloud/server/issues/644
- Filepicker: multiselect https://github.com/nextcloud/server/issues/646
- Filepicker: sort by modified date (or better: respect sorting as in files app) https://github.com/nextcloud/server/issues/645

**Comment by ChristophWurst** [comment]
okay, so nothing we could fix in this app -> close
