### ISSUE TITLE
(HTML) Email is not loading properly 

### ISSUE THREAD

**Issue by mcdaniels2k** [owncloud/mail#1561]
### Steps to reproduce
1. Send an email
2. Open it via mailapp in Owncloud
The mail is displayed like this:
3. Email is not displayed fully (only the busy indicator is showing up - circle with rotating stripes)
![github_mailapp_screen](https://cloud.githubusercontent.com/assets/20438001/16801617/171e1132-48fc-11e6-9a05-fb8bc34c8787.JPG)

### Expected behaviour
The mail should be fully displayed
For example same mail via outlook.com
![github_in_outlook_screen](https://cloud.githubusercontent.com/assets/20438001/16801616/171d67b4-48fc-11e6-9ffe-1a8e3c8c7758.jpg)

### Actual behaviour
The mail is not fully displayed

### ownCloud Mail

**ownCloud Mail version:** 0.5.2

**Mailserver or service:** selfhosted, second accound outlook

**Transport security - IMAP:** STARTTLS

**Transport security - SMTP:** STARTTLS

**Number of accounts:** 2

**ownCloud Mail version build date:** (only if you are using a Nightly Build)
no

#### Server configuration
**Operating system**:
Debian Gnu Linux Jessie
**Web server:**
Apache 2.4.10
**Database:**
5.5.49

**PHP version:**
5.6.22

**ownCloud version:** (see ownCloud admin page)
9.0.3
**Updated from an older ownCloud or fresh install:**
9.0.1 - 9.0.2 - 9.0.3
**List of activated apps:**

  - activity: 2.2.1
  - calendar: 1.2.2
  - comments: 0.2
  - contacts: 1.3.1.0
  - dav: 0.1.6
  - documents: 0.12.0
  - encryption: 1.2.0
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - mail: 0.5.2
  - notes: 2.0.1
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - tasks: 0.9.1
  - templateeditor: 0.1
  - updatenotification: 0.1.0

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**

<?php
$CONFIG = array (
  'instanceid' => 'xxx',
  'passwordsalt' => 'xxx',
  'secret' => 'xxxxx',
  'trusted_domains' =>
  array (
    0 => 'owncloud.it-networker.at',
  ),
  'datadirectory' => '/var/owncloud_data',
  'overwrite.cli.url' => 'https://owncloud.it-networker.at',
  'dbtype' => 'mysql',
  'version' => '9.0.3.2',
  'dbname' => 'xxx',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'xxxx',
  'dbpassword' => 'xxx',
  'logtimezone' => 'UTC',
  'installed' => true,
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'updatechecker' => false,
  'maintenance' => false,
  'loglevel' => 0,
  'mail_smtpmode' => 'php',
  'mail_from_address' => 'owncloud',
  'mail_domain' => 'it-networker.at',
  'mail_smtpauthtype' => 'PLAIN',
  'mail_smtpauth' => 1,
  'mail_smtphost' => 'mail1.it-networker.at',
  'mail_smtpport' => '587',
  'mail_smtpname' => 'owncloud@it-networker.at',
  'mail_smtppassword' => 'xxx',
  'mail_smtpsecure' => 'ssl',
  'theme' => '',
  'htaccess.RewriteBase' => '/',
);

#### Client configuration

**Browser:**
Firefox 45

**Operating system:**
Windows 10 x64

##### Web server error log
not relevant
Insert your webserver log here
not relevant
##### ownCloud log (data/owncloud.log)
```
Please download here:

https://owncloud.it-networker.at/s/nqUL6BaEfJjkJy1


se
```

##### Horde IMAP log (data/horde_imap.log)
```
Insert your horde IMAP log here, see https://github.com/owncloud/mail#debug-mode
```

##### Horde SMTP log (data/horde_smtp.log)
```
Insert your horde SMTP log here, see https://github.com/owncloud/mail#debug-mode
```

##### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by Gomez** [comment]
It would help if you fillout the issue tempate. Horde IMAP log & Browser log is needed.

**Comment by ChristophWurst** [comment]
> mcdaniels2k closed this 9 minutes ago

so did you manage to solve the problem by yourself?

**Comment by mcdaniels2k** [comment]
There is no Horde IMAP log.
I just tried a nightly build 0.5.3
Mails now are loading the content into the app.

The weird thing is, that there was no such improvement in 0.5.3 as far as I can see
