### ISSUE TITLE
Mail app not updating number of unread mails 

### ISSUE THREAD

**Issue by Luzifer2222** [owncloud/mail#1562]
### Steps to reproduce
1. Receive Mail
2. Read Mail
3. Number of unread Mails stays the same on the left column bar

### Expected behaviour
Decreases number of unread Mails on the left column bar

### Actual behaviour
see point 3

### ownCloud Mail

**ownCloud Mail version:** 
0.5.2

**Mailserver or service:**
OpenXchange

**Transport security - IMAP:**
SSL/TLS

**Transport security - SMTP:**
SSL/TLS

**Number of accounts:**
1

#### Server configuration
**Operating system**:
Debian 8 Stable
**Web server:**
Apache 2
**Database:**
Mysql
**PHP version:**
php 5.6.22
**Nextcloud version:**
9.0.50

#### Client configuration
**Browser:**
Firefox Version 45.2.0
**Operating system:**
SL 7.2
#### Logs

Hey there on question.
The Mail app Version 0.5.2 is enabled and I have one Account in there. I encountered that if I get new Mails an read them the Mail App does not automatically update the number of unread Mail in the first column where the Inbox is located.
Only to manually load the site again or press F5 will do that. Is this a known Problem?

**Comment by ChristophWurst** [comment]
Hi,
thanks for reporting. This is a known problem and I'm planning to fix this soon :-)

**Comment by Luzifer2222** [comment]
Perfect thanks!

**Comment by Gomez** [comment]
Duplicate: #1400
