### ISSUE TITLE
"No messages in this folder" after Update OC8->9

### ISSUE THREAD

**Issue by kaffeeringe** [owncloud/mail#1567]
### Steps to reproduce
1. I moved owncloud8/data to /data and changed the config.php accordingly
2. I upgraded from Owncloud 8.0.2 to 9.0.4
3. I reactivated the mail app
4. I switched to the mail app

### Expected behaviour
I expected to see mails in my inbox.

### Actual behaviour
There's only the message "No messages in this folder" - I can call all subfolders and I see all mails there. everything besides the main inbox seems to work. 

I deleted the account and set it up anew. 

### ownCloud Mail

**ownCloud Mail version:** 0.5.2

**Mailserver or service:** 1und1 (@online.de)
**Transport security - IMAP:** (SSL/TLS) 
**Transport security - SMTP:** (SSL/TLS)

**Number of accounts:** 1

#### Server configuration
**Operating system**: ?

**Web server:** Apache 

**Database:** MySQL

**PHP version:** 7.0

**ownCloud version:** 9.0.4 (stable)

**Updated from an older ownCloud or fresh install:** Updates from 8.0.x

**List of activated apps:**  Activity 2.2.1,  Collaborative tags 0.2, Comments 0.2,  Deleted files 0.8.0,  Federation 0.0.4,  First Run Wizard 1.1,  Gallery 14.5.0,  Mail 0.5.2,  Mail Template Editor 0.1,  Notifications 0.2.3,  PDF Viewer 0.8.1,  Provisioning API 0.4.1,  Share Files 0.9.1,  Text Editor 2.1,  Update notification 0.1.0,  Versions 1.2.0,  Video player 0.9.8,  Calendar 1.2.2,  Contacts 1.3.1.0,  Music 0.3.11

**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => 'XXX',
  'passwordsalt' => 'XXX',
  'secret' => 'XXX',
  'trusted_domains' => 
  array (
    0 => 'XXX',
    1 => 'XXX',
  ),
  'datadirectory' => '/www/htdocs/XXX/data',
  'dbtype' => 'mysql',
  'version' => '9.0.4.1',
  'dbname' => 'XXX',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'XXX',
  'dbuser' => 'XXX',
  'dbpassword' => 'XXX',
  'installed' => true,
  'forcessl' => true,
  'theme' => '',
  'maintenance' => false,
  'loglevel' => 0,
  'trashbin_retention_obligation' => 'auto',
  'mail_smtpmode' => 'php',
  'mail_smtpsecure' => 'tls',
  'mail_domain' => 'XXX',
  'mail_from_address' => 'no-reply',
);

#### Client configuration
**Browser:** Firefox 

**Operating system:** Ubuntu 16.04

##### ownCloud log (data/owncloud.log)
{"reqId":"V457CFUNmfoAAFFlPYwAAAAh","remoteAddr":"46.142.82.220","app":"PHP","me
ssage":"opendir(\/tmp): failed to open dir: Permission denied at \/www\/htdocs\/
XXX\/owncloud\/lib\/private\/tempmanager.php#187","level":3,"time":"2016-07
-19T19:10:00+00:00","method":"GET","url":"\/cron.php","user":"--"}
{"reqId":"V457ClUNmfoAAGPSc8IAAAAP","remoteAddr":"46.142.82.220","app":"mail","m
essage":"loading messages 0 to 20 of folder <SU5CT1g=>","level":0,"time":"2016-0
7-19T19:10:02+00:00","method":"GET","url":"\/index.php\/apps\/mail\/accounts\/2\
/folders\/SU5CT1g%3D\/messages","user":"steffen"}
{"reqId":"V457ClUNmfoAAGPSc8IAAAAP","remoteAddr":"46.142.82.220","app":"PHP","me
ssage":"TypeError: Argument 1 passed to OCA\\Mail\\Model\\IMAPMessage::hordeToAs
soc() must be an instance of Horde_Mail_Rfc822_Address, instance of Horde_Mail_R
fc822_Group given, called in \/www\/htdocs\/XXX\/owncloud\/apps\/mail\/lib\
/model\/convertaddresses.php on line 73 at \/www\/htdocs\/XXX\/owncloud\/ap
ps\/mail\/lib\/model\/convertaddresses.php#33","level":3,"time":"2016-07-19T19:1
0:03+00:00","method":"GET","url":"\/index.php\/apps\/mail\/accounts\/2\/folders\
/SU5CT1g%3D\/messages","user":"steffen"}
{"reqId":"V457DFUNmfoAAGPSc8MAAAAP","remoteAddr":"46.142.82.220","app":"mail","m
essage":"loading messages 0 to 20 of folder <SU5CT1g=>","level":0,"time":"2016-0
7-19T19:10:04+00:00","method":"GET","url":"\/index.php\/apps\/mail\/accounts\/2\
/folders\/SU5CT1g%3D\/messages","user":"steffen"}
{"reqId":"V457DFUNmfoAAGPSc8MAAAAP","remoteAddr":"46.142.82.220","app":"PHP","me
ssage":"TypeError: Argument 1 passed to OCA\\Mail\\Model\\IMAPMessage::hordeToAs
soc() must be an instance of Horde_Mail_Rfc822_Address, instance of Horde_Mail_R
fc822_Group given, called in \/www\/htdocs\/XXX\/owncloud\/apps\/mail\/lib\
/model\/convertaddresses.php on line 73 at \/www\/htdocs\/XXX\/owncloud\/ap
ps\/mail\/lib\/model\/convertaddresses.php#33","level":3,"time":"2016-07-19T19:1
0:05+00:00","method":"GET","url":"\/index.php\/apps\/mail\/accounts\/2\/folders\
/SU5CT1g%3D\/messages","user":"steffen"}

##### Horde IMAP log (data/horde_imap.log)
```
Insert your horde IMAP log here, see https://github.com/owncloud/mail#debug-mode
```

##### Horde SMTP log (data/horde_smtp.log)
```
Insert your horde SMTP log here, see https://github.com/owncloud/mail#debug-mode
```

##### Browser log
```
Insert your browser log here, this could for example include:

Content Security Policy: Die Direktive 'frame-src'  sollte nicht mehr verwendet werden. Bitte verwenden Sie stattdessen die Direktive 'child-src'. (unbekannt)
Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf self blockiert ("script-src https://cloud.kaffeeringe.de 'unsafe-eval'"). mail:1:0
Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# instead jquery.min.js:1:0
Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf self blockiert ("script-src https://cloud.kaffeeringe.de 'unsafe-eval'"). mail
getPreventDefault() sollte nicht mehr verwendet werden. Verwenden Sie stattdessen defaultPrevented.

**Comment by ChristophWurst** [comment]
> I deleted the account and set it up anew.

Did that solve your issue?

**Comment by kaffeeringe** [comment]
No. I still can't see my inbox - only all the subfolders.

**Comment by ChristophWurst** [comment]
> I upgraded from Owncloud 8.0.2 to 9.0.4

Is this the upgrade path you took? That shouldn't be possible

**Comment by kaffeeringe** [comment]
Yes I did. Automatic upgrade didn't work, so I made it manually:
1 .New owncloud-folder with OC 9
2. copied config.php, 
3. redirected subdomain to new folder
4. started update

That worked all in all. Only I can't see my inbox ;-)

**Comment by kaffeeringe** [comment]
Sorry. the old version was 8.2.1.4

**Comment by kaffeeringe** [comment]
Suddenly there are mails in my inbox. I can only scroll back 9 days, but it seems to work for now.
