### ISSUE TITLE
Drop support for old ownCloud core versions

### ISSUE THREAD

**Issue by ChristophWurst** [owncloud/mail#1572]
At the moment, we support 6 major versions of ownCloud. See https://github.com/owncloud/mail/blob/1b3c2438a85ea87cdb1efdba550b9c095b8dad87/appinfo/info.xml#L13

This means that in theory we have to manually test PRs and releases for several ownCloud versions. In practice, this does not happen. I'm developing on core master and occasionally I test stable releases on my production system (mostly the newest stable release of oc). Additionally the list of beta testers is really short, hence I don't feel comfortable specifying that this app works on older releases too.

From a technical point of view we could move forward faster and we'd have to make fewer (or maybe no) version hacks anymore and use the newer features/APIs oc/nc provides.

Therefore I would like to propose that we stop supporting older releases as long as this app in development. How about targeting 9.1 and master only?

cc @Gomez @DeepDiver1975 @jancborchardt @irgendwie @tahaalibra

**Comment by DeepDiver1975** [comment]
as long as we are capable to fix issues in older mail app versions for older oc version I'm fine with this move.
Objections is keeping 9.0 as well?

**Comment by ChristophWurst** [comment]
> as long as we are capable to fix issues in older mail app versions for older oc version I'm fine with this move.

If you are talking about back-porting all bugfixes – no, sorry, I don't have enough time for that.

**Comment by DeepDiver1975** [comment]
> If you are talking about back-porting all bugfixes

Not all - only in case of really critical bugs.

**Comment by jancborchardt** [comment]
Yeah, probably best would be to branch off the last state which is supported for older releases just in case there’s some critical bugs we should backport.

But in general of course – if there’s simply no time to support all of this, especially considering that we’re still pre-1.0, then we have to focus.

**Comment by ChristophWurst** [comment]
> Yeah, probably best would be to branch off the last state which is supported for older releases just in case there’s some critical bugs we should backport.

We have tags for the releases, hence we know exactly from were we'd have to create a branch in case we want to fix an older release.

**Comment by Gomez** [comment]
@ChristophWurst You are the main maintainer so its your call. If possible and not that time-consuming we can try to support 9.0, too. But lets decide that on concrete issues / features.

:+1: 
Close?

**Comment by DeepDiver1975** [comment]
> Objections is keeping 9.0 as well?

9.0 as minimum would be my preference

**Comment by ChristophWurst** [comment]
> 9.0 as minimum would be my preference

Jawohl, let me prepare a PR :rocket:

**Comment by plastikschnitzer** [comment]
@ChristophWurst I can do beta testing for you on 9.0 and 9.1, I am running both and it looks like I will always have the two latest stable releases available for testing.

**Comment by ChristophWurst** [comment]
@plastikschnitzer awesome, thanks a lot! :-)
