### ISSUE TITLE
Disable automatic preview window

### ISSUE THREAD

**Issue by Juliku** [owncloud/mail#1576]
Is there any chance to implement a setting, that the preview / read window to the right is disabled? I dont want the first mail in a folder to be opened just by opening the folder.

**Comment by ChristophWurst** [comment]
@jancborchardt

**Comment by jancborchardt** [comment]
We’re not going to implement it since there is no reason to not show the first mail. Then the right pane would be either empty, or the message list would be comically wide. Sorry but neither makes a lot of sense. ;)
