### ISSUE TITLE
Scrolling down to load new messages is broken

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/mail#1578]
Somehow stops loading new messages at some point and also twitch moves up top of the list.

@ChristophWurst as we talked about.

**Comment by jancborchardt** [comment]
@ChristophWurst don’t remember – was this fixed?

**Comment by ChristophWurst** [comment]
what is this new label 'the-details' about? :D

the issue should be fixed. Re-open if not. Thx

**Comment by ChristophWurst** [comment]
is this the new 'priority' a.k.a. *jan wants you to fix this soon* label?

**Comment by ChristophWurst** [comment]
maybe we could call it *let's make Mail great again* then. Doesn't that sound better? :see_no_evil:

**Comment by mar1u5** [comment]
Sounds like Trump and "Make America great again" 😜 @ChristophWurst

**Comment by jancborchardt** [comment]
@ChristophWurst basically it’s all the little details which when fixed:
- make the app seem more stable and reliable
- alleviate lots of small annoyances
- make the app more fun to use :)

Lots of the stuff we talked about during the week. Also some of them are small things similar to starter issues or possibly easier JS things I could try fixing. ;)
