### ISSUE TITLE
Newlines inserted for replies again

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/mail#1592]
It seems that #1151 is back @ChristophWurst  ;D

![capture du 2016-07-29 18-12-52](https://cloud.githubusercontent.com/assets/925062/17255147/3f01a150-55b8-11e6-9036-73a4db5cfa10.png)

**Comment by ChristophWurst** [comment]
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/17247710-add-printer-friendly-view?utm_campaign=plugin&utm_content=tracker%2F216487&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F216487&utm_medium=issues&utm_source=github).

**Comment by jancborchardt** [comment]
![](http://www.reactiongifs.com/r/2013/10/money.gif)

**Comment by ChristophWurst** [comment]
Can't reproduce -> close

**Comment by ChristophWurst** [comment]
Approved-by: @jancborchardt
