### ISSUE TITLE
Only ask for notification permissions & mailto integration _after_ adding first account

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/mail#1608]
Currently you are bombarded with both requests when you open the Mail app for the first time, even without any accounts connected.

The requests should only come _after_ the first account has been successfully added. For the setup where your account is automatically added via LDAP etc, it of course should also ask directly.

**Comment by ChristophWurst** [comment]
dup of https://github.com/owncloud/mail/issues/1449

**Comment by jancborchardt** [comment]
Hehe, sorry ,D
