### ISSUE TITLE
Search/filter mails

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/mail#161]
We should use the existing search field in the top bar so folks can filter their mail. The mail in the content area should be shown according to the search term as-you-type.

Everything should be taken into account: to, from, cc, subject, body, attachment names, …
We can start with the current folder and expand from there.

**Comment by jancborchardt** [comment]
Instead of adding another search field in the top left, we should use the existing search field in the top bar.

Similarly we already do this in the apps management and in files. cc @butonic

**Comment by jancborchardt** [comment]
First iteration up at https://github.com/owncloud/mail/pull/472 :)

**Comment by jancborchardt** [comment]
Done by the awesome @DeepDiver1975 via https://github.com/owncloud/mail/pull/472 ;)

**Comment by 1337sup3rh4x0r** [comment]
Global search including all subfolders is not yet available, right?

**Comment by jancborchardt** [comment]
@1337sup3rh4x0r no, that would require more work but we should do it and set that for a future milestone. Can you maybe open a new issue for that? :)

**Comment by 1337sup3rh4x0r** [comment]
If contributing is so easy, I am glad to help ;)

**Comment by jancborchardt** [comment]
@1337sup3rh4x0r sure, everyone can report issues and also review pull requests. :) Also join us in #owncloud-mail on IRC if you like.
