### ISSUE TITLE
[Feature] Should accept attachments direct upload

### ISSUE THREAD

**Issue by Josta** [owncloud/mail#1619]
### Expected behaviour
Should offer a file upload button or dropin field when writing an email.

### Actual behaviour
Only allows for adding attachments from Owncloud files app, which is a great feature, but extra work if I just want to write an email including a local file that I have.

### Mail app

**Mail app version:** 0.5.2

**Comment by mar1u5** [comment]
Duplicate: https://github.com/owncloud/mail/issues/462
