### ISSUE TITLE
Contact autocompletion is case sensitive

### ISSUE THREAD

**Issue by zinks-** [owncloud/mail#197]
When chosing the recipient of my mail, for example contact "Roland" is not found if I start typing "rol".

**Comment by jancborchardt** [comment]
@zinks- @nielsha can you provide futher details of your setup?

**Comment by zinks-** [comment]
I'm using the latest stable versions of oc and contacts, here some mysql info :

``mysql  Ver 14.14 Distrib 5.5.43, for debian-linux-gnu (x86_64) using readline 6.2``

```
character_set_client = utf8

character_set_connection = utf8

character_set_database = latin1

character_set_filesystem = binary

character_set_results = utf8

character_set_server = latin1

character_set_system = utf8

collation_connection = utf8_general_ci

collation_database = latin1_swedish_ci

collation_server = latin1_swedish_ci
```

**Comment by wurstchristoph** [comment]
It's a bug in the contacts app: https://github.com/owncloud/contacts/issues/813

**Comment by jancborchardt** [comment]
Being worked on in Contacts: https://github.com/owncloud/contacts/pull/910

**Comment by jancborchardt** [comment]
Fixed by https://github.com/owncloud/contacts/pull/952 – will be in Contacts 8.1
