### ISSUE TITLE
Automatic redirect for external links in Firefox

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/mail#206]
Automatic redirect doesn’t work for me in Firefox. It works in Chrome though …

@LukasReschke (carried over from https://github.com/owncloud/mail/pull/192)

**Comment by jancborchardt** [comment]
Also, in Firefox for some reason the redirection page shows the noscript warning (as code) up top:
![capture du 2015-04-17 10 08 33](https://cloud.githubusercontent.com/assets/925062/7199142/88847d3a-e4f2-11e4-9362-fa92d9db61dc.png)

**Comment by Gomez** [comment]
The bug does not get any attention @ mozilla. I voted for the bug.

**Comment by RandolfCarter** [comment]
Getting
```
PHP Fatal error:  Call to undefined method OCP\\AppFramework\\Http\\ContentSecurityPolicy::disallowScriptDomain() in /var/www/owncloud/apps/mail/lib/controller/messagescontroller.php on line 176, referer: https://mydomain/owncloud/index.php/apps/mail
```
when trying to run latest master, and folders except inbox aren't refreshed - is it related to this issue? Is it maybe just a setup issue on my part?

**Comment by LukasReschke** [comment]
If you use core master as well as mail master you need to pull both branches. Stable8 + 7 of core should run fine also.

**Comment by RandolfCarter** [comment]
I tried with core 8.1b2 and mail master branch.

**Comment by LukasReschke** [comment]
> I tried with core 8.1b2 and mail master branch.

Yes. That won't work at the moment as the beta 2 does not contain the needed core changes. You need to apply https://github.com/owncloud/core/issues/16463 for that :-( 

Next 8.1 build should work though! :smile:

**Comment by RandolfCarter** [comment]
Ah of course. I saw that one but didn't realize it was a change to the core repo. Must have been quite tired already ;)
