### ISSUE TITLE
Add Account: seems freezed due to mail server side issue 

### ISSUE THREAD

**Issue by PoPoutdoor** [owncloud/mail#210]
Test with not much used email account, after click on 'connect' the spinner keep on for a very long time (I think over 3 minutes) without any messages and looks like owncloud instance lockup.

Verify settings with desktop email client and found that the server is not responding (no imap response)

Web server error log:

FastCGI-stderr: PHP message: PHP Fatal error:  Call to a member function getId() on a non-object in /${webroot}/owncloud/apps/mail/lib/db/mailaccountmapper.php on line 66

**Comment by Xenopathic** [comment]
Given that this means looking through the entire code base, deferring to 0.2

**Comment by jancborchardt** [comment]
Maybe these situations can be prevented by improving autoconfig: #678 cc @zinks-
