### ISSUE TITLE
Secure mail account passwort in db

### ISSUE THREAD

**Issue by Gomez** [owncloud/mail#244]
Passwort is stored cleartext in db, should be saved encrypted.

This should help:
https://github.com/owncloud/core/pull/10642

**Comment by jancborchardt** [comment]
This is still an issue when using ownCloud 8 and 8.1. We should encrypt the password, right @LukasReschke?

**Comment by jancborchardt** [comment]
@Gomez fix at https://github.com/owncloud/mail/pull/510
