### ISSUE TITLE
Reading a message does not decrease "unread" counter

### ISSUE THREAD

**Issue by zinks-** [owncloud/mail#246]
The count of a folder's unread messages (displayed in the side bar) doesn't change untill the account is reloaded.

**Comment by wurstchristoph** [comment]
I found out that ``prevUnseen`` is always ``false`` [here](https://github.com/owncloud/mail/blob/master/js/views/folder.js#L72-L74)

Could it be that ``_previousAttributes`` does not hold the old attribute values anymore? Maybe it´s related to [this](https://stackoverflow.com/questions/7208393/previous-attribute-of-backbone-js-isnt-persistent)
