### ISSUE TITLE
Error after deleting last mail in folder

### ISSUE THREAD

**Issue by PoPoutdoor** [owncloud/mail#261]
### Expected behaviour
Mail deleted, current mail no longer selected (maybe jump to latest mail as current selected mail in current folder)

### Actual behaviour
Mail deleted, program try to read already deleted mail (use the same mail id?)

#### ownCloud log (data/owncloud.log)
```
Fatal 	index 	OCP\AppFramework\Db\DoesNotExistException: This email (0) can't be found. Probably it was deleted from the server recently. Please reload. 
Error 	PHP 	Array to string conversion at /${owncloud_root}/lib/private/log.php#154 
```

**Comment by ChristophWurst** [comment]
@PoPoutdoor could you please test if that error still occurs with the latest mail app nightly? Thanks

**Comment by PoPoutdoor** [comment]
Console error is gone for latest nightly, but the "Error loading message" in message view still there.

Is it possible to trigger "Load more..." after last mail in current list deleted? 

I think this is less confused for most users, also improves impressions with more user friendly server response.
