### ISSUE TITLE
Error message not cleared at all

### ISSUE THREAD

**Issue by PoPoutdoor** [owncloud/mail#266]
It's a known bug for @hotmail(outlook.com) while deleting mail.

The error message never get cleared until a forced page refresh (Ctrl-r).

**Comment by jancborchardt** [comment]
@PoPoutdoor I assume that the error is fixed since we worked a lot on the app. Are you still in by the way? :) Come over to #owncloud-mail on IRC again!

**Comment by PoPoutdoor** [comment]
@jancborchardt Can't test the fix right now, have to setup a virtual server for OC 7.0.4 and up.

**Comment by jancborchardt** [comment]
@PoPoutdoor or simply install ownCloud locally to have a dev environment. :)
