### ISSUE TITLE
"Check mail" button and filtered empty folders

### ISSUE THREAD

**Issue by PoPoutdoor** [owncloud/mail#268]
1. When Mail first loaded, folder without mail not display on sidebar.
2. After some time, new mail delivered to the not displayed folder at server.
3. Click "Check mail" button on top of mail list, folder with mail by now is not displayed. Folder only display after page refresh.

I think this is a bad idea to hide empty folders for 0.1, for a page reload takes up to 30 seconds (browser cache cleared, depends on internet link speed and server side processing power) from start to finished.

With integrated all accounts sidebar (default to collapsed folder view), the empty folder code should be dropped.

**Comment by jancborchardt** [comment]
The »hide empty folders« code was dropped. Let’s continue discussion in https://github.com/owncloud/mail/issues/385
