### ISSUE TITLE
Send new mail/message from account of last selected folder (currently active one)

### ISSUE THREAD

**Issue by zinks-** [owncloud/mail#297]
When composing a new mail, the 'from' email address seems to always be the first account.
If we were in a folder of another account before cicking the new mail button, the 'from' field should default to that account's identity/email address (Thunderbird does this).

**Comment by Xenopathic** [comment]
Deferring to 0.2

**Comment by jancborchardt** [comment]
Review at https://github.com/owncloud/mail/pull/791 :)
