### ISSUE TITLE
Delete mail: Array to string conversion in log 

### ISSUE THREAD

**Issue by PoPoutdoor** [owncloud/mail#299]
Message being logged for every deletion:

  Error 	PHP 	Array to string conversion at /${OC_ROOT}/lib/private/log.php#154

**Comment by jancborchardt** [comment]
I’ll close this cause of inactivity. Seems it’s fixed with https://github.com/owncloud/mail/pull/286 / https://github.com/owncloud/mail/pull/306 being merged.
