### ISSUE TITLE
After adding a new account - its not shown immediately in settings

### ISSUE THREAD

**Issue by Gomez** [owncloud/mail#304]
The account is there, i can see the inbox, but the account is not in settings. 

Full refresh is needed

**Comment by jancborchardt** [comment]
Bumped to 0.1 because it’s a bad first-run experience. cc @wurstchristoph

**Comment by jancborchardt** [comment]
@wurstchristoph do you want to look into this? It seems similar to https://github.com/owncloud/mail/pull/474

**Comment by jancborchardt** [comment]
@Gomez can you solve that for 0.1? Otherwise it results in a subpar UX, especially on first run.

**Comment by jancborchardt** [comment]
Can we fix this for 0.1? @Gomez @DeepDiver1975

**Comment by Gomez** [comment]
Not in my area of experience. Maybe later on...
