### ISSUE TITLE
Moving mails to folders

### ISSUE THREAD

**Issue by RandolfCarter** [owncloud/mail#326]
As a user, I want to be able to move mails into other IMAP folders (e.g. for archiving, and to clean up the INBOX).
I didn't see any option to do this at the moment.

Drag&Drop would be a good option here (as e.g. possible in Roundcube).

App version: master - commit c6d82af

**Comment by jancborchardt** [comment]
Closing in favor of https://github.com/owncloud/mail/issues/411 which has this and more (like account creation).
