### ISSUE TITLE
Scroll bar hidden/overlayed by title bar

### ISSUE THREAD

**Issue by RandolfCarter** [owncloud/mail#328]
### Steps to reproduce
1. Open any mail
2. Check the titlebar region with respect to the scrollbar for the message.

### Actual behaviour
On the top 50 pixels or so, the title bar covers the scrollbar. See this screenshot:
![owncloud-mail-titlebar](https://cloud.githubusercontent.com/assets/2631274/4319234/a71c5782-3f29-11e4-97bf-7a7f19ead1be.png)

### Expected behaviour
The scrollbar should either start below the title bar or should not be overlayed by it

### Client configuration
**Browser:** Firefox 32.0.1 / Chrome 37.0.2062
**Operating system:** Windows 7

**Comment by jancborchardt** [comment]
We could do the same magic we did to fix this in the Files app: The scrollbar issue has been fixed btw: https://github.com/owncloud/core/pull/15260 ;)

**Comment by Xenopathic** [comment]
Moving to 0.2, it doesn't seem urgent

**Comment by stefan-niedermann** [comment]
@jancborchardt

> We could compute it by JS, look how wide the scrollbar is, and subtract that width – but that would not be very clean.

Why not use calc-property? http://caniuse.com/#search=calc

**Comment by jancborchardt** [comment]
@stefan-niedermann does calc allow us to say something like:
`width of this container minus scrollbar, but only in case scrollbar is present. Otherwise use width of this container`?
I assume not. :D

**Comment by jancborchardt** [comment]
Fix at https://github.com/owncloud/mail/pull/563, please review :)

**Comment by RandolfCarter** [comment]
:+1 thanks!

**Comment by jancborchardt** [comment]
Reopening as #563 only fixed this for mobile.

**Comment by jancborchardt** [comment]
@aidanamavi if you find a fix for this I’d be very happy. :) Since you said on IRC it should be a simple matter – as I said I didn’t manage so far.

**Comment by Bullnados** [comment]
If u have a widther Screen u have the following problem, that the title bar is not width enough.
The second one is the transparency of the title bar. The mail text looks through title bar, hope you can see that. Perhpas minimize monitor contrast.
![bug](https://cloud.githubusercontent.com/assets/11041576/8472885/36bd8908-20a5-11e5-8458-c4e22ccb3c97.JPG)

**Comment by jancborchardt** [comment]
Yeah, same issue in reverse.

I would simply use the same JS as in core to fix this: https://github.com/owncloud/core/pull/15260
Unless @aidanamavi you got the CSS fix as you mentioned? :)

**Comment by jancborchardt** [comment]
Fix pull request at https://github.com/owncloud/mail/pull/874, please review! :)
