### ISSUE TITLE
Deleting messages from trash

### ISSUE THREAD

**Issue by zinks-** [owncloud/mail#339]
Right now there is no way to remove a message from the trash: the 'delete' icon only moves the message to the same folder (= does nothing)

We could
1. completely remove the 'delete' icons from the trashed messages and only let people empty the trash as a whole
2. or have the delete icons really delete and purge the messages
3. or both : let people delete select messages from the trash, and empty the whole trash if they want.

**Comment by jancborchardt** [comment]
@irgendwie you mentioned you are interested in working on this? Would be a cool task to pick up and fix for 0.1. :)

**Comment by irgendwie** [comment]
@jancborchardt currently working on it!

**Comment by jancborchardt** [comment]
@irgendwie great stuff, looking forward! You can also submit a pull request white it’s still work-in-progress, then others can already look at it and review.

**Comment by jancborchardt** [comment]
Fixed via https://github.com/owncloud/mail/pull/574 thanks to @irgendwie! :)
