### ISSUE TITLE
UI, user pov

### ISSUE THREAD

**Issue by PoPoutdoor** [owncloud/mail#387]
From generic users' perspective, current UI is not as good as other desktop client, a lot slower and some operation seems not responding.

Current code:

**Load Apps**
* Wait a long time(relative to Files) for sidebar shown up
* Wait a longer time for first account's INBOX's most recent mails list to shown up
* Wait a long time for the most recent mail's content on display

**Change folder view**
* Wait a long time for selected folder's most recent mails list to shown up
* Wait a long time for the most recent mail's content on display

**Mail operation**
* Delete mail (only supported operation ATM)

**Nice to have Features**
* Organize mail (create folders, move mail to another folder, automatic executed rules)
* Anti-Virus support (owncloud server side backend or third-party online scan service)
* More owncloud main apps integration 
* Advanced settings/preference to customized account based default action (like select which account to load first, which folder is opened by default for the selected account, or delete mail directly without moving to trash.)
* key management (like user's own GPG key, senders key)

**Idea**

For the "slow" part:

* Caching of sidebar (mail account and folders does not changed often, use permanent cache on load and validate/update cache after the most recent mail's content loaded)
* Caching of mail list (after the most recent mail's content loaded, store every account/folder's mail list in short term cache)
* Networking twist (owncloud server-side packet management support, e.g. incoming packet priority/stack settings)

For the event/response part:

* Add ability to interrupt default actions, e.g. can stop loading the most recent mail's content after selected folder's most recent mails list loaded (by mouse double-click or keyboard shortcut, very helpful for users with mail server-side rules that deliver important mails to folders other than INBOX.). 

I know some ideas more likely belongs to owncloud core, some may not be possible/implemented at all, just my 5 cents.

**Comment by jancborchardt** [comment]
I would say it would be better to discuss this in separate smaller issues. For example:

* Performance improvements: https://github.com/owncloud/mail/issues/212
* Organizing mails into folders: https://github.com/owncloud/mail/issues/411

With such a big umbrella issue we won’t really have the discussion lead to anywhere. ;)
