### ISSUE TITLE
json error when subject is blank

### ISSUE THREAD

**Issue by PoPoutdoor** [owncloud/mail#389]
Message list not show while subject line is blank(maybe white space).

~~~
TypeError: jsondata is null
~~~

**Comment by jancborchardt** [comment]
@PoPoutdoor @zinks- @DeepDiver1975 any update here? Does the issue still occur?

**Comment by zinks-** [comment]
I never could reproduce the issue

**Comment by wurstchristoph** [comment]
Neither could I reproduce this.

Tested with different mails with blank or no subject

**Comment by jancborchardt** [comment]
Ok, I’m closing this then. @PoPoutdoor please let us know when the issue occurs again and we can reopen.
