### ISSUE TITLE
Reply box: to field not decoded properly

### ISSUE THREAD

**Issue by PoPoutdoor** [owncloud/mail#396]
Another spam mail... Extracts from headers:
~~~
Date: Fri, 26 Sep 2014 06:50:32 +0100
Reply-To: "MEN'S HEALTH" <Allonym@emal.com>
From: "MEN'S HEALTH" <Allonym@emal.com>
......
Subject:
Content-Type: text/html; charset="us-ascii"
Content-Transfer-Encoding: 8bit
Return-Path: Allonym@emal.com
~~~
This is display on reply box *to*
~~~
"MEN&#x27;S HEALTH" <Allonym@emal.com>
~~~

Note: header subject line is not set, as #389 but this one is rendered without other problem.

**Comment by jancborchardt** [comment]
Set to 0.1 as it’s a basic encoding issue we need to get right across the app.

**Comment by jancborchardt** [comment]
cc @LukasReschke for encoding. M)

**Comment by jancborchardt** [comment]
This is fixed by now. Please reopen if there’s still issues.
