### ISSUE TITLE
Blank mail content: iconv illegal character

### ISSUE THREAD

**Issue by PoPoutdoor** [owncloud/mail#399]
Another spam trigger OC error:
~~~
Error 	PHP 	iconv(): Detected an illegal character in input string at /${OC_ROOT}/apps/mail/lib/message.php#443 
~~~
Mail header
~~~
Subject:  Re:
MIME-Version: 1.0
Content-Type: text/plain; charset="us-ascii"
......
Content-Transfer-Encoding: quoted-printable
~~~
In mail header indicate **charset="us-ascii"**, but the correct encoding is **windows-1252**. The illegal character is converted to UTF-8 as XML &#146, which is display as **&#8217;** (XML &#8217) if decoded as windows-1252 and converted to UTF8.

**Comment by jancborchardt** [comment]
@PoPoutdoor @zinks- @DeepDiver1975 do you know how to fix this? Probably needed for 0.1 if a mail can not be shown.

**Comment by PoPoutdoor** [comment]
@jancborchardt Sorry for the late reply for the Chinese new year holidays!

First of all, we have to decided how to handle non-compliance encoding.

If we are not going to deal with this for 0.1, please set a version number we like to have this fixed.

If we want to fixed this from 0.1, from my limited php coding experiences, all source encodings should be converted to UTF-8 first (with error handling) and data passed along should be safe for further processing.

**Comment by jancborchardt** [comment]
@PoPoutdoor how much of a problem is this? Does this actually lead to many emails not being able to display? Since you encountered the bug, you can probably judge best if this is essential (0.1) or can wait til after.

**Comment by PoPoutdoor** [comment]
@jancborchardt This only happens for the junk mails, may be mail from some ancient M$ windows based mail clients. This does not affects me much for my daily use, but should be addressed for if we can avoid displaying the wrong encoded data.

My POV is fix this on later versions.

**Comment by jancborchardt** [comment]
Thanks for the clarification – putting it in the backlog. :)

**Comment by Xenopathic** [comment]
This issue happens with base64 encoded emails, which I (sometimes) receive from real people. Perhaps Content-Transfer-Encoding isn't being honoured?

Here is a test script:

```
<?php

$text = 'this is a test email';

$to = 'email@domain.com';
$from = 'testing@domain.com';

$subject = 'this is a test';
$nl = "\r\n";

//$contentType = '8bit';
$contentType = 'base64';

$headers = "From: $from$nl".
        "MIME-Version: 1.0$nl".
        "Content-Type: text/plain;$nl".
        "Content-Transfer-Encoding: $contentType$nl$nl";

if ($contentType === 'base64') {
        $text = chunk_split(base64_encode($text));
}

mail($to, $subject, "", $headers . rtrim($text));
```

When set to '8bit', the email is correctly parsed by the Mail app, but when set to 'base64', external clients (GMail Android app, Thunderbird) will read the email fine, but the Mail app gives no content and the `iconv()` error is printed to the logs.

**Comment by jancborchardt** [comment]
Summoning @LukasReschke ;)

**Comment by clementhk** [comment]
https://github.com/php-mime-mail-parser/php-mime-mail-parser is the only parser that works for me so far, maybe it make sense to use it instead, and hey, what is the reason that we don't make some sort of 3rdparty sub-module like core?

**Comment by Xenopathic** [comment]
@clementhk Horde already has a MIME parser, but it was disconnected: see #441

**Comment by clementhk** [comment]
Man I wish all these libs are a lot more lightweight...
You might need this btw https://github.com/php-mime-mail-parser/php-mime-mail-parser/blob/master/src/Charset.php.
I imported it from thunderbird.
