### ISSUE TITLE
Proposal: Exchange Support

### ISSUE THREAD

**Issue by pierrejochem** [owncloud/mail#404]
Include exchange support:

https://github.com/jamesiarmes/php-ews

I'm really sure that will be awesome for many people and will be a decision criteria for the whole product especially with ldap and AD logins.

**Comment by apg1980** [comment]
I would appreciate this very much.

**Comment by DeepDiver1975** [comment]
> I would appreciate this very much.

hit fork and start coding - pull requests are welcome - thx

**Comment by pierrejochem** [comment]
I will check your code and then we will see ;-) It would be perfect to have a mechanis like "storages" in the owncloud core project to implement new protocols

**Comment by clementhk** [comment]
It looks a bit like you need an opposite of https://github.com/jamesiarmes/php-ews, this thing look like it is for php to communicate with Exchange. While what we really need here is for owncloud to act like ews.
I think.

**Comment by clementhk** [comment]
Ooops, I misunderstood your POV.
I was thinking this mail app as an email server (when integrating with a Postfix/Dovecot).

**Comment by pierrejochem** [comment]
After checking the code I can only say this is only possible with core changes because currently it is only made for imap :-(

**Comment by Spacefish** [comment]
Hi, IMHO Exchange Servers can be configured to expose mailboxes via IMAP so you could just enable IMAP on your Exchange Server and use the current mail app to connect to Exchange!
Of course this is not an option if you don´t have the Exchange server under your control.

**Comment by pierrejochem** [comment]
@Spacefish: I know and also POP3 ;-)

**Comment by DeepDiver1975** [comment]
> After checking the code I can only say this is only possible with core changes because currently it is only made for imap :-(

well - this is part of the competition - right? :wink: 

Things to be done from my pov to allow other protocols to be used/implemented:
- define interfaces for account and message
- create a factory which will instantiate account objects based on some input (e.g. use an array where one item holds the account type) 
- enhance the setup screen to allow account based ui parts to specify the settings

**Comment by pierrejochem** [comment]
@DeepDiver1975: Right! ;-)

But first of all I have to finalize a new storage type for OC - Core :-D

**Comment by DeepDiver1975** [comment]
> But first of all I have to finalize a new storage type for OC - Core :boom:

storage? core? I don't get the connection to mail

**Comment by pierrejochem** [comment]
That was just a hint that I have to finish that before I can invest time into the mail enhancement :wink:

**Comment by ChristophWurst** [comment]
I'd say for now we should focus on getting IMAP to work properly before we add any other protocols :see_no_evil:
