### ISSUE TITLE
Text hidden by "reply/send button"

### ISSUE THREAD

**Issue by seal20** [owncloud/mail#410]
owncloud version 7.0.4
Mail apps version: clone of December 10th 2014
Browser: firefox

To reproduce the bug:
* Type a long mail in the (direct reply ui or the new message ui)
*When you reach the bottom of the box on the far right, the text is hidden by the reply (send) button (cf screenshot).
* If you continue to type, the box is extended when you create a new line, but the text is again hidden at the end of the line.

To fix the bug:
* The box should expands one line before it is expanding now

 or
* the reply/send button should be out of the text field.

![owncloud mail hiding text](https://cloud.githubusercontent.com/assets/6326493/5429881/58230fba-8441-11e4-89ad-b37c86e7eb09.png)

**Comment by jancborchardt** [comment]
@seal20 the pull request https://github.com/owncloud/mail/pull/414 looked nice – can you resubmit that, but with only one commit? Thanks!

**Comment by jancborchardt** [comment]
Sorry, my fault – this was of course already fixed with https://github.com/owncloud/mail/pull/416 :) Thank you again @seal20! :rocket:
