### ISSUE TITLE
Sent mails appears in the inbox not the sent folder

### ISSUE THREAD

**Issue by seal20** [owncloud/mail#412]
### Configuration
Owncloud 7.0.4
Mails git 10/12/2014
Mail server: private imap on vps

### Steps to reproduce
* send a mail through the apps
* the mail is successfully sent but appear nowhere
* Reload mails (check mail)
* the mail just sent is in the inbox but without the "text message". (the text of the message is visible in roundcube so I think owncloud hides it somehow like a quote).

### Expected behavior
* The sent mail appear in the sent folder
* If I send a mail with the same account but from rouncube, sent mails are added to the sent folders.

I understand and appreciate that owncloud wants to keep settings at a minimum. But perhaps a ui to define the different folders should exist for some case like mine where it doesn't work automatically.

**Comment by jancborchardt** [comment]
@DeepDiver1975 @zinks- any update on this here? @DeepDiver1975 you mentioned before that the Mail app doesn’t seem to save sent mails in the Sent folder anymore.

**Comment by jancborchardt** [comment]
Probably fixed by https://github.com/owncloud/mail/pull/407 – @seal20 please reopen if not.

**Comment by seal20** [comment]
Yes it is fixed! thanks a lot
