### ISSUE TITLE
Only admin user are allowed to autocomplete contacts

### ISSUE THREAD

**Issue by Bonbadil** [owncloud/mail#418]
Hello,

I'm the admin of my owncloud. My wife is a regular user. We just tried this mail app (and it's great, by the way! :-)).
But contact autocomplete on my wife's account doesn't work. The Firefox's network console say that the server answer 403 Forbidden with a JSON message "Logged in user must be an admin". The autocomplete works well on my account.
I've installed mail with a clone of the master branch of this repository on the commit 939e7abcc45f2121f23cdf2c978f65fe9300d41c.

Could this be corrected, please? Thank you for reading.

**Comment by jancborchardt** [comment]
@Bonbadil thank you for reporting the issue! :) You are very welcome to join us on IRC in #owncloud-mail (freenode), and any issue reports are always appreciated. :rocket:
