### ISSUE TITLE
URL not detected

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/mail#420]
url not detected

http://www.amazon.de/s/ref=nb_sb_noss?__mk_de_DE=%C3%85M%C3%85%C5%BD%C3%95%C3%91&url=search-alias%3Daps&field-keywords=Fax%2C+Kopierer+scanner+Laser&rh=i%3Aaps%2Ck%3AFax%5Cc+Kopierer+scanner+Laser

**Comment by jancborchardt** [comment]
What character does it fail at? Can you fix it?

**Comment by jancborchardt** [comment]
Works for @wurstchristoph and me.

@wurstchristoph can you commit the change where you put that URL in the tests? :)
