### ISSUE TITLE
sending/sharing a link to someone uses users language instead of recipients language

### ISSUE THREAD

**Issue by ferdiga** [owncloud/mail#421]
### Steps to reproduce
1. set your language to german
2. send a link to english speaking person
3. recipient does not understand

### Expected behaviour
recipient should get the mail in HIS language
### Actual behaviour
recipient gets the mail in MY language

### Server configuration
**Operating system**:
debian 7
**Web server:**
apache
**Database:**
mysql
**PHP version:**

**ownCloud version:** (see ownCloud admin page)
7.0.4

**Updated from an older ownCloud or fresh install:**

**List of activated apps:**

**The content of config/config.php:**

```
Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by DeepDiver1975** [comment]
@ferdiga thanks a lot for your feedback - I have to ask you to open this issue in the core repo. This repo is for the mail app which is not related to the mail share link feature which is used in core. THX
