### ISSUE TITLE
Inbox messages not shown

### ISSUE THREAD

**Issue by godlike64** [owncloud/mail#423]
Hi,

I just downloaded the owncloud mail app from git to try it out. While I can connect properly and browse through all my folders (tip: maybe add a setting to login to IMAP server using same credentials as the logged in user ;)), the Inbox folder is never shown. When trying to access it, I get a small error tooltip at the top:

Error while loading messages.

The spinwheel for the message list is endlessly loading and does not disappear. I can browse the rest of my folders just fine.

I'm using Dovecot 2.2.13 for my IMAP server, with no prefix for the inbox namespace. I am sorry if I don't know how to get debugging information for you, but if you point me in the right direction, I can upload what you need.

Thanks for a great app btw. Cheers!

**Comment by godlike64** [comment]
BTW I think I'm having the exact opposite bheaviour of #334

**Comment by godlike64** [comment]
Fixed by updating to Owncloud 7.0.4. Thanks

**Comment by jancborchardt** [comment]
@godlike64 cheers! :) Glad that everything works now
