### ISSUE TITLE
Don't load external images

### ISSUE THREAD

**Issue by RandolfCarter** [owncloud/mail#424]
### Steps to reproduce
1. Go to mail app
2. Load any mail with linked external images

### Expected behaviour
The external images should not show up immediately, only after an additional request to do so (similar to Thunderbird's default behavior).

### Actual behaviour
External images are immediately loaded (proxied somehow via owncloud, but still).
This might be considered a security concern (as Junk mail senders get notified if their mail is read...).

### Server configuration
mostly not relevant
Mail app version: 0.1.3 (not sure if this is still the current one... according to master in github.com/owncloud/mail, it seems to be. it's not the current master version though but from some time ago).

### Client configuration
not relevant

### Logs
not relevant

**Comment by DeepDiver1975** [comment]
@lukasreschke how we do it? Thx

**Comment by jancborchardt** [comment]
@LukasReschke needs your security input ;) Is the way we currently do it already OK?

**Comment by DeepDiver1975** [comment]
> Is the way we currently do it already OK?

actually not for un-trusted senders

**Comment by LukasReschke** [comment]
My opinion slightly differs here, the images are proxied and so a lot of the usual privacy concerns fall away. IP and User Agent are NOT leaked to the remote host, the only thing that is leaked is "somebody read the mail".

What I'd suggest instead is to use a cronjob that fetches the mails in some certain intervals and then caches the images on the ownCloud instance. In this case there is no additional information leaked than "the mail account exists and the mail was received" and the image link in the mail is replaced. However, that's something that a proper configured mail server will anyway leak ("Recipient address does not exists"-bouncer). This is by the way the same way as GMail solves this :)

Let me find out how this cronjob thingy works - never really used it :see_no_evil: 
Technically speaking this should be not *that* hard to implement as we already do the parsing anyways and would just have to store the images and references … somewhere … ;-)

Ref https://github.com/owncloud/mail/issues/189

**Comment by LukasReschke** [comment]
Let me get into the code again and look into this … tomorrow … ;-)

**Comment by DeepDiver1975** [comment]
but isn't the pure download of an image a clear indicator to the spammer that the email he did spam is valid? I though this was the prime reason for non loading images in html email.

**Comment by jancborchardt** [comment]
@LukasReschke what’s the current state on this? :)

**Comment by raimund-schluessler** [comment]
In my opinion external images should not be downloaded automatically. Otherwise the sender gets the information that "somebody read the mail" which is sometimes far than enough. Especially as ownCloud also focuses on privacy there should'nt be a compromise when it can actually be safer. Probably I didn't get how the mail app does it (I haven't had a look into the code), but the fact that images are loaded automatically is suspect. Also other mail apps don't load automatically (Gmail, thunderbird, Outlook), so there must be a reason ;)

For reference:
http://security.stackexchange.com/questions/12522/how-does-preventing-automatic-download-of-pictures-help-to-protect-my-privacy
https://support.office.com/en-us/article/Block-or-unblock-automatic-picture-downloads-in-email-messages-15e08854-6808-49b1-9a0a-50b81f2d617a

**Comment by Trim** [comment]
I think too that images should'nt be automatically downloaded.

I like the solution of Horde: only show Text part of mails by default (if there's none, show nothing) and add a banner to display HTML part with a warning about leaked informations.

The big problem for me, is that's easy to insert a unique identifier in HTML links for spammers.

**Comment by jancborchardt** [comment]
@LukasReschke please comment here on how we will do this (cronjob, like Gmail).

**Comment by arno01** [comment]
I support it. The images AND external resources SHOULD NOT be automatically loaded due to privacy & security concerns. It is already implemented in RoundCube and RainLoops webmail clients.

**Comment by jancborchardt** [comment]
@raimund-schluessler @Trim @arno01 @RandolfCarter does someone of you want to dig in and implement that? :) Or do you know someone who is up for the task? You are very welcome in our IRC channel #owncloud-mail, and I’m sure @LukasReschke can help you on any security-related questions.

**Comment by RandolfCarter** [comment]
Awesome :+1: !

**Comment by jancborchardt** [comment]
@RandolfCarter you’re welcome in #owncloud-mail on IRC if you want to test and contribute more. :)
