### ISSUE TITLE
"New Message" button disabled when using an empty account

### ISSUE THREAD

**Issue by wurstchristoph** [owncloud/mail#427]
I discovered that the mail app does not allow sending any mails as long as the current account does not have mails yet:
![oc_mail_sent1](https://cloud.githubusercontent.com/assets/1374172/6541510/9eaaf77e-c4d6-11e4-8401-025c6260a23c.png)

To be able to send new messages, I have to send an initial mail to this account. Then, the button is enabled again:

![oc_mail_sent2](https://cloud.githubusercontent.com/assets/1374172/6541511/a0906f06-c4d6-11e4-943c-78a674155d11.png)

**Comment by jancborchardt** [comment]
@DeepDiver1975 @PoPoutdoor @zinks- something for you ;)

@wurstchristoph thanks for the notice! Do you also have an idea why the message list is so wide in comparison to the message itself? Do you use a multi-monitor setup or something like that?

**Comment by wurstchristoph** [comment]
@jancborchardt do you mean the width of the third column? The screenshot is cropped, the whole screen looks like this:
![oc_mail](https://cloud.githubusercontent.com/assets/1374172/6541669/f6a0161e-c4de-11e4-952f-116805388283.png)
I guess this is how it should look like ;-)
