### ISSUE TITLE
Attachment name wrong on download & save to files (only on one mail server)

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/mail#438]
When downloading attachments or saving them to files, the name is not preserved. They are just named »(2).« when saving to files and just »2« when downloading.

cc @DeepDiver1975 @wurstchristoph any idea? Can you reproduce?

**Comment by wurstchristoph** [comment]
Works for me in Firefox and Chrome. Files are downloaded with the exact same file name as the original mail attachment. Tested with simple text (.txt) files.

What is logged if you use this https://github.com/wurstchristoph/mail/blob/issue438/lib/controller/messagescontroller.php#L152 ?

**Comment by jancborchardt** [comment]
```
Resource interpreted as Document but transferred with MIME type application/octet-stream: "http://localhorst/owncloud/index.php/apps/mail/accounts/1/folders/SU5CT1g=/messages/9267/attachment/2".
```

Also when hovering over the download button, that link shows (with the »/2«).

**Comment by jancborchardt** [comment]
Oh, and where should the logger message appear? I can’t see anything else in the owncloud.log nor apache error.log, nor in the JS console. – debugging is set to true in the config though.

**Comment by wurstchristoph** [comment]
There should be a log entry in owncloud.log like this (log level has to be set to 0 inside ```config/config.php```)

    {"reqId":"lzpxoJCzuWbDF4WU23Mc","remoteAddr":"::1","app":"mail","message":"downloading attachment <message-2W49VX.txt>","level":0,"time":"2015-03-30T11:11:02+00:00","method":"GET","url":"\/index.php\/apps\/mail\/accounts\/6\/folders\/SU5CT1g=\/messages\/40\/attachment\/2"}

I have the same hover url, so I guess that's what it should look like:
![oc_attach](https://cloud.githubusercontent.com/assets/1374172/6895285/d50a721c-d6de-11e4-8a36-c87403f63c51.png)

**Comment by jancborchardt** [comment]
Ah right, the log level was it. Here you go:
```
{"reqId":"EXFJeCm3BEOxdOBlXbDa","remoteAddr":"127.0.0.1",
"app":"no app in context",
"message":"Accessing the API class is deprecated! Use the appropriate services instead!",
"level":0,"time":"2015-03-30T11:27:46+00:00","method":"GET",
"url":"\/owncloud\/index.php\/apps\/mail\/accounts\/1\/folders\/SU5CT1g=\/messages\/8826\/attachment\/2"}
{"reqId":"EXFJeCm3BEOxdOBlXbDa","remoteAddr":"127.0.0.1",
"app":"mail","message":"downloading attachment <>",
"level":0,"time":"2015-03-30T11:27:49+00:00","method":"GET",
"url":"\/owncloud\/index.php\/apps\/mail\/accounts\/1\/folders\/SU5CT1g=\/messages\/8826\/attachment\/2"}
```

**Comment by jancborchardt** [comment]
@wurstchristoph any more insight on this?

**Comment by jancborchardt** [comment]
@DeepDiver1975 @LukasReschke for reference, this only happens with my `@owncloud.com` email address.

**Comment by jancborchardt** [comment]
@DeepDiver1975 this happened again today with the `@owncloud.com` account – see attachment of Frank’s latest mail. Saving locally works fine. Saving in the cloud has the proper document, but `(2).` as name.

**Comment by jancborchardt** [comment]
@DeepDiver1975 you need to do this. :)

**Comment by jancborchardt** [comment]
Aaand same yet again. With downloading attachments, this error in the JS console:
```
Resource interpreted as Document but transferred with MIME type application/octet-stream: "http://127.0.0.1/owncloud/index.php/apps/mail/accounts/-1/folders/YWxsLWluYm94ZXM=/messages/WzE2LDExMzA5XQ==/attachment/2".
```

And when saving to Files, this in the owncloud.log:
```
"message":"Undefined index: extension at owncloud\/apps\/mail\/lib\/controller\/messagescontroller.php#256",
"method":"POST",
"url":"\/owncloud\/index.php\/apps\/mail\/accounts\/-1\/folders\/YWxsLWluYm94ZXM%3D\/messages\/WzE2LDExMzA5XQ%3D%3D\/attachment\/2"
```

@DeepDiver1975 get on it ;)

**Comment by itheiss** [comment]
@jancborchardt  Can't reproduce this. Have tried with diffrent files, with and without proper file extension. What is meant by: "only on one mail server" ?

**Comment by jancborchardt** [comment]
It’s on our @owncloud.com mail server, on my personal one this didn’t happen.

**Comment by DeepDiver1975** [comment]
Stuff like this is depending on the mail - especially on how it is composed.

**Comment by jancborchardt** [comment]
@DeepDiver1975 just forwarded you a mail with an attachment where this happens.

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 just forwarded you a mail with an attachment where this happens.

pointless since forwarding manipulates the mail messages

**Comment by PoPoutdoor** [comment]
@jancborchardt Can you post the full headers?

**Comment by jancborchardt** [comment]
Moving to 0.3 since it’s specific to a setup and specific mails.

**Comment by ChristophWurst** [comment]
@DeepDiver1975 did you have a look at this? Any suspicion what could cause it on that specific setup?

**Comment by jancborchardt** [comment]
Closing this since we moved mail servers or so and I didn’t have this issue for some time now.
