### ISSUE TITLE
[Feature] Scam/phishing detection

### ISSUE THREAD

**Issue by tanghus** [owncloud/mail#44]
I recently noticed that my preferred MUA KMail wasn't very good for detecting if a mail was a cleverly crafted scam. [This is not the case anymore](https://bugs.kde.org/show_bug.cgi?id=307818) and it would be great if ownCloud mail could implement something similar, for example detect if an anchor has a title and it shows an url which is not the url defined in href, and give the user a warning.

**Comment by ChristophWurst** [comment]
out of scope for now
