### ISSUE TITLE
Several folders highlighted when clicking through the list fast

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/mail#440]
When you click on different folders faster than they can load, the sidebar can look like this:
![mail-folders](https://cloud.githubusercontent.com/assets/925062/6893967/9a023f40-d6d1-11e4-8282-d3a67f4fede5.png)
(In this case the »Sent« folder is open since it was clicked last.)

To fix this, we should remove the highlight on any other folder when clicking on a new folder. cc @wurstchristoph @zinks-

**Comment by wurstchristoph** [comment]
Moreover, if you switch folders that fast, the message column is loaded for each folder you clicked (ajax responses coming in). This looks odd and should be fixed too

**Comment by jancborchardt** [comment]
@wurstchristoph it seems your PR https://github.com/owncloud/mail/pull/452 introduced a separate issue: When you have multiple accounts, the last folder you opened for each account is always highlighted.

Can you look into this? :)

**Comment by wurstchristoph** [comment]
Sorry, fixed it with PR https://github.com/owncloud/mail/pull/489 ;-)

**Comment by jancborchardt** [comment]
Well it was my fault for the sloppy review. ;D
