### ISSUE TITLE
unable to activate on oc82 error

### ISSUE THREAD

**Issue by apg1980** [owncloud/mail#442]
{"reqId":"3bd29d01792382cdd7866b580da665f7","remoteAddr":"10.10.20.10","app":"index","message":"Exception: {\"Message\":\"Cannot include autoload. Did you run install dependencies using composer?\",\"Code\":0,\"Trace\":\"#0 \\\/OWNCLOUD-DATA\\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/lib\\\/private\\\/app.php(117): require_once()\\n#1 \\\/OWNCLOUD-DATA\\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/lib\\\/private\\\/app.php(98): OC_App::requireAppFile('mail')\\n#2 \\\/OWNCLOUD-DATA\\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/lib\\\/private\\\/app.php(77): OC_App::loadApp('mail')\\n#3 \\\/OWNCLOUD-DATA\\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/lib\\\/base.php(751): OC_App::loadApps()\\n#4 \\\/OWNCLOUD-DATA\\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/index.php(36): OC::handleRequest()\\n#5 {main}\",\"File\":\"\\\/OWNCLOUD-DATA\\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/apps\\\/mail\\\/appinfo\\\/app.php\",\"Line\":6}","level":4,"time":"2015-04-01T06:55:21+00:00","method":"GET","url":"\/owncloud\/index.php\/settings\/ajax\/navigationdetect.php?app=mail"}

**Comment by DeepDiver1975** [comment]
https://github.com/owncloud/mail#developer-setup-info

> Cannot include autoload. Did you run install dependencies using composer?

**Comment by apg1980** [comment]
Yes sorry i have forgotten to do so.
Now it works. 
Thanks
