### ISSUE TITLE
Question: predefine mailserver settings with user_ldap

### ISSUE THREAD

**Issue by apg1980** [owncloud/mail#443]
Hi your app is pretty cool thanks a lot for this. 
My question is how to implement default server settings for all users with single sign on of the existing user_ldap credentials. 
Best regards

Update infos:
It would be great to define in admin settings following variables for static auto imap configuration:
- internal imapserver ip and port
- internal smtpserver ip and port
The credentials should be taken from user_ldap credentials to log on the imap mailbox

**Comment by jancborchardt** [comment]
Closing as duplicate of https://github.com/owncloud/mail/issues/166 – let’s continue there. :)
