### ISSUE TITLE
»Message sent« notification is buggy

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/mail#448]
When sending an email, the »message sent« notification below the input field is a bit buggy. When clicking the send button it shows `[object Object]` while loading and then when it’s sent it will say:

`Message sent to &amp;quot;Jan-Christoph Borchardt&amp;quot; &amp;lt;jan@bla.bla&amp;gt;`

Seems something is escaped wrongly. cc @DeepDiver1975 @LukasReschke @wurstchristoph

**Comment by LukasReschke** [comment]
We need to re-evaluate all usages of `t()` and remove the manual escaping, it is now done automatically.

For example in `message: t('mail', 'Message sent to {Receiver}', {Receiver: escapeHTML(to.val())})`  the `escapeHTML` has to get removed.

**Comment by jancborchardt** [comment]
Fixed by https://github.com/owncloud/mail/pull/458, thanks to @wurstchristoph @DeepDiver1975 :)
