### ISSUE TITLE
Emails not put into sent folder

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/mail#449]
Written emails are not put into the sent folder atm. They are correctly sent, but it seems like they are not.

Related to https://github.com/owncloud/mail/issues/94 https://github.com/owncloud/mail/issues/312 https://github.com/owncloud/mail/issues/412

Any idea @zinks- @DeepDiver1975 @wurstchristoph

**Comment by wurstchristoph** [comment]
I guess there is an issue somewhere here: https://github.com/owncloud/mail/blob/master/lib/controller/accountscontroller.php#L277-L283
Maybe this PR helps: https://github.com/owncloud/mail/pull/407

I'll have a look...

**Comment by jancborchardt** [comment]
Fixed by https://github.com/owncloud/mail/pull/407, thank you @wurstchristoph! :)
