### ISSUE TITLE
Release date of 0.1

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/mail#453]
We waited a while to release a first version. Now we decided on a release date.

**We will release ownCloud Mail 0.1 on May 6, 2015**
(late afternoon, about 19:00 Central European Standard Time)

That’s exactly 2 years and 2 months after the first commits in this repository. We just have a handful of issues open for the 0.1 milestone also, so that should be doable as well:  https://github.com/owncloud/mail/milestones/0.1

### Fix
* [x] fix & review the remaining [open issues and pull requests for 0.1](https://github.com/owncloud/mail/milestones/0.1)
* [x] add all contributors to readme and appinfo #607
* [x] pull latest translations from Transifex

### Promo
* [x] new screenshot
* [ ] write short [release email](https://mailman.owncloud.org/pipermail/devel/2014-September/000607.html) (for user and devel list)
* [ ] spread it on social media

### Publish
* [x] tag [0.1](https://github.com/owncloud/mail/releases/tag/v0.1.0)
* [x] submit to [apps.owncloud.com](https://apps.owncloud.com/content/show.php/Mail?content=169914)
* [x] test installation
* [x] approve
* [x] give some good ratings! ;)

### Post-release
* [x] close 0.1 milestone and move remaining issues to 0.2
* [x] look through issues to plan 0.2 priorities
* [x] prepare for fixing possible issues

@DeepDiver1975 @zinks- @LukasReschke @Gomez @wurstchristoph @Xenopathic @PoPoutdoor let’s do this! :)

**Comment by jancborchardt** [comment]
We just put a bunch more issues in the 0.1 milestone. Don’t worry, we’ll also release if not all of them are done. It’s just to have a better overview of what we think is feasible and would be nice for a first release.

Everything from the 0.1 milestone we don’t finish will move to 0.2, and the 0.2 moves to 0.3, and so on.

**Comment by jancborchardt** [comment]
@DeepDiver1975 @wurstchristoph I introduced an »priority« label to highlight the 0.1 issues which are particularly important and we should focus on: https://github.com/owncloud/mail/issues?q=is%3Aopen+is%3Aissue+label%3Apriority – do you agree with that?

**Comment by wurstchristoph** [comment]
good idea :+1:

**Comment by Xenopathic** [comment]
Since we are about a week away from 0.1, I'm going to start marking any non-bug issues that haven't got some WIP implementation available as 0.2. Correct me if I'm wrong anyone!

**Comment by DeepDiver1975** [comment]
Awsome initiative @Xenopathic THX

**Comment by jancborchardt** [comment]
@Xenopathic good call dude, thank you for managing that stuff. :)

**Comment by jancborchardt** [comment]
Updated the original post with the stuff we need to do. Anything I missed (also cc @clementhk @irgendwie)

**Comment by clementhk** [comment]
I just installed it for the first time, it feels like still have a long way to go :).
Hope you'll get more contributors once it's launched.

**Comment by zinks-** [comment]
@clementhk you mean you managed all that work without having the app up and running? :astonished:

**Comment by jancborchardt** [comment]
@clementhk yeah, for sure. :) What exact points did you stumble over or where did you miss things which are not in issues yet? Please open new issues for all of those. :)

**Comment by jancborchardt** [comment]
Btw everyone, we need to also especially test the integration with Contacts (recipient suggestions) and Files (attachment loading and saving).

**Comment by clementhk** [comment]
@zinks- with travis :)

**Comment by jancborchardt** [comment]
@clementhk woah :D well done. In any case I hope you now dogfood the app. ;)

**Comment by jancborchardt** [comment]
Ok, release is later today (~19:00 CEST, in 7 hours) so let’s get to fixing the last remaining 0.1 issues! https://github.com/owncloud/mail/milestones/0.1

**Comment by jancborchardt** [comment]
As you probably noticed we did not tag the release, mainly because of the subfolders not loading: https://github.com/owncloud/mail/issues/611

We’re extending it for two days, to Friday May 8. Let’s work on the last stretch for https://github.com/owncloud/mail/milestones/0.1 and give the app a good testing! :)

**Comment by jancborchardt** [comment]
Everyone – we have the app _not yet_ tagged, but already submitted to the appstore: https://apps.owncloud.com/content/show.php/Mail?content=169914

You can already vote the score up and become a fan! :)

**Comment by jancborchardt** [comment]
Ok, now everything’s done. @DeepDiver1975 let’s tag the 0.1 release tomorrow (Monday) and start to spread it?

**Comment by jancborchardt** [comment]
We’re silently live: https://apps.owncloud.com/content/show.php?content=169914 :)

**Comment by irgendwie** [comment]
:+1:

**Comment by jancborchardt** [comment]
Closing this now. Thanks to everyone of you for the hard work! :) I really enjoy being part of this small community.

The only thing left now is to spread it a bit more. In the next days (when there are no big issues found) I’ll write a mail to the user and devel mailing list. Then we can also tweet about it a bit and such. :)
