### ISSUE TITLE
Ability to add attachments when replying

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/mail#460]
Currently adding attachments is only possible for new messages. Should also be possible for replies.

**Comment by Xenopathic** [comment]
This seems like a bug - leaving on 0.1

**Comment by jancborchardt** [comment]
Yeah, it’s definitely expected to work as it does also for new mails.

**Comment by jancborchardt** [comment]
This would really be good for 0.1 @DeepDiver1975

**Comment by jancborchardt** [comment]
Can we do this for 0.1 then? Probably doesn't involve as much jQuery as #462

**Comment by DeepDiver1975** [comment]
> Can we do this for 0.1 then? Probably doesn't involve as much jQuery as #462

doable

**Comment by Xenopathic** [comment]
I've tried to get started on this, but the code is an absolute mess! There's sending logic in js/send-mail.js for replies and in js/views/sendmail.js for new mails, templates/compose.php seems completely broken at the moment, and there are so many hooks and events all over the place it's getting hard to keep track of things.

**Comment by Xenopathic** [comment]
So here's the idea - we have a Handlebars template for new messages, which I will extend so we can pre-fill fields (like the To and Subject), then use that same template not just for new messages but underneath existing mails for replies. Also means the user has more control over email replies (manual Subject editing for example).

**Comment by jancborchardt** [comment]
I would still prefer to by default hide some fields in the case of reply, such as the subject. But we’ll see about that when we’re at it. I think it’s a great idea to unify it as stuff like #568 (add bcc for replies) will also be fixed. :)

**Comment by ChristophWurst** [comment]
fixed with PR #819
