### ISSUE TITLE
Current folder highlight is removed when opening another unread mail

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/mail#461]
1. Go to your inbox, wait until the current message is loaded
2. Click on another _unread_ message
3. Observe how the highlight of the Inbox entry in the sidebar disappears

@DeepDiver1975 @wurstchristoph any idea?

**Comment by wurstchristoph** [comment]
The following line seems to cause it: https://github.com/owncloud/mail/blob/master/js/views/folder.js#L81

Therefore I guess it's about handlebars rendering the folder element again, so the ```active``` class is removed
