### ISSUE TITLE
Multiple folders get loaded when switching fast

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/mail#467]
As @wurstchristoph mentioned in issue #440:

>  if you switch folders that fast, the message column is loaded for each folder you clicked (ajax responses coming in). This looks odd and should be fixed too

When another folder is clicked, the previous ajax call should probably be cancelled right away.

@DeepDiver1975 @zinks- something for you? :)

**Comment by zinks-** [comment]
The behavior I observe on my instance is slightly different: when I quicly click on folder A then B, Folder A listing is shown but Folder B is the one selected in the navigation.

Properly fixing this bug will most likely correct the two behaviors.
I'm on it!

**Comment by zinks-** [comment]
The messages from folder B are actually appended to the list of messages, beneath those form folder A.

**Comment by jancborchardt** [comment]
@zinks- great to hear you’re digging into it! Will happily review any pull request. :)
