### ISSUE TITLE
Folder with whitespace in it doesn't list emails

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/mail#468]
1. having a folder with a whitespace in it - like 'work reports'
2. clicking on this element
3. get a listing for this email folder but instead "no messages in this folder" is shown

git clone from 5 minutes ago and ownCloud 8.0.2

**Comment by jancborchardt** [comment]
Does this also happen when you use ownCloud 8.1 (git master)?

**Comment by MorrisJobke** [comment]
@jancborchardt Yes.

**Comment by jancborchardt** [comment]
@DeepDiver1975 @wurstchristoph @zinks- @Gomez can you reproduce? It worked for me when I tested with a folder.

**Comment by wurstchristoph** [comment]
I created a folder named "test folder" and copied some mails into it: same result, "no messages in this folder"

**Comment by jancborchardt** [comment]
Ok, we need to fix that then. @DeepDiver1975 @wurstchristoph @Gomez someone of you want to take it on?

**Comment by wurstchristoph** [comment]
I had a quick look. Seems like the IMAP request for the status of each folder is malformed when there is whitespace in the name.
IMAP calls should look like this:

    9 STATUS INBOX (MESSAGES RECENT UIDNEXT UIDVALIDITY UNSEEN)

so the IMAP server returns something like

    * STATUS "INBOX" (MESSAGES 31 RECENT 0 UIDNEXT 33 UIDVALIDITY 1428599115 UNSEEN 0)
    9 OK Status completed.

However, for a folder called "test folder" this is sent:

    12 STATUS "test folder""" (MESSAGES RECENT UIDNEXT UIDVALIDITY UNSEEN)

Therefore the server returns

    12 BAD Error in IMAP command STATUS: Status items must be list.

This results in an exception thrown [here](https://github.com/owncloud/mail/blob/master/lib/mailbox.php#L180), so the "no_select" attribute is set to true by the client and therefore no mails are downloaded if you click the folder.
