### ISSUE TITLE
Clicking "new message" doesn't result in anything

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/mail#469]
* clicking new message
* something to type a new message in will appear, but instead following JS error appears:

```
TypeError: this.aliases[0] is undefined sendmail.js:24
```

git clone from 5 minutes ago
Browser: Firefox

**Comment by jancborchardt** [comment]
Does this also happen with Chrome, and when you use ownCloud 8.1 (git master)?

**Comment by MorrisJobke** [comment]
Works now :( I haven't changed anything. Also browsing various folders and messages doesn't affect it anymore.

**Comment by jancborchardt** [comment]
Strange - maybe just a caching error, or related to first time setup.

**Comment by MorrisJobke** [comment]
Yes. When not refreshing after the setup it doesn't work -> bad first user experience

**Comment by MorrisJobke** [comment]
Also with current git master of the server

**Comment by jancborchardt** [comment]
cc @DeepDiver1975 @wurstchristoph :)
