### ISSUE TITLE
IMAP errors seem not to be logged.

### ISSUE THREAD

**Issue by Henni** [owncloud/mail#485]
When sending an email the mail app tells me that there is an IMAP error.
This is done by a short message below the mail input area.
I am missing further information about this error either instead of the short message or in the log file of owncloud.

![owncloud-imap-error](https://cloud.githubusercontent.com/assets/1267827/7165967/2acb2a74-e3ab-11e4-9d25-4ff15896edfe.png)

**Comment by Henni** [comment]
On a second thought the error message should definitely occur where it currently is but with more details.

It shouldn't appear (only) in the log. There shouldn't be an admin required to fix a simple mail setup error.

**Comment by Xenopathic** [comment]
From what I remember there is nothing much we can do in such a situation - the IMAP server literally just replies with `BAD`. It might be a good idea to log exactly what command caused that though... Anyhow, moving to 0.2

**Comment by DeepDiver1975** [comment]
since #522 the while IMAP conversation is written to data/horde.log in case debug mode is enabled in the config.php - maybe this helps ....

```php
<?php
define('DEBUG', 1);

**Comment by ChristophWurst** [comment]
closing this as I don't see any (easy) way to fix this.
