### ISSUE TITLE
Submit mails by ctrl+enter

### ISSUE THREAD

**Issue by wurstchristoph** [owncloud/mail#491]
Like most other mail clients do it, we could submit new messages an replies when the user hits ctrl+enter

**Comment by jancborchardt** [comment]
Yup. Maybe this is just a matter of correctly writing the HTML so that the form knows what the submit button is.

**Comment by jancborchardt** [comment]
Fixed by you in https://github.com/owncloud/mail/pull/493 ;)

If in the commit or in the Pull request you say something like »fix https://github.com/owncloud/mail/pull/493«, Github will automatically close the corresponding issue on merge.

**Comment by wurstchristoph** [comment]
I know...just forgot to add it ;-)

**Comment by jancborchardt** [comment]
This seems to be broken on master for new messages. For replies it still works. Can you check it out @wurstchristoph? :)

**Comment by wurstchristoph** [comment]
Confirmed ;-)
It works In FF, but not in Chrome. @jancborchardt Which browser did you use when you encountered the problem?

**Comment by jancborchardt** [comment]
@wurstchristoph yup, it was Chrome. :)

**Comment by DeepDiver1975** [comment]
ctrl+enter will work out of the box on forms with a submit button properly setup - there should be no need for additional js Kung-Fu

**Comment by jancborchardt** [comment]
@DeepDiver1975 yeah, that’s what I thought too.

**Comment by jancborchardt** [comment]
So for replies, we have to make `<div class="reply-message-fields">` a form. And for new messages, we need to make `<div id="new-message">` a form. @wurstchristoph do you want to check that out?

**Comment by wurstchristoph** [comment]
I can do that, but I'll try to focus on PR #505 first :)

**Comment by jancborchardt** [comment]
Yup! :)

**Comment by aidanamavi** [comment]
The hot key's Javascript wasn't compatible across all browser and operating system combinations, so I fixed that issue with PR #796. This needed to be done regardless of any HTML love.

We can bring the HTML to W3C standards with a separate issue and PR, which I would be happy to work on.

**Comment by wurstchristoph** [comment]
fixed by #796
