### ISSUE TITLE
error in the reported age of the mails for under 5 min

### ISSUE THREAD

**Issue by seal20** [owncloud/mail#492]
When a mail was received in the last 5 min (could see this for 3 and 1 min) the reported age of the mail is " in 1 min" or "in 3 min", which I think is strange and should read "1 min ago".

See attached screenshot showing "in 3 minutes" instead of "3 minutes ago".

I heard a similar "strange" strings for age of files from an user but could not reproduce it, I get "a minute ago" after a "few seconds ago" which is the correct behaviour and should be the same for mails too.

The same behaviour is also visible in French but I couldn't find the strings in Transifex to narrow the error in the code.
Does the age come  from a core library?

![problem in age reported for email](https://cloud.githubusercontent.com/assets/6326493/7179289/48388c98-e471-11e4-9b47-000321770588.png)

**Comment by jancborchardt** [comment]
@MorrisJobke didn’t you babble something about time-travel compliance? ;D

I still think that any date in the future is stupid to show and should just be cut off at »seconds ago«. We also don’t show negative file sizes.

**Comment by DeepDiver1975** [comment]
> See attached screenshot showing "in 3 minutes" instead of "3 minutes ago".

looks like one of the servers involved has no synchronized time - not really an issue we can take care of

**Comment by clementhk** [comment]
I agree that if it is from "Date" in email's header, then it should be display as is.

**Comment by jancborchardt** [comment]
Ok so not our call to fix. It’s a server issue.

**Comment by MorrisJobke** [comment]
For the record (from IRC)

```
22:44 <jancborchardt> MorrisJobke: can you check this out? https://github.com/owncloud/mail/issues/492
22:44 <jancborchardt> MorrisJobke: cause you said something about the date being »time-travel compliant« or whatever ;)
22:45 <MorrisJobke> jancborchardt: I just said, that it is possible. I have nothing more to say :P (and there is even a translation for relative dates in the future)
22:47 <jancborchardt> MorrisJobke: well but should we not block that?
22:47 <MorrisJobke> jancborchardt: why?
22:47 <jancborchardt> MorrisJobke: because it is impossible for something to happen in the future, it has to be a bug
22:47 <MorrisJobke> jancborchardt: I feel better to show that actually, than manipulating the date of a mail (even if it strange)
22:48 <jancborchardt> MorrisJobke: well, when the server is only a few minutes or seconds off then it just looks weird
22:48 <MorrisJobke> jancborchardt: showing something different then what actually is there set would be even more weird
22:48 <jancborchardt> only if the difference is a day or more
22:50 <MorrisJobke> but it maybe cause other weird bug, for example if you filter for it and you display something with "just now" but it is "in 30mins" and then the users searches for everything between now and 30 minutes ago -> message not found ... how weird is this?!?
22:50 <MorrisJobke> jancborchardt: ^
22:51 <jancborchardt> well that would have to be accounted for of course :) »now« would have to include everything in the future
22:52 → ClementHK joined (~ClementHK@119.122.120.107)
22:53 <MorrisJobke> then you see it listed as now -> 30 seconds later you search for something from 30seconds ago to 5minutes ago -> boom ... I would say it will cause huge headaches afterwards if you do something like that ...simply show what is written in the mail ...don't force the user to get some cleaned up data displayed ... that is something that would annoy me
22:53 <MorrisJobke> apps that think that cleaning up some "maybe weird" data and present this as the truth
22:54 <MorrisJobke> looks weird, but then you can say: "hey you send me an mail from the future - isn't this funny? Back to topic: fix the time on your machine"
```

**Comment by MorrisJobke** [comment]
That's just my opinion.

**Comment by seal20** [comment]
Fair enough. but I don't have control over that mail server so I will have to enjoyed time travel.
