### ISSUE TITLE
Automatic lazy loading of more messages when scrolled to the end of the list

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/mail#499]
Currently when you scroll down the message list you need to manually click »Load more …«. Instead, more mails should automatically get loaded shortly before you reach the end of the list.

Similar to pull to refresh / automatically loading newer messages: https://github.com/owncloud/mail/issues/104

**Comment by Xenopathic** [comment]
Deferring to 0.2

**Comment by ChristophWurst** [comment]
I'll give [backbone paginator] a go
