### ISSUE TITLE
oC 8.1 alpha 1 mail app doesn't load

### ISSUE THREAD

**Issue by LEDfan** [owncloud/mail#506]
Hi

I just upgraded my production oC installation to 8.1. I completely deinstalled mail (removing tables etc) and installed it again from git. 

When I try to load the app, the two GIF spinners keep spinning for ever. In the browser's console there are some error:
````
TypeError: jsondata.folders is undefined mail.js:191:10
````

Thanks!

**Comment by DeepDiver1975** [comment]
@LEDfan can you please have a look in the network tab and post the response of the request 'apps/mail/accounts/{accountId}/folders' - THX

**Comment by LEDfan** [comment]
@DeepDiver1975 that request is never made....

![selectie_030](https://cloud.githubusercontent.com/assets/2996275/7219078/4a85d21a-e68f-11e4-9c9b-c40a4ea4267b.png)

**Comment by DeepDiver1975** [comment]
can you please paste the contents of the browser locastorage '/index.php/apps/mail/accounts/{accountId}/folders' - thx

**Comment by LEDfan** [comment]
@DeepDiver1975 thanks, clearing the localstorage via `localStorage.clear()` solved it.
