### ISSUE TITLE
Mail Template

### ISSUE THREAD

**Issue by hitam4450** [owncloud/mail#523]
After selecting a mail template e.g. Notification of activities and saving it ( reply of OC8.02: saved),
then I leave the administration tab. retuning to the menu item Mail templates shows me no template selected!

What went wrong and why?

best regards, Hitam4450

**Comment by DeepDiver1975** [comment]
> mail template e.g.

the mail template editor is maintained here: https://github.com/owncloud/templateeditor

Please reopen your issue there - THX
