### ISSUE TITLE
App doesn't work in Firefox: Account creation screen is shown everytime the app is opened

### ISSUE THREAD

**Issue by zinks-** [owncloud/mail#524]
I can't use the mail app in Firefox. I've had the case with **two different owncloud servers** (8.0.2 and daily build) + mail master.

Problem has been observed with latest Iceweasel, latest official Firefox on Debian 8 and Mac OS 10.10.3.

After I set up the first account, I can see my mail.
However If I navigate away and come back to the mail app (or reload the page), I am only shown the "create new account" page.

An ajax request to `https://server/owncloud/index.php/apps/mail/accounts` is made and seems to return the proper account details, but nothing else happens after that.

It works in Chrome (and chromium) on Debian 8 and Mac OS.

**Comment by jancborchardt** [comment]
It works fine for me. :\ Can anyone else reproduce this @DeepDiver1975 @wurstchristoph @PoPoutdoor?

**Comment by jancborchardt** [comment]
And do you have any more info, like browser error log?

**Comment by zinks-** [comment]
The two instances that didn't work with Firefox yesterday evening, now work. This lead me to think this was a cache issue.
I did more tests, here is a summary of everything :

1. Clear Firefox cache.
2. Setup a new OC (daily) instance with mail (master) installed [*]
3. Add the mail account using Firefox : it **looks like** it works untill you...
4. ...navigate away and come back to the page (or just reload). Then it's back to the "Connect your mail account" screen, **although the account does appear in the "cog" settings menu**.
5. Chromium can access it just fine.
6. **Clear Firefox Cache** : Tadaaa! it works

[*] I have a vagrant setup to help you do just that very fast!  https://github.com/zinks-/vagrant-owncloud-mail

Those tests predictably reproduce the behavior.
Could this be a side effect of the caching recently introduced to the app ?

**Comment by jancborchardt** [comment]
Yeah, this sounds like it is related to the caching introduced in #501 

@zinks- can you test a commit from before the change and check if the problem also occurs?

**Comment by zinks-** [comment]
Can't make it happen at bc13fa0
But it does at the #501 merge: 423a5f6
#501 seems to blame

**Comment by jancborchardt** [comment]
Can confirm this. There’s a ` script-src http://localhorst 'unsafe-eval'` warning in the Firefox console, but not in Chrome.

@LukasReschke your job. :)

**Comment by jancborchardt** [comment]
Fixed by disabling caching for now: https://github.com/owncloud/mail/pull/536
