### ISSUE TITLE
Some strings are not displayed as translated

### ISSUE THREAD

**Issue by zinks-** [owncloud/mail#532]
Some UI strings are displayed in English regardless of the user's preference.
"New message", "Add mail account", "Check messages ..."

The translations are present in the l10n files.
I tested with French and Dutch.

**Comment by zinks-** [comment]
To make sure it wasn't a caching issue, I tested at bc13fa0, before the 501 merge. The problem existed then too.

**Comment by jancborchardt** [comment]
Hm, I can’t confirm that. Just tested with German and French and it all works nicely.

For @DeepDiver1975 it also worked well. Do you still encounter this issue @zinks-? Can anyone confirm @Gomez @wurstchristoph?

**Comment by wurstchristoph** [comment]
Tested it with German and all strings seem to be translated

**Comment by jancborchardt** [comment]
@zinks- do you have some more info? Does it still happen? Any browsers, and ownCloud 8.0 or current master?

**Comment by zinks-** [comment]
Probably something on my end, as now the issue has gone away!

**Comment by Xenopathic** [comment]
@zinks- Excellent! One more issue for 0.1 closed!
