### ISSUE TITLE
Loading messages is performance-heavy

### ISSUE THREAD

**Issue by Xenopathic** [owncloud/mail#533]
It took my Raspberry Pi 128 seconds to load my inbox. Not good. The whole time the CPU was pegged at 100% too. Using IMAPS going through Gmail (my inbox is pretty big though, 100s of mails).

**Comment by jancborchardt** [comment]
It only loads the first 20 messages though, so a big inbox shouldn’t really be slower.

But … Raspberry Pi ;)

**Comment by Xenopathic** [comment]
@jancborchardt Yeah, but for only the first 20 messages over 2 minutes is a *little* excessive...

**Comment by jancborchardt** [comment]
Yup, that’s true.

**Comment by Xenopathic** [comment]
I'll do some Blackfire benchmarks at some point, after 0.1 perhaps.

**Comment by jancborchardt** [comment]
@Xenopathic show me the benchmarks ;D

**Comment by ChristophWurst** [comment]
The performance should be better since https://github.com/owncloud/mail/pull/1486
