### ISSUE TITLE
Small glitches on setup

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/mail#537]
1. When adding a new account, the inbox is reloaded again after a few seconds.
2. Adding a new account when one already exists, a loading spinner is shown overlaying the sidebar. Rather it should be below the existing account.

**Comment by Xenopathic** [comment]
I have a feeling this will take some time to implement - it's bad UX, but it's not major -> 0.2

**Comment by jancborchardt** [comment]
Still cc'ing @Gomez @DeepDiver1975 just in case someone has a bit of free time. ;)

**Comment by jancborchardt** [comment]
The first issue:

> When adding a new account, the inbox is reloaded again after a few seconds.

is really strange and should definitely be fixed for 0.1 – it makes for a really unstable experience.

**Comment by DeepDiver1975** [comment]
> Adding a new account when one already exists, a loading spinner is shown overlaying the sidebar. Rather it should be below the existing account.

4fc341e4e751d9125fbf94834a1c78f9da4b76a7 simply disables the spinner for now - moving it has some impact I'm not willing to take at the moment

**Comment by jancborchardt** [comment]
Solved by #590
