### ISSUE TITLE
Unread messages in sent

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/mail#539]
Sometimes some of my sent messages are marked as unread (bold). Hence an unread counter also shows on the »Sent« folder, which doesn’t really make sense. When I send a message, it should be marked as read.

**Comment by wurstchristoph** [comment]
Strange, messages are flagged as seen when they are appended to the sent folder:
https://github.com/owncloud/mail/blob/a3321b7f0e431cbfd3fd45cba17ef26838eea65e/lib/mailbox.php#L306-L314

Did you send those messages with the mail app or any other client?

**Comment by jancborchardt** [comment]
Sent them with the Mail app. Definitely happens with Firefox, in the uid-validity branch. Can you test with that setup?

**Comment by wurstchristoph** [comment]
Tested and reproduced. @DeepDiver1975 removed it here https://github.com/owncloud/mail/commit/0918ec30ca30b4eff9d4371e5c2328142bd75660#diff-ef08cb2c2dca0d6f4b3094d65f79ea93L313

There is no flag set now:
https://github.com/owncloud/mail/blob/uid-validity/lib/mailbox.php#L316-L327

I'm pretty sure we should add it back ;-)
