### ISSUE TITLE
Show draft count

### ISSUE THREAD

**Issue by ChristophWurst** [owncloud/mail#540]
Evolution shows a draft counter (similar to the unread message counter):
![](https://cloud.githubusercontent.com/assets/1374172/7332503/4a39c412-eb42-11e4-87f8-f7d5a6135f47.png)

I think this is great as you are reminded that there are messages left that have not been sent :)

**Comment by jancborchardt** [comment]
Yup, we should have that! :)

**Comment by tahaalibra** [comment]
currently...it gives the count for "unseen"...should this be updated to use "total"

**Comment by tahaalibra** [comment]
or should there be both unseen and total..

**Comment by ChristophWurst** [comment]
It should show the total number of messages, seen/unseen makes no sense for drafts imho.

**Comment by jancborchardt** [comment]
Yeah, total number should be shown.
