### ISSUE TITLE
Unread counter decremented if message gets starred/unstarred

### ISSUE THREAD

**Issue by wurstchristoph** [owncloud/mail#542]
If I change the starred flag on a message the unread counter in the folder list is decremented each time

**Comment by zinks-** [comment]
I think `thisModel.get('flags').set('flagged', !starred);`
https://github.com/owncloud/mail/blob/master/js/views/message.js#L70
triggers `this.collection.on('change:flags', this.changeFlags, this);` https://github.com/owncloud/mail/blob/master/js/views/message.js#L157
and
```
changeFlags: function(model) {
    var unseen = model.get('flags').get('unseen');
    var prevUnseen = model._previousAttributes.flags.get('unseen');
    if (unseen === prevUnseen) {
        this.trigger('change:unseen', model, unseen);
    }
},

```
https://github.com/owncloud/mail/blob/master/js/views/message.js#L171

Also sometimes, in the last snippet above, this error occurs :
```
TypeError: model._previousAttributes.flags.get is not a function
http://localhost:8120/owncloud/apps/mail/js/views/message.js?v=87e9b948428e2e5a3ea164593fc50d0d
Line 173

```

**Comment by jancborchardt** [comment]
Fixed by https://github.com/owncloud/mail/pull/636 thanks to @irgendwie! :)
