### ISSUE TITLE
Style the 'mail sent' message

### ISSUE THREAD

**Issue by zinks-** [owncloud/mail#546]
The notification that the message has been successfully sent can easily be missed by users, because it's plain and disappears after a few seconds.

**Comment by jancborchardt** [comment]
Do you have any suggestion? Would a static »Message sent!« notification be better, which doesn’t vanish?
For replies ideally of course we have threading #21 and the answer is directly appended. But for new messages we can’t really do that.

**Comment by jancborchardt** [comment]
This was fixed by https://github.com/owncloud/mail/pull/584, where we use the standard yellow ownCloud notification up top.
