### ISSUE TITLE
Show only spinners... Stuck there

### ISSUE THREAD

**Issue by yeupou** [owncloud/mail#561]
Hello,

I'm giving the mail app a try but I cannot get past the spinners. Nothing shows up either if I click on the configure wheel.

Dependencies and all show be fine and I'm using owncloud 7 as including in Debian stable.

Latest log message is
{"app":"webdav","message":"Sabre\\DAV\\Exception\\MethodNotAllowed: The resource you tried to create already exists","level":4,"time":"2015-05-01T15:16:29+00:00"}
but I dont know if it has any relevance.

**Comment by DeepDiver1975** [comment]
> Dependencies and all show be fine and I'm using owncloud 7 as including in Debian stable.

the mail app requires ownCloud 8 at least

**Comment by DeepDiver1975** [comment]
https://github.com/owncloud/mail/blob/master/appinfo/info.xml#L14

**Comment by yeupou** [comment]
Ok, it may be worth to update the main description of the app then "An email app for ownCloud (minimum version 7)." https://github.com/owncloud/mail

**Comment by jancborchardt** [comment]
@yeupou thank you! Corrected it https://github.com/owncloud/mail/blob/master/README.md

Please let us know of any other issues you encounter. You are also very welcome in our IRC channel #owncloud-mail. :)
