### ISSUE TITLE
Automatically reduce size of textarea again after sending

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/mail#562]
Currently when you wrote a long answer to an email, the textarea is very tall (as it should be). However after successfully sending it should collapse to the default height again.

I tried that by calling `$('.reply-message-body').autosize();` after the value of the textarea is emptied but it doesn’t really work. :\

Any ideas @owncloud/designers?

**Comment by clementhk** [comment]
https://github.com/owncloud/mail/blob/4ee3a386b3004fe345cbb05b4d2fc60815c19761/js/jquery.autosize.js#L248

**Comment by jancborchardt** [comment]
@clementhk how can I call that function outside of the library though?

`$('textarea').on('autosize.resize', adjust);` does not work.

**Comment by jancborchardt** [comment]
Wanted to move to the new autosize version but that comes with quite some issues. Postponing to 0.2

**Comment by clementhk** [comment]
Doesn't it look a bit like we need to call `$('textarea').autosize.resize;` after we use js to empty textarea?

**Comment by clementhk** [comment]
Anyways I think it'll be good to upgrade autosize.

**Comment by jancborchardt** [comment]
@clementhk well, try:
```
$('.reply-message-body').val('');
$('.reply-message-body').autosize.resize;
```
… nothing will happen.

As said above, we will only update to the new  autosize with 0.2 – I just tried it and there are some glitches.

**Comment by clementhk** [comment]
Try this.

```
$('.reply-message-body').val('');
$('.reply-message-body').trigger('autosize.resize');
```

**Comment by jancborchardt** [comment]
@clementhk that was it, thank you! Please review https://github.com/owncloud/mail/pull/622
