### ISSUE TITLE
Autofill of the email settings form

### ISSUE THREAD

**Issue by colmoneill** [owncloud/mail#566]
These were the values that autofilled when adding an account to the mail app.

![screenshot from 2015-05-01 22 35 44](https://cloud.githubusercontent.com/assets/2122318/7438664/2baf8e98-f068-11e4-987c-f8bc1b79ad57.png)

I had to go and delete the autofilled values to find out what the form actually wanted, and it filled in based on my oC account, which are not the same as my external mail settings.

**Comment by jancborchardt** [comment]
So in this case the full name (first field) is correctly filled. The problem is that the email address and password are prefilled with the _ownCloud username and password_.

Is there any way we can prevent this? I heard you did something like that for the LDAP app @blizzz? cc @owncloud/designers

**Comment by blizzz** [comment]
If you totally want to avoid auto-fill, then this is how I did it: 

Template: https://github.com/owncloud/core/blob/c6151053ba97eb474a4b3f5249e3a0c99ad05d95/apps/user_ldap/templates/part.wizard-server.php#L1

CSS: https://github.com/owncloud/core/blob/master/apps/user_ldap/css/settings.css#L207

**Comment by Xenopathic** [comment]
@blizzz WOW, that's a hack and a half! :see_no_evil:

**Comment by blizzz** [comment]
seems to be the only thing that works so far and is not overly complicated. 
Yet.

**Comment by jancborchardt** [comment]
Fix at https://github.com/owncloud/mail/pull/601, please review!
