### ISSUE TITLE
Centering the form

### ISSUE THREAD

**Issue by colmoneill** [owncloud/mail#567]
Adding in a new mail account, the form seems to be off center? 

![screenshot from 2015-05-01 22 35 44](https://cloud.githubusercontent.com/assets/2122318/7438675/5685e81a-f068-11e4-9188-842f09e445b2.png)

**Comment by jancborchardt** [comment]
Yes it is. And I expect you to submit a pull request to fix it. :rocket: :D

**Comment by colmoneill** [comment]
I submitted a pull request. Details in the request.

**Comment by ChristophWurst** [comment]
#580 has been merged -> close
