### ISSUE TITLE
Add BCC in reply form

### ISSUE THREAD

**Issue by colmoneill** [owncloud/mail#568]
The reply form at the end of a displayed mail has a carbon copy field, but not a blackened cc field.

**Comment by jancborchardt** [comment]
Right, good call. We must’ve forgot. :D

**Comment by jancborchardt** [comment]
This is also blocked by the rework of the message / reply fields regarding adding attachments from the computer: https://github.com/owncloud/mail/issues/462 – moving to 0.3 also because it’s less important than the other stuff.

**Comment by ChristophWurst** [comment]
fixed with PR #819
