### ISSUE TITLE
Automatically filter mailing list messages into labels

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/mail#57]
(This feature is probably not something for the near future, just writing it down to not forget. From discussions with @garrett & @hbons.)

Mailing lists should not come through the inbox, not even on first setup. There should automatically be a filter and label set up for each mailing list where messages come in from.

Think similar to the new Gmail inbox where they automatically filter Social, Promotions, Updates and Forums out of the primary inbox.

**Comment by ChristophWurst** [comment]
I'm closing in doubt of a 'phase 2'. @jancborchardt #564 will help to organize your inbox ;-)
