### ISSUE TITLE
Confusion between Mail and Contacts app

### ISSUE THREAD

**Issue by colmoneill** [owncloud/mail#570]
Because of the usage of the 'contact monograms' in the inbox list, I thought that 'starring' was going to place that contact into my favourite contacts, not add it to my favourite emails.

![screenshot from 2015-05-01 23 31 31](https://cloud.githubusercontent.com/assets/2122318/7438887/b1e6674e-f06c-11e4-870b-81feec45eb41.png)

I guess this is more a tribute to the platform than anything else, but it's because I'm so used to seeing my contacts listed with their initials this way, I thought for a few seconds that it would interact with the Contacts app.

Just to be clear, I'm definitively not looking to be able to favourite a contact from within Mail, I'm just pointing out (my &) the potential confusion.

Should the single email interaction tools —favourite, delete, reply, reply all, etc— not be moved to the open email panel?

**Comment by jancborchardt** [comment]
'tis fixed!
