### ISSUE TITLE
iframe needs to be resized on parent window resize

### ISSUE THREAD

**Issue by Xenopathic** [owncloud/mail#573]
When the browser window gets resized, the width of the iframe changes, reflowing the content of the message and causing the height to change. However, that height doesn't get updated, so a second scrollbar can show up inside the iframe. We should run a handler on window resize that updates the height property of the iframe, and probably some CSS to prevent the scrollbar showing up between updates.

cc @jancborchardt

**Comment by jancborchardt** [comment]
I’d say this is something for 0.2

**Comment by aidanamavi** [comment]
I can't seem to replicate these issues with the latest masters of Mail and ownCloud on both Firefox and Chrome. When the browser window is resized, the iFrame's height is always correct; if necessary, the iFrame horizontal scroll bar will adjust.

With this current fix, there is no noticeable change with Firefox; however, with Chrome the javascript will add 20 height pixels every time the browser's window is adjusted, which leaves large amounts of white space at the end of the iFrame content and before the horizontal iFrame scroll bar.
:-1:
