### ISSUE TITLE
Unused variable

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/mail#578]
see https://scrutinizer-ci.com/g/owncloud/mail/inspections/494787a4-e0ec-4cce-8d94-12fa7d86fdaa/issues/files/lib/account.php?status=new&orderField=path&order=asc#inspectioncomment-780081936

**Comment by Xenopathic** [comment]
Removing the milestone - this can be fixed (along with other similar issues) whenever

**Comment by ChristophWurst** [comment]
Broken link. I assume that has been fixed already.
