### ISSUE TITLE
Loaded message replaces »New message« form

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/mail#591]
1. Open a folder (or initial load)
2. Click the »New message« button before everything loaded
3. The new message dialog will show
4. Will swiftly get replaced by the topmost message in the folder which is loaded
5. AND the new message button is disabled

This shouldn’t happen. The last user action/click should always get the upper hand. In that case the message list should show the messages of the folder, but the right content area should show the new message form.

@DeepDiver1975

**Comment by DeepDiver1975** [comment]
this is actually not that easy - we have to remove the composer in case the user switches the folder.

The same happens in the described scenario above - I see no way to differentiate the two calls.

**Comment by DeepDiver1975** [comment]
maybe we simply enable the new message button after the initial load?

**Comment by DeepDiver1975** [comment]
AH - insert evil grin meme ...

**Comment by jancborchardt** [comment]
Solved by #594
