### ISSUE TITLE
'Check mail' button label changes

### ISSUE THREAD

**Issue by wurstchristoph** [owncloud/mail#595]
After the app is loaded the button says 'Check messages ...'
![](https://cloud.githubusercontent.com/assets/1374172/7463496/40d0160e-f2ba-11e4-9fe1-9d27ebb85bbf.png)

However, after clicking it once, it says 'Check mail'
![](https://cloud.githubusercontent.com/assets/1374172/7463497/40d1b73e-f2ba-11e4-8393-fc22d1e8fd33.png)

Not a critical bug but some consistency would be great ;-)

**Comment by jancborchardt** [comment]
Good catch! Fix at https://github.com/owncloud/mail/pull/598 :)
