### ISSUE TITLE
Store reply drafts on IMAP server

### ISSUE THREAD

**Issue by ChristophWurst** [owncloud/mail#602]
Currently reply message are simply cached in local storage. For best integration with other mail clients, those draft should also be saved to IMAP

**Comment by jancborchardt** [comment]
@wurstchristoph @irgendwie someone of you want to work on this for 0.2? It would indeed be good to finish up the draft stuff.

**Comment by ChristophWurst** [comment]
@jancborchardt I'll try to finish it in 0.2. First step: #819

**Comment by ChristophWurst** [comment]
fixed with PR #819
