### ISSUE TITLE
Attach files via ownCloud public link instead of as real attachment

### ISSUE THREAD

**Issue by Xenopathic** [owncloud/mail#608]
For large files, sending via email is highly inefficient and often denied by server configuration. Similar to Thunderbird's File Link, the user should be able to (with one click) publicly share a file in their ownCloud and attach that file as a link to the email.

**Comment by jancborchardt** [comment]
Homie, we thought of everything already ;) https://github.com/owncloud/mail/issues/251

So yeah, that would be really cool, also for security reasons to keep the files on one’s own space. If you’re up for it, we can have it in 0.2 :)

**Comment by Xenopathic** [comment]
Hmm, I must have missed that (I *did* look for duplicates!)

**Comment by jancborchardt** [comment]
Well at least it means we’re on the same page – and we have a volunteer for the implementation. :tada: :D

**Comment by Xenopathic** [comment]
*cough* *splutter* :worried:
