### ISSUE TITLE
Subfolders don't load

### ISSUE THREAD

**Issue by zinks-** [owncloud/mail#611]
Clicking on a subfolder does not show it's content, the spinners stay on screen.

the error occurrs in this code (**folder.js**) :
```js
	updateTitle: function() {

		var activeAccount = Mail.State.currentAccountId;
		var activeFolder = Mail.State.currentFolderId;
		activeAccount = this.collection.get(activeAccount);
		activeFolder = activeAccount.get('folders').get(activeFolder);
		var unread = activeFolder.get('unseen');
```
``TypeError: activeFolder is undefined``

The Json message list is retrieved successfully, though.

**Comment by irgendwie** [comment]
Having a subfolder in the inbox even leads to only one spinner (in the middle) and no rendering (only the navigation with account settings appears) for me.
