### ISSUE TITLE
'Delete permanently' tipsy not shown for next message

### ISSUE THREAD

**Issue by wurstchristoph** [owncloud/mail#614]
The tipsy should be shown for the next message in the message list if one clicks the trash icon.

Steps to reproduce
- go to trash folder
- click  trash icon of a message (not the first one)
- watch how it vanishes and the next one comes up
- the next messages tipsy should be shown, even if you don't move your cursor

There is no issue when deleting the first message in the list, the next tipsy is shown immediately.

tipsy was introduced here https://github.com/owncloud/mail/pull/574

**Comment by jancborchardt** [comment]
@irgendwie can you check that out? :)
