### ISSUE TITLE
Accounts don't load, Horde log says "NO Mailbox does not exist, or must be subscribed to."

### ISSUE THREAD

**Issue by sndrsk** [owncloud/mail#617]
This is happening on a Dreamhost shared server with a Dreamhost-hosted IMAP e-mail account.

### Steps to reproduce
1. Added e-mail account

### Expected behaviour
Mail app should load

### Actual behaviour
Yellow banner that says "error while loading the selected account" and account does not load

### Server configuration
**Operating system**: Debian wheezy/sid

**Database:** SQL

**PHP version:** 5.4

**ownCloud version:** (see ownCloud admin page) 8.0.3

**Updated from an older ownCloud or fresh install:** Updated

**List of activated apps:** Only default apps, plus mail

**The content of config/config.php:** No custom parameters

**Are you using external storage, if yes which one:** Dropbox

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

#### Web server error log
No errors in server log

#### ownCloud log (data/owncloud.log)
{"reqId":"0a2efb968237a9fdc594b8b0d0d295a9","remoteAddr":"173.29.212.66","app":"index","message":"Exception: {\"Message\":\"IMAP error reported by server.\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/user\\\/owncloud.domain.tld\\\/apps\\\/mail\\\/vendor\\\/pear-pear.horde.org\\\/Horde_Imap_Client\\\/Horde\\\/Imap\\\/Client\\\/Socket.php(4208): Horde_Imap_Client_Socket->_getLine(Object(Horde_Imap_Client_Interaction_Pipeline))\\n#1 \\\/home\\\/user\\\/owncloud.domain.tld\\\/apps\\\/mail\\\/vendor\\\/pear-pear.horde.org\\\/Horde_Imap_Client\\\/Horde\\\/Imap\\\/Client\\\/Socket.php(4136): Horde_Imap_Client_Socket->_sendCmdChunk(Object(Horde_Imap_Client_Interaction_Pipeline), Array)\\n#2 \\\/home\\\/user\\\/owncloud.domain.tld\\\/apps\\\/mail\\\/vendor\\\/pear-pear.horde.org\\\/Horde_Imap_Client\\\/Horde\\\/Imap\\\/Client\\\/Socket.php(1656): Horde_Imap_Client_Socket->_sendCmd(Object(Horde_Imap_Client_Interaction_Pipeline))\\n#3 \\\/home\\\/user\\\/owncloud.domain.tld\\\/apps\\\/mail\\\/vendor\\\/pear-pear.horde.org\\\/Horde_Imap_Client\\\/Horde\\\/Imap\\\/Client\\\/Base.php(1724): Horde_Imap_Client_Socket->_status(Array, 63)\\n#4 \\\/home\\\/user\\\/owncloud.domain.tld\\\/apps\\\/mail\\\/lib\\\/account.php(216): Horde_Imap_Client_Base->status(Array)\\n#5 \\\/home\\\/user\\\/owncloud.domain.tld\\\/apps\\\/mail\\\/lib\\\/controller\\\/folderscontroller.php(62): OCA\\\\Mail\\\\Account->getListArray()\\n#6 [internal function]: OCA\\\\Mail\\\\Controller\\\\FoldersController->index()\\n#7 \\\/home\\\/user\\\/owncloud.domain.tld\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(158): call_user_func_array(Array, Array)\\n#8 \\\/home\\\/user\\\/owncloud.domain.tld\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(86): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Mail\\\\Controller\\\\FoldersController), 'index')\\n#9 \\\/home\\\/user\\\/owncloud.domain.tld\\\/lib\\\/private\\\/appframework\\\/app.php(97): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Mail\\\\Controller\\\\FoldersController), 'index')\\n#10 \\\/home\\\/user\\\/owncloud.domain.tld\\\/lib\\\/private\\\/appframework\\\/routing\\\/routeactionhandler.php(44): OC\\\\AppFramework\\\\App::main('FoldersControll...', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#11 [internal function]: OC\\\\AppFramework\\\\routing\\\\RouteActionHandler->__invoke(Array)\\n#12 \\\/home\\\/user\\\/owncloud.domain.tld\\\/lib\\\/private\\\/route\\\/router.php(250): call_user_func(Object(OC\\\\AppFramework\\\\routing\\\\RouteActionHandler), Array)\\n#13 \\\/home\\\/user\\\/owncloud.domain.tld\\\/lib\\\/base.php(782): OC\\\\Route\\\\Router->match('\\\/apps\\\/mail\\\/acco...')\\n#14 \\\/home\\\/user\\\/owncloud.domain.tld\\\/index.php(36): OC::handleRequest()\\n#15 {main}\",\"File\":\"\\\/home\\\/user\\\/owncloud.domain.tld\\\/apps\\\/mail\\\/vendor\\\/pear-pear.horde.org\\\/Horde_Imap_Client\\\/Horde\\\/Imap\\\/Client\\\/Socket.php\",\"Line\":4496}","level":4,"time":"2015-05-05T23:29:55+00:00"}

#### Horde log
------------------------------
>> Tue, 05 May 2015 23:29:54 +0000
>> Connection to: imap://mail.domain.tld:993/
>> Server connection took 0.0885 seconds.
S: * OK [CAPABILITY IMAP4rev1 UIDPLUS CHILDREN NAMESPACE THREAD=ORDEREDSUBJECT THREAD=REFERENCES SORT QUOTA IDLE AUTH=PLAIN] Courier-IMAP ready. Copyright 1998-2008 Double Precision, Inc.  See COPYING for distribution information.
C: 1 [INITIAL CLIENT RESPONSE (username: user@domain.tld)]
S: +
C: a2V2aW5Ac2FuZGVycy5pbwBrZXZpbkBzYW5kZXJzLmlvAHc1OWozMURHTkNQejFNblFyTFdKMmdBQQ==
S: 1 OK LOGIN Ok.
>> Command 1 took 0.0221 seconds.
C: 2 CAPABILITY
S: * CAPABILITY IMAP4rev1 UIDPLUS CHILDREN NAMESPACE THREAD=ORDEREDSUBJECT THREAD=REFERENCES SORT QUOTA IDLE AUTH=PLAIN
S: 2 OK CAPABILITY completed
>> Command 2 took 0.0024 seconds.
C: 3 LIST "" *
S: * LIST (\HasNoChildren) "." "INBOX.Stuff to keep.Software and licenses"
S: * LIST (\HasNoChildren) "." "INBOX.Stuff to keep.Work"
S: * LIST (\HasChildren) "." "INBOX.Stuff to keep"
S: * LIST (\HasNoChildren) "." "INBOX.Stuff to keep.Accounts"
S: * LIST (\HasNoChildren) "." "INBOX.Radio.Weather"
S: * LIST (\HasNoChildren) "." "INBOX.Radio.Club.Hamfest"
S: * LIST (\HasNoChildren) "." "INBOX.Radio.State.Media hits"
S: * LIST (\HasChildren) "." "INBOX.Radio.Club"
S: * LIST (\HasChildren) "." "INBOX.Radio.State"
S: * LIST (\HasChildren) "." "INBOX.Radio"
S: * LIST (\HasNoChildren) "." "INBOX.Trash"
S: * LIST (\HasNoChildren) "." "INBOX.Junk"
S: * LIST (\HasNoChildren) "." "INBOX.Sent"
S: * LIST (\HasNoChildren) "." "INBOX.Drafts"
S: * LIST (\HasNoChildren) "." "INBOX.old-messages"
S: * LIST (\Marked \HasChildren) "." "INBOX"
S: 3 OK LIST completed
>> Command 3 took 0.0196 seconds.
C: 4 STATUS INBOX (MESSAGES RECENT UIDNEXT UIDVALIDITY UNSEEN)
C: 5 STATUS Drafts (MESSAGES RECENT UIDNEXT UIDVALIDITY UNSEEN)
C: 6 STATUS Sent (MESSAGES RECENT UIDNEXT UIDVALIDITY UNSEEN)
C: 7 STATUS Junk (MESSAGES RECENT UIDNEXT UIDVALIDITY UNSEEN)
C: 8 STATUS Trash (MESSAGES RECENT UIDNEXT UIDVALIDITY UNSEEN)
C: 9 STATUS Radio (MESSAGES RECENT UIDNEXT UIDVALIDITY UNSEEN)
C: 10 STATUS "Radio.State" (MESSAGES RECENT UIDNEXT UIDVALIDITY UNSEEN)
C: 11 STATUS "Radio.State.Media hits" (MESSAGES RECENT UIDNEXT UIDVALIDITY UNSEEN)
C: 12 STATUS Radio.Club (MESSAGES RECENT UIDNEXT UIDVALIDITY UNSEEN)
C: 13 STATUS Radio.Club.Hamfest (MESSAGES RECENT UIDNEXT UIDVALIDITY UNSEEN)
C: 14 STATUS Radio.MISA (MESSAGES RECENT UIDNEXT UIDVALIDITY UNSEEN)
C: 15 STATUS old-messages (MESSAGES RECENT UIDNEXT UIDVALIDITY UNSEEN)
C: 16 STATUS "Stuff to keep" (MESSAGES RECENT UIDNEXT UIDVALIDITY UNSEEN)
C: 17 STATUS "Stuff to keep.Accounts" (MESSAGES RECENT UIDNEXT UIDVALIDITY UNSEEN)
C: 18 STATUS "Stuff to keep.Software and licenses" (MESSAGES RECENT UIDNEXT UIDVALIDITY UNSEEN)
C: 19 STATUS "Stuff to keep.Work" (MESSAGES RECENT UIDNEXT UIDVALIDITY UNSEEN)
S: * STATUS "INBOX" (MESSAGES 6 RECENT 0 UIDNEXT 2487 UIDVALIDITY 1419816080 UNSEEN 4)
S: 4 OK STATUS Completed.
>> Command 4 took 0.0163 seconds.
S: 5 NO Mailbox does not exist, or must be subscribed to.
>> Command 5 took 0.0162 seconds.
S: 6 NO Mailbox does not exist, or must be subscribed to.
>> Command 6 took 0.0193 seconds.
S: 7 NO Mailbox does not exist, or must be subscribed to.
>> Command 7 took 0.0196 seconds.
S: 8 NO Mailbox does not exist, or must be subscribed to.
>> Command 8 took 0.0199 seconds.
S: 9 NO Mailbox does not exist, or must be subscribed to.
>> Command 9 took 0.0201 seconds.
S: 10 NO Mailbox does not exist, or must be subscribed to.
>> Command 10 took 0.0203 seconds.
S: 11 NO Mailbox does not exist, or must be subscribed to.
>> Command 11 took 0.0196 seconds.
S: 12 NO Mailbox does not exist, or must be subscribed to.
>> Command 12 took 0.0196 seconds.
S: 13 NO Mailbox does not exist, or must be subscribed to.
>> Command 13 took 0.0198 seconds.
S: 14 NO Mailbox does not exist, or must be subscribed to.
>> Command 14 took 0.0199 seconds.
S: 15 NO Mailbox does not exist, or must be subscribed to.
>> Command 15 took 0.0201 seconds.
S: 16 NO Mailbox does not exist, or must be subscribed to.
>> Command 16 took 0.0202 seconds.
S: 17 NO Mailbox does not exist, or must be subscribed to.
>> Command 17 took 0.0204 seconds.
S: 18 NO Mailbox does not exist, or must be subscribed to.
>> Command 18 took 0.0204 seconds.
S: 19 NO Mailbox does not exist, or must be subscribed to.
>> Command 19 took 0.0505 seconds.
C: 20 LOGOUT
S: * BYE Courier-IMAP server shutting down
S: 20 OK LOGOUT completed
>> Command 20 took 0.0019 seconds.

**Comment by jancborchardt** [comment]
@DeepDiver1975 @zinks- @wurstchristoph any idea?

**Comment by Xenopathic** [comment]
Looks like we are getting `INBOX.Trash` returned from the LIST, but for some reason are using `Trash` without the sub-folder structure.

**Comment by clementhk** [comment]
https://github.com/owncloud/mail/blob/master/lib/mailbox.php#L165
This could be why...
There is a horde bug making folderID inconsistent, that's why we have this, but maybe I should dig into it sometime to fix it upstream for good..

**Comment by clementhk** [comment]
I think you can remove the part that is removing `INBOX` prefix from `getFolderId() `, we only have problem when creating mailbox. We could make a hack to make folderId consistent for now.

**Comment by jancborchardt** [comment]
@DeepDiver1975 @clementhk @Xenopathic 0.1 or 0.2?

**Comment by clementhk** [comment]
Unhack `getFolderId()` and test it, if it works then 0.1.

**Comment by clementhk** [comment]
```
	public function getFolderId() {
		$folderId = $this->mailBox->utf8;
		if (strlen($folderId) > 6 && strpos($folderId, 'INBOX' . $this->delimiter) === 0) {
			return substr($folderId, 6);
		}
		return $folderId;
	}
```

-->


```
	public function getFolderId() {
		return $this->mailBox->utf8;
	}
```

**Comment by jancborchardt** [comment]
@Xenopathic or @DeepDiver1975 can you do that?

**Comment by sndrsk** [comment]
I just implemented that fix from @clementhk on my server and it works! oC and horde logs both look good.

**Comment by jancborchardt** [comment]
@Xenopathic @DeepDiver1975 can you also test this and then submit a pull request? @clementhk is away til later.

**Comment by clementhk** [comment]
There are further works in upstream horde but here this can be closed.
