### ISSUE TITLE
cc is not filling in from draft

### ISSUE THREAD

**Issue by clementhk** [owncloud/mail#619]
#613 tried to fix cc problem but it didn't fix the whole thing.
I think `value="{{replyCc}}"` was introduced from filling in cc from draft, but the problem is that `replyCc` is not a list. I think to fix it down to the bottom we need to make draft in local storage to store CC in list, then use is directly, or parse what is stored to make it a list, then fill it in.

**Comment by jancborchardt** [comment]
@wurstchristoph :)

**Comment by jancborchardt** [comment]
I’m moving this to 0.2 for now. @wurstchristoph if you want to fix this before though please do. :)
