### ISSUE TITLE
Adding attachment with no file selected results in phantom attachment

### ISSUE THREAD

**Issue by Xenopathic** [owncloud/mail#620]
~~Clicking on 'Add attachment from Files' brings up the dialog, but then clicking 'Choose' just does nothing and an error is printed to the JS log: `TypeError: this.$filePicker is null`~~

Going to add an attachment, but not selecting anything and clicking Choose results in a phantom attachment appearing, and an error appearing in the JS log: `TypeError: this.$filePicker is null`

Occurs on oC master and oC 8.0.3

**Comment by jancborchardt** [comment]
It does work for me with no problems.

**Comment by jancborchardt** [comment]
Closing in favor of core issue https://github.com/owncloud/core/issues/16106 (disable the Choose button until a file is chosen)
