### ISSUE TITLE
Need a spinner on attachment chooser

### ISSUE THREAD

**Issue by Xenopathic** [owncloud/mail#621]
When adding an attachment, the file chooser dialog is initially displayed empty while the file list is fetched. During this time the user may think something is broken, or that they must click on Choose to choose a file (I certainly did... ref #620). We should have a spinner indicating the content is loading.

cc @jancborchardt

**Comment by jancborchardt** [comment]
@Xenopathic this is a core issue though with the filepicker. We didn’t code that in the Mail app. :) Can you open it in core instead?

**Comment by jancborchardt** [comment]
Closing this in favor of core issue https://github.com/owncloud/core/issues/16105
