### ISSUE TITLE
Integrate account settings better, move from settings section directly to sidebar

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/mail#625]
I’m thinking of something like this:
![capture du 2015-05-06 12 56 42](https://cloud.githubusercontent.com/assets/925062/7491980/636c02dc-f3ef-11e4-9079-68c208ec5b59.png)

What do you think @DeepDiver1975 @Xenopathic @wurstchristoph @owncloud/designers?

I’m definitely sure that the account settings (deletion, modification etc) should go directly there via the dot-dot-dot icon. I’m not entirely sure the »Add new mail account« function needs to go there as it’s not used that often.

**Comment by Xenopathic** [comment]
Well, 'Add new mail account' should be where it is at the moment - that much makes sense. I think this proposal could be quite good though, keeping everything in one place. :+1: from me

**Comment by enoch85** [comment]
Why move away from how ownCloud handles settings in all the other apps/core? It´s better, but could be a bit confusing. 

What about a whole new settings page? I guess there will be added more settings in the future, right?

**Comment by jancborchardt** [comment]
Well, we won't be able to cram everything in there anyway. Like signatures and aliases etc. So we might need to rethink that in this case.

Also, when you look at the news app, folder renaming and deletion are handled in the sidebar directly as well. To disconnect that (like we have in Mail right now) would be arbitrary.
