### ISSUE TITLE
Having a subfolder in Inbox leads to "Error while loading the selected account."

### ISSUE THREAD

**Issue by irgendwie** [owncloud/mail#626]
![pic](http://i.imgur.com/2BWglym.png)

**What doesn't work:** Having subfolders in Inbox
**What works:** Having subfolders everywhere else instead of Inbox
**Mail-Provider:** Strato.de
**Owncloud-Log:** `{"reqId":"0d8796a92c585d32c9551fa8da2ec226","remoteAddr":"::1","app":"index","message":"Exception: {\"Message\":\"IMAP error reported by server.\",\"Code\":0,\"Trace\":\"#0 \\\/opt\\\/lampp\\\/htdocs\\\/oc\\\/apps\\\/mail\\\/vendor\\\/pear-pear.horde.org\\\/Horde_Imap_Client\\\/Horde\\\/Imap\\\/Client\\\/Socket.php(4208): Horde_Imap_Client_Socket->_getLine(Object(Horde_Imap_Client_Interaction_Pipeline))\\n#1 \\\/opt\\\/lampp\\\/htdocs\\\/oc\\\/apps\\\/mail\\\/vendor\\\/pear-pear.horde.org\\\/Horde_Imap_Client\\\/Horde\\\/Imap\\\/Client\\\/Socket.php(4136): Horde_Imap_Client_Socket->_sendCmdChunk(Object(Horde_Imap_Client_Interaction_Pipeline), Array)\\n#2 \\\/opt\\\/lampp\\\/htdocs\\\/oc\\\/apps\\\/mail\\\/vendor\\\/pear-pear.horde.org\\\/Horde_Imap_Client\\\/Horde\\\/Imap\\\/Client\\\/Socket.php(1656): Horde_Imap_Client_Socket->_sendCmd(Object(Horde_Imap_Client_Interaction_Pipeline))\\n#3 \\\/opt\\\/lampp\\\/htdocs\\\/oc\\\/apps\\\/mail\\\/vendor\\\/pear-pear.horde.org\\\/Horde_Imap_Client\\\/Horde\\\/Imap\\\/Client\\\/Base.php(1724): Horde_Imap_Client_Socket->_status(Array, 63)\\n#4 \\\/opt\\\/lampp\\\/htdocs\\\/oc\\\/apps\\\/mail\\\/lib\\\/account.php(216): Horde_Imap_Client_Base->status(Array)\\n#5 \\\/opt\\\/lampp\\\/htdocs\\\/oc\\\/apps\\\/mail\\\/lib\\\/controller\\\/folderscontroller.php(62): OCA\\\\Mail\\\\Account->getListArray()\\n#6 [internal function]: OCA\\\\Mail\\\\Controller\\\\FoldersController->index()\\n#7 \\\/opt\\\/lampp\\\/htdocs\\\/oc\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(158): call_user_func_array(Array, Array)\\n#8 \\\/opt\\\/lampp\\\/htdocs\\\/oc\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(86): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Mail\\\\Controller\\\\FoldersController), 'index')\\n#9 \\\/opt\\\/lampp\\\/htdocs\\\/oc\\\/lib\\\/private\\\/appframework\\\/app.php(97): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Mail\\\\Controller\\\\FoldersController), 'index')\\n#10 \\\/opt\\\/lampp\\\/htdocs\\\/oc\\\/lib\\\/private\\\/appframework\\\/routing\\\/routeactionhandler.php(44): OC\\\\AppFramework\\\\App::main('FoldersControll...', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#11 [internal function]: OC\\\\AppFramework\\\\routing\\\\RouteActionHandler->__invoke(Array)\\n#12 \\\/opt\\\/lampp\\\/htdocs\\\/oc\\\/lib\\\/private\\\/route\\\/router.php(250): call_user_func(Object(OC\\\\AppFramework\\\\routing\\\\RouteActionHandler), Array)\\n#13 \\\/opt\\\/lampp\\\/htdocs\\\/oc\\\/lib\\\/base.php(767): OC\\\\Route\\\\Router->match('\\\/apps\\\/mail\\\/acco...')\\n#14 \\\/opt\\\/lampp\\\/htdocs\\\/oc\\\/index.php(36): OC::handleRequest()\\n#15 {main}\",\"File\":\"\\\/opt\\\/lampp\\\/htdocs\\\/oc\\\/apps\\\/mail\\\/vendor\\\/pear-pear.horde.org\\\/Horde_Imap_Client\\\/Horde\\\/Imap\\\/Client\\\/Socket.php\",\"Line\":4496}","level":4,"time":"2015-05-06T11:09:19+00:00","method":"GET","url":"\/oc\/index.php\/apps\/mail\/accounts\/2\/folders"}`

**Comment by jancborchardt** [comment]
@irgendwie can you also test this with other mail providers such as Gmail? Is the same problem present there?

**Comment by LEDfan** [comment]
I have the same problem (#627) with zoho.com as mail provider. Note that some time ago (one week?) it wokred.

**Comment by Xenopathic** [comment]
This is a recurrence of #617

**Comment by Aesculapius** [comment]
I'm having the same with a courier-imap server. Used to work perfectly before, but since upgrading to 8.1.1, it fails. I've re-entered account details several times...

**Comment by jancborchardt** [comment]
@Aesculapius can you please open a separate issue and fill out the issue template so we have the proper data?

**Comment by okias** [comment]
@Aesculapius same issue. Upgraded to 8.1.x and installed Mail and getting this error. Also courier-imap.
