### ISSUE TITLE
Attachment download cannot be opened by the browser properly ....

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/mail#628]
When downloading an attachment Firefox always wants to open the attachment with VLC.

I suspect we are not properly communicating the mime type to the browser.

Investigating ....

**Comment by DeepDiver1975** [comment]
@LukasReschke your change basically is causing this because the content type of the download is always application/octet-stream - https://github.com/owncloud/mail/commit/1813d46d8cedb96ba145d8ae9b02b6a16eb52787

https://github.com/owncloud/mail/blame/master/lib/attachment.php#L94

Isn't setting the disposition content enough? https://github.com/owncloud/mail/blame/master/lib/attachment.php#L97

**Comment by LukasReschke** [comment]
What? VLC? That looks fishy… Let me take a look at this right now… *sigh*

**Comment by LukasReschke** [comment]
That said setting the disposition is generally not always sufficient. There are specific mimetypes that can anyways lead to potential security problems – in core we do have a list of "secure mimetypes" that maps insecure ones to alternatives (such as text/html to text/plain). The approach we use in this app is the easiest and most bullet proof one though.

**Comment by jancborchardt** [comment]
So – bug in Mail or not? If yes, 0.1 or 0.2?

**Comment by LukasReschke** [comment]
Can't reproduce. Do you happen to have a custom handler registered? https://support.mozilla.org/en-US/kb/applications-panel-set-how-firefox-handles-files

**Comment by DeepDiver1975** [comment]
Can't reproduce this on another machine -> 0.2

**Comment by DeepDiver1975** [comment]
![bildschirmfoto von 2015-05-09 00 55 39](https://cloud.githubusercontent.com/assets/1005065/7547056/2419b91e-f5e6-11e4-8753-57a632a8f49e.png)

**Comment by DeepDiver1975** [comment]
![bildschirmfoto von 2015-05-09 00 57 12](https://cloud.githubusercontent.com/assets/1005065/7547069/590a4b3e-f5e6-11e4-921d-c43c9099fe4d.png)

**Comment by ChristophWurst** [comment]
@DeepDiver1975 does this still happen? I remember having a similar bug where Firefox suggested to open any downloaded file with sqliteman. The problem on my system was the [Gnome defaults-list](https://wiki.archlinux.org/index.php/Default_applications#gnome-defaults-list).
Does that happen with other web applications too?

**Comment by jancborchardt** [comment]
Closing because of missing info and inability to reproduce. :)
