### ISSUE TITLE
Update unread counter when mails have been read on other client

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/mail#639]
Basically when:
* opening a folder
* refreshing a folder

The unread cound shoul also always be adjusted since the mails could have been read on another client.

**Comment by DeepDiver1975** [comment]
We should have a look at https://dev.horde.org/api/master/lib/Imap_Client/class-Horde_Imap_Client_Data_Sync.html - this class seems to implement all we need.

Any volunteer? @irgendwie @wurstchristoph

**Comment by wurstchristoph** [comment]
@DeepDiver1975 awesome! This could also fix #733!

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 awesome! This could also fix #733!

yes - I'd guess so - wana take a look? @wurstchristoph

**Comment by wurstchristoph** [comment]
@DeepDiver1975 sure, but not in the next few weeks. I'm too busy ATM :/

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 sure, but not in the next few weeks. I'm too busy ATM :/

no worries - your support is welcome anytime! Take care - all the best!

**Comment by jancborchardt** [comment]
Hehe cool, now that @wurstchristoph is also in the ownCloud organization I can assign him ;)

**Comment by ChristophWurst** [comment]
Too much for 0.3, maybe we can get horde sync working in 0.4. Let's be optimistic :-)

**Comment by ChristophWurst** [comment]
Whoops, I was too optimistic. Let's continue in #1356
