### ISSUE TITLE
min OC version

### ISSUE THREAD

**Issue by aimlessadam** [owncloud/mail#642]
i have been watching this project with great anticipation for the past few months, waiting for the 0.1 version to drop.  checking in today, it seemed this would be the day so i left the project root page open in a browser and was hitting refresh periodically... then, during the last refresh, i saw the Readme.md change from saying "An email app for ownCloud (minimum version 7)..." to "An email app for ownCloud (minimum version 8)..." and, sigh, there went my excitement. 

i definitely understand that the world is moving forward, and supporting older versions is costly, but i'm still running a couple apps that are not ready for OC 8. and since it seems like the min version got bumped on release day, i'm posting this to ask if v8 is a hard requirement?

thank you in any case for working on this, OwnCloud sooo needs a native mail client capable of working with files.  This will be quickly the #1 app i predict.

**Comment by DeepDiver1975** [comment]
@aimlessadam Thanks a lot for your feedback! I'm glad to hear about your excitement!

Let me see how much work it will be to make if OC7 compliant!

**Comment by aimlessadam** [comment]
thank you very much!

**Comment by jancborchardt** [comment]
Yeah, maybe it makes sense to see about ownCloud 7 compatibility. Thank you for the feedback @aimlessadam – you are very welcome in our IRC channel #owncloud-mail! :)

**Comment by zinks-** [comment]
an argument against it is that we're only 0.1, and when we hit 1.0 oc7 probably won't be suported anymore
but then.. it all depends on the amount of work to make it compatible for now

**Comment by clementhk** [comment]
Hi,

If we do this, I think we should only support the installations that uses PHP >= 5.4, since there are a lot of changes that requires >= 5.4, but OC 7 only requires PHP 5.3.8.
How shall we deal with this? Is it allow to have a different dependency in Apps?

**Comment by DeepDiver1975** [comment]
We can specify min php version in info.xml - that's not an issue. 

We will see how big the effort is to make the app oc7 compliant.

**Comment by jancborchardt** [comment]
Fixed by https://github.com/owncloud/mail/pull/649, I also updated the readme. Thank you for noting this @aimlessadam! :) You’re very welcome in our IRC channel #owncloud-mail

**Comment by aimlessadam** [comment]
wow i was travelling yesterday, and missed a lot.  you guys were very busy.  thank you.

i have to work on coaxing a php upgrade into my centos-6 today first, but i hope to be trying v0.1 later today or tomorrow.  

thank you again!

**Comment by jancborchardt** [comment]
@aimlessadam thank _you_ for catching this :) – please also report any further issues or requests you have.

**Comment by zinks-** [comment]
After makaber's reports on IRC, I tested which version of OC7 work:

7.0.2 fails : doesn't have the script() function
7.0.3 fails to load the app, as it tries to query urls such as this one : /owncloud/index.php/apps/mail/accounts/{accountId}/folders (literal placeholders)
7.0.4 works (tested receiving/sending emails)

**Comment by DeepDiver1975** [comment]
So we shall require 7.0.4 minimum.  Appstore can't handle this. Apps page on oc7 gives a :hankey: about dependencies in info.xml

**Comment by jancborchardt** [comment]
I updated the [readme](https://github.com/owncloud/mail/blob/master/README.md) and the [appstore page](https://apps.owncloud.com/content/show.php/Mail?content=169914) to say minimum 7.0.4 – that’s as much as we can do.

(We could also detect lower versions and show something but that’s not really worth the effort.)

**Comment by aimlessadam** [comment]
thank you.  I am sorry if i am wasting anyone's time here, or should be posting this elsewhere instead of under the OC v7 compat issue, but i am running into a problem here and am unsure if it is OC7 related or, probably more likely, some other issue with my install.  I sideloaded php PHP 5.4.16  via the redhat software collections on my OC 7.05 / Centos 6.6 box to meet the php requriement, and started apache up under that php version.  everything appears to work for owncloud, the admin page dependency check is all green (including not telling me my php is outdated anymore), and the mail app comes up, showing me all of my imap folders and message counts in the left panel, but the middle panel is blank and the right hand panel just shows the (ajax?) spinner.  

my owncloud log is logging " php[XXXXX]: {PHP} syntax error, unexpected '[' at XXX/apps/mail/appinfo/routes.php#11 " which, googling around, for other apps has pointed to missing dependencies.  
I ran the phar update, and otherwise have the following installed:
php54-php.x86_64, php54-php-cli.x86_64, php54-php-common.x86_64, php54-php-devel.x86_64, php54-php-gd.x86_64, php54-php-intl.x86_64, php54-php-mbstring.x86_64, php54-php-mysqlnd.x86_64
php54-php-pdo.x86_64, php54-php-pear.noarch, php54-php-pecl-zendopcache.x86_64, php54-php-process.x86_64, php54-php-pspell.x86_64, php54-php-xml.x86_64, php54-runtime.x86_64

is there anything obviously wrong?

thank you

**Comment by zinks-** [comment]
It looks like there is something wrong with your php/apache setup, as php 5.4 accepts [] for arrays. I can probably help you but I think this isn't the right place. Contact me by mail (see my profile) or come to IRC #owncloud-mail on freenode https://webchat.freenode.net/
