### ISSUE TITLE
Folderlist scrolls to the top when switching tabs

### ISSUE THREAD

**Issue by wurstchristoph** [owncloud/mail#645]
I have an account with many folders, so if I open the last one, I have to scroll down in the folder list. If I switch to another tab and then back, the folder list magically scrolls up to the top.

Is there any reason this is done?

tested with FF 37.0.2

Steps to reproduce:
- open mail app
- open a folder where you have to scroll down
- switch to another tab
- switch back
- the folder list scrolled up

**Comment by jancborchardt** [comment]
@wurstchristoph I can’t reproduce this with either Firefox or Chrome. @irgendwie @zinks- can you?

@wurstchristoph can you record a short video/gif illustrating the issue? Maybe I also just don’t understand it correctly.

**Comment by wurstchristoph** [comment]
cannot reproduce anymore, closing this for now :smile:
