### ISSUE TITLE
When saving attachment to ownCoud, be able to create new directory

### ISSUE THREAD

**Issue by damiongans** [owncloud/mail#646]
When saving an attachment included in an email to ownCloud, it would be cool to be able to create new folders.

**Comment by jancborchardt** [comment]
@damiongans that’s actually a very good point! This is a request to the core file picker though – can you reopen the issue in https://github.com/owncloud/core/issues ? Feel free to @-mention me with @jancborchardt and I will tag it accordingly. :)

By the way – you are very welcome in our IRC channel #owncloud-mail! :)
