### ISSUE TITLE
unable to download mail v0.1 from the apps store

### ISSUE THREAD

**Issue by j-ed** [owncloud/mail#647]
I just wanted to download the first official release of the mail app but the following message is displaced once the download-button is clicked:

![20150509_130810_oc_mail_v0 1_missing](https://cloud.githubusercontent.com/assets/2572764/7549945/bcf52e82-f64c-11e4-91d5-6fd580f73abb.jpg)

**Comment by irgendwie** [comment]
As it says in the description:
>The ownCloud Mail app is not yet released - announcement will follow the next days.

It's still under development, so please have a little patience. :smile:

**Comment by jancborchardt** [comment]
I changed the description of the app to prevent confusion: https://apps.owncloud.com/content/show.php?content=169914
