### ISSUE TITLE
Ability to include original message / inline reply

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/mail#648]
One thing we still do differently by default from other mail apps is that we simply remove the previous reply. That’s one of the reasons I sometimes still fire up another mail app, just to be able to inline reply or to not have the message thread lost for people cc’d after.

We could solve that by having a setting to »include original message«. Either for every message next to the reply button, or globally in the settings.

What it would simply do is copy the previous message, put `>` in front of it and paste it below what you just wrote (or if you didn’t write yet, have 3 empty lines above it). That would also automatically give us inline replies since then you can just go in manually and inline reply.

**Comment by jancborchardt** [comment]
This is currently the _only_ reason why I still sometimes need to start up Geary to reply to an email. ;) @DeepDiver1975 @wurstchristoph @irgendwie @zinks- anyone of you wants to work on this?

**Comment by irgendwie** [comment]
I will take a look the next days. :+1:

**Comment by jancborchardt** [comment]
@irgendwie great stuff! :) (Will mark this as »Developing« because I can’t yet assign you.)

**Comment by jancborchardt** [comment]
Fixed by Alex @irgendwie via #679!
