### ISSUE TITLE
Automatically choose the first inbox when opening the app

### ISSUE THREAD

**Issue by enoch85** [owncloud/mail#659]
### Steps to reproduce

1. "Login" to your mail (Open your mail in ownCloud)

### Actual behaviour

The mail is loading, and keeps loading until you press any folder in the mailbox.

http://i.imgur.com/y5FdUwV.png

### Expected behaviour

The first folder in the mailbox should be opened automatically

### Server and Version

8.0.3
PHP 5.5
Mail 0.1

**Comment by jancborchardt** [comment]
Loading the first inbox directly is the way it was designed and like it should work right now. Do you have more info there, like the owncloud.log, or are there JS errors?

**Comment by enoch85** [comment]
Nothing in owncloud.log but unrelated stuff. JS, I don't know. Here is a video for you. :) (Sorry for the music, couldn't turn it off)
http://youtu.be/sm46YIBUjP8

**Comment by jancborchardt** [comment]
Any idea @zinks- @wurstchristoph @irgendwie? Can you reproduce?

**Comment by irgendwie** [comment]
If there is **more** than 1 mailbox configured, I get the same behavior as @enoch85 - therefore reproducible.

**Comment by wurstchristoph** [comment]
@jancborchardt yes, I also noticed this behavior on my multi account setup.
Additionally I tested it with one account and there the first inbox is opened automatically

**Comment by DeepDiver1975** [comment]
I'm not able to reproduce this - hopefully one of you guys can debug this - THX

**Comment by enoch85** [comment]
Seems like it's when you have a MultiAccount setup. I'm on Chrome btw. 

**Version 42.0.2311.135 m (64-bit)**

**Comment by jancborchardt** [comment]
I can’t reproduce it either – I have 2 accounts and works fine for me on both Chrome and Firefox. Just loads the first inbox.

@enoch85 @wurstchristoph @irgendwie since you can reproduce it, can you debug and fix this? :)

**Comment by enoch85** [comment]
Just tell me were to look and I can try to debug it at least.

**Comment by enoch85** [comment]
@jancborchardt Is one of your accounts Gmail? Maybe it´s related? Just a wild guess.

**Comment by enoch85** [comment]
Some infor from the browser:

```
Failed to load resource: the server responded with a status of 404 (Not Found)
mail.js?v=597ddb5eade0260b4575bd57938e8405:712 Uncaught TypeError: Cannot read property 'get' of undefined(anonymous function) @ mail.js?v=597ddb5eade0260b4575bd57938e8405:712_.each._.forEach @ underscore.js?v=597ddb5eade0260b4575bd57938e8405:79Mail.UI.setFolderActive @ mail.js?v=597ddb5eade0260b4575bd57938e8405:710Mail.UI.loadMessages @ mail.js?v=597ddb5eade0260b4575bd57938e8405:413Mail.Communication.get.success @ mail.js?v=597ddb5eade0260b4575bd57938e8405:354$.ajax.success @ mail.js?v=597ddb5eade0260b4575bd57938e8405:200x.Callbacks.c @ jquery.min.js?v=597ddb5eade0260b4575bd57938e8405:4x.Callbacks.p.fireWith @ jquery.min.js?v=597ddb5eade0260b4575bd57938e8405:4k @ jquery.min.js?v=597ddb5eade0260b4575bd57938e8405:6x.ajaxTransport.send.r @ jquery.min.js?v=597ddb5eade0260b4575bd57938e8405:6
2https://en0ch.se/core/vendor/jquery/dist/jquery-migrate.min.map Failed to load resource: the server responded with a status of 404 (Not Found)
jquery-migrate.min.map:1 GET https://en0ch.se/core/vendor/jquery/dist/jquery-migrate.min.map 404 (Not Found)
```

What am I looking at?

**Comment by enoch85** [comment]
Tested on IE, same error.

**Comment by jancborchardt** [comment]
@enoch85 neither of mine are Gmail, no. @irgendwie @wurstchristoph are one of yours Gmail? (if yes then it might be related)

**Comment by enoch85** [comment]
Just tested, *not Gmail related*. Same issue if i remove the Gmail account and add another one.

**Comment by enoch85** [comment]
Just downloaded 8.1 beta and set it up on a VM, installed the mail app with the same setup as in my production machine. It works as expected here, could it be related to 8.0.3??

**Comment by jancborchardt** [comment]
@enoch85 can you maybe track it down? Try if 8.0.0 to 8.0.3 works with a fresh install (you can check out the tags via git) or where it breaks.

**Comment by enoch85** [comment]
I´ll leave that to someone else for now. I have to go to work :)

**Comment by irgendwie** [comment]
@jancborchardt Both used mail accounts are **not** Gmail.

I experience the same error as @enoch85.

Also I used the current master of OC @jancborchardt and still expierence the same error:

`Uncaught TypeError: Cannot read property 'get' of undefined
(anonymous function) @ mail.js?v=5529836605bfa3cdc0d0b4e45c40edd4:712
_.each._.forEach @ underscore.js?v=5529836605bfa3cdc0d0b4e45c40edd4:79
Mail.UI.setFolderActive @ mail.js?v=5529836605bfa3cdc0d0b4e45c40edd4:710
Mail.UI.loadMessages @ mail.js?v=5529836605bfa3cdc0d0b4e45c40edd4:413
Mail.Communication.get.success @ mail.js?v=5529836605bfa3cdc0d0b4e45c40edd4:354
$.ajax.success @ mail.js?v=5529836605bfa3cdc0d0b4e45c40edd4:200
x.Callbacks.c @ jquery.min.js?v=5529836605bfa3cdc0d0b4e45c40edd4:4
x.Callbacks.p.fireWith @ jquery.min.js?v=5529836605bfa3cdc0d0b4e45c40edd4:4
k @ jquery.min.js?v=5529836605bfa3cdc0d0b4e45c40edd4:6
x.ajaxTransport.send.r @ jquery.min.js?v=5529836605bfa3cdc0d0b4e45c40edd4:6`

**Comment by enoch85** [comment]
Did one last thing before I went to work - did a fresh install of the app and reset the MySQL tables.

No luck.
