### ISSUE TITLE
"Check messages" should sync deleted messages as well.

### ISSUE THREAD

**Issue by enoch85** [owncloud/mail#663]
It seems like the Check Messages button only checks for new messages. If I delete messages on the IMAP server, and go back to ownCloud Mail and press Check Messages, it still appears as I have the same amount of new messages.

Don't know if it´s intended? 

### Server and Version

8.0.3
PHP 5.5
Mail 0.1

**Comment by enoch85** [comment]
Related #538

**Comment by enoch85** [comment]
- [ ] Delete (sync) message on ownCloud, if deleted on mailserver.
- [X] Delete (sync) message on mailserver, if deleted on ownCloud.

**Comment by wurstchristoph** [comment]
> Delete (sync) message on ownCloud, if deleted on mailserver.

@enoch85  what do you mean by that? That messages deleted in other mail clients disappear from the message list automatically?

**Comment by enoch85** [comment]
@wurstchristoph Yes, the server should sync both ways, not just sync if I delete the message on the mailserver.

**Comment by wurstchristoph** [comment]
@enoch85 I had a look at the code, it seems like the background checks of changes of a folder use the UID validity which only changes if there are new messages AFAIK

@DeepDiver1975 is that correct? Is there any way to detect deleted messages?

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 is that correct? Is there any way to detect deleted messages?

AFAIK changes to a mailbox are detectable by comparing UIDVALIDITY and UIDNEXT. Depending on the mail server implementation this might be insufficient. 

I guess this requires some more research

**Comment by wurstchristoph** [comment]
@enoch85 for automatically synced message flags, I created #733 as it's not related to this issue in my opinion

**Comment by aidanamavi** [comment]
There are two separate issues discussed in this thread, respectively.
1. Messages deleted in other mail clients should disappear from the ownCloud message list when the ownCloud 'Check Messages ...' button is click.
2. Messages deleted in other mail clients should disappear from the ownCloud message list automatically.

For issue 1, please use this thread.
For issue 2, please use thread #733 to discuss further.

I do not have issue 1.
I am running the following configuration:
ownCloud 8.0.3
Mail 0.1.3
PHP 5.5.20

@enoch85 Do you still have issues with the 'Check Messages ...' button syncing your message list?
