### ISSUE TITLE
Delete keyboard button as shortcut to delete current mail

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/mail#670]
Other mail apps delete the current mail when you click the keyboard »Delete« button. We should do that too.

**Comment by irgendwie** [comment]
Backspace to delete Mail? The delete key is enough for that - I still think of "Go back in history" when using backspace. And I think a lot of people do that.

**Comment by enoch85** [comment]
Agree with @irgendwie on this. Delete button is enough. Imagine if accediently press the Backspace by mistake.

**Comment by jancborchardt** [comment]
Ok, I’m fine with that as well. Changing the title & description. :)

**Comment by biolumin** [comment]
I'm going to work on this. :)

**Comment by jancborchardt** [comment]
Fixed by @aidanamavi via #706
