### ISSUE TITLE
Add an option for creating new contacts when sending/receiving emails to/from them.

### ISSUE THREAD

**Issue by rvega** [owncloud/mail#675]
When sending or receiving an email from a person who is not in my contacts list (Contacts application), she should be added automatically to the contacts list, it'd probably be useful to add it to a group called "automatically added" or similar. 

Gmail does this by default and it's nice to simply start typing a name or address and have it auto-completed without having to manually create a contact.

**Comment by jancborchardt** [comment]
This is a duplicate of https://github.com/owncloud/mail/issues/363 ;) let’s continue there.

**Comment by rvega** [comment]
Ah, sorry, I swear I searched first :)

**Comment by jancborchardt** [comment]
@rvega no worries, the search is often not perfect. :)
