### ISSUE TITLE
Make 'New message' button static

### ISSUE THREAD

**Issue by wurstchristoph** [owncloud/mail#681]
If you have multiple accounts and/or accounts with many folders you often have to scroll down the folders list to get to the very last account. If you then want to compose a new mail, you have to scroll up again to be able to click the 'New message' button.

I think we should make the button static and scroll the folders list only

what do you think @jancborchardt?

**Comment by Xenopathic** [comment]
Agreed - that'd be a good idea. :+1:

**Comment by jancborchardt** [comment]
Yeah, good call!

**Comment by jancborchardt** [comment]
Fixed at https://github.com/owncloud/mail/pull/703 – please review :)
