### ISSUE TITLE
Show inboxes on top of accounts and other folders

### ISSUE THREAD

**Issue by wurstchristoph** [owncloud/mail#682]
I really like what [Geary](https://wiki.gnome.org/Apps/Geary) does:
- list the inbox for each account
- list all accounts after that

It looks like this:
![](http://worldofgnome.org/uploads/2013/03/geary1.png)

Additionally, if accounts are collapsed by default, the interface is cleaner: one can quickly navigate to the desired folder instead of having to scroll through all the accounts/folders like in the current version of the mail app.

ref #120 #677

**Comment by jancborchardt** [comment]
As said in #677:

> I would say rather than #682 we’d fare better with this »priority collapsing« #677 combined with a unified inbox #120 (and maybe other unified folders). :)

What do you think?

**Comment by wurstchristoph** [comment]
Yes, priority collapsing sounds great too - let's try it out ;-)
