### ISSUE TITLE
Message is rendered, although you change to another folder

### ISSUE THREAD

**Issue by irgendwie** [owncloud/mail#684]
**Steps to reproduce:**
1. Open a folder which contains mails.
2. Wait until the message list spinner is gone and all messages are listed, but the message content spinner is still there.
3. Quickly click on another folder, but this time an empty one.

**Expected behavior:**
* 'No mails in this folder' message is shown

**Actual behavior:**
* 'No mails in this folder' message is shown
* but the first message of the previous folder is also rendered above of the 'No mails in this folder' message

**Comment by jancborchardt** [comment]
Can confirm.

Similar happens with the drafts folder:
1. Open the drafts folder
2. Wait until the message list spinner is gone and all messages are listed, but the message content spinner is still there.
3. Quickly click on another folder, but this time any other one with mails in it.

Expected: The new folder is shown, and the first Mail in it.

Actual behavior: Message list of the new folder is shown, but the message view still shows the draft to edit.

cc @wurstchristoph @zinks- @DeepDiver1975

**Comment by jancborchardt** [comment]
Oh and cc @biolumin as well – this might be a JS issue you can fix. :)
