### ISSUE TITLE
Drafts: quick feedback that message has been saved as draft

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/mail#685]
We have an awesome drafts feature, but new users don’t know that they can just leave the composer / reply field and it will be saved.

Ideally when navigating away from the new message or the reply, there could be a OC.Notification.showTemporary to say »Message saved as draft«. This feedback will let them know that the feature exists.

(This has come up in a small usability test I did with a person new to the Mail app.)

cc @irgendwie @biolumin :)

**Comment by wurstchristoph** [comment]
Do you mean this: https://github.com/owncloud/mail/blob/b7977ae2dbd51c7cda2ea32280538d6e96e08794/js/views/sendmail.js#L220-L226

I implemented it, but it seems to be broken

**Comment by jancborchardt** [comment]
@wurstchristoph yeah, that. It probably doesn’t work because the container `#new-message-msg` is not visible anymore when switching to a different mail. Can you use `OC.Notification.showTemporary` instead?
