### ISSUE TITLE
Error while loading accounts

### ISSUE THREAD

**Issue by tflidd** [owncloud/mail#686]
I use owncloud 7.0.5 on Ubuntu 14.04 (with Apache/Mysql).

I downloaded the most recent mail app 0.1.3, unpacked it to the apps folder and activated it. When I load the mail-app, there is a yellow message saying "Error while loading accounts" and in the logfiles there ist
````
{"reqId":"5559e9be2ad41","app":"index","message":"Doctrine\\DBAL\\DBALException: An exception occurred while executing 'SELECT * FROM mail_accounts WHERE user_id = ?' with params [\"username\"]:\n\nSQLSTATE[42S02]: Base table or view not found: 1146 Table 'cloud.mail_accounts' doesn't exist","level":4,"time":"May 18, 2015 13:31:42","method":"GET","url":"\/owncloud\/index.php\/apps\/mail\/accounts"}
````
It seems that the table mail_accounts has not been created. I don't use any prefix, database name is cloud, so the table name cloud.mail_accounts seems to make sens. Is there anything else I need to activate? On the personal page I didn't find a setting where to enable or configure mail accounts, on the admin-page neither.

**Comment by jancborchardt** [comment]
Maybe the problem is that you don’t use any prefix? @DeepDiver1975 @zinks- did we hardcode the prefix somewhere?

Btw @tflidd the preferred way of installing apps is through ownCloud itself. Just open the apps menu, go to »Apps« then to »Productivity« and install it from there. Simpler than downloading and uploading the zip yourself.

**Comment by tflidd** [comment]
For testing, I set up a virtual Server with ipv6only and the app store is only available via ipv4 ;-(

**Comment by jancborchardt** [comment]
Hm, maybe we should make the app store available via IPv6 as well? @karlitschek @LukasReschke 

@tflidd regardless of that, can you test with an IPv4 server?

**Comment by tflidd** [comment]
I did some more test. I downloaded a fresh OC 7.0.6 and OC 8.0.4 (as *.tar.bz2). I installed both, after the initial installation, I logged out, renamed all databases without the "oc_"-prefix and made this changement as well in the config.php.
With OC 8.0.4, I could install the mail app right away via the app-store (in both cases). Very nice lightweight mail client ;-)
On OC 7.0.6 I get this famous:
````
{"reqId":"55841b26bd940","app":"core","message":"App does not provide an info.xml file","level":3,"time":"2015-06-19T13:37:42+00:00","method":"POST","url":"\/oc2\/index.php\/settings\/ajax\/enableapp.php"}
````
Both setups are on the same server and only in different subdirectories (Ubuntu 14.04, Apache, Mysql, mod_php).
OC 7.0.6-config:
````
<?php
define('DEBUG',true);
$CONFIG = array (
  'instanceid' => 'oc0d658f2a24',
  'passwordsalt' => '839518b20b17025c6af8ffb1c1e04b',
  'secret' => 'xxxxx',
  'trusted_domains' => 
  array (
    0 => 'myhost',
  ),
  'datadirectory' => '/var/www/oc2/data',
  'overwrite.cli.url' => 'https://myhost/oc2',
  'dbtype' => 'mysql',
  'version' => '7.0.6.2',
  'dbname' => 'ocbackup',
  'dbhost' => 'localhost:/var/run/mysqld/mysqld.sock',
  'dbtableprefix' => '',
  'loglevel' => '0',
  'dbuser' => 'ocbackup',
  'dbpassword' => 'xxxx',
  'installed' => true,
);
````
and for OC 8.0.4:
````
<?php
define('DEBUG',true);
$CONFIG = array (
  'instanceid' => 'ocmr3ngu09p3',
  'passwordsalt' => 'TH8hiIMlIIRGw01NXKpiTMRujjekzg',
  'secret' => 'xxxxx',
  'trusted_domains' => 
  array (
    0 => 'myhost',
  ),
  'datadirectory' => '/var/www/oc8/owncloud/data',
  'overwrite.cli.url' => 'https://myhost/oc8/owncloud',
  'dbtype' => 'mysql',
  'version' => '8.0.4.2',
  'dbname' => 'octtoc8',
  'dbhost' => 'localhost:/var/run/mysqld/mysqld.sock',
  'dbtableprefix' => '',
  'dbuser' => 'oc_admin',
  'dbpassword' => 'xxxx',
  'installed' => true,
  'loglevel' => 0,
);
````

**Comment by tflidd** [comment]
little follow up: For the OC 7 setup, I got the archive from apps.owncloud.com and installed it manually. Now it works and I don't see the error that I had before.
The first setup with the problems was a backup-snapshot from a long running setup (numerous upgrades) which still runs on OC 7.0.5 (not yet updated).

**Comment by jancborchardt** [comment]
@tflidd does it work with the newly released ownCloud 8.1?

**Comment by srt10coupe** [comment]
No

**Comment by srt10coupe** [comment]
No oC 8.1.1git

**Comment by tflidd** [comment]
I checked on OC 8.1.0 (debian-package), there I don't see any problems.

**Comment by jancborchardt** [comment]
@tflidd thanks for checking! :) You’re very welcome helping more with our release by testing pull requests and reporting more issues. Also join our IRC channel #owncloud-mail :)

**Comment by srt10coupe** [comment]
»Apps« then to »Productivity« and install it from there. Failed
![screenshot_2015-08-09-12-00-49](https://cloud.githubusercontent.com/assets/399997/9154453/ed2dc0c0-3e8e-11e5-9d9f-fca5e8f1b7c8.png)

The app can not be installed because it contains unauthorized code.

**Comment by jancborchardt** [comment]
@srt10coupe please open a separate issue for that, and fill out the issue template (server logs and more) that we need to debug this.
