### ISSUE TITLE
"to" field is case sensitive

### ISSUE THREAD

**Issue by nielsha** [owncloud/mail#688]
The "to" field seems to be case sensitive. In my opinion this is unnecessary.

**Comment by jancborchardt** [comment]
Can you describe this further? When I write an email address with mixed case it seems to make no difference. Do you mean we should lowercase the email address automatically?

cc @DeepDiver1975 @zinks-

**Comment by zinks-** [comment]
this is #197 
and still happening to me too !

**Comment by jancborchardt** [comment]
Ok, I reopened #197 – closing this as duplicate. @nielsha let’s continue in #197
