### ISSUE TITLE
Log error in conjunction with Contacts app (due to partly broken import)

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/mail#707]
Due to the Contacts app currently having a bug which doesn’t import contact pictures (https://github.com/owncloud/contacts/issues/904), I get these error logs in the Mail app:
```
{"message":"Accessing the API class is deprecated! Use the appropriate services instead!","method":"GET","url":"\/owncloud\/index.php\/apps\/contacts\/addressbook\/local\/2\/contact\/325\/photo"}
{"message":"Accessing the API class is deprecated! Use the appropriate services instead!","method":"GET","url":"\/owncloud\/index.php\/apps\/contacts\/addressbook\/local\/2\/contact\/404\/photo"}
{"message":"Accessing the API class is deprecated! Use the appropriate services instead!","method":"GET","url":"\/owncloud\/index.php\/apps\/contacts\/addressbook\/local\/2\/contact\/256\/photo"}
```

Not sure if it’s something we can/should fix, but might be something we can prevent by checking if the image exists. Any idea @zinks- @wurstchristoph @DeepDiver1975?

**Comment by DeepDiver1975** [comment]
> {"message":"Accessing the API class is deprecated! Use the appropriate services instead!","method":"GET","url":"\/owncloud\/index.php\/apps\/contacts\/addressbook\/local\/2\/contact\/325\/photo"}

this message is pure debug information and has no impact on functionality - nothing we can/need/should take care of - from the mail perspective
