### ISSUE TITLE
Folder list whitespace in Chrome, but not in Firefox

### ISSUE THREAD

**Issue by wurstchristoph** [owncloud/mail#712]
I don't know which one is the intended one, but Chrome and FF show different folder list bottom:
# Firefox
![](https://cloud.githubusercontent.com/assets/1374172/7771307/b8907636-0096-11e5-86ea-d0e9e96750ed.png)
# Chrome
![](https://cloud.githubusercontent.com/assets/1374172/7771310/ba141e36-0096-11e5-9766-595cae8b5ff0.png)

@jancborchardt any idea?

**Comment by jancborchardt** [comment]
This is not intended - the whitespace should be there for both.

Maybe you saw it in the folder list as well, which might be a similar issue. If anyone knows how to fix it, please do :) cc @biolumin @colmoneill

**Comment by jancborchardt** [comment]
Fixed by @aidanamavi via #716 :)
