### ISSUE TITLE
Outlook authentication failed

### ISSUE THREAD

**Issue by ludenticus** [owncloud/mail#714]
I cannot create a new outlook email account (@hotmail). I've double-checked every option

imap-mail.outlook.com
SSL 993

smtp-mail.outlook.com
STARTTLS 587

I've tried as well:
STARTTLS 25
SSL/TLS 465
SSL/TLS 25
SSL/TLS 3535

Each time, the answer is the same:

Authentication was successful, but authorization failed

![screenshot from 2015-05-23 09-36-02](https://cloud.githubusercontent.com/assets/813198/7784676/f4303a12-0133-11e5-9362-a5f2029fa198.png)

To be on the safe side, I wrote my password on a text manager and copied it as such directly to the login.live.com page to verify that it is working. After login, I copied it to the owncloud app.

Any idea?

**Comment by irgendwie** [comment]
Maybe this helps? http://www.msoutlook.info/question/773

**Comment by ludenticus** [comment]
I can confirm that it is mandatory to have the Two Step Verification enabled and provide an App password instead of the user pass. No need to manual config.
Thanks for your prompt reply. I'm closing the issue as solved.

**Comment by jancborchardt** [comment]
@irgendwie can you add this to our wiki page on troubleshooting? Where it also mentions the Google auth?
