### ISSUE TITLE
Support sending mail through php's builtin mail() function

### ISSUE THREAD

**Issue by zinks-** [owncloud/mail#729]
Some webhosts disable outgoing connections on common smtp ports. They often allow sending mail throught the php mail() function, which connects to some smtp server chosen by the hoster.

Web hosting services known to block smtp connections :

- 1&1 (1und1)

**Comment by DeepDiver1975** [comment]
Nice finding ... THX

We can fix this by adding a config switch and disable all the smtp stuff

**Comment by jancborchardt** [comment]
(@DeepDiver1975 can we exclude issues opened by repo contributors from the owncloud-bot messages? Or shut it down altogether? It's really more annoying more often that it's worth. :\

**Comment by marius01** [comment]
Thank you for creating this post! Do you think it can be fixed? (or is it already). Sorry for asking so much "noob-questions".
