### ISSUE TITLE
disallowScriptDomain() error

### ISSUE THREAD

**Issue by colmoneill** [owncloud/mail#731]
### Steps to reproduce
1. select a mail message

### Expected behaviour
Load email content

### Actual behaviour
```
Fatal error: Call to undefined method OCP\AppFramework
\Http\ContentSecurityPolicy::disallowScriptDomain() in /var/www/html/owncloud-core/apps/mail/lib/controller/messagescontroller.php on line 176
```

### Server configuration
**Operating system**: Ubuntu 14.04

**Web server:** Apache

**Database:** SQLite

**PHP version:** PHP Version 5.5.9-1ubuntu4.9

**ownCloud version:**  8.1 alpha 2 (git) 

**Updated from an older ownCloud or fresh install:** no

**List of activated apps:** News

### Additional:
In my local install, I'm getting this error for all messages after attempting to load. Is this just me?

Line 176 of that file concerns `dissalowScriptDomain` indeed:

```
// Harden the default security policy
// FIXME: Remove once ownCloud 8.1 is a requirement for the mail app
if(class_exists('\OCP\AppFramework\Http\ContentSecurityPolicy')) {
	$policy = new ContentSecurityPolicy();
	$policy->allowEvalScript(false);
	$policy->disallowScriptDomain('\'self\'');
	$policy->disallowConnectDomain('\'self\'');
	$policy->disallowFontDomain('\'self\'');
	$policy->disallowMediaDomain('\'self\'');
	$htmlResponse->setContentSecurityPolicy($policy);
}
```
![screenshot from 2015-05-26 20 41 57](https://cloud.githubusercontent.com/assets/2122318/7820559/81e4109c-03e9-11e5-8c3f-a3b7819ba39f.png)

**Comment by LukasReschke** [comment]
ownCloud 8.1 Alpha 2 will not run with the current master. See https://github.com/owncloud/mail/issues/206#issuecomment-104200771 for details how to work around this until the next alpha / beta / rc has been released.

**Comment by jancborchardt** [comment]
@colmoneill btw if you use the Contacts app as well and add images to the contacts, the faces will nicely show up in the message list. ;)
