### ISSUE TITLE
Ctrl-click on a link leads to redirect not working

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/mail#732]
1. Ctrl-click on a link (because you're used to needing to do that to open links in new tabs)
2. See this:
![redirect](https://cloud.githubusercontent.com/assets/925062/7821892/287333e0-03f2-11e5-98c3-a1cf2f1de62d.png)
(Chrome in incognito mode, ownCloud 7 latest stable)

cc @LukasReschke your job ;)

**Comment by wurstchristoph** [comment]
Works in FF/Chrome on OC8 stable, so it seems to be an OC7 issue

**Comment by jancborchardt** [comment]
Only happens in HTML mails it seems.

**Comment by jancborchardt** [comment]
@LukasReschke :)

**Comment by jancborchardt** [comment]
It’s also an issue with stable8 according to @ronoliverclarin in https://github.com/owncloud/mail/issues/784 – so we should fix it! :)

**Comment by LukasReschke** [comment]
We (i.e. me) worked hard on it and it is fixed in current master. Will be fixed with the next release. Thanks for reporting :smile:
