### ISSUE TITLE
No server side mail access?

### ISSUE THREAD

**Issue by poVoq** [owncloud/mail#739]
Maybe I misunderstand the purpose of this plug-in, but it seems to get mails from the IMAP server through the client, at least partially. i.e. it fails getting mail through the owncloud interface with a computer that is in a local network (but does not have access to the internet) through a server that runs owncloud and which has access to the internet and the imap server I am trying to access.

Thus it seems to me that through this setup the server can't regularly check for emails automatically, nor notify the user of new mails through the owncloud notification system, nor can it download emails while the client is not connected etc.

Is this the intended behaviour?

**Comment by DeepDiver1975** [comment]
This app is an imap client whoch connects to an imap server.  From my understanding there is no limitation with respect to being connected to the internet or not.

As long as the app is open in a browser tab you will receive notifications via html5 notification (no all browsets support that).

I hopw this helps.  Thx

**Comment by poVoq** [comment]
Ok, so it is a pure client side app? The server just supplies the java script code?
So what would be exactly the advantage over a regular client application? At best the convenience to load it though the Owncloud interface...
A well, I was hoping it would actually run on the server and just display the emails to the client.

**Comment by Xenopathic** [comment]
@poVoq There seems to be a misunderstanding - the IMAP client bit of the app is implemented server-side, with notifications passed to the client.

**Comment by poVoq** [comment]
hmm, so maybe it is the smtp part that make the app fail to load when I connect from a client that has no internet connection?

**Comment by Xenopathic** [comment]
@poVoq The app is completely client-independent, as all connections to external mail servers are made from the server-side PHP code.

**Comment by poVoq** [comment]
Ahh, I tried it again, and now it worked. very strange and sorry to have bothered you. Keep up the great work!
