### ISSUE TITLE
Fetch new messages in background

### ISSUE THREAD

**Issue by ChristophWurst** [owncloud/mail#751]
Like loading top messages when opening/opening a folder, also new messages (loaded in background) should be fetched in background (related to https://github.com/owncloud/mail/pull/715)

**Comment by jancborchardt** [comment]
@wurstchristoph can you clarify what you mean by this? Also, 0.2 or 0.3?

**Comment by wurstchristoph** [comment]
When detecting changes (new messages) in background, additionally to showing a notification the app should download the messages in the meantime so they are already loaded to cache when the user switches back to the mail app.

**Comment by jancborchardt** [comment]
Ahh right, yes.
