### ISSUE TITLE
Deletion broken, does not switch to other message and current message still stays in detail view

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/mail#753]
Just test it with current master cc @DeepDiver1975 @zinks- @irgendwie @AidanAmavi 

Correct behavior should be: https://github.com/owncloud/mail/issues/730

**Comment by irgendwie** [comment]
Werde es mir in den nächsten Tagen mal ansehen!

**Comment by irgendwie** [comment]
Fixed by PR #757

**Comment by jancborchardt** [comment]
@irgendwie hehe, @aidanamavi was faster than you. ;)

**Comment by irgendwie** [comment]
:see_no_evil: 

![I'm not even mad](http://www.mememaker.net/static/images/memes/3153718.jpg)

**Comment by jancborchardt** [comment]
lol, good one

**Comment by aidanamavi** [comment]
lol
