### ISSUE TITLE
Reseting the app - can't enable again

### ISSUE THREAD

**Issue by Ulrar** [owncloud/mail#764]
Hi,

Tried to reset the app to use the git version, since the version coming with owncloud doesn't handle sub-sub folder correctly. I ran the SQL drops, and now I can't enable the app again because "App directory already exists"

thanks

**Comment by jancborchardt** [comment]
@Ulrar sub-subfolders also don’t work on master yet: https://github.com/owncloud/mail/issues/618 ;)

@irgendwie @zinks- @clementhk any idea here?

**Comment by zinks-** [comment]
@Ulrar @jancborchardt I'm guessing the "enable" button you are pressing is trying to download and activate the appstore version instead of just activating the one you cloned from here.

If you have access to your server/host's command line, try enabling the app with the occ command in the owncloud root folder : 

```
sudo -u yourwebserveruser php occ app:enable mail
```

**Comment by jancborchardt** [comment]
Hm, the cloned folder should always take precedence though. cc @DeepDiver1975

**Comment by DeepDiver1975** [comment]
Having an app installed twice is not supported. 
My suggestion is to either install apps via git or the app store.  Mixing them up is a bad idea.

**Comment by Ulrar** [comment]
Hi,

Thanks, php occ app:enable mail did work !
I get an internal server error then, but I guess it's just the git version that's currently broken ?
If sub-subfolders still doesn't work I guess I'll just wait anyway, I deleted the app and put back the original version, I got back access to owncloud. Thanks !

**Comment by zinks-** [comment]
@Ulrar Make sure you download composer and run the composer install command as seen here : https://github.com/owncloud/mail#developer-setup-info
