### ISSUE TITLE
When fetching messages in background, use a single request

### ISSUE THREAD

**Issue by ChristophWurst** [owncloud/mail#769]
Loading messages in background can be sped up if we use only one request  instead of up to 10 (which causes 10 requests to the IMAP server) :rocket:

**Comment by DeepDiver1975** [comment]
so we would need to add a bulk get route - hmmmm

**Comment by DeepDiver1975** [comment]
see http://www.l1ghtm4n.com/post/53259404576/patterns-for-rest-api-bulk-operations

we can add some query logic to the index route like

GET /index.php/apps/mail/messages?id=123&id=124&id=125

**Comment by jancborchardt** [comment]
@wurstchristoph also something to postpone to 0.3?

**Comment by wurstchristoph** [comment]
@jancborchardt I would say we can do this in 0.2, this will give some additional speedup to #766 :rocket:

**Comment by jancborchardt** [comment]
Fixed by https://github.com/owncloud/mail/pull/866 :rocket:
