### ISSUE TITLE
Groups and Contacts in Mail / Attachments

### ISSUE THREAD

**Issue by ghost** [owncloud/mail#770]
Hi,

Would be nice, if using Contacts (and Groups!!!) would be possible in OwnCloud Mail,
as well as save and send attachments directly from your PC.

A customer has just shown me that this is not possible.
Does anybody know when 0.2 arrives? (Off-Topic)

**Comment by DeepDiver1975** [comment]
> send attachments directly from your PC.

planned feature #462

**Comment by DeepDiver1975** [comment]
> if using Contacts

already possible

**Comment by DeepDiver1975** [comment]
> (and Groups!!!)

hmmm - @jancborchardt would that make sense?

**Comment by aspdye** [comment]
@DeepDiver1975 I think it would. Then you could send email to groups. As a kind of mailing list.

**Comment by jancborchardt** [comment]
The groups requirement is being discussed in https://github.com/owncloud/mail/issues/772 :) @ghost let’s continue there.
