### ISSUE TITLE
[master] under yet unknown conditions the check-messages-button disappears

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/mail#773]

**Comment by DeepDiver1975** [comment]
... and the load-more button as well ... happened after clicking the check-button

**Comment by jancborchardt** [comment]
@DeepDiver1975 as we said back in the days: »Der wer’s entdeckt, der macht `git bisect`.« :D

**Comment by DeepDiver1975** [comment]
fixed for my with #843
