### ISSUE TITLE
Mass E-Mails to Users

### ISSUE THREAD

**Issue by aspdye** [owncloud/mail#774]
Have just read an article in the Forum, and promised to note this here:

It would be a great idea to include a feature in the email app that allows you to send mass emails to all users or individual user groups of your OwnCloud.

Reference (German): https://forum.owncloud.org/viewtopic.php?f=21&t=28786

**Comment by DeepDiver1975** [comment]
kind of related to #772

**Comment by jancborchardt** [comment]
This seems to be exactly the same as https://github.com/owncloud/mail/issues/772 (or at least so similar that we can keep it to one issue) – closing as duplicate hence.

**Comment by jancborchardt** [comment]
This seems to be exactly the same as https://github.com/owncloud/mail/issues/772 (or at least so similar that we can keep it to one issue) – closing as duplicate hence.
