### ISSUE TITLE
POP3 Support for Privacy

### ISSUE THREAD

**Issue by aspdye** [owncloud/mail#775]
Currently OwnCloud Mail only supports IMAP. Would it not be great also to support the POP3-Standard. This would be a feature for privacy-nerds, so their emails would be not longer stored on the servers but directly in the OwnCloud (maybe encrypted :+1:).

To retrieve the e-mails could be a OwnCloud mail - do app.

**Comment by DeepDiver1975** [comment]
Supporting POP3 by itself is not an issue - but I question the benefit of it.

Using IMAP allows the use of other mail clients as well - e.g. on a mobile device.
Using an POP3 approach where the mail are downloaded to the ownCloud server this would no longer be possible.

Furthermore I don't get the privacy benefit - either you trust the mail server then there is no need to move them away asap or you don't trust it - but then why use it at all?

**Comment by jancborchardt** [comment]
I agree with @DeepDiver1975 – downloading mails will make it impossible to use with other clients. Nowadays where many people have two devices (smartphone and computer) this would not be feasible.

**Comment by aspdye** [comment]
Ok. I see :)
