### ISSUE TITLE
Predefined mail accounts

### ISSUE THREAD

**Issue by soumplis** [owncloud/mail#780]
In future version would be nice if we could add predefined settings for the mail accounts for every user and/or have a set of predefined settings (custom list created by the admin) for users to choose from (ex. Gmail, yahoo mail, corporate accounts etc).

**Comment by aspdye** [comment]
Sounds great. Here are my ideas for this feature:

-Admin: Black and Whitelist for IMAP-Servers and! Domains 
 example: (only) allowed: sample.com (Domain) @ imap.hoster.de
 disallowed: gmail.com (Domain) @ imap.gmail.com

-Predefinded Accounts and Setting to disable Custom User Accounts
example: max@sample.com -> OwnCloud User Max
info@sample.com -> OwnCloud Group! Sales

-Management of User E-Mail Accounts in User-Settings

**Comment by DeepDiver1975** [comment]
duplicate #166

**Comment by jancborchardt** [comment]
@soumplis @aspdye always make sure you search through the issues before opening new ones. ;) And you’re very welcome in our IRC channel #owncloud-mail! :)
