### ISSUE TITLE
Switch faster to new message when deleting other one

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/mail#783]
Now with our new awesome message caching, what still seems slow is the switching to the next message when deleting one. It seems that the code waits for the slideup animation to be finished.

@wurstchristoph @irgendwie want to work on that? :)

**Comment by wurstchristoph** [comment]
To fix this we could move code that should be executed immediately out of the passed function: https://github.com/owncloud/mail/blob/master/js/views/message.js#L98-L115
