### ISSUE TITLE
Javascript error

### ISSUE THREAD

**Issue by ronoliverclarin** [owncloud/mail#784]
When I tried to click a link in mail content and redirects me to a new window.
This error I always see:
![image](https://cloud.githubusercontent.com/assets/2889432/8208155/9d6230aa-1538-11e5-9a16-0822f6512295.png)

**Comment by jancborchardt** [comment]
Yup, you probably used Ctrl-Click on the link :) Same issue as https://github.com/owncloud/mail/issues/732

@LukasReschke FIX IT! :D

**Comment by LukasReschke** [comment]
![](https://cloud.githubusercontent.com/assets/1005065/8183663/eeb2217c-1439-11e5-9fcb-a0f58093ce27.jpg)
