### ISSUE TITLE
Autofill 'from' in new message

### ISSUE THREAD

**Issue by irgendwie** [owncloud/mail#788]
If you have a multi mail account setup and click on new message, you have to choose between the two mail accounts as transmitter of the mail. Default value is 'from <>', means empty.

Would be cool, to autofill from - if you have selected a mail account specific folder - with the specific mail account.

**Comment by jancborchardt** [comment]
DUPLICATE OF https://github.com/owncloud/mail/issues/297
![](http://tech.firstpost.com/wp-content/uploads/gallery/2013/jul/n00b_121651258548_640x360.jpg)
