### ISSUE TITLE
Opening messages sometimes does not expand the cc list automatically

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/mail#789]
This seems to happen due to the new message caching. ;) @wurstchristoph

**Comment by aidanamavi** [comment]
How do I reproduce this issue, so that I may test the PR?

**Comment by wurstchristoph** [comment]
@aidanamavi 
- open the mail app
- wait for your accounts + messages to load
- click on a message that has cc
- see that cc is not automatically expanded

@jancborchardt is right, it only happens with cached messages
