### ISSUE TITLE
Ability to add event/ics attachments directly to the calendar [$40]

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/mail#79]
When an email has an event (ics file) attached to it, you should be able to easily add it to your calendar. Instead of the »Save to files« the integration button should say »Add to Calendar«.

The question then is how to proceed:
* just add the event, and show a short confirmation? Too opaque – you need some info on what you are about to add
* redirecting to the calendar would rip you out of the flow
* displaying a modal is an option, but might be a ton of work
* opening a new tab with the calendar, with the New event modal open (prefilled with the details) might be best.

Ideal would be if the Mail app could display the info about the event before adding it. Similar to how Gmail does – for even better integration:
![](https://lh3.googleusercontent.com/-0aULRJ_dzvo/UqCpu8YDKMI/AAAAAAAABH4/12EWTFo8Wvo/s1600/gmail_ics.png)

@DeepDiver1975 @georgehrke how can we do this best?

**Comment by jancborchardt** [comment]
We need the public Calendar API in core for this: https://github.com/owncloud/core/pull/11461 – @georgehrke please get on reviewing this!

cc @irgendwie cause you were interested in working on this. ;)

**Comment by arthurlutz** [comment]
+1

**Comment by phsc** [comment]
Will Calendar+ also be supported? Or would it even make sense to focus on implementing this feature for Calendar+?
https://github.com/libasys/calendarplus

**Comment by jancborchardt** [comment]
@phsc ideally this is independent of the Calendar app being used. We aim to separate the CalDAV backend from the apps, see https://github.com/DeepDiver1975/dav

**Comment by jyaworski** [comment]
I'd love to see this get implemented.

**Comment by hitam4450** [comment]
:thumbsup: :thumbsup: :thumbsup:

Me too!

**Comment by ChristophWurst** [comment]
Let me have a look at this for 0.4.5.



> :thumbsup: :thumbsup: :thumbsup:
> 
> Me too!

@hitam4450 github now has reactions, so there is really no need for :+1:-comments ;-)

**Comment by hitam4450** [comment]
Thanks for your advice !!!! :thumbsup:

**Comment by jancborchardt** [comment]
@arthurlutz @hitam4450 if you would like to see this implemented, please donate towards this issue at Bountysource to really help make this happen: https://www.bountysource.com/issues/3248889-ability-to-add-event-ics-attachments-directly-to-the-calendar
– Both @jyaworski and I already put our money where our mouth is. ;)
