### ISSUE TITLE
Unified composer view

### ISSUE THREAD

**Issue by ChristophWurst** [owncloud/mail#795]
ATM I know of at least 2 different composer views (+ different js view code for each of them), but we will need more of them:
- new message composer
- reply message composer
- forward message composer
- mailto-link message composer

To make things nice and easy we should combine all of them (or reuse the first one), so everywhere we use a composer, the same features are available (e.g. HTML content, drafts, attachment)

this is needed for at least the following issues #95, #602, #603, #605, #734, #735

**Comment by DeepDiver1975** [comment]
Yes - that needs to be done.


I suggest to use the new message composer, add attachments from local computer and finally reuse it then.
