### ISSUE TITLE
Pre-Made Templates

### ISSUE THREAD

**Issue by ronoliverclarin** [owncloud/mail#802]
Do you have any plans of adding Pre-made templates for replies or new email messages?

**Comment by LukasReschke** [comment]
Pretty sure @jcfischer doesn't has this plans. But maybe @jancborchardt has :speak_no_evil:

**Comment by jancborchardt** [comment]
Not yet – putting it in the backlog. :)

**Comment by jancborchardt** [comment]
Closing since no one worked on it since a year so it’s not likely someone will take it up. :) Feel free to contribute code though.
