### ISSUE TITLE
Remaining issues for unified inbox

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/mail#803]
Sorted by importance

BUGS
* [x] On new mails, the list is not automatically refreshed

ENHANCEMENTS
* [x] We need to not show the color of the account when there is only one. Simply do not set the background-color of `.mail-account-color`
* [x] The title says »All inboxes - - Mail - ownCloud« (note the »- -« double dash, should be just a single one because there’s no account to show)

Ref https://github.com/owncloud/mail/pull/750

**Comment by jancborchardt** [comment]
Some of these are small issues good as starters, others are pretty high priority to solve. Anyone who wants to take a stab at them is welcome :) @DeepDiver1975 @ChristophWurst @irgendwie @zinks- @aidanamavi @colmoneill :)

**Comment by ChristophWurst** [comment]
@jancborchardt I added another issue @aidanamavi and I discovered while debugging #834: the ``to`` parameter is more or less ignored/useless

**Comment by jancborchardt** [comment]
@ChristophWurst please check off what was fixed by #836 :)

**Comment by DeepDiver1975** [comment]
> account selector in composer does not select any account when unified inbox is the active "account"

@jancborchardt which one should be choosen? From the last selected message?

**Comment by jancborchardt** [comment]
@DeepDiver1975 yes, last active account = account of last open folder/message.

**Comment by jancborchardt** [comment]
@DeepDiver1975 and, the empty first entry should obviously be removed from the dropdown.
