### ISSUE TITLE
account color indicator strange position

### ISSUE THREAD

**Issue by ChristophWurst** [owncloud/mail#804]
One of my mail account's mail address is pretty long, so an ellipsis was shown before the unified inbox merge. Now it's gone + the new color thing has a strage position with this specific account:
![](https://cloud.githubusercontent.com/assets/1374172/8239264/0f6f82ca-15fb-11e5-9343-3abac4f4c3e1.png)

@jancborchardt @aidanamavi any idea?

**Comment by jancborchardt** [comment]
Whoops, my fault. Self-assigning. Any new contributor who wants to dive into design fixes can take this up though! :)
