### ISSUE TITLE
Some errors on latest master ....

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/mail#807]
{"reqId":"ae058bed3f3dc112f433bd0d3a913133","remoteAddr":"178.25.225.40","app":"PHP","message":"Argument 8 passed to OCA\\Mail\\Controller\\AccountsController::__construct() must implement interface OCP\\ILogger, instance of OCA\\Mail\\Service\\Logger given, called in \/var\/www\/owncloud\/apps3\/mail\/appinfo\/application.php on line 68 and defined at \/var\/www\/owncloud\/apps3\/mail\/lib\/controller\/accountscontroller.php#102","level":3,"time":"2015-06-19T09:27:24+00:00","method":"POST","url":"\/index.php\/apps\/mail\/accounts\/-1\/send"}

{"reqId":"bdedba33b325a693e1fbd6fa1aebb558","remoteAddr":"178.25.225.40","app":"PHP","message":"usort() expects parameter 1 to be array, null given at \/var\/www\/owncloud\/apps3\/mail\/lib\/service\/unifiedmailbox.php#63","level":3,"time":"2015-06-19T09:33:19+00:00","method":"GET","url":"\/index.php\/apps\/mail\/accounts\/-1\/folders\/YWxsLWluYm94ZXM=\/messages"}

**Comment by ChristophWurst** [comment]
fixed in #806, our log wrapper doesn't implement the ``ILogger`` interface

https://github.com/owncloud/mail/pull/806/files#diff-5bd6b7207da4e0ec68c11bc2d8ffe756L91

**Comment by DeepDiver1975** [comment]
> fixed in #806, our log wrapper doesn't implement the ILogger interface

cool - thx - did we yet test if #806 is working on stable7?

**Comment by ChristophWurst** [comment]
No, I'll have to set up a stable7 instance.

Would it be possible to have travis test stable7 too?

**Comment by ChristophWurst** [comment]
we do test it (stable7 + mysql) on travis

**Comment by DeepDiver1975** [comment]
> we do test it (stable7 + mysql) on travis

yes - but we do not test appframeworks phpdoc parsing to get an understanding of parameter types - may guts feeling is telling be that this feature was not available in oc7

**Comment by LukasReschke** [comment]
Was no PHPDoc and simply a fail at https://github.com/owncloud/mail/pull/806/files#diff-5bd6b7207da4e0ec68c11bc2d8ffe756L102 :see_no_evil:

**Comment by DeepDiver1975** [comment]
> yes - but we do not test appframeworks phpdoc parsing to get an understanding of parameter types - may guts feeling is telling be that this feature was not available in oc7

I love version information on our public api - https://github.com/owncloud/core/blob/master/lib/public/appframework/controller.php#L157

so this change is okay :+1:
