### ISSUE TITLE
Admin user (with database access) can access all mail accounts

### ISSUE THREAD

**Issue by tflidd** [owncloud/mail#809]
You store the passwords of mail accounts in some encrypted form. But you can just duplicate an entry and change user_id and name and hijack this mail account (you don't need to know the password).

I know it's probably impossible to protect users against an admin with full access to the system. But if you mess up a restore of a backup and/or change the user-ids, someone can get access to another users mail account by accident. 
You integrate the mail password in the login process (like for a webmailer) and don't store it permanently.

**Comment by Xenopathic** [comment]
So this is a feature request for supporting mail accounts where the password used is the login password?

**Comment by tflidd** [comment]
That's one option. Or at least take something like the server-side-encryption, where the SSL-keys are  protected by the login-password.

**Comment by DeepDiver1975** [comment]
We plan to add background/cron jobs to the mail app as well - without access to the account this will not work.

**Comment by jancborchardt** [comment]
So, we close this?

**Comment by Xenopathic** [comment]
@jancborchardt No, I think this is a valid enhancement request. Think of it as similar to the 'SMB/CIFS with OC login' external storage that we have available. It should be possible to use the ownCloud login password to connect to mail accounts, without storing that password anywhere (or alternatively, encrypting the password with the user's login password). Obviously background jobs would be disabled in this circumstance.

**Comment by jancborchardt** [comment]
Sooo @Xenopathic @DeepDiver1975 any update here? I’m closing since there hasn’t been any update or interest in a year, feel free to open a pull request if it’s still current.
