### ISSUE TITLE
Decrease unread counter of inboxes when messages are read in unified inbox

### ISSUE THREAD

**Issue by ChristophWurst** [owncloud/mail#812]
Reading messages in the unified inbox does not decrease the unread counter of the respective inbox

**Comment by jancborchardt** [comment]
Already in https://github.com/owncloud/mail/issues/803 – should we rather have individual issues for that? cc @DeepDiver1975

**Comment by DeepDiver1975** [comment]
> Already in #803 – should we rather have individual issues for that? cc @DeepDiver1975

Having them all in one seems find for me.

**Comment by ChristophWurst** [comment]
> Already in #803 – should we rather have individual issues for that? cc @DeepDiver1975

Whoops sorry

**Comment by DeepDiver1975** [comment]
No worries.
