### ISSUE TITLE
Mail is always using AutoConfig

### ISSUE THREAD

**Issue by Nawuko** [owncloud/mail#813]
The check on line https://github.com/owncloud/mail/blob/master/lib/controller/accountscontroller.php#L199 dosent work. $_POST elements are strings, so this IF can never be "false".

Edit: Tested with the current commit 1695a91dc50d69ca7c08771c290f840104224502 using owncloud  https://github.com/owncloud/core/commit/5ed9743570173fbea59f150c2fe8da8d6c681cba

**Comment by DeepDiver1975** [comment]
$autoDetect is a boolean - see https://github.com/owncloud/mail/blob/master/lib/controller/accountscontroller.php#L191

**Comment by ChristophWurst** [comment]
@DeepDiver1975 I thought so too, but to be sure I added ``error_log(gettype($autoDetect))`` for quick debugging this, and I get ``string`` in the logs.

Should casting also work for POST requests? [Documentation](https://doc.owncloud.org/server/8.1/developer_manual/app/controllers.html) only mentions GET requests

**Comment by Nawuko** [comment]
Yes it SHOULD be a boolean but it is not, that is my whole point.

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 I thought so too, but to be sure I added error_log(gettype($autoDetect)) for quick debugging this, and I get string in the logs.
> 
> Should casting also work for POST requests? Documentation only mentions GET requests

hmmmm .... should make no difference

@Raydiation bug or feature? THX

**Comment by Raydiation** [comment]
Should be casted to a Boolean, see https://github.com/owncloud/core/blob/master/lib/private/appframework/http/dispatcher.php

**Comment by DeepDiver1975** [comment]
@Nawuko @ChristophWurst please test #814 - THX

**Comment by Nawuko** [comment]
bool and boolean both works. The fault was actually the space between bool and $autoDetect.
Fixed with https://github.com/owncloud/mail/pull/814

**Comment by Nawuko** [comment]
Ohh.

error_log(gettype($smtpPort)) also returns string. @DeepDiver1975 I think it's a general issue with spaces between the type and value name.

**Comment by ChristophWurst** [comment]
@Nawuko good catch! That seems to be the problem, so I opened another PR where I fix all those PHPDoc types: #815

**Comment by Nawuko** [comment]
@ChristophWurst I found the same error on different apps (like activity). All returning a string as type and not a int, bool or so. Maybe you should consider changing the regex to something like this: https://regex101.com/r/jI1zR0/2

**Comment by ChristophWurst** [comment]
@Nawuko could you please open an issue for that in core? https://github.com/owncloud/core/issues thanks a lot for debugging this :-)

**Comment by Raydiation** [comment]
And submit a pull request, should be simple :)
