### ISSUE TITLE
vacation messages

### ISSUE THREAD

**Issue by aspdye** [owncloud/mail#816]
Would be nice to add a function to send "vacation messages" ;)

**Comment by ChristophWurst** [comment]
Do you mean an autoresponder? https://en.wikipedia.org/wiki/Autoresponder

**Comment by Xenopathic** [comment]
This can be implemented via the Sieve protocol, #564

**Comment by aspdye** [comment]
:+1: yes. We could Integrate Filters via Sieve. Should be inside the Horde Library ;)

**Comment by ChristophWurst** [comment]
Let's continue in #564
