### ISSUE TITLE
CSS coding style

### ISSUE THREAD

**Issue by ChristophWurst** [owncloud/mail#817]
ATM there are many CSS classes with ``_`` in their names:
- ``.mail_account`` but also ``.mail-account-name``
-  ``#mail_messages`` and ``#mail-message``
- …

This can be really confusing and therefore ``_`` should be replaced by ``-``, see https://github.com/owncloud/core/issues/308

**Comment by jancborchardt** [comment]
Yup. Keep in mind it's _HTML_ classes and IDs, so HTML, CSS and JS has to be adjusted. Also some of the class/ID naming is nearly duplicate and confusing.

**Comment by ChristophWurst** [comment]
A lot has been fixed @Tagada85 in #1224. Thx.
