### ISSUE TITLE
Scroll to top of message when opening new one

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/mail#821]
1. Open a message (_non_-HTML)
2. Scroll down a bit
3. Open another non-HTML message
4. See how you are scrolled down

When opening a new message, you should always be scrolled to the top.
(I guess this happens since the message caching.)
Except maybe in the future we could remember scroll positions for individual messages, but for now scrolling to top is the best solution, otherwise it’s confusing.

**Comment by ChristophWurst** [comment]
@jancborchardt I couldn't reproduce this neither on Firefox nor on Chrome.
Where should I scroll down? Inside the message view? Or maybe the folder view?

When I switch from one non-HTML message to another the new message (view) is scrolled to top

**Comment by jancborchardt** [comment]
You need to scroll inside the message view. It probably only occurs with cached text-only messages. Maybe only with ones which have been open before. Try on mobile as well – that’s where I first saw the issue.

**Comment by jancborchardt** [comment]
I will check this out.

**Comment by jancborchardt** [comment]
Can’t reproduce anymore.
