### ISSUE TITLE
Prefetching messages in background marks them as read

### ISSUE THREAD

**Issue by ChristophWurst** [owncloud/mail#822]
As noticed by @DeepDiver1975, messages are marked as read once they are fetched in background

**Comment by jancborchardt** [comment]
Yeah, I also noticed that since recently! And I was wondering if I had amnesia of read emails …

I’d say priority rather than starter issue.

**Comment by ChristophWurst** [comment]
Some additional debugging information:
horde.log says something like
```
C: 4 UID FETCH 193 (ENVELOPE BODYSTRUCTURE FLAGS RFC822.SIZE INTERNALDATE BODY[HEADER.FIELDS (IMPORTANCE LIST-POST X-PRIORITY CONTENT-TYPE)])
S: * 123 FETCH (UID 193 FLAGS (\Seen)....
```
when opening an unread message (simply called the show route in the browser), so it seems to be flagged as read automatically.

I have to questions regarding this issue:
- can we prevent the IMAP server from automatically setting the flag?
- do we break any existing seen/unseen functionality if we do so?

@DeepDiver1975 @Xenopathic @clementhk

**Comment by Xenopathic** [comment]
We can set the `'peek' => true` flag on a Horde_Imap_Client_Fetch_Query when calling `bodyPart()` or related functions.
