### ISSUE TITLE
Replies do not include the original message anymore / inline replying broken

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/mail#831]
On current master, inline replying is broken because the text of the previous message is not filled in the reply field anymore. It’s just 3 blank lines with `>` for me.

Can you reproduce @ChristophWurst @irgendwie @zinks-?

**Comment by ChristophWurst** [comment]
Cannot reproduce - tested with FF and Chrome. The original message is included as expected

**Comment by jancborchardt** [comment]
Hm, this happens for quite a few mails with me. Sometimes it’s only the last reply. Test with more mails maybe?

Can anyone of you reproduce @irgendwie @DeepDiver1975 @aidanamavi?

**Comment by DeepDiver1975** [comment]
@jancborchardt this should be fixed by #843

**Comment by jancborchardt** [comment]
Seems to, yes.
