### ISSUE TITLE
Cannot send email: "Error when parsing angle address."

### ISSUE THREAD

**Issue by cfra** [owncloud/mail#833]
While viewing emails via IMAP works fine, I cannot send any email from my account. Both for replies and new emails it fails with only this error message appearing in the log:

Sending mail failed: Error when parsing angle address.

**Comment by jancborchardt** [comment]
@cfra which errors does the owncloud.log (in your data folder) show?

**Comment by cfra** [comment]
{"reqId":"8eb0a9647964cbb8afd7de8e864b3847","remoteAddr":"172.19.132.90","app":"mail","message":"Sending
mail failed: Error when parsing angle
address.","level":3,"time":"2015-06-30T16:05:34+00:00"}

**Comment by jancborchardt** [comment]
Any idea @DeepDiver1975 @ChristophWurst @clementhk – what more info do we need?

**Comment by clementhk** [comment]
Mind to tell us sender/receiver's addresses?

**Comment by cfra** [comment]
This ended up to be a pebcak problem on my side. My IMAP/SMTP servers take username@domain as username for logging in and for some reason, I ended up with the from-address being username@domain@domain - no wonder it complains about the address. I re-entered the account information into the mail app and now it works flawlessly.
