### ISSUE TITLE
Define coding & JS guidelines

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/mail#840]
We need to agree on some basic guidelines for our Mail app. Otherwise this will be confusing for new contributors. (Base for discussion is the comment from @DeepDiver1975 at https://github.com/owncloud/mail/pull/834#issuecomment-118004788) – FULLY DISCUSSABLE

1. mailbox sync should be done within checkNotification (yes - adjusting the name might be reasonable)
2. we should minimize calls to the server as much as possible
3. we should rely on existing features and functionalities by using frameworks and libraries
4. we should not use timers (I'll come up with as solution for my own timer as well)
5. the js side of this app should step by step be migrated to fully be a backbone app
6. (by aidan) which overlapping functionality should we use? i.e., typeof vs. isBoolean, or _.each vs. $.each, Javascript, vs. Underscore vs. jQuery vs. Backbone
7. ...

Please chime in @aidanamavi @ChristophWurst @irgendwie @clementhk @Xenopathic @LukasReschke

**Comment by clementhk** [comment]
I always + 1 to readability + performance.
I think things can just be merged and improve in separated PR if one doesn't fully agree with minor details.

**Comment by clementhk** [comment]
@aidanamavi would be cool to have you around, not all of us likes front-end works like you do :)

**Comment by aidanamavi** [comment]
@clementhk Thanks Clement. I really do enjoy front-end UX stuff :)

1. We should use loadMessages, not checkForNotifications, to sync the message list.
loadMessages respects all message changes whereas checkForNotification only respects brand new messages and no changes whatsoever. These can be merged, but require a large rewrite/PR.

2. Reducing calls is always a good idea. However, pragmatism over idealism.
We should accept new code if it resolves an issue, and adds a call, if there is no other written code that can do it without the call; we can remove the call in a future commit.

3. jQuery, Underscore, Backbone.
jQuery for the DOM. Underscore is a Backbone dependency. Backbone for the MVC.
[Exoskeleton](http://exosjs.com/) might be a great replacement for Underscore and Backbone in the future.
https://stackoverflow.com/questions/21553449/does-backbone-js-really-require-underscore-js

4. I can't speak for timers in all cases, however, a timer is better than listening for a scroll event.
Scroll events execute for every pixel whereas a timer executes once per interval. Scrolling a message list, for example, would execute a scroll event over 1428 times in as little as 250ms whereas a timer would fire 1 time in as much as 1000ms. In other words, 1428 AJAX calls for identical information vs. 1.

5. Is this related to list item number 6? If not, can you please clarify @DeepDiver1975 

6. Backbone, Underscore, jQuery, Javascript
We're all interested in execution efficiency, which complicates answering this question. If we can all agree to overlook the efficiency for the sake of simplifying this resolution, this priority should suffice. Like list item number 2, we should approach this with pragmatism. Changing something trivial like typeof to isBoolean (Javascript to Underscore) may be reasonable to request in a commit, however, complete rewrites of functions and methods should be overlooked until something better written is committed.

**Comment by DeepDiver1975** [comment]
> We should use loadMessages, not checkForNotifications, to sync the message list.
> loadMessages respects all message changes whereas checkForNotification only respects brand new messages and no changes whatsoever. These can be merged, but require a large rewrite/PR.

LoadMessages would be sufficient if we only talk about the activly loaded mailbox.
checkForNotifications is designed to return the required information for multiple mailboxes.

e.g. we also want to get updated unread counters on all folders - checkForNotifications has to return this information one point in time.

While checkForNotifications as of today does not yet provide all necessary information we should *from my perspective* keep the design principle here.

Does that make sense?

**Comment by DeepDiver1975** [comment]
> however, a timer is better than listening for a scroll event.
> Scroll events execute for every pixel whereas a timer executes once per interval. Scrolling a message list, for example, would execute a scroll event over 1428 times in as little as 250ms whereas a timer would fire 1 time in as much as 1000ms. In other words, 1428 calls for identical information vs. 1 unique call.

hmm - sounds reasonable - isn't all that already covered in what so ever scrolling/lazyloading/infinite scroll library?

**Comment by DeepDiver1975** [comment]
> Is this related to list item number 6? If not, can you please clarify @DeepDiver1975

Well - from a historical point of view: this app started out as a pure jquery app.
One point in time I did introduce backbone and I kind of like it (compared to other frameworks).

In order to get a clean implementation the next step for me is to migrate the remaining code base to backbone.

**Comment by ChristophWurst** [comment]
I suggest to extend the existing [js readme](https://github.com/owncloud/mail/blob/master/js/README.md). Additionally we could also add a readme for php related guide lines in to the ``lib`` folder.
