### ISSUE TITLE
JS issue with mailto composer view

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/mail#847]
When sending a mail from the standalone mailto composer, this error comes up in the console:
`TypeError: Mail.UI.messageView is undefined. In composer.js:289:5`

@ChristophWurst

**Comment by ChristophWurst** [comment]
@jancborchardt can't reproduce this with Firefox nor Chrome, but I'll have a look at it the next days ;-)

**Comment by jancborchardt** [comment]
(Browser was Firefox btw.)
