### ISSUE TITLE
dual scrollbar

### ISSUE THREAD

**Issue by mitpro** [owncloud/mail#848]
At long e-mails got dual scrollbars (from iframe)

![owncloud_mail_dualscrollbar](https://cloud.githubusercontent.com/assets/12111420/8595065/48a32784-2647-11e5-857a-12322e017e78.PNG)

In file templates/index.php change attribute of iframe (scrolling) - class=mail-message-body: line 101 or 108:

iframe scrolling="no" src="{{htmlBodyUrl}}"   sandbox="allow-popups allow-same-origin" seamless

works well

![owncloud_mail_nodualscrollbar](https://cloud.githubusercontent.com/assets/12111420/8595061/460fc3d8-2647-11e5-9f82-84feecb0ba07.PNG)

owncloud version: 8.1 stable
php: 5.5.9
webserver: Apache/2.4.7 (Ubuntu)
server os: Ubuntu 14.04.2 LTS
client os: Windows 7 x64
browser: chrome & firefox

**Comment by jancborchardt** [comment]
@mitpro can you submit a pull request with your fix? :) Then we can simply test it out and merge it if it works.
