### ISSUE TITLE
Call to undefined method TemplateResponse::setContentSecurityPolicy()

### ISSUE THREAD

**Issue by LJPapenfort** [owncloud/mail#850]
### Steps to reproduce
1. Clone mail from git, get dependencies with composer
2. Activate mail app
3. Try to open mail app

### Expected behaviour
The mail app should open

### Actual behaviour
I get a blank page

### Server configuration
**Operating system**: Ubuntu 14.04

**Web server:** Nginx 1.8.0-1+trusty1 

**Database:** MariaDB 10.0.20+maria-1~trust

**PHP version:** php5 5.5.9+dfsg-1ubuntu4.1

**ownCloud version:** (see ownCloud admin page) ownCloud 8.0.4 (stable) 

**Updated from an older ownCloud or fresh install:** Updated from 8.0.2

**List of activated apps:**Enabled:
 - activity
 - admin_dependencies_chk
 - bookmarks
 - calendar
 - contacts
 - documents
 - files
 - files_external
 - files_pdfviewer
 - files_sharing
 - files_texteditor
 - files_trashbin
 - files_versions
 - files_videoviewer
 - firstrunwizard
 - gallery
 - mail
 - music
 - search_lucene
 - templateeditor
 - updater

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => 'xxx',
  'passwordsalt' => 'xxx',
  'trusted_domains' => 
  array (
    0 => '10.0.0.2',
    1 => 'DOMAIN',
    2 => '10.0.0.1',
  ),
  'overwritehost' => 'DOMAIN',
  'overwriteprotocol' => 'https',
  'overwritewebroot' => '',
  'overwritecondaddr' => '^10\\.0\\.0\\.1$',
  'datadirectory' => '/storage/owncloud',
  'overwrite.cli.url' => 'http://10.0.0.2',
  'dbtype' => 'mysql',
  'version' => '8.0.4.2',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'dbpassword' => 'xxx',
  'installed' => true,
  'knowledgebaseenabled' => true,
  'enable_avatars' => true,
  'log_type' => 'syslog',
  'log_authfailip' => true,
  'logtimezone' => 'Europe/Berlin',
  'cipher' => 'AES-256-CFB',
  'theme' => '',
  'maintenance' => false,
  'secret' => 'xxx',
  'loglevel' => '0',
);
```

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no
### Client configuration
**Browser:** Firefox 38.0

**Operating system:** Ubuntu 14.04

#### Web server error log
```
2015/07/09 14:15:27 [error] 11518#0: *3256 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Call to undefined method OCP\AppFramework\Http\TemplateResponse::setContentSecurityPolicy() in /var/www/owncloud/apps/mail/lib/controller/pagecontroller.php on line 85" while reading response header from upstream, client: 10.0.0.1, server: 10.0.0.2, request: "GET /index.php/apps/mail/ HTTP/1.0", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "DOMAIN" referrer: "https://DOMAIN/index.php/apps/files/"
```

#### ownCloud log (data/owncloud.log)
```
nothing related (i.e. at ~2015/07/09 14:15:27)
```

**Comment by ChristophWurst** [comment]
@LukasReschke

**Comment by DeepDiver1975** [comment]
I cannot reproduce this. This code is only executed in case the class is available.

@tehdartherer as a workaround please comment the code in question so that you can use the app.

THX

**Comment by DeepDiver1975** [comment]
@tehdartherer is there an ownCloud 8.1 running onthis server as well? Maybe php include paths are mixed up?

**Comment by tehdartherer** [comment]
Uncommenting it makes the app usable. Thanks for that tip.
To display html mail I had to uncomment a similar line in 
owncloud/apps/mail/lib/controller/messagescontroller.php .

Regarding the php include paths:
No there is only one owncloud instance running. Nonetheless I could inspect the paths. Any hint where I should look for what exactly?

**Comment by jancborchardt** [comment]
@LukasReschke homie, we need your expertise here! :)

**Comment by jancborchardt** [comment]
Closing because it can’t be reproduced, assumed fixed. Let us know if the issue persists, then we can reopen. :)
