### ISSUE TITLE
Folders were created two times

### ISSUE THREAD

**Issue by Bullnados** [owncloud/mail#858]
German and English folders shown and created.
![unbenannt](https://cloud.githubusercontent.com/assets/11041576/8657678/5e520982-299f-11e5-91ed-5aaef7ddd52c.PNG)

**Comment by ChristophWurst** [comment]
@Bullnados are those folders only shown in the mail app or also in other mail clients?

As far as I know this app doesn't create folder's like 'Spam' automatically.

**Comment by Bullnados** [comment]
Also in an other (web)-mail client. I try to reproduce it with new mail, but i cant. With my main account i have a similiar problem but there i have just duplicate "Papierkorb" and "Trash" also shown in webmail and Outlook

**Comment by Bullnados** [comment]
Close that until I habe more time to reproduce this issue.
