### ISSUE TITLE
Problems using PHP-Mail

### ISSUE THREAD

**Issue by aspdye** [owncloud/mail#868]
Getting this Error if i try to connect via php-mail:

 	Creating account failed: Error connecting to SMTP server. 

Have configured the config.php correctly (think so) :( I didnt type anything into the smtp-fields.

Config:

<?php
$CONFIG = array (
  'instanceid' => 'XX',
  'passwordsalt' => 'XX',
  'secret' => 'XX',
  'trusted_domains' => 
  array (
    0 => 'XX',
  ),
  'datadirectory' => 'XX',
  'overwrite.cli.url' => 'XX',
  'dbtype' => 'mysql',
  'version' => '8.1.0.8',
  'dbname' => 'XX',
  'dbhost' => 'XX',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'XX',
  'dbpassword' => 'XX',
  'logtimezone' => 'UTC',
  'installed' => true,
  'app.mail.transport' => 'php-mail'
);

**Comment by jancborchardt** [comment]
Please post all the info we ask for in the issue template: https://raw.githubusercontent.com/owncloud/core/master/issue_template.md

**Comment by aspdye** [comment]
### Steps to reproduce
1. Starting Mail-App
2. Type in Adress, Name, IMAP Details, !SMTP empty!
3. Click on "Connect"

### Expected behaviour
Connecting to Mail Account using PHP-Mail

### Actual behaviour
Tells, that the App fails to connect to SMTP.

### Server configuration
**Operating system**:
Linux (1and1)
**Web server:**
1and1 Shared Hosting
**Database:**
MySQL 5
**PHP version:**
5.6
**ownCloud version:** (see ownCloud admin page)
8.1
**Updated from an older ownCloud or fresh install:**
fresh!
**List of activated apps:**
Calendar, Contacts, Mail (and the standard apps of ownCloud 8.1)
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**
<?php
$CONFIG = array (
'instanceid' => 'XX',
'passwordsalt' => 'XX',
'secret' => 'XX',
'trusted_domains' =>
array (
0 => 'XX',
),
'datadirectory' => 'XX',
'overwrite.cli.url' => 'XX',
'dbtype' => 'mysql',
'version' => '8.1.0.8',
'dbname' => 'XX',
'dbhost' => 'XX',
'dbtableprefix' => 'oc_',
'dbuser' => 'XX',
'dbpassword' => 'XX',
'logtimezone' => 'UTC',
'installed' => true,
'app.mail.transport' => 'php-mail'
);
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system --public
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No.
**Are you using encryption:** yes/no
No.
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No.

```
On ownCloud 7+ with access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

On ownCloud 6 with access to your command line run e.g.:
sqlite3 data/owncloud.db or mysql -u root -p owncloud
then execute:  select * from oc_appconfig where appid='user_ldap';

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query above.

Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**
Microsoft Edge, Chrome, Firefox
**Operating system:**
Windows 10 Insider Preview, Windows 8.1, ubuntu 14.10, 
### Logs
#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Creating account failed: Error connecting to SMTP server. 
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by DeepDiver1975** [comment]
Did you install the app from git? The version on the appstore does not yet contain the necessary code.

**Comment by aspdye** [comment]
OK. This is embarrassing. actually I use the appstore version. I will change that. Question: Can I update the Git version (and move to the appstore version when the app is stable)?

**Comment by DeepDiver1975** [comment]
basically you remove the mail folder from your apps folder and clone the code from github

```sh
git clone https://github.com/owncloud/mail.git

**Comment by DeepDiver1975** [comment]
closing this for now - THX
