### ISSUE TITLE
Adding second account results in message loading issue

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/mail#870]
On first run, or after you deleted the second account and add another one, there are issues with the unified inbox. Mails don’t get loaded, the message list is outdated.

cc @ChristophWurst @irgendwie @zinks-

**Comment by ChristophWurst** [comment]
let me have a look at this…

**Comment by ChristophWurst** [comment]
step | result
-----|------
add first account | :white_check_mark:
add second account | :white_check_mark:
delete second account | :white_check_mark:
add back second account | :boom:
