### ISSUE TITLE
autocomplete from ALL email addresses

### ISSUE THREAD

**Issue by jospoortvliet** [owncloud/mail#879]
If you have an index of all mails, you can auto-add all names and mail addresses to the address book and autocomplete from every email address ever send to or received or even just mentioned in an email. It is absolutely nice to know that if you type a name in your 'to' and the mail app doesn't auto-complete there is no point trying to search for an email from that person or look otherwise to find an address: it isn't there, go google for it ;-)

**Comment by jancborchardt** [comment]
Google Mail adds these folks as kinda shadow-contacts to Google Contacts under the entry »Contacted« or so. So they do not sync down to your clients, but they are there and can be handled by Gmail.

**Comment by ChristophWurst** [comment]
@jospoortvliet that, and php7 support has been implemented in mail 0.4 which has been released today ;-)

**Comment by jospoortvliet** [comment]
Whoah! :+1:

**Comment by jancborchardt** [comment]
So @jospoortvliet wasn't this the feature which kept you from using ownCloud Mail in production? Or what to fix next? ;)
