### ISSUE TITLE
If you change your mail password on the server, the interface fails to connect and shows an endless spinner

### ISSUE THREAD

**Issue by BernhardPosselt** [owncloud/mail#887]
This is in the logs: **\"Horde_Imap_Client_Exception\",\"Message\":\"Authentication failed.\"**

How to reproduce:
* Set up a mail account
* Change your mail password (e.g. using passwd myuser on the server)
* Reload the webinterface

**Comment by DeepDiver1975** [comment]
Basically a known issue.  Thanks!

**Comment by ChristophWurst** [comment]
dup of #1475
