### ISSUE TITLE
javascript not enabled 

### ISSUE THREAD

**Issue by tony5** [owncloud/mail#888]
when clicking on a link in an email the redirect does not work. if you click the link you will be forwarded to the link page. at the top of the screen I see  div id="nojavascript"> <div> This application requires JavaScript for correct operation. Please <a href="http://enable-javascript.com/" target="_blank" rel="noreferrer">enable JavaScript</a> and reload the page. </div> </div>

if I view the page http://enable-javascript.com/ is says that it is enabled.

this happens on a clean install of OC 8.1 and OC 8.0.5

**Comment by DeepDiver1975** [comment]
In an html message or a plain text mail? Thx

**Comment by tony5** [comment]
I think it is plain text.
for example responding to a email from github clicking the link "view it on github" will create the problem.

I will try other links and see if they work

**Comment by jancborchardt** [comment]
Maybe also something for @LukasReschke regarding the redirect CSP stuff?

**Comment by LukasReschke** [comment]
Which version of the app etc? - We really need an issue template for this repository as well :speak_no_evil:

**Comment by jancborchardt** [comment]
@tony5 please fill out the issue template: https://raw.githubusercontent.com/owncloud/core/master/issue_template.md

**Comment by tony5** [comment]
I will complete a issue template later today.
in the meantime I think the link being generated is not working correctly for me.
it looks like %2F is being generated in the URL and being ignored by the browser.
if I adjust the link adding / in place of %2F I will get a page with a redirect warning and a click to visit box.

**Comment by tony5** [comment]
### Steps to reproduce
1. click view it on GitHub link in email
2. click redirect link in html mail
3.

### Expected behaviour
Tell us what should happen

should be redirected to webpage

### Actual behaviour
Tell us what happens instead

redirect page opens and spinner spins and does not stop.
click here if dot automatically directed link will open page.

removing %2F in url will open a redirect link page 

### Server configuration
**Operating system**:
ubuntu 14.4 

**Web server:**
apache 2.4

**Database:**
mysql
**PHP version:**
5.5

**ownCloud version:** (see ownCloud admin page)
8.1
**Updated from an older ownCloud or fresh install:**
fresh install
**List of activated apps:**
 - activity: 2.0.1
 - calendar: 0.7.2
 - contacts: 0.4.0.0
 - documents: 0.10.0
 - files: 1.1.9
 - files_locking: 
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - files_videoviewer: 0.1.3
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - mail: 0.1.3
 - news: 5.3.8
 - provisioning_api: 0.2
 - templateeditor: 0.1
 - updater: 0.6


**The content of config/config.php:**

<?php
$CONFIG = array (
  'instanceid' => 'xxxx',
  'passwordsalt' => 'xxxx',
  'secret' => 'xxxxxxx',
  'trusted_domains' => 
  array (
    0 => 'xxx.lan',
  ),
  'datadirectory' => '/var/www/html/owncloud/data',
  'overwrite.cli.url' => 'http://xxx.lan/owncloud',
  'dbtype' => 'mysql',
  'version' => '8.1.0.8',
  'dbname' => 'owncloud1',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'me',
  'dbpassword' => 'password',
  'logtimezone' => 'UTC',
  'installed' => true,
  'theme' => '',
  'maintenance' => false,
  'memcache.local' => '\OC\Memcache\APCu',
  'app.mail.server-side-cache.enabled' => true,
);

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
### Client configuration
**Browser:**
firefox
**Operating system:**
ubuntu 14.04
### Logs
#### Web server error log
no errors


#### ownCloud log (data/owncloud.log)
{"reqId":"n+uXnZqvyE0STypFRL+O","remoteAddr":"","app":"PHP","message":"Undefined index: REQUEST_URI at \/var\/www\/html\/owncloud\/apps\/documents\/appinfo\/app.php#49","level":3,"time":"2015-07-20T16:15:01+00:00"}

#### Browser log
```


Content Security Policy: The page's settings blocked the loading of a resource at self ("script-src http://xxx.lan 'unsafe-eval'").
http://xxx.lan/owncloud/index.php/apps/mail/
Line 0

**Comment by tony5** [comment]
@jancborchardt 
If I do a ctrl + click on the links it will work fine.
not what I expected.
take care

**Comment by jancborchardt** [comment]
@LukasReschke ^ something for you to fix. ;)

**Comment by jancborchardt** [comment]
@LukasReschke can you check that out? ^

**Comment by itheiss** [comment]
Tested with latest version from master and can't reproduce this. I took a mail from GitHub an clicked the link as mentioned. Everything was fine. No erros no hassels.

Can anybody else trying to reproduce this?

**Comment by PoPoutdoor** [comment]
Tested with latest master, with other mail's link on Firefox, text and html content.

1. middle click -> direct open in new tab (bypass Mail code)
2. ctrl-click -> direct open in new tab (bypass Mail code)
3. right-mouse-click -> run Mail code (show redirect message, but no auto redirect) and open link target.

No error with GitHub's mail on right-mouse-click.

**Comment by foxbow** [comment]
I'm seeing the same issue on a pretty different set-up: 

Is it possible that it depends on the user language? My installation is set to 'german', maybe that is a hint.

### Server configuration
**Operating system**:
Debian 6

**Web server:**
nginx

**Database:**
sqlite

**PHP version:**
5.4.41-0+deb7u1

**ownCloud version:** (see ownCloud admin page)
8.1.1

**Updated from an older ownCloud or fresh install:**
Uddated from 8.0.4 (whcih has shown the same error)

**List of activated apps:**
Activity  1.2.0
Calendar  0.10.24
Deleted files  0.6.2
PDF Viewer  0.7
Share Files  0.6.2
Text Editor  0.4
Updater  0.4
Versions  1.0.6
Contacts  0.4.0.0
Gallery  13.0.0
Mail  0.1.3

**The content of config/config.php:**
$CONFIG = array (
  'instanceid' => '5112297a1ec88',
  'passwordsalt' => '...',
  'datadirectory' => '/../owncloud/data',
  'dbtype' => 'sqlite3',
  'version' => '8.1.1.3',
  'installed' => true,
  'loglevel' => '3',
  'maintenance' => false,
  'forcessl' => true,
  'theme' => '',
  'maxZipInputSize' => 1073741824,
  'allowZipDownload' => true,
  'trusted_domains' => 
  array (
    0 => '...',
  ),
  'mail_from_address' => 'cloud',
  'mail_smtpmode' => 'php',
  'mail_domain' => '...',
  'secret' => '...',
);

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no


### Client configuration
Google Chrome

**Operating system:**
Ubuntu 14.4 / 64

**Comment by PoPoutdoor** [comment]
@foxbow My language setting is Chinese, still cannot reproduce this. 

Can you try Firefox as client to verify the problem is not browser related?

**Comment by foxbow** [comment]
@PoPoutdoor Wicked, with Firefox I'm getting the "<div id="nojavascript"><div>Diese Anwendung benötigt...</div></div>" verbatim on the page, the HTML code including the <div> tags. But no autoforwarding. Clicking the link works - probably since the overlay DIV is not blocking it like on Chrome. Same behaviour with Firefox on Windows7. 

IE8 offers me the choice to either return to the 'Mail-App' or to click a large white bar which brings me to the target page. So with IE8 the there's no complaints about javascript not working, but no try to autoforward either.

Also external images are no longer loaded, that was working with the old version, but maybe it's some kind of side effect or pointing at a similar direction.

**Comment by PoPoutdoor** [comment]
@foxbow This is strange... no idea, maybe Mail app code corrupts while download, or problems with server filesystem while Mail app code is written to.

Anyway, it doesn't hurt to do a fsck on server, re-download and apply Mail app code to the server.

**Comment by foxbow** [comment]
@PoPoutdoor I'll go through the installation and see if anything changes when I tweak everything according to the installation/upgrade notes.

**Comment by ChristophWurst** [comment]
@tony5 could you please post the exact location the link points to in the message? It's probably something like ``https://xxxxxx/owncloud/index.php/apps/mail/redirect?src=http%3A%2F%2Fwww.example.com``

**Comment by ChristophWurst** [comment]
Also a screenshot of the shown page could help debugging this ;-)

**Comment by tony5** [comment]
left clicking on the link "Reply to this email directly or view it on GitHub." will produce 

![java-error](https://cloud.githubusercontent.com/assets/9308991/9502933/0a28424c-4c02-11e5-8416-70f21f2031e3.png)
the url would be 
owncloud/index.php/apps/mail/redirect?src=https%3A%2F%2Fgithub.com%2Fowncloud%2Fmail%2Fissues%2F888

**Comment by tony5** [comment]
@ChristophWurst
I also see this. the spinner will spin for ever until I click "click here if you are not automatically redirected"

![redirect](https://cloud.githubusercontent.com/assets/9308991/9503577/d098a234-4c05-11e5-9908-2e55a3d22c25.png)

**Comment by ChristophWurst** [comment]
Hm, looks like the problems described in https://github.com/owncloud/mail/issues/206…

**Comment by tony5** [comment]
@ChristophWurst 
the link you posted is 404

**Comment by ChristophWurst** [comment]
> @ChristophWurst
> the link you posted is 404

sorry. I fixed it ;-)

**Comment by Gomez** [comment]
Cant reproduce with current master.
@tony5 & @foxbow are using 0.1.3 so it is solved with the coming 0.2 and master.

Please test again with master or 0.2 (soon released).

**Comment by PoPoutdoor** [comment]
Dig up something from Horde site: http://wiki.horde.org/FAQ/Admin/Troubleshoot?referrer=FAQ%2FAdmin#toc9

**Comment by foxbow** [comment]
After an Update to 8.1.3 it all works fine for me too. On both Firefox and Chrome. Yay!
