### ISSUE TITLE
Reply box hard to reach for long mails

### ISSUE THREAD

**Issue by Bullnados** [owncloud/mail#900]
Why is the answer box at the bottom? If u have long Mails u have to scroll down every time.
Would it not be better to answer like in Outlook/Thunderbird. Perfect would be clicking answer/forward button and than reading mode change to writing mode. Would also more logical, because u read a mail form bot to top and not vice versa.

**Comment by jancborchardt** [comment]
We should introduce a floating reply button at the bottom of the viewport if the reply box is below the edge of the viewport.

**Comment by Bullnados** [comment]
But the box is still at bottom?

**Comment by jancborchardt** [comment]
@Bullnados yes, as with basically all other email apps.
