### ISSUE TITLE
JS error when open email

### ISSUE THREAD

**Issue by rakshazi** [owncloud/mail#915]
Hello!
When I try to open any email in app (latest version - cloned from repo 10 mins ago), I got JS error: "Uncaught ReferenceError: getScrollBarWidth is not defined" in helper.js, here is block of code with problematic function:
```javascript

	// adjust controls/header bar width
	window.adjustControlsWidth = function() {
		if($('#mail-message-header').length) {
			var controlsWidth;
			if($(window).width() > 768) {
				controlsWidth =
					$('#content').width() -
					$('#app-navigation').width() -
					$('#mail_messages').width() -
					getScrollBarWidth();
			}
			$('#mail-message-header').css('width', controlsWidth);
			$('#mail-message-header').css('min-width', controlsWidth);
		}
	};

```

I use Chrome 44.0.2403.125 (64-bit) Linux version from Google repo.

Please, fix this problem!

**Comment by jancborchardt** [comment]
@ChristophWurst @DeepDiver1975 getScrollBarWidth is from core/js/js.js – do we need to duplicate that function here, or is there a way to call it? When I tried I didn’t get that issue.

**Comment by DeepDiver1975** [comment]
> Please, fix this problem!

@rakshazi you are welcome to contribute to fix this problem - THX

**Comment by ChristophWurst** [comment]
@jancborchardt depends on whether that function is available in all supported OC core versions. Do you know  when it was introduced?

@rakshazi which OC version are use using?

**Comment by rakshazi** [comment]
@DeepDiver1975 I hate frontend developing and my JS is bad. Duplicating is very bad way and I have no good idea for fix this problem (if I know another way, I make pull request then).
@ChristophWurst OC version on my server is 8.0.4 stable, updated by official updater.

**Comment by DeepDiver1975** [comment]
8.0.4 does not know this function - https://github.com/owncloud/core/blob/v8.0.4/core/js/js.js

So we better duplicate the code in the mail app

**Comment by rakshazi** [comment]
@DeepDiver1975 ok, if I just duplicate this function in my local git repo (in apps dir), will be this good way? Or you have another way for this?
