### ISSUE TITLE
ownCloud as a Horde VFS backend

### ISSUE THREAD

**Issue by szepeviktor** [owncloud/mail#922]
(Virtual File System)

I'm planning to attach files from ownCloud in Horde Imp webmail.
1
Is Horde->ownCloud authentication or VFS (partly) implemented here in mail?
2
Is there a documentation on how to access ownCloud from another PHP application (Horde)?

**Comment by szepeviktor** [comment]
BTW Does mail support attaching files to emails from ownCloud?

**Comment by Xenopathic** [comment]
@szepeviktor I don't think implementing Horde VFS support is in the scope of the Mail app - you are talking about attaching files from ownCloud to Horde Webmail, which is a completely different project. We don't use the Webmail component, just IMAP Client and various other helper utilities.

**Comment by szepeviktor** [comment]
@Xenopathic Thank you for your answer.

Could you advise where to find documentation on ownCloud external API?

**Comment by Xenopathic** [comment]
@szepeviktor The easiest way is to leverage standard WebDAV via the `/remote.php/webdav` endpoint.
