### ISSUE TITLE
Delete mail in the middle, next displayed mail is the one above before deletion

### ISSUE THREAD

**Issue by PoPoutdoor** [owncloud/mail#923]
OC 8.1.0.8
Mail latest

Seems after you delete a message from the message list, default action is to load message newer than the one deleted.

Think about the procedure when you start working on message other than the first (top) one...

**Comment by aspdye** [comment]
Please follow the issue template so we get the info we need to be able to debug and fix the problem:
https://raw.githubusercontent.com/owncloud/core/master/issue_template.md

**Comment by jancborchardt** [comment]
@PoPoutdoor it is intended design to load the next newest mail. That allows you to work through mails chronologically. Especially helpful when there are multiple mails on the same topic while we do not have threading yet.

Or what do you mean?

**Comment by PoPoutdoor** [comment]
Let's say I read mail from the top of list, I keep this.

I click somewhere on the list to read the message of interest, click trash icon while I'm done with that message.

Before the deletion, message below is what I expected to read next.
I repeat read-trash/keep until I'm done with mail.

With current default date sort, every time the next message to display is jump up. So, I have to click one message below to get my message read-trash.

Until date sort can be set at UI, this behaviour brings user bad impressions working with Mail.

**Comment by jancborchardt** [comment]
Well, this is by design. If you want to read messages achronologically, you can start at the very top and delete from there, then the next one will be the next youngest. But if you want to properly read them chronologically, the next one will always be the next chronologically.
