### ISSUE TITLE
composer issue

### ISSUE THREAD

**Issue by PoPoutdoor** [owncloud/mail#928]
*console command:* php composer.phar install

*error message:* sh: hg: command not found

https://github.com/owncloud/mail/blob/master/composer.lock#L58

**Comment by clementhk** [comment]
Just install hg. 

Clement

**Comment by PoPoutdoor** [comment]
First of all, please update document about the requirement and procedure to install **hg**.

BTW, I'm not familiar with composer. So, how can I get **hg** and get it installed?

**Comment by Xenopathic** [comment]
`apt-get install mercurial`

`yum install mercurial`

`emerge mercurial`

`pacman -S mercurial`

One of those should do it. And the Mercurial requirement isn't one of ownCloud Mail's, it's one of the development tool Composer. Please go to their documentation for further instructions.
