### ISSUE TITLE
message.js error with keyboard delete (tooltip issue)

### ISSUE THREAD

**Issue by PoPoutdoor** [owncloud/mail#929]
If delete mail with mouse click on trash icon, no error.
After delete mail with keyboard, error in console:

> TypeError: Argument 1 of Document.elementFromPoint is not a finite floating-point value.

https://github.com/owncloud/mail/blob/master/js/views/message.js#L110

**Comment by jancborchardt** [comment]
@irgendwie @ChristophWurst @zinks- any idea?

**Comment by irgendwie** [comment]
@jancborchardt This happens bc a button event has no property clientX or clientY in comparison to mosue events. As currently the tipsies don't seem to work, is this workaround still needed (manually trigger mouseover?) or can we drop it?

**Comment by jancborchardt** [comment]
The question is if we need the tooltips there. I’d say they are useful to display in the trash so you know that the deletion from there is permanent. (Not anywhere else though – just like before.)
