### ISSUE TITLE
German Translation (use the formal term of address)

### ISSUE THREAD

**Issue by aspdye** [owncloud/mail#931]
Hi,

Just discoverd that OwnCloud Mail is not correct translated at the following:

Malvelope - Suchst du nach einer Möglichkeit deine E-Mails zu verschlüseln?

Normally oC Mail should use "Suchen Sie" and "Suchst Du" in the way the user set this in his Settings (German -Du / German-Sie),

**Comment by DeepDiver1975** [comment]
de: Suchst Du - https://github.com/owncloud/mail/blob/master/l10n/de.json#L64
de_DE: Suchen Sie - https://github.com/owncloud/mail/blob/master/l10n/de_DE.json#L64

**Comment by aspdye** [comment]
cool :)
