### ISSUE TITLE
Unable to connect to any IMAP servers

### ISSUE THREAD

**Issue by fossxplorer** [owncloud/mail#934]
Using Mail current master and oC stable8.1.
Tried Yahoo with manual and auto setup. 
From IRC/#owncloud-testing
For Yahoo i see "PHP","message":"fsockopen(): unable to connect to mx-eu.mail.am0.yahoodns.net:143 (Connection refused)
<fossxplorer> telnet mx-eu.mail.am0.yahoodns.net 143 => telnet: connect to address 188.125.69.79: Connection refused
<fossxplorer>  telnet imap.mail.yahoo.com 993 => Connected to imap.mail.yahoo.com
<fossxplorer> trying manual setup with imap.mail.yahoo.com gives "Creating account failed: Error connecting to mail server"

Gmail manual setup:
"app":"mail","message":"Creating account failed: Mail server denied authentication."

tail -f data/horde.log 
>> Server connection took 0.0294 seconds.
S: * OK Gimap ready for requests from 192.168.0.100 w197mb115006947wme
C: 1 CAPABILITY
S: * CAPABILITY IMAP4rev1 UNSELECT IDLE NAMESPACE QUOTA ID XLIST CHILDREN X-GM-EXT-1 XYZZY SASL-IR AUTH=XOAUTH2 AUTH=PLAIN AUTH=PLAIN-CLIENTTOKEN AUTH=XOAUTH
S: 1 OK Thats all she wrote! w197mb115006947wme
>> Command 1 took 0.0177 seconds.
C: 2 AUTHENTICATE PLAIN [INITIAL CLIENT RESPONSE (username: myuser@gmail.com)]
S: * NO [WEBALERT https://accounts.google.com/ContinueSignIn?sarp=1&scc=1&plt=AKgnsbscFKHUlLNh-4dsZoDWGlaM84R0LSQ-f1lAlnvRxLDL3Ec4MtLEIT3XTuYjfRRs-hjubnnyuwsaxAjTtC4iH1wt3jfXYZK2ypE2yqjrUVm2QCYhHg-4x31ZSR2r797iOU3smctt8NEqDSV7NJEYz_sBMC0H6UgCwyKNgIn-DB6qbxI9IQJi5XNlxuxT5kJOMt_p13qV6qxH_uM2Dm5lSP9x1jG12Ay7mauV2_dXPWIsJ217Y0o] Web login required.
S: 2 NO [ALERT] Please log in via your web browser: https://support.google.com/mail/accounts/answer/78754 (Failure)
>> Command 2 took 0.1755 seconds.

**Comment by fossxplorer** [comment]
Update: i was using a username@yahoo.no account which didn't work, but another account with username@yahoo.com seems to work :)

**Comment by clementhk** [comment]
It looks like a gmail account though. Well, good that it works.

**Comment by fossxplorer** [comment]
@clementhk i've updated my comment above. Yahoo works while Gmail doesn't.

**Comment by DeepDiver1975** [comment]
> while Gmail doesn't.

did you follow https://support.google.com/mail/answer/78754

**Comment by ASKEL** [comment]
All according to the recommendations made
From the browser on the server running the ownCloud, gmail works. After the service there.

>> Mon, 21 Sep 2015 22:00:07 +0000
>> Connection to: imap://imap.gmail.com:993/
>> Server connection took 0.0552 seconds.
S: * OK Gimap ready for requests from --------------
C: 1 CAPABILITY
S: * CAPABILITY IMAP4rev1 UNSELECT IDLE NAMESPACE QUOTA ID XLIST CHILDREN X-GM-EXT-1 XYZZY SASL-IR AUTH=XOAUTH2 AUTH=PLAIN AUTH=PLAIN-CLIENTTOKEN AUTH=XOAUTH
S: 1 OK Thats all she wrote! 
>> Command 1 took 0.0178 seconds.
C: 2 AUTHENTICATE PLAIN [INITIAL CLIENT RESPONSE (username: user@domain.com)]
S: * NO [WEBALERT https://accounts.google.com/--------] Web login required.
S: 2 NO [ALERT] Please log in via your web browser: https://support.google.com/mail/accounts/answer/78754 (Failure)
>> Command 2 took 0.0686 seconds.

**Comment by ChristophWurst** [comment]
Please check if mail 0.4 fixes that issue. I'm closing this ticket now due to inactivity, but feel free to re-open if you still face that problem. Thanks.
