### ISSUE TITLE
"No messages in this folder!" on first use

### ISSUE THREAD

**Issue by PoPoutdoor** [owncloud/mail#935]
This happens daily on first use.

![screenshot-2015-08-13 03 43 53](https://cloud.githubusercontent.com/assets/1781047/9235147/887db2f0-416f-11e5-848b-a8b06dc417f9.jpg)

![screenshot-2015-08-13 03 44 12](https://cloud.githubusercontent.com/assets/1781047/9235150/8f94198a-416f-11e5-9c29-341c0c3acfac.jpg)

The overlap disappeared after page reload.

Seems a cache problem on folders other than Inbox.

Browser: Firefox 38.1.1

**Comment by jancborchardt** [comment]
@PoPoutdoor is this latest master?

@ChristophWurst @irgendwie any idea?

**Comment by PoPoutdoor** [comment]
@jancborchardt This is latest master code.

**Comment by irgendwie** [comment]
I cannot reproduce this, what are the steps to reproduce this? @PoPoutdoor

**Comment by PoPoutdoor** [comment]
@irgendwie 

1. Open Firefox (close if already opened, wait a while and open)
2. Login to Owncloud, then select Mail app
3. After everything settled, pick random account/mail folder except Inbox
4. The message content area shown as first screenshot.
5. Click on message list area randomly, the contents displayed with "No message..." overlapped as second screenshot.

**Comment by irgendwie** [comment]
Mmh, still not reproducible for me, sorry. Everything works as expected for me!

Anything interesting in the log files @PoPoutdoor?
Do you have some kind of special setup?
Did you try to clean your browser cache?

**Comment by PoPoutdoor** [comment]
Nothing special on server side.

Just clear browser cache, this only for Yahoo account now.

**Comment by irgendwie** [comment]
So it only happens with the Yahoo account now?
Anything relevant in the owncloud log?

**Comment by PoPoutdoor** [comment]
Update: 

Everyday I empty message in those folders on Yahoo account, before shutdown firefox.
On the next time I use Mail app, those folders filled with new mails.

From the Mail app side, (sorry, I'm not catching up with code by now) some kind of cache indicated the folders have no messages. (lazy loading?) somehow not detected there have mail now and show "No message...". So, the "No message..." layer never hide.

**Comment by PoPoutdoor** [comment]
Double check with latest code, nothing related to this issue on web server log, owncloud log and FF js console.

**Comment by PoPoutdoor** [comment]
ping @irgendwie

**Comment by PoPoutdoor** [comment]
After playing with xdebug, I got something:
~~~
jquery-1.10.2.js:1805

Stack: at.matchesSelector
~~~
![error](https://cloud.githubusercontent.com/assets/1781047/11373789/aea635a6-930e-11e5-9462-550e43cafc86.jpg)

**Comment by PoPoutdoor** [comment]
Upgraded to stable 8.1 fix jquery problem.

**Comment by PoPoutdoor** [comment]
Found out jquery issue is a server side config conflict, not related to this issue.

**Comment by irgendwie** [comment]
@PoPoutdoor Sorry, still can't reproduce this issue. Is the unified inbox (with multi-account setup) or inbox (with single-account setup) loaded on startup? Or is no folder automatically selected at startup?

I see, you use the noscript addon - did you try to reproduce this issue in firefox, without any addons loaded, just to make sure? (private mode and/or restart firefox without addons)

@owncloud/mail anyone who can reproduce this issue or has an idea?

**Comment by PoPoutdoor** [comment]
@irgendwie I'm pretty sure this is not browser related (test with opera), maybe cache related.

I'll post update after server side issue resolved.

**Comment by PoPoutdoor** [comment]
After server config issue fixed, nailed down the jquery error indeed related to stable 8.1.

Have to wait core resolved jquery issue, then continue debugging this.

**Comment by Gomez** [comment]
You opened a ticket in core? Would you link it here, please.

**Comment by PoPoutdoor** [comment]
core ticket #20911

**Comment by phsc** [comment]
For the lazy guys: ;-)
https://github.com/owncloud/core/issues/20911

**Comment by PoPoutdoor** [comment]
Seems Jquery issue related to Firefox, have to debug this with Opera ATM.

**Comment by PoPoutdoor** [comment]
Try with Firefox 42.0 developer, same jquery error.

**Comment by PoPoutdoor** [comment]
Let's discuss Jquery error  #1180

**Comment by PoPoutdoor** [comment]
Replaced with #1188
