### ISSUE TITLE
Button styling on Firefox OS

### ISSUE THREAD

**Issue by ChristophWurst** [owncloud/mail#939]
Seems like there is some inconsistent button styling when using the mail app on FF OS:

![2015-08-15-08-20-01](https://cloud.githubusercontent.com/assets/1374172/9287872/41dffa38-432c-11e5-85b4-5f9935e3204d.png)

@jancborchardt @colmoneill any idea? should we fix this?

Also #484 applies for FF OS :wink:

**Comment by ChristophWurst** [comment]
Hm, just noticed there's also a little translation inconsistency. First it shows 'Nachrichten prüfen…', then 'E-Mails abrufen…'

**Comment by ChristophWurst** [comment]
> Hm, just noticed there's also a little translation inconsistency. First it shows 'Nachrichten prüfen…', then 'E-Mails abrufen…'

Same goes for English: 'Check messages…' becomes 'Checking mail…'

**Comment by jancborchardt** [comment]
@ChristophWurst do you want to change the »Checking mail …« to »Checking messages …«? :)

Regarding the buttons, good point. This seems to be a general thing with ownCloud maybe, not just related to the Mail app? Do you know how to overwrite that or what causes it?

**Comment by ChristophWurst** [comment]
> @ChristophWurst do you want to change the »Checking mail …« to »Checking messages …«? :)

@jancborchardt I can do that ;-)

> Regarding the buttons, good point. This seems to be a general thing with ownCloud maybe, not just related to the Mail app?

Yup, seems like button styles are also different in the calendar app:
![2015-08-15-12-38-06](https://cloud.githubusercontent.com/assets/1374172/9288534/fda49724-434a-11e5-8ad4-df591703bfd4.png)

> Do you know how to overwrite that or what causes it?
Not yet, I didn't have a look at the code. Maybe those buttons have different classes…

**Comment by ChristophWurst** [comment]
Since this issue only occurs on this specific platform, I'm moving it to the backlog (I don't use FF OS anymore)

**Comment by aspdye** [comment]
I think there is no need to fix this for Firefox OS :laughing: 
http://techcrunch.com/2015/12/08/mozilla-will-stop-developing-and-selling-firefox-os-smartphones/

**Comment by ChristophWurst** [comment]
> I think there is no need (not longer) to fix this for Firefox OS :laughing::
> http://techcrunch.com/2015/12/08/mozilla-will-stop-developing-and-selling-firefox-os-smartphones/

Yes, indeed. Let's close this for now.
