### ISSUE TITLE
Can't connect in SMTP

### ISSUE THREAD

**Issue by ArnoStrasbourg** [owncloud/mail#940]
Hi all,
I was prevousely use the mail app in my owncloud. I was then connected in HHTP.
I transfered my owncloud in HTTPS a couple of day ago. After re-installing mail 0.1.3, I can't connect my account. 
I click on manual configuration, and complete :
- SMTP Host : ssl0.ovh.net
- Port 465 (SSL/TLS)
- my SMTP User 
- my SMTP Password.

Nevertheless, when I click on "connect", the message is "Creating account failed: No password provided".

Is that a problem with my ssl ?
Could someone help me please ?

Tx in advance.

Arnaud.

**Comment by ghoudmon** [comment]
Hi,

It works for me with the same ovh smtp server.
I'm on OC 8.1.3 (through https too) and Mail 0.2.0.

Try to upgrade the app.

Guillaume.

**Comment by ChristophWurst** [comment]
I'm closing this ticket due to inactivity. Please re-open and fill out the issue template if you still see those problems.
