### ISSUE TITLE
Unable to create bluehost mail account

### ISSUE THREAD

**Issue by rodrigoaguilera** [owncloud/mail#945]
My mail works ok with other mail clients.

I'm using php 5.6.9 and when I try to create an mail account with the manual setup I get:

Error when communicating with the server

In the  Horde_Smtp_Connection read() method. I'm the master repo of owncloud mail.

I traced the error a bit and seems that the horde libraries have problems with php 5.6

With gmail there is no problem.

Might be related:
https://github.com/owncloud/mail/issues/444

**Comment by DeepDiver1975** [comment]
Please provide log entries from data/owmcloud.log and enable IMAP logging -  See readme of this repo. Thx

**Comment by ChristophWurst** [comment]
I'm closing this because we didn't get the necessary information to debug this.
