### ISSUE TITLE
Change Password / Login with... / Integrate 

### ISSUE THREAD

**Issue by aspdye** [owncloud/mail#947]
Changing Password of Inbox directly in OwnCloud Mail :)

-Odin Plesk (should be easy; API; like in RainLoop)
-cPanel (")
-Gmail (maybe with a "Dev Tools Acess" ?!)

Directly add Mail Account via Provider-API (for "noob"-users):

-Gmail (Log-In with Gmail)
-Outlook.com (")
-Yahoo (")

Maybe that would be integrateable with other oC Apps like Calendar or Contacts.
Like: Sync your E-Mails, Contacts and Calendar (and maybe Drive?!) with OwnCloud.

**Comment by DeepDiver1975** [comment]
duplicate https://github.com/owncloud/mail/issues/887
