### ISSUE TITLE
Show Security Level of E-Mail

### ISSUE THREAD

**Issue by aspdye** [owncloud/mail#948]
German!!: https://mailbox.org/mailbox-org-informiert-vor-e-mail-versand-ueber-sicherheitslevel-der-empfaenger/

Would be nice for oC Mail too :)

**Comment by aspdye** [comment]
In Addition to that: http://techcrunch.com/2015/11/12/gmail-will-soon-warn-users-when-emails-arrive-over-unencrypted-connections/

**Comment by ChristophWurst** [comment]
Technically, we don't know which transport security the configure SMTP server will use, hence I doubt we can do anything in that regard. Feel free to re-open if I'm wrong and you can provide more in-depth information on how to do those checks. Thanks @aspdye.
