### ISSUE TITLE
add back »Forward« functionality

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/mail#95]
When clicking »Forward«, it should work similar to Thunderbird but more integrated:

* [ ] a new »Recipient / cc / subject / message« block opens below
* [ ] the message is appended in the message field, and people have room to type something above
* [ ] the button says »Forward«

**Comment by Xenopathic** [comment]
Marking as priority - seems like a pretty major feature to me

**Comment by jancborchardt** [comment]
Moving this to 0.2 though as it’s not as important as other stuff in the milestone and we’re running out of time. :)

**Comment by jancborchardt** [comment]
This is blocked by #462 cc @aidanamavi @LukasReschke @Gomez – and it would be really good to be able to do both with 0.2

**Comment by wurstchristoph** [comment]
> a new »Recipient / cc / subject / message« block opens below

I assume that we want to support drafts on that composer too, therefore I recommend to have a unified composer view first that could easily be used here.

**Comment by sonicmaster** [comment]
How can i forward an email?????????????

**Comment by LukasReschke** [comment]
You can't yet as you can see in this ticket!!!!!!!!!!!!!

**Comment by Bullnados** [comment]
Will this being implemented in 0.2? <-- yes just one

**Comment by jancborchardt** [comment]
@Bullnados @sonicmaster this feature is blocked by https://github.com/owncloud/mail/pull/819 – so please help us and review that! :)

**Comment by Bullnados** [comment]
@jancborchardt 
Im sorry to say that i cant help you. My php-knowledge is 0. :(
I just can report bugs

**Comment by jancborchardt** [comment]
@Bullnados you do not need PHP knowledge to check out a branch (apply a patch via git – read on how to do that) and simply test it by firing up your ownCloud and clicking around. ;)

**Comment by Gomez** [comment]
As #819 is closed, this can be implemented? Does something needs more testing? Can we find a Doer (unfortunate i am not a good js dev)
