### ISSUE TITLE
Problem with "free.fr" provider

### ISSUE THREAD

**Issue by ecmu** [owncloud/mail#950]
With this provider, "no message in this folder" is always shown.

In the owncloud.log :
{"reqId":"Th4LPIp0ylyOHn3rhnI9","remoteAddr":"192.168.0.17","app":"PHP","message":"Undefined index: count at \/var\/www\/owncloud\/apps\/mail\/vendor\/pear-pear.horde.org\/Horde_Imap_Client\/Horde\/Imap\/Client\/Socket.php#2457","level":3,"time":"2015-08-02T10:41:20+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/mail\/accounts\/2\/folders\/SU5CT1g%3D\/messages"}

In horde.log :

    Sun, 02 Aug 2015 10:41:11 +0000
    Connection to: imap://imap.free.fr:993/
    Slow Command: 7.554 seconds
    Server connection took 7.5538 seconds.
    S: * OK IMAP4 ready
    C: 1 CAPABILITY
    S: * CAPABILITY IMAP4REV1 X-NETSCAPE LOGIN-REFERRALS AUTH=PLAIN
    S: 1 OK completed
    Command 1 took 0.1207 seconds.
    C: 2 [INITIAL CLIENT RESPONSE (username: xxx)]
    S: 2 OK [CAPABILITY IMAP4rev1 ACL BINARY CATENATE CHILDREN CONDSTORE ENABLE ESEARCH ESORT I18NLEVEL=1 ID IDLE LIST-EXTENDED LIST-STATUS LITERAL+ LOGIN-REFERRALS MULTIAPPEND NAMESPACE QRESYNC QUOTA RIGHTS=ektx SASL-IR SEARCHRES SORT THREAD=ORDEREDSUBJECT UIDPLUS UNSELECT WITHIN XLIST] LOGIN completed
    Command 2 took 0.4005 seconds.
    C: 3 EXAMINE INBOX
    S: * 50 EXISTS
    S: * 0 RECENT
    S: * OK [UNSEEN 1] mailbox contains unseen messages
    S: * OK [UIDVALIDITY 1] UIDs are valid for this mailbox
    S: * OK [UIDNEXT 129074] next expected UID is 129074
    S: * FLAGS (\Answered \Deleted \Draft \Flagged \Seen $Forwarded $MDNSent Forwarded $Junk $NotJunk Junk JunkRecorded NonJunk NotJunk)
    S: * OK [PERMANENTFLAGS ()] junk-related flags are not permanent
    S: * OK [HIGHESTMODSEQ 524995] modseq tracked on this mailbox
    S: 3 OK [READ-ONLY] EXAMINE completed
    Command 3 took 0.1188 seconds.
    C: 4 UID SORT RETURN (ALL COUNT) (DATE) US-ASCII ALL
    S: * ESORT (TAG "4") UID COUNT 50 ALL 129023:129046,129048:129073
    S: 4 OK UID SORT completed
    Command 4 took 0.051 seconds.
    C: 5 LOGOUT
    S: * BYE zimbra59-e10.priv.proxad.net Zimbra IMAP4rev1 server closing connection
    S: 5 OK LOGOUT completed
    Command 5 took 0.1092 seconds.

In "horde.log", I see the correct count of 50 messages in INBOX, and the correct count of unread messages in the left sidebar, but no log to retrieve messages details and "no message in this folder"...

Thanks for helping.

**Comment by DeepDiver1975** [comment]
Looks like an issue with the Horde lib. Please report this upstream

**Comment by leizh** [comment]
You can look at #740 for a workaround .
