### ISSUE TITLE
Unified inbox problem

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/mail#952]
Currently the unified inbox doesn’t load, I get this console error with Firefox:
```
Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# instead jquery.min.js:1:0
Content Security Policy: Les paramètres de la page ont empêché le chargement d'une ressource à self (« script-src http://localhorst 'unsafe-eval' »). mail
Deprecation warning: tipsy is deprecated. Use tooltip instead. js.js:1903:2
Deprecation warning: tipsy is deprecated. Use tooltip instead. js.js:1903:2
Champs mot de passe présents sur une page non sécurisée (http://). Cela représente un risque de sécurité permettant le vol d'identifiants de connexion.[En savoir plus] <inconnu>
TypeError: seed is undefined placeholder.js:69:0
```

Any idea @ChristophWurst @irgendwie @PoPoutdoor @zinks- @Gomez?

**Comment by ChristophWurst** [comment]
Seems like something here is causing it: https://github.com/owncloud/mail/blob/09910026f9362b4dccbd76b716c8579d88a5f3e8/js/views/message.js#L32-L36

This means for some reason the ``from`` attribute is not set on that message.

**Comment by jancborchardt** [comment]
Then we should fail gracefully there, right? Just show no avatar at all.
