### ISSUE TITLE
Coop with Mailvelope 

### ISSUE THREAD

**Issue by aspdye** [owncloud/mail#967]
Hi,

What do you think about an cooperation with Mailvelope, in Style of GMX and Web.de:

https://www.mailvelope.com/de/blog/gmx-and-web-de-launch-pgp
https://www.mailvelope.com/de/coop_webde

That would integrate OwnCloud Mail better with Mailvelope (Backup, Key-Server).

**Comment by jancborchardt** [comment]
Mailvelope is already working with ownCloud Mail, and the issue you’re looking for is at https://github.com/owncloud/mail/issues/27 – let’s continue there.

**Comment by aspdye** [comment]
Not really ;) I know that we support Mailvelope as a plugin. But we haven't got an deeply integration, like Cooperation Partners (United Internet [GMX, Web.de] and the Deutsche Telekom AG).

As an example (german):

Mailvelope selbst unterstützt keinen Mechanismus für die Passwortwiederherstellung. Wenn Sie Ihr Passwort vergessen oder Ihren privaten Schlüssel verlieren, können Sie die entsprechenden verschlüsselten Nachrichten nicht mehr entschlüsseln. 

!!!Dies trifft für das Verfahren in Kooperation mit WEB.DE und GMX nicht zu. Hier können Sie eine Sicherung zur Passwortwiederherstellung einrichten. Weitere Informationen zur Kooperation finden Sie hier.!!!

(https://www.mailvelope.com/de/faq#lost_pwd)

"Besonderheiten der verschlüsselten Kommunikation bei WEB.DE"

Sicherung erstellen
Im Unterschied zur herkömmlichen Verschlüsselung mit Mailvelope können WEB.DE Nutzer eine Sicherung für Schlüssel und Passwort erstellen. Dabei verschlüsselt Mailvelope den privaten Schlüssel und das Passwort und speichert diese auf den WEB.DE Servern. So wird sichergestellt, dass weder WEB.DE noch Mailvelope Zugriff auf diese Daten haben. Über einen Code auf einem Wiederherstellungsbeleg kann der Nutzer diese wiederherstellen oder die verschlüsselte Kommunikation auf anderen Geräten einrichten. Die Sicherung ist optional, wird aber dringend empfohlen.
Einfacher Austausch über Schlüssel-Server
Alle von Mailvelope in Kooperation mit WEB.DE erzeugten Schlüssel werden standardmäßig auf einem Schlüsselserver abgelegt. Auf diesem Server werden auch die in Kooperation mit GMX erzeugten Schlüssel abgelegt. Dadurch ist ein einfacherer Austausch möglich. Der Schlüsselserver ist nur für die Kunden von WEB.DE und GMX zugänglich. Der Nutzer kann seinen öffentlichen Schlüssel jederzeit entfernen. 

(https://www.mailvelope.com/de/coop_webde)

**Comment by jancborchardt** [comment]
cc @toberndo and @uggrock of Mailvelope. :)
