### ISSUE TITLE
HTML Editor

### ISSUE THREAD

**Issue by aspdye** [owncloud/mail#972]
Hi,

Dont know if this is already planned :( But some options like "Bolt" or "Color" would be nice :)

**Comment by ChristophWurst** [comment]
dup of #782

Please search the existing issues before creating new ones

**Comment by aspdye** [comment]
I've searched for "HTML Editor" and "Editor" and was wondering why nobody has the same question :D
Ahh....Its called "Rich Text E-Mails / HTML mails" ;)

Sorry!
