### ISSUE TITLE
Custom from

### ISSUE THREAD

**Issue by LIyoai** [owncloud/mail#975]
Please add a custom from like https://github.com/r3c/custom_from for Roundcube

**Comment by jancborchardt** [comment]
You’re looking for sending from aliases: https://github.com/owncloud/mail/issues/122 – please look through existing issues before opening new ones. :) Thanks!

**Comment by jancborchardt** [comment]
You’re looking for sending from aliases: https://github.com/owncloud/mail/issues/122 – please look through existing issues before opening new ones. :) Thanks!
