### ISSUE TITLE
Can't access subfolders

### ISSUE THREAD

**Issue by LIyoai** [owncloud/mail#977]
Subfolders are displayed on the left (folder.subfolder) , but I can not enter them.

**Comment by aspdye** [comment]
Please follow the issue template so we get the info we need to be able to debug and fix the problem. Thanks!

**Comment by ChristophWurst** [comment]
subfolders or subsubfolder? have a look at #618

**Comment by ChristophWurst** [comment]
Closing this because we didn't get any information meanwhile and to me it seems like a duplicate of #618 or similar
