### ISSUE TITLE
Disable send and reply buttons as long as message is empty

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/mail#99]
For the new message, the send button should be disabled in the beginning. It should only be enabled as soon as:
* there is at least one recipent
* and there is at least a subject OR a message body OR an attachment (in the future)

For replies, since there’s only the message body, there should at least be the message body. In the future with advanced capabilities for replies (attachments and cc/bcc), it’s probably similar to the new message logic.

**Comment by jancborchardt** [comment]
@RandolfCarter @seal20 the fix is at https://github.com/owncloud/mail/pull/479 – please test! :)

**Comment by wurstchristoph** [comment]
There's a little bug there (at least on FF): The button state works perfectly for the first mail you send/reply. However, for the second one, the button is initially enabled, even though the message box is cleared.

Steps to reproduce:
- send/reply a message
- send/reply again (without filling the message box of course)
- message will be sent

**Comment by jancborchardt** [comment]
Good catch - will fix it.
