### ISSUE TITLE
Delete hotkey doesn’t work atm

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/mail#990]
Using the Del key to delete the current mail does not work currently.

**Comment by ChristophWurst** [comment]
Please follow the issue template so we get the info we need to be able to debug and fix the problem. Thanks!

**Comment by jancborchardt** [comment]
Expected: Press Del on your keyboard and mail gets deleted

What actually happened: It doesn’t work.

Current master on everything. Also you can me cross-wise. :D

**Comment by ChristophWurst** [comment]
Cannot reproduce

**Comment by jancborchardt** [comment]
Hm seems fixed indeed. Sorry :D

**Comment by ChristophWurst** [comment]
:smile:
