### ISSUE TITLE
Create issue template for the mail app

### ISSUE THREAD

**Issue by ChristophWurst** [owncloud/mail#997]
We should consider creating an own issue template where we can get useful information like
* mail app version
* horde.log
* how many account (unified inbox)
* which provider (own server or proprietary service)
* server side caching enabled

Basically we can use the core issue template and adapt it to our needs.

@jancborchardt  @itheiss @Gomez @DeepDiver1975 anything else that could be helpful?

**Comment by aspdye** [comment]
More information about the Provider should be given:

-Provider
-Encryption (SSL, STARTTLS, no)
-Mail Transport (PHP, SMTP)

**Comment by ChristophWurst** [comment]
@aspdye thanks for your input! Could you create such an issue template and open a PR? :-)

**Comment by aspdye** [comment]
I will create a template tomorrow ;)

**Comment by ChristophWurst** [comment]
@aspdye still up for creating that issue template? :-)

**Comment by aspdye** [comment]
Oh ... Thank you for reminding ;) i will so this. This weekend ;)

**Comment by aspdye** [comment]
What do you think about this:

### Mail 
**Mailserver or Service:** (Postfix, Gmail, Exchange, ...) :

**Encryption?** (No, SSL, TLS, STARTTLS): 

**Mail Transport:** (SMTP or PHP Mail)

**Number of Accounts used in Unified Inbox:**

**ownCloud Mail Version:** (see ownCloud apps page)

**Comment by ChristophWurst** [comment]
> Encryption? (No, SSL, TLS, STARTTLS):

I would name that 'Transport security' and split it into 'IMAP transport security' and 'SMTP transport security'. Instead of 'No' I think 'None' sounds better.

> Number of Accounts used in Unified Inbox:

'Number of accounts' should be enough.

Could you create a PR so we can discuss it there? Thank you :-)

**Comment by aspdye** [comment]
I have changed these things. I will create an pull request for the issue_template.md in owncloud/mail soon ;)

### Mail 
**Mailserver or Service:** (Postfix, Gmail, Exchange, ...):

**Transport Security - IMAP** (None, SSL, TLS, STARTTLS): 

**Transport Security - SMTP** (None, SSL, TLS, STARTTLS):

**Mail Transport:** (SMTP or PHP Mail)

**Number of Accounts:**

**ownCloud Mail Version:** (see ownCloud apps page)

**Comment by ChristophWurst** [comment]
> I will create an pull request for the issue_template.md in owncloud/mail soon ;)

Awesome! Thanks a lot!

**Comment by PoPoutdoor** [comment]
Just test with unsupported Owncloud version 7.0.3 to install Mail 0.2, I can enable and page also shown Mail as enabled. After leaving the page, Mail doesn't show in App pulldown menu for sure.

So, I think we also need info about Owncloud version. 
PHP version and php handler (php/php-fpm/etc...) may be helpful too.

**Comment by ChristophWurst** [comment]
> I will create an pull request for the issue_template.md in owncloud/mail soon ;)
> 
> Awesome! Thanks a lot!

@aspdye where's the PR? :D

**Comment by aspdye** [comment]
Coming. Today ;)

**Comment by jancborchardt** [comment]
So this is fixed, right? :)

**Comment by ChristophWurst** [comment]
> So this is fixed, right? :)

yes, thanks for closing
